<?php
$option = '';
if(isset($result) && !empty($result)){
    $option.= '<option value"">-- '.$this->translate("Select").' --</option>';
    foreach($result as $district){
        $option.='<option value="'.$district['geo_id'].'">'.$district['geo_name'].'</option>';
    }
    $option.= '<option value="other">'.$this->translate("Other").'</option>';
}else{
    $option.= '<option value="other">'.$this->translate("Other").'</option>';
}
echo $option;
?>