<?php
use Zend\Session\Container;
$languagecontainer = new Container('language');
$startYear=date("Y", strtotime("-1 year"));
$startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
$endYear = date('Y');
$endMonth = date('m');

$startDate = date('Y-m', strtotime('+1 month', strtotime('-1 year')));
$endDate=date('Y-m');
?>
<style>
.bluebox, .dashboard-stat2{
    border:1px solid #3598DC;
}
.mrp-monthdisplay{
  display:inline-block!important;
  border-radius: 0px 5px 5px 0px;
  cursor:pointer;
}

.mrp-lowerMonth, .mrp-upperMonth{
  color: #40667A;
  font-weight:bold;
  font-size: 11px;
  text-transform:uppercase;
}

.mrp-to{
  color: #aaa;
  margin-right: 0px;
  margin-left: 0px;
  font-size: 11px;
  text-transform: uppercase;
  /* background-color: #eee; */
  padding: 5px 3px 5px 3px;
}

.mpr-calendar{
  display:inline-block;
  padding: 3px 5px;
  border-right: solid #999 1px;
}

.mpr-calendar::last-child{
  border-right: none;  
}

.mpr-month{
  padding: 20px;
  text-transform: uppercase;
  font-size: 12px;
}

.mpr-calendar h5{
  width:100%;
  text-align:center;
  font-weight:bold;
  font-size:18px
}

.mpr-selected{
  
}

.mpr-month:hover{
  border-radius: 5px;
  box-shadow: 0 0 0 1px #ddd inset;
  cursor:pointer;
}

.mpr-selected.mpr-month:hover{
  border-radius: 0px;
  box-shadow: none;
}

.mpr-calendarholder .col-xs-6 {
  max-width: 250px;
  min-width: 250px;
}

.mpr-calendarholder .col-xs-1{
  max-width: 150px;
  min-width: 150px;
}

.mpr-calendarholder .btn-info{
  background-color: #40667A;
  border-color: #406670;
  width:100%;
  margin-bottom: 10px;
  text-transform: uppercase;
  font-size: 10px;
  padding: 10px 0px;
}

.mpr-quickset{
  color: #666;
  text-transform: uppercase;
  text-align: center;
}

.mpr-yeardown, .mpr-yearup{
  margin-left: 5px;
  cursor: pointer;
  color: #666;
}

.mpr-yeardown{
  float:left;
}

.mpr-yearup{
  float:right;
}

.mpr-yeardown:hover,.mpr-yearup:hover{
  color: #40667A;
}

.mpr-calendar:first .mpr-selected:first{
    background-color: #40667A;
}

.mpr-calendar:last .mpr-selected:last{
    background-color: #40667A;
}

.popover{
  max-width: 1920px!important;
}
.table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th{
  padding:<?php echo(isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US')?'8':'3'; ?>px;
  font-size:<?php echo(isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US')?'14':'13'; ?>px;
}
@media screen and (min-width:320px) and (max-width: 760px){
    #daterange-container{
        width:100% !important;
    }
    #showDateRange,#closeDateRange{
        margin-left:0% !important;
    }
}
@media screen and (min-width:761px) and (max-width: 970px){
    #daterange-container{
        width:100% !important;
    }
    #showDateRange,#closeDateRange{
        margin-left:52% !important;
    }
}
.tabbable {
    margin: 10px;
    height: auto;
    overflow: hidden;
    border-bottom: 1px solid #ccc;
}
.nav-tabs {
    margin: 0;
}
.tab-content {
    height: 100%; 
    border-left: 1px solid #ccc ; 
    border-right: 1px solid #ccc;
    padding:15px;
}
</style>

<div class="page-bar">
    <h1 class="page-title"><?php echo $this->translate('Summary'); ?></h1>
</div>

<br>
<br>

<div class="tabbable">
<ul class="nav nav-tabs nav-justified" role="tablist">
    <li role="presentation" class="active">
        <a href="#samplesReceivedTab" aria-controls="samplesReceivedTab" role="tab" data-toggle="tab">
            <h3><?php echo number_format($summaryTabInfo[0]["total_samples_received"]);?></h3>
            <?php echo $this->translate('Samples Received'); ?>
        </a>
    </li>
    <li role="presentation">
        <a href="#suppressionRateTab" aria-controls="suppressionRateTab" role="tab" data-toggle="tab">
            <h3><?php echo number_format($summaryTabInfo[0]["suppressed_samples_percentage"], 2);?>%</h3>            
            <?php echo $this->translate('Suppression Rate'); ?>
        </a>
    </li>
    <li role="presentation">
        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
            <h3><?php echo number_format($summaryTabInfo[0]["rejected_samples_percentage"], 2);?>%</h3>
            Rejection Rate
        </a>
    </li>
    <li role="presentation">
        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
            <h3>1st Line</h3>
            Regimen
        </a>
    </li>
    <li role="presentation">
        <a href="#messages" aria-controls="messages" role="tab" data-toggle="tab">
            <h6>Reg All</h6>
            All Regimen
        </a>
    </li>
    
</ul>
<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="samplesReceivedTab">
                <div class="row">                   
                    <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Samples Received'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body" style="cursor:pointer;">
                                    <div id="samplesReceivedGraphContainer"></div>
                                </div>
                            </div>
                        </div>
                       
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box">
                                
                                        <div class="portlet box blue">
                                            <div class="portlet-title">
                                                <div class="caption" id="samplesReceivedBlockTitle">
                                                    <i class="fa fa-cogs"></i><?php echo $this->translate('Facility Wise Samples Received Summary'); ?>
                                                </div>
                                            </div>
                                            <div class="portlet-body">
                                                    <div class="form-group">                                
                                                    <div class="col-md-12 text-center">
                                                                <label for="districtWiseSamplesReceivedSummaryCheckbox" onclick="toggleSummary('districtWiseSamplesReceivedSummary','facilityWiseSamplesReceivedSummary');">
                                                                    <input type="radio" id="districtWiseSamplesReceivedSummaryCheckbox" name="showSummaryType" value="yes" checked> District
                                                                </label>
                                                                <label for="facilityWiseSamplesReceivedSummaryCheckbox" onclick="toggleSummary('facilityWiseSamplesReceivedSummary','districtWiseSamplesReceivedSummary');">
                                                                    <input type="radio" id="facilityWiseSamplesReceivedSummaryCheckbox" name="showSummaryType" value="no" > Facilities
                                                                </label>
                                                    </div>
                                                </div>

                                                <div class="table-toolbar" id="districtWiseSamplesReceivedSummary">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="samplesReceivedDistrict">
                                                        <thead>
                                                            <tr>
                                                                <th> <?php echo $this->translate('District'); ?> </th>
                                                                <th> <?php echo $this->translate('Samples Received'); ?> </th>
                                                                <th> <?php echo $this->translate('Samples Tested'); ?></th>
                                                                <th> <?php echo $this->translate('Samples Pending'); ?></th>
                                                                <th> <?php echo $this->translate('Samples Rejected'); ?></th>
                                                                <th> <?php echo $this->translate('DBS(%)'); ?> </th>                                                              
                                                                <th> <?php echo $this->translate('Plasma'); ?> </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td colspan="7" class="dataTables_empty">Loading data from server</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>

                                                <div class="table-toolbar" id="facilityWiseSamplesReceivedSummary">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="samplesReceivedFacility">
                                                        <thead>
                                                            <tr>
                                                                <th> <?php echo $this->translate('District'); ?> </th>
                                                                <th> <?php echo $this->translate('Facility'); ?> </th>
                                                                <th> <?php echo $this->translate('Samples Received'); ?> </th>
                                                                <th> <?php echo $this->translate('Samples Tested'); ?></th>
                                                                <th> <?php echo $this->translate('Samples Pending'); ?></th>
                                                                <th> <?php echo $this->translate('Samples Rejected'); ?></th>
                                                                <th> <?php echo $this->translate('DBS(%)'); ?> </th>                                                              
                                                                <th> <?php echo $this->translate('Plasma'); ?> </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td colspan="7" class="dataTables_empty">Loading data from server</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                
                                            </div>
                                        </div>
                                
                            </div>

                        </div>
                        
                    </div>

    </div>
    <div role="tabpanel" class="tab-pane fade" id="suppressionRateTab">
                        <div class="row">                   
                    <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Suppression Rate'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body" style="cursor:pointer;">
                                    <div id="suppressionRateGraphContainer"></div>
                                </div>
                            </div>
                        </div>
                       
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box">
                                
                                        <div class="portlet box blue">
                                            <div class="portlet-title">
                                                <div class="caption" id="suppressionRateBlockTitle">
                                                    <i class="fa fa-cogs"></i><?php echo $this->translate('Facility Wise Suppression Rate Summary'); ?>
                                                </div>
                                            </div>
                                            <div class="portlet-body">
                                                    <div class="form-group">                                
                                                    <div class="col-md-12 text-center">
                                                                <label for="districtWiseSuppressionRateSummaryCheckbox" onclick="toggleSummary('districtWiseSuppressionRateSummary','facilityWiseSuppressionRateSummary');">
                                                                    <input type="radio" id="districtWiseSuppressionRateSummaryCheckbox" name="showSummaryType" value="yes" checked> District
                                                                </label>
                                                                <label for="facilityWiseSuppressionRateSummaryCheckbox" onclick="toggleSummary('facilityWiseSuppressionRateSummary','districtWiseSuppressionRateSummary');">
                                                                    <input type="radio" id="facilityWiseSuppressionRateSummaryCheckbox" name="showSummaryType" value="no" > Facilities
                                                                </label>
                                                    </div>
                                                </div>

                                                <div class="table-toolbar" id="districtWiseSuppressionRateSummary">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="suppressionRateDistrict">
                                                        <thead>
                                                            <tr>
                                                                <th> <?php echo $this->translate('District'); ?> </th>
                                                                <th> <?php echo $this->translate('Valid Results'); ?> </th>
                                                                <th> <?php echo $this->translate('Suppressed Results'); ?></th>
                                                                <th> <?php echo $this->translate('Non Suppressed Results'); ?></th>
                                                                <th> <?php echo $this->translate('Samples Rejected'); ?></th>                                                                
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td colspan="5" class="dataTables_empty">Loading data from server</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>

                                                <div class="table-toolbar" id="facilityWiseSuppressionRateSummary">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="suppressionRateFacility">
                                                        <thead>
                                                            <tr>
                                                                <th> <?php echo $this->translate('District'); ?> </th>
                                                                <th> <?php echo $this->translate('Facility'); ?> </th>
                                                                <th> <?php echo $this->translate('Valid Results'); ?> </th>
                                                                <th> <?php echo $this->translate('Suppressed Results'); ?></th>
                                                                <th> <?php echo $this->translate('Non Suppressed Results'); ?></th>
                                                                <th> <?php echo $this->translate('Samples Rejected'); ?></th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td colspan="6" class="dataTables_empty">Loading data from server</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                
                                            </div>
                                        </div>
                                
                            </div>

                        </div>
                        
                    </div>


    </div>
    <div role="tabpanel" class="tab-pane fade" id="messages">
        Message
    </div>
  </div>
</div>
<br>
<br>
<div class="row">
                            <div class="col-md-12 col-sm-12">                     
                            
                            
                            <div class="portlet box">
                                
                                        <div class="portlet box blue">
                                            <div class="portlet-title">
                                                <div class="caption" id="blockTitle">
                                                    <i class="fa fa-cogs"></i><?php echo $this->translate('SUMMARY OF KEY INDICATORS'); ?>
                                                </div>
                                            </div>
                                            <div class="portlet-body">
                                                <div class="table-toolbar" id="keyIndicatorsSummary">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="keyIndicatorsSummary">
                                                        <thead>
                                                            <tr>
                                                                <th> <?php echo $this->translate('Months'); ?> </th>
                                                                <th> <?php echo $this->translate('Jan \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Feb \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Mar \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Apr \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('May \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('jun \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Jul \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Aug \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Sep \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Oct \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Nov \'17'); ?> </th>
                                                                <th> <?php echo $this->translate('Dec \'17'); ?> </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <?php foreach($keySummaryIndicators as $key=>$indicators){ ?>
                                                            <tr>
                                                                <td><?php echo $this->translate(strtoupper(str_replace('-',' ',$key)));?></td>
                                                                <?php foreach($indicators['month'] as $months){ ?>
                                                                <td><?php echo $months;?></td>
                                                                
                                                                <?php } ?>
                                                            </tr>
                                                            <?php } ?>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                
                                            </div>
                                        </div>
                                
                            </div>

                        </div>
                        

                        

</div>

                    
   
    

    <script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
    
    <script type="text/javascript">
            var oTableSamplesReceivedDistrict = null;
            var oTableSamplesReceivedFacility = null;
            var oTableSuppressionRateDistrict = null;
            var oTableSuppressionRateFacility = null;
            $(function() {
              districtWiseSamplesReceivedSummaryFn();
              facilityWiseSamplesReceivedSummaryFn();
              
              districtWiseSuppressionRateSummaryFn();
              facilityWiseSuppressionRateSummaryFn();
              
              toggleSummary('districtWiseSamplesReceivedSummary','facilityWiseSamplesReceivedSummary');
              toggleSummary('districtWiseSuppressionRateSummary','facilityWiseSuppressionRateSummary');
              getSamplesReceivedGraphInfo();
              getSuppressionRateGraphInfo();
            });
            
            function districtWiseSamplesReceivedSummaryFn(){
                oTableSamplesReceivedDistrict = $('#samplesReceivedDistrict').DataTable( {
                    "bProcessing": true,
                    "bServerSide": true,
                    "scrollX": true,
                    "aoColumns": [
                        {"sClass":"center"},
                        {"sClass":"center"},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false}
                        ],
                    "iDisplayLength": 10,
                    "aaSorting": [[ 0, "asc" ]],
            
                    "sAjaxSource": "<?php echo $this->url('summary',array('action' => 'samples-received-district')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {                
                        $.ajax({
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    }
                });
            }
            
            
            function facilityWiseSamplesReceivedSummaryFn(){
                oTableSamplesReceivedFacility = $('#samplesReceivedFacility').DataTable( {
                    "bProcessing": true,
                    "bServerSide": true,
                    "scrollX": true,
                    "aoColumns": [
                        {"sClass":"center"},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false}
                        ],
                    "iDisplayLength": 10,
                    "aaSorting": [[ 0, "asc" ]],
            
                    "sAjaxSource": "<?php echo $this->url('summary',array('action' => 'samples-received-facility')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {                
                        $.ajax({
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    }
                });
            }
    
            function districtWiseSuppressionRateSummaryFn(){
                oTableSuppressionRateDistrict = $('#suppressionRateDistrict').DataTable( {
                    "bProcessing": true,
                    "bServerSide": true,
                    "scrollX": true,
                    "aoColumns": [
                        {"sClass":"center"},
                        {"sClass":"center"},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false}
                        ],
                    "iDisplayLength": 10,
                    "aaSorting": [[ 0, "asc" ]],
            
                    "sAjaxSource": "<?php echo $this->url('summary',array('action' => 'suppression-rate-district')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {                
                        $.ajax({
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    }
                });
            }
            
            
            function facilityWiseSuppressionRateSummaryFn(){
                oTableSuppressionRateFacility = $('#suppressionRateFacility').DataTable( {
                    "bProcessing": true,
                    "bServerSide": true,
                    "scrollX": true,
                    "aoColumns": [
                        {"sClass":"center"},
                        {"sClass":"center"},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false},
                        {"sClass":"center","bSortable":false}
                        ],
                    "iDisplayLength": 10,
                    "aaSorting": [[ 0, "asc" ]],
            
                    "sAjaxSource": "<?php echo $this->url('summary',array('action' => 'suppression-rate-facility')); ?>",
                    "fnServerData": function ( sSource, aoData, fnCallback ) {                
                        $.ajax({
                            "dataType": 'json',
                            "type": "POST",
                            "url": sSource,
                            "data": aoData,
                            "success": fnCallback
                        });
                    }
                });
            }
    
            function toggleSummary(showId,hideId){
                
                $("#"+showId).show();
                $("#"+hideId).hide();
                if(showId==='districtWiseSamplesReceivedSummary'){
                    $("#samplesReceivedBlockTitle").html("<i class='fa fa-cogs'></i><?php echo $this->translate('District Wise Samples Received Summary'); ?>");
                }else if(showId==='facilityWiseSamplesReceivedSummary'){
                    $("#samplesReceivedBlockTitle").html("<i class='fa fa-cogs'></i><?php echo $this->translate('Facility Wise Samples Received Summary'); ?>");
                }else if(showId==='districtWiseSuppressionRateSummary'){
                    $("#suppressionRateBlockTitle").html("<i class='fa fa-cogs'></i><?php echo $this->translate('District Wise Suppression Rate Summary'); ?>");
                }else if(showId==='facilityWiseSuppressionRateSummary'){
                    $("#suppressionRateBlockTitle").html("<i class='fa fa-cogs'></i><?php echo $this->translate('Facility Wise Suppression Rate Summary'); ?>");
                }
               
            }
            
            function getSamplesReceivedGraphInfo(){
                $.post("<?php echo $this->url('summary', array('action' => 'samples-received-graph')); ?>",{},
                function(data) {
                    $("#samplesReceivedGraphContainer").html(data);
                });
            }
            
            function getSuppressionRateGraphInfo(){
                $.post("<?php echo $this->url('summary', array('action' => 'suppression-rate-graph')); ?>",{},
                function(data) {
                    $("#suppressionRateGraphContainer").html(data);
                });
            }
    </script>
