<div id="regimenGroupBarChartData"></div>
<script>
    $(function() {
        $('#regimenGroupBarChartData').highcharts({
            chart: {
                zoomType: 'xy',
                marginTop: 100
            },
            legend: {
                align: 'center',
                verticalAlign: 'top',
                floating: true,
                x: 0,
                y: 30
            },
            title: {
                text: ''
            },
            subtitle: {
                text: ''
            },
            exporting: {
                chartOptions: {
                    subtitle: {
                        text: '<?php echo $this->translate('Regimen Groups'); ?>',
                    }
                }
            },
            credits: {
                enabled: false
            },
            xAxis: [{
                categories: [<?php
                                if (isset($result['current_regimen']) && !empty($result['current_regimen'])) {
                                    foreach ($result['current_regimen'] as $currentRegimen) {
                                        echo "'" . $currentRegimen . "',";
                                    }
                                }
                                ?>],
                tickInterval: 1,
                //minorTicks: true,
                //tickPosition: 'inside',
                crosshair: true
            }],
            yAxis: [{ // Primary yAxis
                allowDecimals: true,
                min: 0,
                max: 100,
                labels: {
                    format: '{value}%',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                },
                title: {
                    text: '<?php echo $this->translate('Suppression Rate'); ?>',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                },
                opposite: true
            }, { // Secondary yAxis
                allowDecimals: false,
                min: 0,
                title: {
                    text: '<?php echo $this->translate('Valid Results'); ?>',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                },
                labels: {
                    format: '{value}',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                }
            }],
            tooltip: {
                shared: true
            },

            series: [{
                name: '<?php echo $this->translate('Valid Results'); ?> (R)',
                type: 'column',
                yAxis: 1,
                data: [
                    <?php if (isset($result['valid_results']) && !empty($result['valid_results'])) {
                        foreach ($result['valid_results'] as $validResult) {
                            echo $validResult . ',';
                        }
                    ?>
                    <?php  } ?>
                ],
                tooltip: {
                    valueSuffix: ' '
                }

            }, {
                name: '<?php echo $this->translate('Suppression Rate'); ?>(L)',
                type: 'spline',
                lineWidth: 0,
                data: [
                    <?php if (isset($result['suppression_rate']) && !empty($result['suppression_rate'])) {
                        foreach ($result['suppression_rate'] as $suppressionRate) {
                            echo ($suppressionRate > 0) ? $suppressionRate . ',' : null;
                        }
                    ?>
                    <?php  } ?>
                ],
                marker: {
                    symbol: 'diamond'
                },
                tooltip: {
                    valueSuffix: '%'
                },
                states: {
                    hover: {
                        lineWidthPlus: 0
                    }
                },
            }]
        });
    });
</script>