<div id="regimenGroupBarChartData"></div>
<script>
    $(function () {
        $('#regimenGroupBarChartData').highcharts({
            chart: {
                zoomType: 'xy',
                marginTop: 100
            },
            legend: {
                align: 'center',
                verticalAlign: 'top',
                floating: true,
                x: 0,
                y: 30
            },
            title: {
                text: ''
            },
            subtitle: {
                text: ''
            },
            exporting:{
                    chartOptions:{
                        subtitle: {
                            text:'<?php echo $this->translate('Regimen Groups'); ?>',
                        }
                    }
                },
            credits: {
                      enabled: false
               },
            xAxis: [{
                categories: [<?php
                    if(isset($result['current_regimen']) && count($result['current_regimen'])>0){
                      foreach($result['current_regimen'] as $currentRegimen){
                          echo "'".$currentRegimen."',";
                      }
                    }
                    ?>],
                tickInterval: 20,
                //minorTicks: true,
                tickPosition: 'inside',
                crosshair: true
            }],
            yAxis: [{ // Primary yAxis
                allowDecimals: false,
                min: 0,
                labels: {
                    format: '{value}%',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                },
                title: {
                    text: '<?php echo $this->translate('Suppression Rate'); ?>',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                }
            }, { // Secondary yAxis
                allowDecimals: false,
                min: 0,
                title: {
                    text: '<?php echo $this->translate('Valid Results'); ?>',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                },
                labels: {
                    format: '{value}',
                    style: {
                        color: Highcharts.getOptions().colors[1]
                    }
                },
                opposite: true
            }],
            tooltip: {
                shared: true
            },
            
            series: [{
                name: '<?php echo $this->translate('Valid Results'); ?> (R)',
                type: 'column',
                yAxis: 1,
                data: [
                <?php if(isset($result['valid_results']) && count($result['valid_results']) >0){
                      foreach($result['valid_results'] as $validResult){                     
                        echo $validResult.',';
                      }
                      ?>
               <?php  } ?>
                ],
                tooltip: {
                    valueSuffix: ' '
                }
        
            }, {
                name: '<?php echo $this->translate('Suppression Rate'); ?>(L)',
                type: 'spline',
                data: [
                <?php if(isset($result['suppression_rate']) && count($result['suppression_rate']) >0){
                      foreach($result['suppression_rate'] as $suppressionRate){                     
                        echo $suppressionRate.',';
                      }
                      ?>
               <?php  } ?>
                ],
                tooltip: {
                    valueSuffix: '%'
                }
            }]
        });
    });
</script>