<div id="suppressionRateBarChartData" style="min-height:600px;"></div>
<script>
       $(function () {
             $('#suppressionRateBarChartData').highcharts({
                     chart: {
                         zoomType: 'xy',
                         marginTop: 100
                     },
                     legend: {
                          align: 'center',
                          verticalAlign: 'top',
                          floating: true,
                          x: 0,
                          y: 30
                        },
                     title: {
                         text: ''
                     },
                     subtitle: {
                         text: ''
                     },
                     exporting:{
                             chartOptions:{
                                 subtitle: {
                                     text:'<?php echo $this->translate('Suppression Rate Data'); ?>',
                                 }
                             }
                         },
                     credits: {
                               enabled: false
                        },
                     xAxis: [{
                         categories: [<?php
                             if(isset($result['date']) && count($result['date'])>0){
                               foreach($result['date'] as $date){
                                   echo "'".$date."',";
                               }
                             }
                             ?>],
                         crosshair: true
                     }],
                     yAxis: [{ // Primary yAxis
                         allowDecimals: false,
                         min: 0,
                         labels: {
                             format: '{value}%',
                             style: {
                                 color: Highcharts.getOptions().colors[1]
                             }
                         },
                         title: {
                             text: '<?php echo $this->translate('Suppression Rate'); ?>',
                             style: {
                                 color: Highcharts.getOptions().colors[1]
                             }
                         }
                     }, { // Secondary yAxis
                         allowDecimals: false,
                         min: 0,
                         title: {
                             text: '<?php echo $this->translate('Valid Results'); ?>',
                             style: {
                                 color: Highcharts.getOptions().colors[1]
                             }
                         },
                         labels: {
                             format: '{value}',
                             style: {
                                 color: Highcharts.getOptions().colors[1]
                             }
                         },
                         opposite: true
                     }],
                     tooltip: {
                         shared: true
                     },
                     
                     series: [{
                         name: '<?php echo $this->translate('Valid Results'); ?> (R)',
                         type: 'column',
                         yAxis: 1,
                         data: [
                         <?php if(isset($result['valid_results']) && count($result['valid_results']) >0){
                               foreach($result['valid_results'] as $validResult){                     
                                 echo $validResult.',';
                               }
                               ?>
                        <?php  } ?>
                         ],
                         tooltip: {
                             valueSuffix: ' '
                         }
                 
                     }, {
                         name: '<?php echo $this->translate('Suppression Rate'); ?> (L)',
                         type: 'spline',
                         data: [
                         <?php if(isset($result['samples_rate']) && count($result['samples_rate']) >0){
                               foreach($result['samples_rate'] as $samplesRate){                     
                                 echo $samplesRate.',';
                               }
                               ?>
                        <?php  } ?>
                         ],
                         tooltip: {
                             valueSuffix: '%'
                         }
                     }]
              });
       });
</script>