<div id="samplesReceivedGraphicalData"></div>
<script>
       $(function () {
        $('#samplesReceivedGraphicalData').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        exporting:{
            chartOptions:{
                subtitle: {
                    text:'<?php echo $this->translate('Samples Received'); ?>',
                }
            }
        },
       credits: {
              enabled: false
       },
        xAxis: {
            categories: [<?php
            if(isset($result['date']) && count($result['date'])>0){
              foreach($result['date'] as $date){
                  echo "'".$date."',";
              }
            }
            ?>]
        },
        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: '<?php echo $this->translate('No. of Samples'); ?>'
            }
        },
        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    '<?php echo $this->translate('Total'); ?>: ' + this.point.stackTotal;
            }
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                pointPadding: 0.2,
                borderWidth: 0,
                cursor: 'pointer',
                point: {
                    events: {
                        click: function (e) {
                            doSampleTestedRedirect(e.point.category);
                        }
                    }
                }
            }
        },
        series: [<?php
        if(isset($result['sampleName']) && count($result['sampleName']) >0){
              foreach($result['sampleName'] as $key=>$condition){                     
              ?>
              {
              name:'<?php echo $this->translate(strtoupper($key)); ?>',
              data:[<?php
                  foreach($condition as $count){
                     echo '{y:'.$count.'},';
                  }
              ?>],
              },
              <?php
              }
        }
            ?>
        ],
        colors: ['#ff1900','#60d18f',],
    });
    });
</script>