                    <link rel="stylesheet" type="text/css" href="<?php echo $this->basePath('assets/global/css/jasny-bootstrap.min.css'); ?>"/>
                    <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="<?php echo $this->url('config', array('action' => 'index')) ?>"><?php echo $this->translate('Config'); ?></a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <?php echo $this->translate('Edit Config'); ?>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"> <?php echo $this->translate('Edit Config'); ?> </h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-body">
                                <div class="portlet-body form">
                                    <form class="form-horizontal" name="editGlobalInformation" id="editGlobalInformation" method="post" role="form" enctype="multipart/form-data" action="<?php echo $this->url('config', array('action' => 'edit')); ?>" autocomplete="off" onsubmit="validateNow();return false;">
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Language'); ?> <span class="font-red-mint">*</span></label>
                                            <div class="col-md-4">
                                                <select class="form-control isRequired" id="language" name="language" title="<?php echo $this->translate('Please choose instance language'); ?>">
                                                   <?php
                                                   foreach($locales as $locale){
                                                   ?>
                                                      <option value="<?php echo $locale['locale_id']; ?>" <?php echo($config['language'] == $locale['locale_id'])?'selected="selected"':''; ?>><?php echo ucwords($locale['display_name']); ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Sample Waiting Month Range'); ?> <span class="font-red-mint">*</span></label>
                                            <div class="col-md-4">
                                                <input type="text" class="form-control isNumeric isRequired" id="sample_waiting_month_range" name="sample_waiting_month_range" title="<?php echo $this->translate('Please enter sample waiting month range'); ?>" value="<?php echo $config["sample_waiting_month_range"]; ?>"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Announcement Message'); ?></label>
                                            <div class="col-md-4">
                                                <textarea class="form-control" id="announcement_msg" name="announcement_msg"><?php echo $config["announcement_msg"]; ?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Header'); ?></label>
                                            <div class="col-md-4">
                                                <input type="text" class="form-control" id="header" name="header" value="<?php echo $config["header"]; ?>"/>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Result PDF High Viral Load Message'); ?></label>
                                            <div class="col-md-4">
                                                <textarea class="form-control" id="h_vl_msg" name="h_vl_msg"><?php echo $config["h_vl_msg"]; ?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Result PDF Low Viral Load Message'); ?></label>
                                            <div class="col-md-4">
                                                <textarea class="form-control" id="l_vl_msg" name="l_vl_msg"><?php echo $config["l_vl_msg"]; ?></textarea>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Do you want to show smiley at result pdf?'); ?></label>
                                            <div class="col-md-4">
                                                <input type="radio" id="show_smiley_yes" name="show_smiley" value="yes" <?php echo (isset($config["show_smiley"]) && $config["show_smiley"] == 'yes')?'checked="checked"':''; ?>/> Yes&nbsp;&nbsp;
                                                <input type="radio" id="show_smiley_no" name="show_smiley" value="no" <?php echo (isset($config["show_smiley"]) && $config["show_smiley"] == 'no')?'checked="checked"':''; ?>/> No
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label class="col-md-3 control-label"><?php echo $this->translate('Logo'); ?></label>
                                            <div class="col-md-4">
                                                <div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
                                                      <?php
                                                      if(isset($config['logo']) && trim($config['logo'])!= '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . trim($config['logo']))){
                                                      ?>
                                                       <img src="/uploads/logo/<?php echo trim($config['logo']); ?>" alt="Logo image"/>
                                                      <?php } else { ?>
                                                       <img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&text=No image"/>
                                                      <?php } ?>
                                                    </div>
                                                    <div>
                                                      <span class="btn btn-default btn-file"><span class="fileinput-new"><?php echo $this->translate('Select image'); ?></span><span class="fileinput-exists"><?php echo $this->translate('Change'); ?></span>
                                                      <input type="file" id="logo" name="logo" title="Please select logo image" onchange="getNewImage('<?php echo trim($config['logo']); ?>');">
                                                      </span>
                                                      <?php
                                                      if(isset($config['logo']) && trim($config['logo'])!= '' && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . trim($config['logo']))){
                                                      ?>
                                                        <a id="clearImage" href="javascript:void(0);" class="btn btn-default" data-dismiss="fileupload" onclick="clearImage('<?php echo trim($config['logo']); ?>')"><?php echo $this->translate('Clear'); ?></a>
                                                      <?php } ?>
                                                      <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput"><?php echo $this->translate('Remove'); ?></a>
                                                    </div>
                                                </div>
                                                <div class="box-body">
                                                  <?php echo $this->translate('Please make sure logo image size of'); ?>: <code>170x175</code>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input type="hidden" name="removedLogoImage" id="removedLogoImage"/>  
                                                    <button type="submit" class="btn green"><?php echo $this->translate('Submit'); ?></button>
                                                    <a href="<?php echo $this->url('config', array('action' => 'index')); ?>" class="btn default"><?php echo $this->translate('Cancel'); ?></a>                                                    
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
<script type="text/javascript">
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editGlobalInformation'
        });
        if (flag) {
            if (duplicateName) {
              document.getElementById('editGlobalInformation').submit();
            }
        }
    }
    
    function clearImage(img){
        $('.fileinput').fileinput('clear');
        $('#clearImage').hide();
        $("#offerImage").addClass("isRequired");
        $("#removedLogoImage").val(img);
    }
     
    function getNewImage(img){
        $('#clearImage').hide();
        $("#removedLogoImage").val(img);
    }
</script>             