                    <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="/users">Users</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">Add</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"> Add User
                    </h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-body">


                                <div class="portlet-body form">
                                    <form class="form-horizontal" name="addUserInformation" id="addUserInformation" method="post" action="/users/add" role="form"  autocomplete="off">
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Name <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="text" id="username" name="username" class="form-control isRequired" placeholder="" title="Please enter the name">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">User Type <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <select class="form-control isRequired" name="role" id="role" title="Please select the role">
                                                        <option value="">--Select--</option>
                                                        <?php
                                                            $options = [];
                                                            foreach($roles as $r) {
                                                            //$options[$r['access_type_name']][$r['role_id']] = $r['role_name'];
                                                        ?>
                                                          <option value="<?php echo $r['role_id']; ?>"><?php echo ucwords($r['role_name']); ?></option>
                                                        <?php
                                                       }
                                                       ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Facility </label>
                                                <div class="col-md-6">
                                                    <select class="form-control" id="facility" name="facility[]" title="Please select facility" multiple>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Email <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="email" id="email" name="email" class="form-control isEmail isRequired" placeholder="" title="Please enter valid email">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Mobile </label>
                                                <div class="col-md-6">
                                                    <input type="tel" id="mobile" name="mobile" class="form-control" placeholder="" title="Please enter mobile number">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Password <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="password" id="password" name="password" class="form-control isRequired" placeholder="" title="Please enter the password">
                                                </div>
                                            </div>
                                            
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input type="button" class="btn green" value="Submit" onclick="validateNow();return false;">
                                                    <a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn default">Cancel</a>
                                                    
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
<script type="text/javascript">
    $(function () {
        $('#facility').select2({
            placeholder: "Select facilities",
            allowClear: true
        });
    });
    
    $('#role').on('change',function(){
        if(this.value!= '' && this.value!= 1){
            $('#facility').select2('val', '');
            $.post("<?php echo $this->url('users', array('action' => 'get-role-facilities')); ?>", {role : this.value},
            function(data){
                $('#facility').html(data);
                $('#facility').select2('open');
            });
        }else{
           $('#facility').select2('val', '');
        }
    });
    
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'addUserInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('addUserInformation').submit();
            }
        }
    }
</script>