                    <?php
                    $mappedFacilities = array();
                    if(isset($user['facilities']) && count($user['facilities']) >0){
                        foreach($user['facilities'] as $row){
                           $mappedFacilities[] = $row['facility_id'];
                        }
                    }
                    ?>
                    <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="/users">Users</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">Edit</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"> Edit User
                    </h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-body">


                                <div class="portlet-body form">
                                    <form class="form-horizontal" name="editUserInformation" id="editUserInformation" method="post" action="/users/edit" role="form" autocomplete="off">
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Name <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="text" id="username" name="username" class="form-control isRequired" placeholder="" value="<?php echo $user->user_name; ?>" title="Please enter the name">
                                                    <input type="hidden" id="userId" name="userId" class="form-control isRequired" placeholder="" value="<?php echo base64_encode($user->user_id); ?>">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">User Type <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <select class="form-control isRequired" name="role" id="role" title="Please select the role">
                                                        <option value="">--Select--</option>
                                                        <?php
                                                            $options = [];
                                                            foreach($roles as $r) {
                                                            // $options[$r['access_type_name']][$r['id']] = $r['role_name'];
                                                        ?>
                                                          <option value="<?php echo $r['role_id']; ?>" <?php echo ($user->role == $r['role_id'] ? " selected='selected' " : ""); ?> ><?php echo ucwords($r['role_name']); ?></option>
                                                        <?php
                                                       }
                                                       ?>                                                        
                                                        
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Facility </label>
                                                <div class="col-md-6">
                                                    <select class="form-control" id="facility" name="facility[]" title="Please select facility" multiple>
                                                      <?php
                                                      foreach($facilities as $row){
                                                      ?>
                                                        <option value="<?php echo $row['facility_id']; ?>" <?php echo (in_array($row['facility_id'],$mappedFacilities))?'selected="selected"':''; ?>><?php echo ucwords($row['facility_name']); ?></option>
                                                      <?php } ?>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Email <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="email" id="email" name="email" class="form-control isEmail isRequired" placeholder="" value="<?php echo $user->email; ?>" title="Please enter valid email">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Mobile <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="tel" id="mobile" name="mobile" class="form-control " placeholder="" value="<?php echo $user->mobile; ?>" >
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Password </label>
                                                <div class="col-md-6">
                                                    <input type="password" id="password" name="password" class="form-control" placeholder="">
                                                </div>
                                            </div>
                                            
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Status <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <select class="form-control isRequired" name="status" id="status" title="Please select the status">
                                                        <option value="">--Select--</option>
                                                        <option value="active" "<?php echo ($user->status == 'active' ? " selected='selected' " : ""); ?>">Active</option>
                                                        <option value="inactive" "<?php echo ($user->status == 'inactive' ? " selected='selected' " : ""); ?>">Inactive</option>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <input type="button" class="btn green" value="Submit" onclick="validateNow();return false;">
                                                    <a href="<?php echo $this->url('users', array('action' => 'index')); ?>" class="btn default">Cancel</a>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
<script type="text/javascript">
    $(function () {
        $('#facility').select2({
            placeholder: "All Facilities",
            allowClear: true
        });
    });
    
    $('#role').on('change',function(){
        if(this.value!= '' && this.value!= 1){
            $('#facility').select2('val', '');
            $.post("<?php echo $this->url('users', array('action' => 'get-role-facilities')); ?>", {role : this.value},
            function(data){
                $('#facility').html(data);
                $('#facility').select2('open');
            });
        }else{
           $('#facility').select2('val', '');
        }
    });
    
    duplicateName = true;
    function validateNow() {
        flag = deforayValidator.init({
            formId: 'editUserInformation'
        });
        if (flag) {
            if (duplicateName) {
                $.blockUI();
                document.getElementById('editUserInformation').submit();
            }
        }
    }
</script>