
                    <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="/users">Users</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">Edit</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"> Edit User
                    </h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-body">


                                <div class="portlet-body form">
                                    <form class="form-horizontal" method="post" action="/users/edit" role="form">
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Name <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="text" id="username" name="username" class="form-control" placeholder="" value="<?php echo $user['username']; ?>">
                                                    <input type="hidden" id="userId" name="userId" class="form-control" placeholder="" value="<?php echo $user['user_id']; ?>">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">User Type <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <select class="form-control" name="role" id="role">
                                                        <option value="">--Select--</option>
                                                        <?php foreach($roles as $r) { ?>
                                                        <option value="<?php echo $r['id'] ?>"  <?php echo ($user['role'] == $r['id'] ? " selected='selected' " : ""); ?>><?php echo $r['role_name'] ?></option>
                                                        <?php } ?>
                                                    </select>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Email <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="email" id="email" name="email" class="form-control" placeholder="" value="<?php echo $user['email']; ?>">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Mobile <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <input type="tel" id="mobile" name="mobile" class="form-control" placeholder="" value="<?php echo $user['mobile']; ?>" >
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Password </label>
                                                <div class="col-md-6">
                                                    <input type="password" id="password" name="password" class="form-control" placeholder="Leave blank to retain old password">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Status <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <select class="form-control" name="status" id="status">
                                                        <option value="">--Select--</option>
                                                        <option value="active" "<?php echo ($user['status'] == 'active' ? " selected='selected' " : ""); ?>">Active</option>
                                                        <option value="inactive" "<?php echo ($user['status'] == 'inactive' ? " selected='selected' " : ""); ?>">Inactive</option>
                                                    </select>
                                                </div>
                                            </div>    
                                                                                     
                                            
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <button type="submit" class="btn green">Submit</button>
                                                    <button type="button" class="btn default" onclick="document.location.href='/users'">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
