<?php
use Zend\Session\Container;

//\Zend\Debug\Debug::dump($user);die;

$selectedOrg = [];

foreach($map as $m){
    $selectedOrg[] = $m['organization_id'];
}

$logincontainer = new Container('credo');

?>
        <link href="<?php echo $this->basePath('assets/global/plugins/multiselect/css/multi-select.css'); ?>" rel="stylesheet" type="text/css" />
                    <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="/users">Users</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                Map Facilities
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"> Map User to Facilities
                    </h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-body">


                                <div class="portlet-body form">
                                    <form class="form-horizontal" method="post" action="/users/map" role="form">
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">User Name</label>
                                                <div class="col-md-6">
                                                    <span class="form-control" style="border:0;"><?php echo $user['username']; ?></span>
                                                    <input type="hidden" id="userId" name="userId" class="form-control" placeholder="" value="<?php echo $user['user_id']; ?>">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">User Role</label>
                                                <div class="col-md-6">
                                                    <span class="form-control" style="border:0;">
                                                        <?php echo $user['role_name']; ?>
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Access Level</label>
                                                <div class="col-md-6">
                                                    <span class="form-control" style="border:0;">
                                                        <?php echo $user['access_type_name']; ?>
                                                    </span>
                                                </div>
                                            </div>
                                            
                                            
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Facilities <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <a href='#' id='select-all' class="btn btn-info">Select all</a>
                                                    &nbsp;
                                                    <a href='#' id='deselect-all' class="btn btn-info">Deselect all</a>
                                                    <br>
                                                    <br>
                                                    <select id="facilities" name="facilities[]" multiple="multiple" style="width:100%;">
                                                        <?php
                                                       
                                                        foreach ($facilities as $fac){
                                                            
                                                            if($user['access_type'] != $fac['org_type']){
                                                                continue;
                                                            }
                                                            ?>
                                                            <option value="<?php echo $fac['org_id'] ?>" <?php echo (in_array($fac['org_id'], $selectedOrg)) ? " selected='selected' " : ""; ?> ><?php echo $fac['name'] ?></option>
                                                            <?php
                                                        }
                                                        ?>
                                                    </select>

                                                </div>
                                            </div>




                                                                                     
                                            
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <button type="submit" class="btn green">Submit</button>
                                                    <button type="button" class="btn default" onclick="document.location.href='/users'">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                    <script src="<?php echo $this->basePath('assets/global/plugins/multiselect/js/jquery.multi-select.js'); ?>" type="text/javascript"></script>
                    <script>
                        $(document).ready(function(){
                                $('#facilities').multiSelect();
                                $('#select-all').click(function(){
                                  $('#facilities').multiSelect('select_all');
                                  return false;
                                });
                                $('#deselect-all').click(function(){
                                  $('#facilities').multiSelect('deselect_all');
                                  return false;
                                });
                                

                        })
                    </script>
                    