           <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <?php echo $this->translate('Roles'); ?>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"></h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                      <i class="fa fa-cogs"></i><?php echo $this->translate('Manage Roles'); ?>
				    </div>
                                </div>    
                                <div class="portlet-body">
                                    <div class="table-toolbar">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="btn-group pull-right">
                                                    <a href="/roles/add" class="btn sbold green"> <?php echo $this->translate('Add New'); ?>
                                                        <i class="fa fa-plus"></i>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                        <br>
                                        <table id="roleTable" class="table table-striped table-bordered table-hover table-checkable order-column">
                                            <thead>
                                                <tr>
                                                    <th><?php echo $this->translate('Role Name'); ?></th>
                                                    <th><?php echo $this->translate('Role Code'); ?></th>
                                                    <th><?php echo $this->translate('Status'); ?></th>
                                                    <th><?php echo $this->translate('Action'); ?> </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td colspan="4" class="dataTables_empty">Loading data from server</td>
                                                </tr>
                                            </tbody>
                                        </table>

                                    </div>
                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
<script type="text/javascript">
    /* Table initialisation */
     oTable = null;
    $(document).ready(function() {
    $('#roleTable').dataTable( {
		"bAutoWidth": false,
        "bProcessing": true,
        "bServerSide": true,
         "aoColumns": [
		{"sClass":"center"},
        {"sClass":"center"},
        {"sClass":"center"},
        {"sClass":"center","bSortable":false}
            ],
        "sAjaxSource": "<?php echo $this->url('roles',array('action' => 'index')); ?>",
         "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
    } );

} );
       
</script>