<!-- BEGIN PAGE HEADER-->
<!-- BEGIN THEME PANEL -->
<!-- END THEME PANEL -->
<!-- BEGIN PAGE BAR -->
<style>
    .select2-selection__choice {
        color: black !important;
    }

    th {
        display: revert !important;
    }

    .red {
        background: lightcoral !important;
    }

    .green {
        background: lightgreen !important;
    }

    .yellow {
        background: yellow !important;
    }

    .center {
        text-align: center;
    }

    #syncStatusTable tr:hover {
        cursor: pointer;
        background: #666 !important;
        color: #fff;
    }

    #syncStatusTable tr td {
        text-align: left;
        padding-left: 10px;
    }

    #syncStatusTable tr td status-indicator {

        margin-right: 5px;
    }
</style>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <?php echo $this->translate('Lab-Status'); ?>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?php echo $this->translate('Lab Sync'); ?>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div id="syncStatusTable"></div>
                </div>
            </div>
        </div>
        <!-- END BASIC DETAILS TABLE-->
    </div>
</div>
<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    sTable = null;
    $(document).ready(function() {
        initData();
    });

    function initData() {
        $.blockUI();
        $.post("<?php echo $this->url('sync-status', array('action' => 'sync-status')); ?>", {},
            function(data) {
                $("#syncStatusTable").html(data);
                $.unblockUI();
            });
    }

    function exportSyncStatus() {
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({
            message: '<h2><?php echo $this->translate('Processing...'); ?></h2>'
        })).ajaxStop($.unblockUI);
        $.post("<?php echo $this->url('sync-status', array('action' => 'export-sync-status-excel')); ?>", {
                fromDate: $('#mrp-lowerDate').val(),
                toDate: $('#mrp-upperDate').val()
            },
            function(data) {
                if (data == "" || data == null || data == undefined) {
                    alert('<?php echo $this->translate('Unable to export excel'); ?>');
                } else {
                    window.open('/temporary/' + data, '_blank');
                }
            });
    }
</script>
