<!-- BEGIN PAGE HEADER-->
<!-- BEGIN THEME PANEL -->
<!-- END THEME PANEL -->
<!-- BEGIN PAGE BAR -->
<style>
    .select2-selection__choice {
        color: black !important;
    }

    th {
        display: revert !important;
    }

    .red {
        background: lightcoral !important;
    }

    .green {
        background: lightgreen !important;
    }

    .yellow {
        background: yellow !important;
    }

    .center {
        text-align: center;
    }

    #syncStatusTable tr:hover {
        cursor: pointer;
        background: #eee !important;
    }
</style>
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <?php echo $this->translate('Lab-Status'); ?>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?php echo $this->translate('Lab Status Overview'); ?>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <table id="labStatusTable" class="table table-striped table-bordered table-hover table-checkable order-column">
                        <thead>
                            <tr>
                                <th> <?php echo $this->translate('Lab Name'); ?> </th>
                                <th> <?php echo $this->translate('Last Synced on'); ?> </th>
                                <th> <?php echo $this->translate('Last Results Sync from Lab'); ?> </th>
                                <th> <?php echo $this->translate('Last Requests Sync from VLSTS'); ?> </th>
                            </tr>
                        </thead>
                        <tbody id="syncStatusTable">
                            <tr>
                                <td colspan="4" class="dataTables_empty">Loading data from server</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END BASIC DETAILS TABLE-->
    </div>
</div>
<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    sTable = null;
    $(document).ready(function() {
        /* oTable = $('#labStatusTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [{
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                }
            ],
            "aaSorting": [
                [1, "desc"]
            ],
            "sAjaxSource": "<?php echo $this->url('sync-status', array('action' => 'sync-status')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "type",
                    "value": "status"
                });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        }); */
        initData();
    });

    function initData(){
        $.blockUI();
        $.post("<?php echo $this->url('sync-status', array('action' => 'sync-status')); ?>", {},
            function(data) {
                $("#syncStatusTable").html(data);
                //$('#labStatusTable').dataTable();
                $.unblockUI();
            });
    }
</script>