<?php 

$today = new DateTimeImmutable();
$twoWeekExpiry = $today->sub(DateInterval::createFromDateString('2 weeks'));
$threeWeekExpiry = $today->sub(DateInterval::createFromDateString('4 weeks'));

foreach ($result as $key => $aRow) {
    $color = "red";
    $aRow['latest'] = $aRow['latest'] ?: $aRow['requested_on'];
    $latest = (!empty($aRow['latest'])) ? new DateTimeImmutable($aRow['latest']) : null;

    if (empty($latest)) {
        $color = "red";
    } elseif ($latest >= $twoWeekExpiry) {
        $color = "green";
    } elseif ($latest > $threeWeekExpiry && $latest < $twoWeekExpiry) {
        $color = "yellow";
    } elseif ($latest >= $threeWeekExpiry) {
        $color = "red";
    }
    /* Assign data table variables */ ?>
<tr class="<?php echo $color; ?>" data-facilityId="<?php echo base64_encode($aRow['facility_id']);?>">
    <td><?= ucwords($aRow['labName']); ?></td>
    <td><?= date("d-M-Y (h:i: a)", strtotime($aRow['latest'])); ?></td>
    <td><?= date("d-M-Y (h:i: a)", strtotime($aRow['lastResultsSync'])); ?></td>
    <td><?= date("d-M-Y (h:i: a)", strtotime($aRow['lastRequestsSync'])); ?></td>
</tr>
<?php } ?>