<?php

use Application\Service\CommonService;

$today = new DateTimeImmutable();
$twoWeekExpiry = $today->sub(DateInterval::createFromDateString('2 weeks'));
$threeWeekExpiry = $today->sub(DateInterval::createFromDateString('4 weeks'));

foreach ($result as $key => $aRow) {
    $color = "red";
    $aRow['latest'] = $aRow['latest'] ?? $aRow['requested_on'];
    $latest = CommonService::verifyIfDateValid($aRow['latest']) ? new DateTimeImmutable($aRow['latest']) : null;

    if (empty($latest)) {
        $color = "red";
    } elseif ($latest >= $twoWeekExpiry) {
        $color = "green";
    } elseif ($latest > $threeWeekExpiry && $latest < $twoWeekExpiry) {
        $color = "yellow";
    } elseif ($latest >= $threeWeekExpiry) {
        $color = "red";
    }
    /* Assign data table variables */ ?>
    <tr class="<?php echo $color; ?>" data-facilityId="<?php echo base64_encode($aRow['facility_id']); ?>">
        <td><?= ($aRow['labName']); ?></td>
        <td><?= $this->humanReadableDateFormat($aRow['latest'], true); ?></td>
    </tr>
<?php
}
