<?php

use Application\Service\CommonService;

$today = new DateTimeImmutable();
$twoWeekExpiry = $today->sub(DateInterval::createFromDateString('2 weeks'));
$threeWeekExpiry = $today->sub(DateInterval::createFromDateString('4 weeks'));

foreach ($result as $key => $aRow) {
    $color = "<status-indicator negative pulse></status-indicator>";
    $aRow['latest'] = $aRow['latest'] ?? $aRow['requested_on'] ?? null  ;
    $latest = CommonService::verifyIfDateValid($aRow['latest']) ? new DateTimeImmutable($aRow['latest']) : null;

    if (is_null($latest)) {
        $color = "<status-indicator negative pulse></status-indicator>";
    } elseif ($latest >= $twoWeekExpiry) {
        $color = "<status-indicator positive pulse></status-indicator>";
    } elseif ($latest > $threeWeekExpiry && $latest < $twoWeekExpiry) {
        $color = "<status-indicator intermediary pulse></status-indicator>";
    } elseif ($latest >= $threeWeekExpiry) {
        $color = "<status-indicator negative pulse></status-indicator>";
    }
    /* Assign data table variables */ ?>
    <tr class="" data-facilityId="<?php echo base64_encode($aRow['facility_id']); ?>">
        <td><?= $color. " " . htmlspecialchars($aRow['labName']) ?></td>
        <td><?= $this->humanReadableDateFormat($aRow['latest'], true); ?></td>
    </tr>
<?php
}
