<table class="table table-striped table-bordered table-hover order-column" id="labPerformanceTable">
    <thead>
        <tr>
            <th><?php echo $this->translate('Lab Name'); ?></th>
            <th><?php echo $this->translate('No. of Facilities Sending Samples'); ?></th>
            <th><?php echo $this->translate('Total Samples Registered'); ?></th>
            <th><?php echo $this->translate('Rejected Samples'); ?></th>
            <th><?php echo $this->translate('Total Tests'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($result as $row) { ?>
            <tr>
                <td><?= $row['lab_name']; ?></td>
                <td class="center"><?= $row['total_facilities']; ?></td>
                <td class="center"><?= $row['total']; ?></td>
                <td class="center"><?= $row['rejected']; ?></td>
                <td class="center"><?= $row['total_valid_tests']; ?></td>
            </tr>
        <?php } ?>
    </tbody>

</table>

<script>
    $(function() {
        $("#labPerformanceTable").DataTable();
    });
</script>