                    <!-- BEGIN PAGE BAR -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/hubs/dashboard">Hubs Dashboard</a>
                            </li>
                        </ul>
                    </div>

                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    
                    
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <br>
                    <br>
                    
                    
                    <div class="row">
                                                <div class="col-md-6 col-sm-6">
                            <div class="portlet box">
                                <div class="portlet-body">
                                    
                                    
                                    
                                    
                                    
                                        <div class="portlet box blue">
                                            <div class="portlet-title">
                                                <div class="caption">
                                                    <i class="fa fa-cogs"></i>Test Results
                                                </div>
                                                <div class="tools">
                                                    
                                                </div>
            
                                            </div>
                                            <div class="portlet-body">
                                                <div class="table-toolbar">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="testResults">
                                                        <thead>
                                                            <tr>
                                                                <th> Batch Date </th>
                                                                <th> No. of Samples </th>
                                                                <th> Received Date </th>
                                                                <th> View/Print </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td>20-Apr-2016</td>
                                                                <td>20</td>
                                                                <td>25-Apr-2016</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                    <a href="" class="btn btn-primary btn-xs">Print</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>21-Apr-2016</td>
                                                                <td>24</td>
                                                                <td>25-Apr-2016</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                    <a href="" class="btn btn-primary btn-xs">Print</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>23-Apr-2016</td>
                                                                <td>22</td>
                                                                <td>24-Apr-2016</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                    <a href="" class="btn btn-primary btn-xs">Print</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>24-Apr-2016</td>
                                                                <td>18</td>
                                                                <td>25-Apr-2016</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                    <a href="" class="btn btn-primary btn-xs">Print</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>25-Apr-2016</td>
                                                                <td>14</td>
                                                                <td>26-Apr-2016</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                    <a href="" class="btn btn-primary btn-xs">Print</a>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>                        

                        
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box">
                                <div class="portlet-body">
                                    
                                    
                                    
                                    
                                    
                                        <div class="portlet box blue">
                                            <div class="portlet-title">
                                                <div class="caption">
                                                    <i class="fa fa-cogs"></i>Test Results Waiting
                                                </div>
                                                <div class="tools">
                                                    
                                                </div>
            
                                            </div>
                                            <div class="portlet-body">
                                                <div class="table-toolbar">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="testResults">
                                                        <thead>
                                                            <tr>
                                                                <th> Batch Date </th>
                                                                <th> No. of Samples </th>
                                                                <th> View </th>
                                                                <th> Reminder </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td>20-Apr-2016</td>
                                                                <td>20</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                </td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">Reminder</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>21-Apr-2016</td>
                                                                <td>24</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                </td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">Reminder</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>23-Apr-2016</td>
                                                                <td>22</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                </td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">Reminder</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>24-Apr-2016</td>
                                                                <td>18</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                </td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">Reminder</a>
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>25-Apr-2016</td>
                                                                <td>14</td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">View</a>
                                                                </td>
                                                                <td>
                                                                    <a href="" class="btn btn-primary btn-xs">Reminder</a>
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    
                                </div>
                            </div>
                        </div>                        
                        
                    </div>
        
        <script src="https://code.highcharts.com/highcharts.js"></script>
        
<script>
    $(function () {
    
    
    
    
    
    
    
    
    
    
    
    
    
});
    
</script>        
        
        
