<?php
  use Zend\Session\Container;
  $languagecontainer = new Container('language');

if(isset($searchMonth) && trim($searchMonth)!= ''){
    $splitSearchMonth = explode("-",$searchMonth);
    $startDate = $endDate = $splitSearchMonth[1].'-'.date('m', strtotime($splitSearchMonth[0]));
    $startMonth = $endMonth = date('m', strtotime($splitSearchMonth[0]));
    $startYear = $endYear = $splitSearchMonth[1];
    $startDisplayDate = $endDisplayDate = $searchMonth;
}else if((isset($fromMonth) && trim($fromMonth)!= '') && (isset($toMonth) && trim($toMonth)!= '')){
    $splitFromMonth = explode("-",$fromMonth);
    $startDate = $splitFromMonth[1].'-'.date('m', strtotime($splitFromMonth[0]));
    $startMonth = date('m', strtotime($splitFromMonth[0]));
    $startYear = $splitFromMonth[1];
    $startDisplayDate = $fromMonth;
    $splitToMonth = explode("-",$toMonth);
    $endDate = $splitToMonth[1].'-'.date('m', strtotime($splitToMonth[0]));
    $endMonth = date('m', strtotime($splitToMonth[0]));
    $endYear = $splitToMonth[1];
    $endDisplayDate = $toMonth;
}else{
    $startDate = date("Y", strtotime("-1 year")).'-'.date('m', strtotime('+1 month', strtotime('-1 year')));
    $endDate = date('Y').'-'.date('m');
    $startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
    $endMonth = date('m');
    $startYear = date("Y", strtotime("-1 year"));
    $endYear = date('Y');
    $startDisplayDate  = strtoupper(date('M', strtotime('+1 month', strtotime('-1 year')))).' '.date("Y", strtotime("-1 year"));
    $endDisplayDate  = strtoupper(date('M')).' '.date('Y');
}
//set selected labs
$selectedLabs = array();
if(isset($labFilter) && trim($labFilter)!= ''){
    $selectedLabs = explode(",",$labFilter);
}
//set selected provinces
$selectedProvinces = array();
if(isset($facilityInfo['selectedProvinces']) && count($facilityInfo['selectedProvinces']) >0){
    foreach($facilityInfo['selectedProvinces'] as $province){
        $selectedProvinces[] = $province['location_id'];
    }
}
//set selected districts
$selectedDistricts = array();
if(isset($facilityInfo['labDistricts']) && count($facilityInfo['labDistricts']) >0){
    foreach($facilityInfo['labDistricts'] as $district){
        $selectedDistricts[] = $district['facility_district'];
    }
}
?>
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                      <h1 class="page-title"><?php echo $this->translate('TAT Dashboard'); ?></h1>
                    </div>
                    <!-- END PAGE BAR -->
                    <br/>
                    <br/>

                    <form id="pageFilter" action="#" method="">
                        <div class="row">
                            <div class="col-md-12" style="padding-left:30px;">
                              <div class="col-md-12">
                                  <div class="form-group col-lg-4">
                                      <label class="control-label"><?php echo $this->translate('Provinces'); ?>&nbsp;</label>
                                      <select name="provinces[]" id="provinces" class="form-control" multiple title="<?php echo $this->translate('Please choose provinces'); ?>" onchange="getLocationInfo('provinces');">
                                          <?php
                                          if(isset($facilityInfo['provinces']) && count($facilityInfo['provinces']) > 0){
                                              foreach($facilityInfo['provinces'] as $province){
                                          ?>
                                              <option value="<?php echo $province['location_id']; ?>" <?php echo(in_array($province['location_id'],$selectedProvinces))?'selected="selected"':''; ?>><?php echo ucwords($province['location_name']); ?></option>
                                          <?php } } ?>
                                      </select>
                                  </div>
                                  <div class="form-group col-lg-4">
                                      <label class="control-label"><?php echo $this->translate('Districts'); ?>&nbsp;</label>
                                      <select name="districts[]" id="districts" class="form-control" multiple title="<?php echo $this->translate('Please choose districts'); ?>" onchange="getLocationInfo('districts');">
                                          <?php
                                          if(isset($facilityInfo['provinceDistricts']) && count($facilityInfo['provinceDistricts']) > 0){
                                              foreach($facilityInfo['provinceDistricts'] as $provinceDistrict){
                                          ?>
                                              <option value="<?php echo $provinceDistrict['location_id']; ?>" <?php echo(in_array($provinceDistrict['location_id'],$selectedDistricts))?'selected="selected"':''; ?>><?php echo ucwords($provinceDistrict['location_name']); ?></option>
                                          <?php } } ?>
                                      </select>
                                  </div>
                                  <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Date Range'); ?>&nbsp;</label>
                                    <div id="dashboard-range" class="btn btn-sm form-control"
                                        data-container="body" data-placement="bottom" data-original-title="Change dashboard date range">
                                        <?php echo $this->translate('Date Range'); ?>&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-calendar"></i>&nbsp;
                                        <span class="thin uppercase hidden-xs"></span>&nbsp;
                                        <i class="fa fa-angle-down"></i>
                                        <input type="hidden" name="sampleCollectionDate" id="sampleCollectionDate"/>
                                    </div>
                                  </div>
                              </div>

                              <div class="col-md-12">
                                  <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Clinics'); ?>&nbsp;</label>
                                    <select class="form-control" id="clinics" name="clinics[]" multiple title="<?php echo $this->translate('Please choose clinics'); ?>">
                                      <?php
                                      if(isset($facilityInfo['clinics']) && count($facilityInfo['clinics']) > 0){
                                        foreach($facilityInfo['clinics'] as $clinics){
                                          ?>
                                          <option value="<?php echo $clinics['facility_id']; ?>"><?php echo ucwords($clinics['facility_name']); ?></option>
                                          <?php
                                        }
                                      } ?>
                                    </select>
                                  </div>
                                  <div class="form-group col-lg-4" style="display: none">
                                      <label class="control-label"><?php echo $this->translate('Labs'); ?>&nbsp;</label>
                                      <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please choose labs'); ?>">
                                          <?php
                                          if(isset($facilityInfo['labs']) && count($facilityInfo['labs']) > 0){
                                              foreach($facilityInfo['labs'] as $labs){
                                          ?>
                                              <option value="<?php echo $labs['facility_id']; ?>" <?php echo(in_array($labs['facility_id'],$selectedLabs))?'selected="selected"':''; ?>><?php echo ucwords($labs['facility_name']); ?></option>
                                          <?php } } ?>
                                      </select>
                                  </div>
                              </div>
                              <div class="col-md-12">
                                  <div class="form-group col-lg-12" style="text-align:center;margin-top:10px;">
                                      <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="searchTATData();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                                      <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
                                  </div>
                              </div>
                            </div>
                        </div>
                        <hr style="background: #000 !important;border-color:#ccc;">
                    </form>
                    <div id="page-data-viewer"></div>
<script type="text/javascript">
    $(function() {
        $('#provinces').select2({
            placeholder: "<?php echo $this->translate('All Provinces'); ?>",
            allowClear: true
        });
        $('#districts').select2({
            placeholder: "<?php echo $this->translate('All Districts'); ?>",
            allowClear: true
        });
        $('#clinics').select2({
            placeholder: "<?php echo $this->translate('All Clinics'); ?>",
            allowClear: true
        });
        
        var start = moment().subtract(12, 'months');
        var end = moment();

        function cb(start, end) {
            $('#dashboard-range span').html(start.format('MMM D, YYYY') + ' to ' + end.format('MMM D, YYYY'));
            $('#sampleCollectionDate').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        }

        $('#dashboard-range').daterangepicker({
            format: 'DD-MMM-YYYY',
            separator: ' to ',
            startDate: start,
            endDate: end,
            maxDate:moment(),
            ranges: {
               'Today': [moment(), moment()],
               'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
               'Last 7 Days': [moment().subtract(6, 'days'), moment()],
               'Last 30 Days': [moment().subtract(29, 'days'), moment()],
               'This Month': [moment().startOf('month'), moment().endOf('month')],
               'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            opens: "left"
        }, cb);
        cb(start, end);
        $('#dashboard-range').show();
        setProgress();
        <?php
          if(isset($_GET['facility']) && isset($_GET['category'])){
        ?>
            getTATfromURL();
        <?php
          }
          else{
        ?>
            defaultTAT();
        <?php
          }
        ?>
    });

    function setProgress(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        if( !$('#sampleCollectionDate').val() ) {
            $('#sampleCollectionDate').val(moment().subtract('days', 29).format('YYYY-MM-DD') + ' to ' + moment().format('YYYY-MM-DD'));
        }
    }

    function defaultTAT(){
        var dateRange = $("#sampleCollectionDate").val();
        var category  = $("input:radio[name='optradio']:checked").val();
        $.post("<?php echo $this->url('times', array('action' => 'get-tat-default')); ?>",{sampleCollectionDate:dateRange,category:category},
        function(data) {
            $("#page-data-viewer").html(data);
        });
    }


    function getTATfromURL(){
      var dateRange = $("#sampleCollectionDate").val();
      $.post("<?php echo $this->url('times', array('action' => 'get-tat-from-url')); ?>",{
          facility:'<?php if(isset($_GET['facility'])){echo $_GET['facility'];}?>',
          category:'<?php if(isset($_GET['category'])){echo $_GET['category'];}?>',
          place:   '<?php if(isset($_GET['place'])){echo $_GET['place'];}?>',
          sampleCollectionDate: dateRange
      }
      ,
      function(data) {
          $("#page-data-viewer").html(data);
      });
    }

    function getTATfromSearchField(provinces,districts,clinics,dateRange,category,provinceNames,districtNames,clinicNames){
      setProgress();
      $.post("<?php echo $this->url('times', array('action' => 'get-tat-from-search-field')); ?>",
      {
        provinces:provinces,
        districts:districts,
        clinics:clinics,
        sampleCollectionDate:dateRange,
        category:category,
        provinceNames:provinceNames,
        districtNames:districtNames,
        clinicNames: clinicNames
      },
      function(data) {
          $('#page-data-viewer').html(data);
      });
    }

    function searchTATData(){
      var provinceIDs   = $("#provinces").val();
      var districtIDs   = $("#districts").val();
      var clinicIDs     = $("#clinics").val();
      var dateRange     = $("#sampleCollectionDate").val();
      var category      = $("input:radio[name='optradio']:checked").val();
      var provinceNames = [];
      var districtNames = [];
      var clinicNames   = [];
      var provinces = $('#provinces').select2('data');
      var districts = $('#districts').select2('data');
      var clinics   = $('#clinics').select2('data');

      for(var i=0; i < provinces.length; i++){
        provinceNames[i] = provinces[i].text;
      }
      for(var i=0; i < districts.length; i++){
        districtNames[i] = districts[i].text;
      }
      for(var i=0; i < clinics.length; i++){
        clinicNames[i] = clinics[i].text;
      }
      getTATfromSearchField(provinceIDs,districtIDs,clinicIDs,dateRange,category,provinceNames,districtNames,clinicNames);
    }

    $('#btl-display-table').click(function(){
      if($('#table-container').is(":visible"))
        $('#table-container').hide();
      else
        $('#table-container').show();
    });

    function getTATChartData(idTable){
      var facilities = [];

      for (var i = 0; i < $("#"+idTable+" tbody tr").length; i++) {
        facilities[i] = $("#"+idTable).find("#td-"+i+"-0").text();
      }
      return facilities;
    }

    function fnExcelReport(idTable,idButton) {
        var tab_text = '<html xmlns:x="urn:schemas-microsoft-com:office:excel">';
        tab_text = tab_text + '<head><xml><x:ExcelWorkbook><x:ExcelWorksheets><x:ExcelWorksheet>';

        tab_text = tab_text + '<x:Name>Test Sheet</x:Name>';

        tab_text = tab_text + '<x:WorksheetOptions><x:Panes></x:Panes></x:WorksheetOptions></x:ExcelWorksheet>';
        tab_text = tab_text + '</x:ExcelWorksheets></x:ExcelWorkbook></xml> <meta charset="utf-8"></head><body>';

        tab_text = tab_text + "<table border='1px'>";
        tab_text = tab_text + $(idTable).html();
        tab_text = tab_text + '</table></body></html>';

        var data_type = 'data:application/vnd.ms-excel';

        var ua = window.navigator.userAgent;
        var msie = ua.indexOf("MSIE ");

        if (msie > 0 || !!navigator.userAgent.match(/Trident.*rv\:11\./)) {
            if (window.navigator.msSaveBlob) {
                var blob = new Blob([tab_text], {
                    type: "application/csv;charset=utf-8;"
                });
                navigator.msSaveBlob(blob, 'Test file.xls');
            }
        } else {
            var fullDate = new Date()
            var twoDigitMonth = ((fullDate.getMonth().length+1) === 1)? (fullDate.getMonth()+1) : '0' + (fullDate.getMonth()+1);
            var currentDate = fullDate.getDate() + "_" + twoDigitMonth + "_" + fullDate.getFullYear();
            var seconds = fullDate.getSeconds();
            var minutes = fullDate.getMinutes();
            var hour = fullDate.getHours();
            $(idButton).attr('href', data_type + ', ' + encodeURIComponent(tab_text));
            $(idButton).attr('download', 'TAR_'+currentDate+'_'+hour+minutes+seconds+'.xls');
        }
    }

    function resetEverything(){
        $('#pageFilter')[0].reset();
        $('#provinces').val('').change();
        $('#districts').val('').change();
        $('#clinics').val('').change();
        searchTATData();
    }

    var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

    $(function () {
      startMonth = '<?php echo $startMonth; ?>';
      startYear = '<?php echo $startYear; ?>';
      endMonth = '<?php echo $endMonth; ?>';
      endYear = '<?php echo $endYear; ?>';
      fiscalMonth = 7;
      startDate = parseInt("" + startYear  + startMonth + "");
      endDate = parseInt("" + endYear + endMonth + "");

      content = '<div class="row mpr-calendarholder">';
      calendarCount = endYear - startYear;
      if(calendarCount == 0)
        calendarCount++;
      var d = new Date();
      for(y = 0; y < 2; y++){
                    content += '<div class="col-xs-6" ><div class="mpr-calendar row" id="mpr-calendar-' + (y+1) + '">'
                                                     + '<h5 class="col-xs-12"><i class="mpr-yeardown fa fa-chevron-circle-left"></i><span>' + (startYear + y).toString() + '</span><i class="mpr-yearup fa fa-chevron-circle-right"></i></h5><div class="mpr-monthsContainer"><div class="mpr-MonthsWrapper">';
        for(m=0; m < 12; m++){
          var monthval;
          if((m+1) < 10)
            monthval = "0" + (m+1);
          else
            monthval = "" + (m+1);
                            content += '<span data-month="' + monthval  + '" class="col-xs-3 mpr-month">' + MONTHS[m] + '</span>';
        }
        content += '</div></div></div></div>';
      }
      content += '<div class="col-xs-1">';
      content += '<button class="btn btn-info mpr-close">Apply</button>';
      content += '</div>';
      content += '</div>';

      $(document).on('click','.mpr-month',function(e){
        e.stopPropagation();
            $month = $(this);
            var monthnum = $month.data('month');
            var year = $month.parents('.mpr-calendar').children('h5').children('span').html();
            if($month.parents('#mpr-calendar-1').size() > 0){
              //Start Date
              startDate = parseInt("" + year + monthnum);
              if(startDate > endDate){

                if(year != parseInt(endDate/100))
                  $('.mpr-calendar:last h5 span').html(year);
                   endDate = startDate;
              }
            }else{
              //End Date
              endDate = parseInt("" + year + monthnum);
              if(startDate > endDate){
                if(year != parseInt(startDate/100))
                  $('.mpr-calendar:first h5 span').html(year);
                startDate = endDate;
              }
            }

            paintMonths();
      });


      $(document).on('click','.mpr-yearup',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
            var year = parseInt($(this).prev().html());
            year++;
            $(this).prev().html(""+year);
                    $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });

      $(document).on('click','.mpr-yeardown',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
                    var year = parseInt($(this).next().html());
            year--;
            $(this).next().html(""+year);
                    //paintMonths();
          $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });

      $(document).on('click','.mpr-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        startDate = parseInt(d.getFullYear() + "01");
        var month = d.getMonth() + 1;
        if(month < 9)
          month = "0" + month;
        endDate = parseInt("" + d.getFullYear() + month);
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          var year = $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });

      $(document).on('click','.mpr-prev-year', function(e){
        e.stopPropagation();
        var d = new Date();
        var year = d.getFullYear()-1;
        startDate = parseInt(year + "01");
        endDate = parseInt(year + "12");
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          $('h5 span',$cal).html(year);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });

      $(document).on('click','.mpr-fiscal-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 1;
        else
          year = d.getFullYear();
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(d.getMonth()+1 < 10)
          cm = "0" + (d.getMonth()+1);
        else
          cm = (d.getMonth()+1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + d.getFullYear() + cm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });

      $(document).on('click','.mpr-prev-fiscal', function(){
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 2;
        else
          year = d.getFullYear() - 1;
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(fiscalMonth -1 < 10)
          efm = "0" + (fiscalMonth-1);
        else
          efm = (fiscalMonth-1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + (d.getFullYear() - 1) + efm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear()-1);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });

      var mprVisible = false;
      var mprpopover = $('.mrp-container').popover({
        container: "body",
        placement: "bottom",
        html: true,
        content: content
      }).on('show.bs.popover', function () {
        $('.popover').remove();
        var waiter = setInterval(function(){
          if($('.popover').size() > 0){
            clearInterval(waiter);
            setViewToCurrentYears();
                    paintMonths();
          }
        },50);
      }).on('shown.bs.popover', function(){
        mprVisible = true;
      }).on('hidden.bs.popover', function(){
        mprVisible = false;
      });

      $(document).on('click','.mpr-calendarholder',function(e){
        e.preventDefault();
        e.stopPropagation();
      });
      $(document).on("click",".mrp-container",function(e){
        if(mprVisible){
          e.preventDefault();
            e.stopPropagation();
          mprVisible = false;
        }
      });

      $(document).on("click",function(e){
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
      });

      $(document).on('click','.mpr-close', function(e){
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
      });
    });

    function getLocationInfo(fromSrc){
        var provinces = ($("#provinces").val() == null || $("#provinces").val() == '')?[]:$("#provinces").val();
        var districts = ($("#districts").val() == null || $("#districts").val() == '')?[]:$("#districts").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-location-info')); ?>", {provinces:provinces,districts:districts,fromSrc:fromSrc},
        function(data){
            if(fromSrc == 'provinces'){ $('#districts').val('').change(); }
            $('#labName').val('').change();
            $('#clinics').val('').change();
            var splitLocationInfo = data.split('##');
            if(fromSrc == 'provinces'){ $('#districts').html(splitLocationInfo[0]); }
            $('#labName').html(splitLocationInfo[1]);
            $('#clinics').html(splitLocationInfo[2]);
        });
    }

    function toogleTable(idRow){
      $('#'+idRow+' .table-container').toggleClass('active');
      if (this.resizeTO) clearTimeout(this.resizeTO);
      this.resizeTO = setTimeout(function () {
          // resizeEnd call function with pass context body
          adjustGraph.call($('#'+idRow));
      }, 500);
      if($('#'+idRow+' .table-container').hasClass('active')){
        $('#'+idRow+' .chart-container').addClass('fullSize');
      }
      else{
        $('#'+idRow+' .chart-container').removeClass('fullSize');
      }
    }

    $(window).resize(function(){
        if (this.resizeTO) clearTimeout(this.resizeTO);
        this.resizeTO = setTimeout(function () {
            adjustGraph.call($('body'));
        }, 5);
     });

     function adjustGraph(chart) {
        try {
            if (typeof (chart === 'undefined' || chart === null) && this instanceof jQuery) { // if no obj chart and the context is set
                this.find('.chart-container:visible').each(function () { // for only visible charts container in the curent context
                    $container = $(this); // context container
                    $container.find('div[id$="Chart"]').each(function () { // for only chart
                        $chart = $(this).highcharts(); // cast from JQuery to highcharts obj
                        $chart.setSize($container.width(), $chart.chartHeight, doAnimation = true); // adjust chart size with animation transition
                    });
                });
            } else {
                chart.setSize($('.chart-container:visible').width(), chart.chartHeight, doAnimation = true); // if chart is set, adjust
            }
        } catch (err) {
            // do nothing
        }
    }


    function getRow(table,idChart){
      return '<div class="row time-box" id="row-'+idChart+'" style="height:400px;border: 1px solid rgba(0,0,0,.125);">'
                +'<div class="col-md-6 col-sm-12 table-container" style="height:100%; margin:0px; padding-top:15px; overflow-y: auto">'
                    +'<div class="scrolltable">'
                        +table
                    +'</div>'
                +'</div>'
                +'<div class="col-md-6 col-sm-12 chart-container" style="position:relative; padding: 0; ">'
                    +'<a id="a-btl-display-table" href="javascript:toogleTable(\'row-'+idChart+'\'); ">'
                      +'<span id="btl-display" style="position: absolute; top:20; left 10; z-index:999; cursor:pointer">'
                        +'<i class="fa fa-bar-chart" aria-hidden="true"></i>'
                      +'</span>'
                    +'</a>'
                    +'<a id="a-btl-display-table" style="display:none" href="javascript:fnExcelReport(\'#timeTable\',\'#a-btl-display-table\'); ">'
                      +'<span id="btl-display" style="position: absolute; top:20; left 20; z-index:999; cursor:pointer">'
                        +'<i class="fa fa-download"></i><?php echo $this->translate('Download table'); ?>'
                      +'</span>'
                    +'</a>'
                    +'<div id="'+idChart+'" style="width:100%; min-width:100%;max-width:100%; height: 400px; padding:0 !important; margin: 0"></div>'
                +'</div>'
            +'</div><br>';
    }
</script>
<script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>

<style type="text/css">
    #row-provinceChart .active,
    #row-districtChart .active,
    #row-clinicChart .active{
      display:none;
    }
    #row-provinceChart .chart-container.fullSize,
    #row-districtChart .chart-container.fullSize,
    #row-clinicChart .chart-container.fullSize{
      width: 100% !important
    }
    .table-container{
      margin: 0 !important;
      padding: 0 !important;
      background-color: #cccccc;
      height: 100%;
      overflow-y: hidden !important;
    }
    .time-table{
      margin: 0 !important;
      padding: 0 !important;
      width: 100% !important;
      height: 100% !important;
      display: none
    }
    .time-box{
      background-color: #FFF
    }

    .scrolltable {
      overflow-x: hidden;
      height: 400px;
      width: 100%;
      display: flex;
      display: -webkit-flex;
      flex-direction: column;
      -webkit-flex-direction: column;
      background-color: #f9f9f9
    }
    .scrolltable > .header {
      width: calc(100% - 1px) !important;
    }
    .scrolltable > .body {
        /*noinspection CssInvalidPropertyValue*/
        width: 100%;
        overflow-y:auto;
        flex: 1;
        -webkit-flex: 1;
        background-color: #f9f9f9;
    }
    .scrolltable > .body table{
        width:100%
    }
    table {
        border-collapse: collapse;
        table-layout: fixed;
    }
    td {
        border: 1px solid rgb(227, 227, 227);
        line-height: 1.42857143;
    }
    th {
        background-color: lightgrey;
        border-width: 1px;
        border-color: none !important;
        padding: 6px;
        width:16.67%;
        word-wrap:break-word
    }
    td {
        border-width: 1px;
        line-height: 20px;
        padding: 6px;
        color: #333;
        width:16.67%;
        word-wrap:break-word
    }
    tr:first-child td {
        border-top-width: 0;
    }
    tr:nth-child(odd) {
        background-color: #ffffff;
    }
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }
    .scrollbar{
        margin: 0px;
        float: left;
        height: 100%;
        width: 100%;
        background: #FFF;
        overflow-y: scroll;
    }

    #style-3::-webkit-scrollbar-track{
        -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
        background-color: #F5F5F5;
    }

    #style-3::-webkit-scrollbar{
        width: 6px;
        background-color: #F5F5F5;
    }

    #style-3::-webkit-scrollbar-thumb{
        background-color: #000000;
    }
    .clickable{
      cursor:pointer;
    }
    .clickable:hover{
      background-color:#F5F5F5;
    }
</style>