<?php
  $cont = 0;
  $tableHeader = '';
  $tableBody = '';
  $tableFooter = '';
  $categoryNext = 0;

 ?>
<script type="text/javascript">
    $(function(){
      $('#page-data-viewer').html(
        '<dic class="container">'+
            '<h4><?php echo $this->translate('TAT: '.$place); ?></h4>'+
            getRow('<?php generateTable($results,'provinceTable',$category+1,$labs,$daterange,$category) ?>','provinceChart')+
        '</div>'
      );

      $('.clickable').click(function(){
          if($(this).attr('data-category') != 2){
            window.location.href='/times/dashboard?district='+$(this).attr('id')+'&lab=<?php echo $labs; ?>&range=<?php echo $daterange; ?>&category='+$(this).attr('data-category')+'&place='+$(this).attr('data-place');
          }
      });

      // Stacked Bar Chart for the Turnaround Time
      $('#provinceChart').highcharts({
          chart: {
              type: 'column'
          },
          title: {
              text: '<?php echo $this->translate('TAT Chart'); ?>'
          },
          credits: {
              enabled: false
          },
          xAxis: {
              categories: getTATChartData("provinceTable")
          },
          yAxis: {
              min: 0,
              title: {
                  text: '<?php echo $this->translate('TAT in days'); ?>'
              },
              stackLabels: {
                  enabled: true,
                  style: {
                      fontWeight: 'bold',
                      color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                  }
              }
          },
          legend: {
              align: 'right',
              x: -30,
              verticalAlign: 'top',
              y: 25,
              floating: true,
              backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
              borderColor: '#CCC',
              borderWidth: 1,
              shadow: false
          },
          tooltip: {
              headerFormat: '<b>{point.x}</b><br/>',
              pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
          },
          plotOptions: {
              column: {
                  stacking: 'normal',
                  dataLabels: {
                      enabled: true,
                      color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                  },
                  cursor: '<?php echo ($category ==  1)?'default':'pointer'; ?>',
                  point: {
                      events: {
                        click: function () {
                          <?php if($category!= 1){?>
                            window.location.href='/times/dashboard?district='+this.id+'&lab=<?php echo $labs; ?>&range=<?php echo $daterange; ?>&category=<?php echo $categoryNext+1; ?>&place='+this.category;
                          <?php }?>
                        },
                        mouseOver: function(){
                        }
                      }
                  }
              }
          },
          series:[
            {
                name: 'Collect-Receive',
                data:[<?php
                      foreach ($results as $key) { ?>
                        {
                          y: <?php
                                if(!is_null($key['collect_receive'])){
                                  echo $key['collect_receive'];
                                }else{
                                  echo 0;
                                }
                             ?>,
                          id: '<?php
                                if(!is_null($key['facility_id'])){
                                  echo $key['facility_id'];
                                }else{echo 0;}
                              ?>'
                        },
                    <?php
                      }
                     ?> ]
            },
            {
                name: 'Receive-Register',
                data:[<?php
                      foreach ($results as $key) { ?>
                        {
                          y: <?php
                                if(!is_null($key['receive_register'])){
                                  echo $key['receive_register'];
                                }else{echo 0;}
                            ?>,
                          id: '<?php
                                if(!is_null($key['facility_id'])){
                                  echo $key['facility_id'];
                                }else{echo 0;}
                              ?>'
                        },
                    <?php
                      }
                     ?>
                  ]
            },
            {
                name: 'Register-Analysis',
                data:[<?php
                      foreach ($results as $key) { ?>
                        {
                          y: <?php
                                if(!is_null($key['register_analysis'])){
                                  echo $key['register_analysis'];
                                }
                                else{echo 0;}
                              ?>,
                          id: '<?php
                                if(!is_null($key['facility_id'])){
                                  echo $key['facility_id'];
                                }else{echo 0;}
                              ?>'
                        },
                    <?php
                      }
                     ?> ]
            },
            {
                name: 'Analysis-Authorise',
                data:[<?php
                      foreach ($results as $key) { ?>
                        {
                          y: <?php
                              if(!is_null($key['register_analysis'])){
                                echo $key['analysis_authorise'];
                              }
                              else{echo 0;}
                            ?>,
                          id: '<?php
                                if(!is_null($key['facility_id'])){
                                  echo $key['facility_id'];
                                }else{echo 0;}
                              ?>'
                        },
                    <?php
                      }
                     ?> ]
            }
          ]


      });



    });

</script>

<?php
function generateTable($result,$idTable,$facilityCategory,$labs,$daterange,$categoryVal){
  $cont = 0;
  $tableHeader = '';
  $tableBody = '';
  $tableFooter = '';
//  $category = '';
  $categoryNext = 0;
  $clickable = ($categoryVal == 1)?'':'clickable';
  $tableHeader = '<table class="header">'
                    .'<thead>'
                        .'<th>Places</th>'
                        .'<th>Collect-Receive</th>'
                        .'<th>Receive-Register</th>'
                        .'<th>Register-Analysis</th>'
                        .'<th>Analysis-Authorise</th>'
                        .'<th>Total</th>'
                    .'</thead>'
                  .'</table>';

  foreach ($result as $key) {
    $tableBody .= '<tr class="'.$clickable.'" id="'.$key['facility_id'].'" data-labs="'.$labs.'" data-date-range="'.$daterange.'" data-category="'.$facilityCategory.'" data-place="'.$key['facility'].'">'
                    .'<td id="td-'.$cont.'-0">'.$key['facility'].'</td>'
                    .'<td id="td-'.$cont.'-1">'.$key['collect_receive'].'</td>'
                    .'<td id="td-'.$cont.'-2">'.$key['receive_register'].'</td>'
                    .'<td id="td-'.$cont.'-3">'.$key['register_analysis'].'</td>'
                    .'<td id="td-'.$cont.'-4">'.$key['analysis_authorise'].'</td>'
                    .'<td id="td-'.$cont.'-5">'.($key['collect_receive']+$key['receive_register']+$key['register_analysis']+$key['analysis_authorise']).'</td>'
                  .'</tr>';
    $cont ++;
    $category = $key['category'];
  }
  echo '<div class="scrolltable">'
          .$tableHeader
          .'<div class="body scrollbar" id="style-3">'
              .'<table id="'.$idTable.'">'
                .'<tbody>'
                  .$tableBody
                .'</tbody>'
              .'</table>'
          .'</div>'
       .'</div>';

}
?>
