#!/bin/sh

set -e

# See https://caddyserver.com/docs/conventions#file-locations for details

export XDG_CONFIG_HOME=/config
export XDG_DATA_HOME=/data

exec caddy run --config /etc/caddy/Caddyfile --adapter caddyfile