<?php
use Zend\Session\Container;
$languagecontainer = new Container('language');
$startYear=date("Y", strtotime("-1 year"));
$startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
$endYear = date('Y');
$endMonth = date('m');

$startDate = date('Y-m', strtotime('+1 month', strtotime('-1 year')));
$endDate=date('Y-m');
?>
<style>
.bluebox, .dashboard-stat2{
    border:1px solid #3598DC;
}
.mrp-monthdisplay{
  display:inline-block!important;
  border-radius: 0px 5px 5px 0px;
  cursor:pointer;
}

.mrp-lowerMonth, .mrp-upperMonth{
  color: #40667A;
  font-weight:bold;
  font-size: 11px;
  text-transform:uppercase;
}

.mrp-to{
  color: #aaa;
  margin-right: 0px;
  margin-left: 0px;
  font-size: 11px;
  text-transform: uppercase;
  /* background-color: #eee; */
  padding: 5px 3px 5px 3px;
}

.mpr-calendar{
  display:inline-block;
  padding: 3px 5px;
  border-right: solid #999 1px;
}

.mpr-calendar::last-child{
  border-right: none;  
}

.mpr-month{
  padding: 20px;
  text-transform: uppercase;
  font-size: 12px;
}

.mpr-calendar h5{
  width:100%;
  text-align:center;
  font-weight:bold;
  font-size:18px
}

.mpr-selected{
  
}

.mpr-month:hover{
  border-radius: 5px;
  box-shadow: 0 0 0 1px #ddd inset;
  cursor:pointer;
}

.mpr-selected.mpr-month:hover{
  border-radius: 0px;
  box-shadow: none;
}

.mpr-calendarholder .col-xs-6 {
  max-width: 250px;
  min-width: 250px;
}

.mpr-calendarholder .col-xs-1{
  max-width: 150px;
  min-width: 150px;
}

.mpr-calendarholder .btn-info{
  background-color: #40667A;
  border-color: #406670;
  width:100%;
  margin-bottom: 10px;
  text-transform: uppercase;
  font-size: 10px;
  padding: 10px 0px;
}

.mpr-quickset{
  color: #666;
  text-transform: uppercase;
  text-align: center;
}

.mpr-yeardown, .mpr-yearup{
  margin-left: 5px;
  cursor: pointer;
  color: #666;
}

.mpr-yeardown{
  float:left;
}

.mpr-yearup{
  float:right;
}

.mpr-yeardown:hover,.mpr-yearup:hover{
  color: #40667A;
}

.mpr-calendar:first .mpr-selected:first{
    background-color: #40667A;
}

.mpr-calendar:last .mpr-selected:last{
    background-color: #40667A;
}

.popover{
  max-width: 1920px!important;
}
.table > tbody > tr > td, .table > tbody > tr > th, .table > tfoot > tr > td, .table > tfoot > tr > th, .table > thead > tr > td, .table > thead > tr > th{
  padding:<?php echo(isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US')?'8':'3'; ?>px;
  font-size:<?php echo(isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US')?'14':'13'; ?>px;
}
.select2-search__field,.select2-selection__rendered{
    color:#333;
    text-align:center;
}
.select2-container--default{
    width:100% !important;
}
.select2-selection--multiple{
    border-radius:50px !important;
}
@media screen and (min-width:320px) and (max-width: 760px){
    #daterange-container{
        width:100% !important;
    }
    #showDateRange,#closeDateRange{
        margin-left:0% !important;
    }
}
@media screen and (min-width:761px) and (max-width: 970px){
    #daterange-container{
        width:100% !important;
    }
    #showDateRange,#closeDateRange{
        margin-left:52% !important;
    }
}
</style>
<?php
$sType = '';
foreach($sampleType as $samples){
    $sType.='<option value="'.base64_encode($samples['sample_id']).'">'.ucwords($samples['sample_name']).'</option>';
}
?>
                    <!-- BEGIN PAGE BAR -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                       <h1 class="page-title"><?php echo $this->translate('Labs Dashboard'); ?></h1>
                    </div>

                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    
                    <br>
                    <br>
                    
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <form id="pageFilter" action="#" method="">
                        <div class="row" style="padding-top:10px;padding-bottom:20px;">
                            <div class="col-lg-6">
                                <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more labs. Leave blank for All'); ?>">
                                    <?php
                                    foreach($labName as $lab){
                                        ?>
                                        <option data-name="<?php echo $lab['facility_name']; ?>" value="<?php echo $lab['facility_id']; ?>"><?php echo $lab['facility_code']." - ".$lab['facility_name'];?></option>
                                        <?php
                                    }
                                    ?>
                                    
                                </select>
                            </div>
                            <div class="col-lg-3">
                                <div id="sla-date-range" class="mrp-container form-control">
                                    <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                                    <div class="mrp-monthdisplay ">
                                      <span class="mrp-lowerMonth"><?php echo date('M', strtotime('+1 month', strtotime('-1 year')));; ?> <?php echo $startYear; ?></span>
                                      <span class="mrp-to"> to </span>
                                      <span class="mrp-upperMonth"><?php echo date('M'); ?> <?php echo date('Y'); ?></span>
                                    </div>
                                  <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" onchange=""/>
                                  <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
                                </div>
                            </div>                        
                            <div class="col-lg-3">
                                <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getEverything();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                                <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
                            </div>
                        </div>
                    </form>
                    <hr style="background: #000 !important;border-color:#ccc;">
                    <div class="row" style="margin-bottom:20px;">
                        <div class="col-md-12 col-sm-12" style="text-align:center;">
                            <a id="showDateRange" href="javascript:void(0);" style="color:#0d68e0;box-shadow: 1px 2px 12px rgb(173, 200, 222);border-radius: 12px;padding: 2px 10px 2px 10px;margin-left:26%;"><i class="fa fa-chevron-down" aria-hidden="true"></i> <?php echo $this->translate('Show Date Filter'); ?></a>
                            <a id="closeDateRange" href="javascript:void(0);" style="color:#0d68e0;display:none;box-shadow: 1px 2px 12px rgb(173, 200, 222);border-radius: 12px;padding: 2px 10px 2px 10px;margin-left:26%;"><i class="fa fa-chevron-up" aria-hidden="true"></i> <?php echo $this->translate('Close Date Filter'); ?></a>
                        </div>
                    </div>
                    <form id="dateFilter" action="#" method="">
                        <div class="daterange-container row" style="margin-bottom:20px;display:none;">
                            <div class="col-md-12 col-sm-12" style="text-align:right;">
                                <div id="daterange-container" class="btn btn-sm form-control"
                                    data-container="body"
                                    data-placement="bottom"
                                    data-original-title="Change date range" style="text-align:center;width:50%;">
                                    <i class="icon-calendar"></i>&nbsp;
                                    <span class="thin uppercase hidden-xs"></span>&nbsp;
                                    <i class="fa fa-angle-down"></i>
                                    <input type="hidden" name="daterange" id="daterange"/>
                                </div>&nbsp;&nbsp;
                                <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getSampleResult('daterange');"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                                <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetDateFilter();" style="margin-right:5.8%;"><?php echo $this->translate('Reset'); ?></a>
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div id="sampleResultDetails"></div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Samples Tested'); ?></span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <select id="sampleType" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getTestedSampleResult()">
                                                <option value=""><?php echo $this->translate('All Sample Types'); ?></option>
                                                <?php echo $sType;?>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="portlet-body" style="cursor:pointer;">
                                    <div id="samplesTestedResult"></div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Samples Tested per Lab'); ?></span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <select id="sampleTypeVolume" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getTestedSampleResultBasedLab();">
                                                <option value=""><?php echo $this->translate('All Sample Types'); ?></option>
                                                <?php echo $sType;?>
                                            </select>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="portlet-body" style="cursor:pointer;">
                                    <div id="samplesTestedLabResult"></div>
                                </div>
                            </div>
                        </div>                        
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Gender'); ?> </span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <!--<select id="sampleTypeGender" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getTestedSampleResultBasedGender()">-->
                                            <!--    <option value="">< ?php echo $this->translate('All Sample Types'); ?></option>-->
                                            <!--    < ?php echo $sType;?>-->
                                            <!--</select>-->
                                        </div>
                                    </div>  
                                </div>
                                <div class="portlet-body">
                                    <div id="samplesTestedResultGender" style="height:450px;"></div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Laboratory Turnaround Time'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="labAverageTat" style="height:450px;"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Age'); ?></span>
                                    </div>
                                    <div class="actions" style="width:20%;">
                                        <div class="btn-group" style="width:100%;">
                                            <select id="age" name="age[]" class="form-control" multiple title="<?php echo $this->translate('Please choose age group'); ?>" onchange="getTestedSampleResultBasedAgeGroup();">
                                                <option value="<2"> < 2</option>
                                                <option value="2to5"> 2 - 5</option>
                                                <option value="6to14"> 6 - 14</option>
                                                <option value="15to49"> 15 - 49</option>
                                                <option value=">=50"> >= 50</option>
                                                <option value="unknown"> <?php echo $this->translate('Unknown'); ?></option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="samplesTestedResultAgeGroup"></div>
                                </div>
                            </div>
                        </div>            
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Samples Tested - Pregnant'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="samplesTestedResultPregnantPatient"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Samples Tested - Breastfeeding'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="samplesTestedResultBreastfeedingPatient"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Request Form Completeness'); ?></span>
                                    </div>
                                    <div class="actions" style="width:50%;">
                                        <div class="btn-group" style="width:100%;">
                                            <select id="formFields" name="formFields[]" class="form-control" multiple title="<?php echo $this->translate('Please choose form fields'); ?>" onchange="getRequisitionFormsTested();">
                                                <option value="patient_art_no">Patient ART Number</option>
                                                <option value="patient_age_in_years"> Patient Age</option>
                                                <option value="patient_gender"> Patient Gender</option>
                                                <option value="current_regimen"> Current Regimen</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="portlet-body" id="requisitionForms">
                                    <div id="labDashReqFormBar" style="height:450px;"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Sample Volume'); ?></span>
                                    </div>
                                   <div class="actions">
                                        <div class="btn-group">
                                            <select id="sampleStatus" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getSampleVolume('change');">
                                                <option value=""><?php echo $this->translate('All Samples'); ?></option>
                                                <option value="sample_tested"><?php echo $this->translate('Samples Tested'); ?></option>
                                                <option value="samples_not_tested"><?php echo $this->translate('Samples Not Tested'); ?></option>
                                                <option value="sample_rejected"><?php echo $this->translate('Samples Rejected'); ?></option>
                                            </select>
                                        </div>
                                    </div>                                 
                                </div>
                                <div class="portlet-body" id="pieChartLabResult">
                                    <div id="labDashSampleVolumePie" style="height:450px;"></div>
                                </div>
                            </div>                            
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Female Patients'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body" id="femalePatientPieChart">
                                    <div id="labDashFemalePie" style="height:450px;"></div>
                                </div>
                            </div>                            
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('Line Of Treatment'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body" id="lineOfTreatmentPieChart">
                                    <div id="labDashLineOfTreatmentPie" style="height:450px;"></div>
                                </div>
                            </div>                            
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('VL Suppressed/Not Suppressed'); ?></span>
                                    </div>
                                </div>
                                <div class="portlet-body" id="vlOutComePiechart">
                                    <div id="labDashVlOutcomePie" style="height:450px;"></div>
                                </div>
                            </div>                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject"><?php echo $this->translate('All Facilities - Geolocation'); ?></span>
                                    </div>
                                    
                                    <div class="actions">
                                        <div class="btn-group">
                                            <button class="btn btn-danger" onclick="expandMap();"><span><i class="fa fa-angle-double-right" aria-hidden="true"></i> <?php echo $this->translate('Expand Map'); ?></span></button>
                                        </div>
                                    </div>   
                                    
                                </div>                                
                                <div class="portlet-body">
                                    <div id="controls-polyline"></div>
                                    <div id="gmap-polyline-data"></div>
                                </div>
                            </div>
                        </div>                        
                    </div>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFpbfAKFJZ8Ps7yAGIDZtD4EeBlsb_ANA"></script>
    <script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
    <script>
    //var gfxPath = 'https://raw.githubusercontent.com/highslide-software/pattern-fill/master/graphics/';
    var startDate;
    var endDate;
   
    function getSampleResult(frmSource){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        daterange=$('#daterange').val();
        if(frmSource == 'daterange' && $.trim(daterange) == ''){ alert('<?php echo $this->translate('Please choose date range'); ?>'); return false; }
        if(frmSource !='load'){$.blockUI.defaults.css.border = '1px solid grey'; $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);}
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-result')); ?>",{daterange:daterange,fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#sampleResultDetails").html(data);
        });
    }
    
    function getTestedSampleResult(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        sampleType = $("#sampleType").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result')); ?>",{fromDate:fromDate,toDate:toDate,sampleType:sampleType,facilityId:facilityId},
        function(data) {
            $("#samplesTestedResult").html(data);
        });
    }
    
    function getTestedSampleResultBasedLab(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        sampleType = $("#sampleTypeVolume").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-volume')); ?>",{fromDate:fromDate,toDate:toDate,sampleType:sampleType,facilityId:facilityId},
        function(data) {
            $("#samplesTestedLabResult").html(data);
        });
    }
    
    function getTestedSampleResultBasedGender(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-gender')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#samplesTestedResultGender").html(data);
        });
    }
    
    function getTestedSampleResultBasedAgeGroup(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        age = ($('#age').val() == null)?[]:$('#age').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-age-group')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId,age:age},
        function(data) {
            $("#samplesTestedResultAgeGroup").html(data);
        });
    }
    
    function getTestedSampleResultBasedonPregnantPatient(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-pregnant')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#samplesTestedResultPregnantPatient").html(data);
        });
    }
    
    function getTestedSampleResultBasedonBreastfeedingPatient(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-breastfeeding')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#samplesTestedResultBreastfeedingPatient").html(data);
        });
    }
    
    function getAverageLabTAT(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-lab-turn-around-time')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#labAverageTat").html(data);
        });
    }
    
    function getRequisitionFormsTested(){
        facilityId = $("#labName").val();
        fromDate = $('#mrp-lowerDate').val();
        toDate = $('#mrp-upperDate').val();
        formFields = ($('#formFields').val() == null)?['patient_art_no','patient_age_in_years','patient_gender','current_regimen']:$('#formFields').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-requisition-forms')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId,formFields:formFields},
        function(data) {
            $("#labDashReqFormBar").html(data);
        });
    }
    
    function getSampleVolume(formSrc){
        if(formSrc == 'change'){$.blockUI.defaults.css.border = '1px solid grey';$(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);}
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        sampleStatus = $("#sampleStatus").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-volume')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId,sampleStatus:sampleStatus},
        function(data) {
           $("#labDashSampleVolumePie").html(data);
        });
    }
    
    function femalePatient(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-female-patient-result')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#labDashFemalePie").html(data);
        });
    }
    
    function lineOfTreatment(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-line-of-treatment')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#labDashLineOfTreatmentPie").html(data);
        });
    }
    
    function vlOutComePiechart(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-vl-out-comes')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId},
        function(data) {
            $("#labDashVlOutcomePie").html(data);
        });
    }
    
    function getLabFacilities(){
        facilityId = $("#labName").val();
        fromDate=$('#mrp-lowerDate').val();
        toDate=$('#mrp-upperDate').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-lab-facilities')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId,height:'600px;'},
        function(data) {
            $("#gmap-polyline-data").html(data);
        });
    }
        
    $(function() {
        var start = moment().subtract(12, 'months');
        var end = moment();
        
        function cb(start, end) {
            $('#daterange-container span').html(start.format('MMM D, YYYY') + ' to ' + end.format('MMM D, YYYY'));
            $('#daterange').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        }
    
        $('#labName').select2({
            placeholder: "<?php echo $this->translate('All Labs'); ?>",
            allowClear: true
        });
        
        $('#age').select2({
            placeholder: "<?php echo $this->translate('All Age Group'); ?>",
            allowClear: true
        });
        
        $('#age').on('select2:close', function (evt) {
            var uldiv = $(this).siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>"+count+" items selected</li>");
        });
        
        $('#formFields').select2({
            placeholder: "<?php echo $this->translate('All'); ?>",
            allowClear: true
        });
        
        $('#formFields').on('select2:close', function (evt) {
            var uldiv = $(this).siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>"+count+" items selected</li>");
        });
        
        $('#daterange-container').daterangepicker({
            format: 'DD-MMM-YYYY',
            separator: ' to ',
            startDate: start,
            endDate: end,
            maxDate:moment(),
            ranges: {
               'Today': [moment(), moment()],
               'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
               'Last 7 Days': [moment().subtract(6, 'days'), moment()],
               'Last 30 Days': [moment().subtract(29, 'days'), moment()],
               'This Month': [moment().startOf('month'), moment().endOf('month')],
               'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start, end);
        $('#dashboard-range').show();
        $('#daterange-container span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');
        getEverything();
    });
    
    function getEverything(){
        $.blockUI.defaults.css.border = '1px solid grey'; 
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        if(!$('#sampleCollectionDate').val() ) {
          $('#sampleCollectionDate').val(moment().subtract('days', 179).format('YYYY-MM-DD') + ' to ' + moment().format('YYYY-MM-DD'));
        }
        getSampleResult('load');
        getRequisitionFormsTested();
        getSampleVolume('load');
        getAverageLabTAT();
        getLabFacilities();
        getTestedSampleResult();
        getTestedSampleResultBasedLab();
        getTestedSampleResultBasedGender();
        getTestedSampleResultBasedAgeGroup();
        getTestedSampleResultBasedonPregnantPatient();
        getTestedSampleResultBasedonBreastfeedingPatient();
        femalePatient();
        lineOfTreatment();
        vlOutComePiechart();
    }
       
    function resetEverything(){
       $('#pageFilter')[0].reset();
       $('#labName').val('').change();
       getEverything();
    }
        
    var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    
    $(function () {
      startMonth = <?php echo $startMonth; ?>;
      startYear = <?php echo $startYear; ?>;
      endMonth = <?php echo $endMonth ?>;
      endYear = <?php echo $endYear ?>;
      fiscalMonth = 7;
      if(startMonth < 10)
            startDate = parseInt("" + startYear + '0' + startMonth + "");
      else
        startDate = parseInt("" + startYear  + startMonth + "");
      if(endMonth < 10)
            endDate = parseInt("" + endYear + '0' + endMonth + "");
      else
        endDate = parseInt("" + endYear + endMonth + "");
      
      content = '<div class="row mpr-calendarholder">';
      calendarCount = endYear - startYear;
      if(calendarCount == 0)
        calendarCount++;
      var d = new Date();
      for(y = 0; y < 2; y++){
                    content += '<div class="col-xs-6" ><div class="mpr-calendar row" id="mpr-calendar-' + (y+1) + '">'
                                                     + '<h5 class="col-xs-12"><i class="mpr-yeardown fa fa-chevron-circle-left"></i><span>' + (startYear + y).toString() + '</span><i class="mpr-yearup fa fa-chevron-circle-right"></i></h5><div class="mpr-monthsContainer"><div class="mpr-MonthsWrapper">';
        for(m=0; m < 12; m++){
          var monthval;
          if((m+1) < 10)
            monthval = "0" + (m+1);
          else
            monthval = "" + (m+1);
                            content += '<span data-month="' + monthval  + '" class="col-xs-3 mpr-month">' + MONTHS[m] + '</span>';
        }
        content += '</div></div></div></div>';
      }
      content += '<div class="col-xs-1">';
      //content += '<button class="btn btn-info mpr-fiscal-ytd">Fiscal YTD</button>';
      //content += '<button class="btn btn-info mpr-ytd">YTD</button>';
      //content += '<button class="btn btn-info mpr-prev-fiscal">Previous FY</button>';
      //content += '<button class="btn btn-info mpr-prev-year">Previous Year</button>';
      content += '<button class="btn btn-info mpr-close">Apply</button>';
      content += '</div>';
      content += '</div>';
      
      $(document).on('click','.mpr-month',function(e){
        e.stopPropagation();
                    $month = $(this);
            var monthnum = $month.data('month');
            var year = $month.parents('.mpr-calendar').children('h5').children('span').html();
            if($month.parents('#mpr-calendar-1').size() > 0){
              //Start Date
              startDate = parseInt("" + year + monthnum);
              if(startDate > endDate){
                
                if(year != parseInt(endDate/100))
                  $('.mpr-calendar:last h5 span').html(year);
                   endDate = startDate;
              }
            }else{
              //End Date
              endDate = parseInt("" + year + monthnum);
              if(startDate > endDate){
                if(year != parseInt(startDate/100))
                  $('.mpr-calendar:first h5 span').html(year);
                startDate = endDate;
              }
            }
        
            paintMonths();
      });
      
      
      $(document).on('click','.mpr-yearup',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
                    var year = parseInt($(this).prev().html());
            year++;
            $(this).prev().html(""+year);
                    $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });
      
      $(document).on('click','.mpr-yeardown',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
                    var year = parseInt($(this).next().html());
            year--;
            $(this).next().html(""+year);
                    //paintMonths();
          $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });
      
      $(document).on('click','.mpr-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        startDate = parseInt(d.getFullYear() + "01");
        var month = d.getMonth() + 1;
        if(month < 9)
          month = "0" + month;
        endDate = parseInt("" + d.getFullYear() + month);
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          var year = $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-prev-year', function(e){
        e.stopPropagation();
        var d = new Date();
        var year = d.getFullYear()-1;
        startDate = parseInt(year + "01");
        endDate = parseInt(year + "12");
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          $('h5 span',$cal).html(year);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-fiscal-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 1;
        else
          year = d.getFullYear();
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(d.getMonth()+1 < 10)
          cm = "0" + (d.getMonth()+1);
        else
          cm = (d.getMonth()+1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + d.getFullYear() + cm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-prev-fiscal', function(){
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 2;
        else
          year = d.getFullYear() - 1;
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(fiscalMonth -1 < 10)
          efm = "0" + (fiscalMonth-1);
        else
          efm = (fiscalMonth-1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + (d.getFullYear() - 1) + efm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear()-1);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      var mprVisible = false;
      var mprpopover = $('.mrp-container').popover({
        container: "body",
        placement: "bottom",
        html: true,
        content: content
      }).on('show.bs.popover', function () {
        $('.popover').remove();
        var waiter = setInterval(function(){
          if($('.popover').size() > 0){
            clearInterval(waiter);
            setViewToCurrentYears();
                    paintMonths();
          }
        },50);
      }).on('shown.bs.popover', function(){
        mprVisible = true;
      }).on('hidden.bs.popover', function(){
        mprVisible = false;
      }); 
      
      $(document).on('click','.mpr-calendarholder',function(e){
        e.preventDefault();
        e.stopPropagation();
      });
      $(document).on("click",".mrp-container",function(e){
        if(mprVisible){
          e.preventDefault();
            e.stopPropagation();
          mprVisible = false;
        }
      });
      
      $(document).on("click",function(e){
       
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
      });
      
      $(document).on('click','.mpr-close', function(e){
        //console.log(e);
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
      });
      
    });
    
    function setViewToCurrentYears(){
            var startyear = parseInt(startDate / 100);
        var endyear = parseInt(endDate / 100);
            $('.mpr-calendar h5 span').eq(0).html(startyear);
            $('.mpr-calendar h5 span').eq(1).html(endyear);
    }
    
    function paintMonths(){
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          var year = $('h5 span',$cal).html();
          $('.mpr-month',$cal).each(function(i){
            if((i+1) > 9)
              cDate = parseInt("" + year + (i+1));
            else
              cDate = parseInt("" + year+ '0' + (i+1));
            if(cDate >= startDate && cDate <= endDate){
                $(this).addClass('mpr-selected');
            }else{
              $(this).removeClass('mpr-selected');
            }
          });
        });
        
      $('.mpr-calendar .mpr-month').css("background","");
        //Write Text
        var startyear = parseInt(startDate / 100);
        var startmonth = parseInt(safeRound((startDate / 100 - startyear)) * 100);
        var endyear = parseInt(endDate / 100);
        var endmonth = parseInt(safeRound((endDate / 100 - endyear)) * 100);
        $('.mrp-monthdisplay .mrp-lowerMonth').html(MONTHS[startmonth - 1] + " " + startyear);
        $('.mrp-monthdisplay .mrp-upperMonth').html(MONTHS[endmonth - 1] + " " + endyear);
        //$('#mrp-lowerDate').val(startDate);
        //$('#mrp-upperDate').val(endDate);
        
        if(startmonth < 10)
            startmonth = '0' +startmonth;
        else
        startmonth = startmonth;
        
        if(endmonth < 10){
        endmonth = '0' +endmonth;    
        }
        else{
        endmonth = endmonth;    
        }
        $('#mrp-lowerDate').val(startyear+'-'+startmonth);
        $('#mrp-upperDate').val(endyear+'-'+endmonth);
       
        
            if(startyear == parseInt($('.mpr-calendar:first h5 span').html()))
                    //$('.mpr-calendar:first .mpr-selected:first').css("background","#40667A");
            
             $('.mpr-month').css("color","black");
        if(endyear == parseInt($('.mpr-calendar:last h5 span').html()))
          //$('.mpr-calendar:last .mpr-selected:last').css("background","#40667A");
          $('.mpr-month').css("color","black");
          $('.mpr-calendar:first .mpr-selected:first').css({"background-color": "#40667A","color":"#fff"});
          $('.mpr-calendar:last .mpr-selected:last').css({"background-color": "#40667A","color":"#fff"});
    }
    
    function safeRound(val){
      return Math.round(((val)+ 0.00001) * 100) / 100;
    }
    
    function doSampleResultAwaitedRedirect(frmSource){
       selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
       window.open("/labs/sample-result-awaited?src="+frmSource+"&lab="+selectedLabs);
    }
    
    function doSampleTestedRedirect(month){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?month='+month+'&lab='+selectedLabs, '_blank');
    }
    
    function doSampleTestedBasedonGenderRedirect(month,gender){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?month='+month+'&gender='+gender+'&lab='+selectedLabs, '_blank');
    }
    
    function doSampleTestedBasedonAgeRedirect(month,age){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?month='+month+'&age='+age+'&lab='+selectedLabs, '_blank');
    }
    
    function doSampleTestedBasedonPregnantPatientRedirect(month){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?month='+month+'&gender=F&femaleFilter=P&lab='+selectedLabs, '_blank');
    }
    
    function doSampleTestedBasedonBreastfeedingPatientRedirect(month){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?month='+month+'&gender=F&femaleFilter=BF&lab='+selectedLabs, '_blank');  
    }
    
    function doLabTATRedirect(month){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/get-sample-tested-turn-around-time?month='+month+'&lab='+selectedLabs, '_blank');
    }
    
    function doRequisitionFormRedirect(month){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/requisition-forms-incomplete?month='+month+'&lab='+selectedLabs, '_blank');
    }
    
    function doSampleVolumeRedirect(labCode){
      window.open('/labs/sample-volume?fromMonth='+$('#mrp-lowerDate').val()+'&toMonth='+$('#mrp-upperDate').val()+'&lab='+labCode+'&result='+$("#sampleStatus").val(), '_blank');
    }
    
    function doFemalePatientRedirect(field){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?fromMonth='+$('#mrp-lowerDate').val()+'&toMonth='+$('#mrp-upperDate').val()+'&gender=F&femaleFilter='+field+'&lab='+selectedLabs, '_blank');
    }
    
    function doLineofTreatmentRedirect(field){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?fromMonth='+$('#mrp-lowerDate').val()+'&toMonth='+$('#mrp-upperDate').val()+'&lt='+field+'&lab='+selectedLabs, '_blank');
    }
    
    function doVLResultRedirect(fieldVal){
      selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
      window.open('/labs/samples-tested?fromMonth='+$('#mrp-lowerDate').val()+'&toMonth='+$('#mrp-upperDate').val()+'&result='+fieldVal+'&lab='+selectedLabs, '_blank');
    }
    
    function expandMap(){
       selectedLabs = ($("#labName").val() == null)?'':$("#labName").val();
       window.open("/labs/get-facilities-geolocation?fromDate="+$('#mrp-lowerDate').val()+"&toDate="+$('#mrp-upperDate').val()+"&lab="+selectedLabs);
    }
    
    $("#showDateRange").click(function(){
        $("#showDateRange").hide();
        $("#closeDateRange,.daterange-container").show();
    });
    
    $("#closeDateRange").click(function(){
        $("#closeDateRange,.daterange-container").hide();
        $("#showDateRange").show();
    });
    
    function resetDateFilter(){
       $('#dateFilter')[0].reset();
       $('#daterange-container span').html('<?php echo $this->translate('Choose Date Range'); ?>');
       $('input[name="daterange"]').val('');
       getSampleResult('reset');
    }
</script>