<style>
    .bluebox, .dashboard-stat2{
        border:1px solid #3598DC;
    }
</style>
<?php
$sType = '';
foreach($sampleType as $samples){
    $sType.='<option value="'.base64_encode($samples['type_id']).'">'.ucwords($samples['sample_name']).'</option>';
}
?>
                    <!-- BEGIN PAGE BAR -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Labs Dashboard</a>
                            </li>
                        </ul>
                    </div>

                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    
                    <br>
                    <br>
                    
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-lg-6">
                            <div id="dashboard-report-range" class="btn btn-sm form-control"
                                 data-container="body"
                                 data-placement="bottom"
                                 data-original-title="Change dashboard date range">
                                        DATE RANGE&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-calendar"></i>&nbsp;
                                        <span class="thin uppercase hidden-xs"></span>&nbsp;
                                        <i class="fa fa-angle-down"></i>
                                        <input type="hidden" name="sampleCollectionDate" id="sampleCollectionDate" />
                            </div>
                        </div>
                        <div class="col-lg-4">
                                <a href="javascript:void(0);" class="btn btn-info btn-sm" onclick="getSampleResult(),getTestedSampleResult()">Submit</a>
                            </div>
                    </div><br/>
                    <div class="row">
                        <div id="sampleResultDetails"></div>
                    </div>
                    <div class="row" style="padding-top:10px;padding-bottom:20px;">
                        <div class="col-lg-6">
                                <select class="form-control">
                                    <option>All my Labs</option>
                                    <option>Lab 001</option>
                                    <option>Lab 002</option>
                                    <option>Lab 003</option>
                                    <option>Lab 004</option>
                                    <option>Lab 005</option>
                                </select>
                            </div>
                        <div class="col-lg-6">
                            <div id="dashboard-report" class="btn btn-sm form-control"
                                 data-container="body"
                                 data-placement="bottom"
                                 data-original-title="Change dashboard date range">
                                        DATE RANGE&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-calendar"></i>&nbsp;
                                        <span class="thin uppercase hidden-xs"></span>&nbsp;
                                        <i class="fa fa-angle-down"></i>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">Samples Tested</span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <select id="sampleType" class="btn white btn-outline btn-circle btn-sm dropdown-toggle">
                                                <option value="">Sample Type</option>
                                                <?php echo $sType;?>
                                            </select>
                                        </div>
                                    </div>                                    
                                    
                                </div>
                                <div class="portlet-body" style="cursor:pointer;" onclick="document.location.href='/labs/samples-tested'">
                                    <div id="samplesTestedResult"></div>
                                </div>
                            </div>
                        </div>
                        
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">Samples Tested based on Volume</span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <select id="sampleTypeVolume" class="btn white btn-outline btn-circle btn-sm dropdown-toggle">
                                                <option value="">Sample Type</option>
                                                <?php echo $sType;?>
                                            </select>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="portlet-body" style="cursor:pointer;" onclick="document.location.href='/labs/samples-tested'">
                                    <div id="facilitiesTestedValue"></div>
                                </div>
                            </div>
                        </div>                        
                        
                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">Laboratory Turnaround Time</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="labAverageTat"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Requisition Forms for Testing</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="reqformspie"></div>
                                </div>
                            </div>                            
                            
                            
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Sample Volume</span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <a href="" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> Sample Type
                                                <span class="fa fa-angle-down"> </span>
                                            </a>
                                            <ul class="dropdown-menu pull-right">
                                                <li class="active">
                                                    <a href="javascript:;"> All
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> DBS
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Plasma
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="portlet-body">
                                    <div id="gotoPie"></div>
                                </div>
                            </div>                            
                            
                            
                        </div>

                       
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">Facilities</span>
                                    </div>
                                </div>                                
                                <div class="portlet-body">

                                    <div id="controls-polyline"></div>
                                    <div id="gmap-polyline"  class="mapChart" style="height:600px !important;"></div>
                                    
                                </div>
                            </div>
                        </div>                        
                    </div>
        
        <script src="https://maps.google.com/maps/api/js?libraries=geometry&v=3.22&key=AIzaSyAFpbfAKFJZ8Ps7yAGIDZtD4EeBlsb_ANA"></script>
        <script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/scripts/maplace.min.js'); ?>"></script>
        
        
        <script>
            
            var gfxPath = 'https://raw.githubusercontent.com/highslide-software/pattern-fill/master/graphics/';

            
        function getSampleResult()
        {
            dateRange = $("#sampleCollectionDate").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-result')); ?>",{sampleCollectionDate:dateRange},
        function(data) {
            $("#sampleResultDetails").html(data);
        });
        } 
        function getTestedSampleResult()
        {
            sampleType = $("#sampleType").val();
            dateRange = $("#sampleCollectionDate").val();
            $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result')); ?>",{sampleCollectionDate:dateRange,sampleType:sampleType},
            function(data) {
            $("#samplesTestedResult").html(data);
            });
        }
        function getTestedSampleResultBasedVolume()
        {
            sampleType = $("#sampleTypeVolume").val();
            dateRange = $("#sampleCollectionDate").val();
            $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-volume')); ?>",{sampleCollectionDate:dateRange,sampleType:sampleType},
            function(data) {
            $("#facilitiesTestedValue").html(data);
            });
        }
            
            $(function () {
                
                $('#dashboard-report-range').daterangepicker({
                "ranges": {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                },
                "locale": {
                    "format": "YYYY-MM-DD",
                    "separator": " to ",
                    "applyLabel": "Apply",
                    "cancelLabel": "Cancel",
                    "fromLabel": "From",
                    "toLabel": "To",
                    "customRangeLabel": "Custom",
                    "daysOfWeek": [
                        "Su",
                        "Mo",
                        "Tu",
                        "We",
                        "Th",
                        "Fr",
                        "Sa"
                    ],
                    "monthNames": [
                        "January",
                        "February",
                        "March",
                        "April",
                        "May",
                        "June",
                        "July",
                        "August",
                        "September",
                        "October",
                        "November",
                        "December"
                    ],
                    //"firstDay": 1
                },
                //"startDate": "11/08/2015",
                //"endDate": "11/14/2015",
                opens: "left",
            }, function(start, end, label) {
                $('#dashboard-report-range span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
                $('#sampleCollectionDate').val(start.format('YYYY-MM-DD') + ' - ' + end.format('YYYY-MM-DD'));
            });
                $('#dashboard-report-range span').html(moment().subtract('days', 29).format('MMMM D, YYYY') + ' - ' + moment().format('MMMM D, YYYY'));
                $('#dashboard-report-range').show();
                
                getSampleResult();
                getTestedSampleResult();
                getTestedSampleResultBasedVolume();
                
$('#reqformspie').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        xAxis: {
            categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Forms'
            },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        legend: {
            align: 'right',
            x: -30,
            verticalAlign: 'top',
            y: 25,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
            borderColor: '#CCC',
            borderWidth: 1,
            shadow: false
        },
        tooltip: {
            headerFormat: '<b>{point.x}</b><br/>',
            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                cursor: 'pointer',
                point: {
                    events: {
                        click: function () {
                            window.location.href='/labs/requisition-forms-incomplete';
                        }
                    }
                },
                dataLabels: {
                    enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black'
                    }
                }
            }
        },
        series: [{
            name: 'Incomplete',
            data: [5, 3, 4, 7, 2, 7, 2]
        }, {
            name: 'Complete',
            data: [2, 2, 3, 2, 1, 2, 1]
        }],
    colors: [
        '#64ade5',
        '#8877a9'
    ]
    });

    $('#gotoPie').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: ''
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Labs',
            colorByPoint: true,
            data: [{
                name: 'Lab 001',
                y: 33
            }, {
                name: 'Lab 002',
                y: 24
            }, {
                name: 'Lab 003',
                y: 10
            }, {
                name: 'Lab 004',
                y: 47
            }, {
                name: 'Lab 005',
                y: 19
            }, {
                name: 'Lab 006',
                y: 20
            }]
        }]
    });
    
    
    $('#labAverageTat').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: ''
        },
        subtitle: {
            text: ''
        },
        xAxis: {
            categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
        },
        yAxis: {
            title: {
                text: 'TAT in Hours'
            },plotLines: [{
                    value: 16,
                    color: 'red',
                    width: 2
                }]
        },
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                }
            }
        },
        series: [{
            name: 'Plasma',
            data: [14,16,15,13,16,17,15],
            color : '#64ade5',
            visible : false
        },{
            name: 'DBS',
            data: [15,17,19,10,16,11,12],
            color : '#8877a9',
            visible : false
        },{
            name: 'All',
            data: [14.5,16.5,17,11.5,16,14,13.5],
            color : '#1B325F'
        }
        
        ]
    });
                    
                    
                    
                    
                    
                    
var LocsAv2 = [
    {
       
        lat: -26.305201,
        lon: 31.1349953,
        title: 'Mbabne',
        html: '<h3>Mbabne</h3>',
        draggable: false
    },
    {
        lat: -26.305201,
        lon: 31.6049953,
        title: 'Big Bend',
        html: [
            '<h3>ANOTHER Bend</h3>',
            '<p>Lorem Ipsum..</p>'
        ].join(''),
        zoom: 8,
        visible: true
    },
    {
        lat: -26.210721,
        lon: 31.9243163,
        title: 'Simunye',
        html: '<h3>Simunye</h3>',
        visible: true,
        draggable: false
    },
    {
        lat: -26.782000,
        lon: 31.9285000,
        title: 'Big Bend',
        html: [
            '<h3>Big Bend</h3>',
            '<p>Lorem Ipsum..</p>'
        ].join(''),
        zoom: 8,
        visible: true
    }
];
                    

var locations = [
  //Starting Point is "Home", and links to other locations"//
  ['Mbabne', -26.305201, 31.1349953, '<?php echo $this->basePath('assets/img/lab0.png') ?>', '<strong>No. of Samples : 30</strong>'],
  ['Big Bend', -26.781057, 31.9284363, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 10</strong>'],
  ['Simunye', -26.210721, 31.9243163, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 33</strong>'],
  ['Siteki', -26.434603, 31.9239713, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 40</strong>'],
  ['Maloma', -26.998871, 31.6534333, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 90</strong>']
]

function initMap() {

  var map = new google.maps.Map(document.getElementById('gmap-polyline'), {
    scrollwheel: false,
    zoom: 13,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    center: {
      lat: 0,
      lng: 0
    }
  });
  var markers = [];
  var bounds = new google.maps.LatLngBounds();
  // Add the markers and infowindows to the map
  for (var i = 0; i < locations.length; i++) {

    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(locations[i][1], locations[i][2]),
      title: locations[i][0],     
      map: map,
      icon: locations[i][3]      
    });
    
    marker['infowindow'] = new google.maps.InfoWindow({
        content: locations[i][4]      
    });    
    
    google.maps.event.addListener(marker, 'mouseover', function() {
        this['infowindow'].open(map, this);
    });    
    
    
    markers.push(marker);
    bounds.extend(marker.getPosition());
    if (i > 0) {
      var sitepath = new google.maps.Polyline({
        path: [markers[0].getPosition(), marker.getPosition()],
        geodesic: true,
        strokeColor: '#F00',
        strokeOpacity: 0.5,
        strokeWeight: 2,
        map: map
      });
    }
  }
  map.fitBounds(bounds);
}
google.maps.event.addDomListener(window, "load", initMap);
     
                    
                    
                    
                });
        </script>