<?php

use Zend\Session\Container;
$logincontainer = new Container('credo');
$languagecontainer = new Container('language');
$startYear = date("Y", strtotime("-1 year"));
$startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
$endYear = date('Y');
$endMonth = date('m');

$startDate = date('Y-m', strtotime('+1 month', strtotime('-1 year')));
$endDate = date('Y-m');
?>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/plugins/datepicker/datepicker3.css') ?>">
<style>
    .bluebox,
    .dashboard-stat2 {
        border: 1px solid #3598DC;
    }

    .mrp-monthdisplay {
        display: inline-block !important;
        border-radius: 0px 5px 5px 0px;
        cursor: pointer;
    }

    .mrp-lowerMonth,
    .mrp-upperMonth {
        color: #40667A;
        font-weight: bold;
        font-size: 11px;
        text-transform: uppercase;
    }

    .mrp-to {
        color: #aaa;
        margin-right: 0px;
        margin-left: 0px;
        font-size: 11px;
        text-transform: uppercase;
        /* background-color: #eee; */
        padding: 5px 3px 5px 3px;
    }

    .mpr-calendar {
        display: inline-block;
        padding: 3px 5px;
        border-right: solid #999 1px;
    }

    .mpr-calendar::last-child {
        border-right: none;
    }

    .mpr-month {
        padding: 20px;
        text-transform: uppercase;
        font-size: 12px;
    }

    .mpr-calendar h5 {
        width: 100%;
        text-align: center;
        font-weight: bold;
        font-size: 18px
    }

    .mpr-selected {}

    .mpr-month:hover {
        border-radius: 5px;
        box-shadow: 0 0 0 1px #ddd inset;
        cursor: pointer;
    }

    .mpr-selected.mpr-month:hover {
        border-radius: 0px;
        box-shadow: none;
    }

    .mpr-calendarholder .col-xs-6 {
        max-width: 250px;
        min-width: 250px;
    }

    .mpr-calendarholder .col-xs-1 {
        max-width: 150px;
        min-width: 150px;
    }

    .mpr-calendarholder .btn-info {
        background-color: #40667A;
        border-color: #406670;
        width: 100%;
        margin-bottom: 10px;
        text-transform: uppercase;
        font-size: 10px;
        padding: 10px 0px;
    }

    .mpr-quickset {
        color: #666;
        text-transform: uppercase;
        text-align: center;
    }

    .mpr-yeardown,
    .mpr-yearup {
        margin-left: 5px;
        cursor: pointer;
        color: #666;
    }

    .mpr-yeardown {
        float: left;
    }

    .mpr-yearup {
        float: right;
    }

    .mpr-yeardown:hover,
    .mpr-yearup:hover {
        color: #40667A;
    }

    .mpr-calendar:first .mpr-selected:first {
        background-color: #40667A;
    }

    .mpr-calendar:last .mpr-selected:last {
        background-color: #40667A;
    }

    .popover {
        max-width: 1920px !important;
    }

    .table>tbody>tr>td,
    .table>tbody>tr>th,
    .table>tfoot>tr>td,
    .table>tfoot>tr>th,
    .table>thead>tr>td,
    .table>thead>tr>th {
        padding: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '8' : '3'; ?>px;
        font-size: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '14' : '13'; ?>px;
    }

    .select2-search__field,
    .select2-selection__rendered {
        color: #333;
        text-align: center;
    }

    .select2-container--default {
        width: 100% !important;
    }

    .select2-selection--multiple {
        border-radius: 10px !important;
    }

    @media screen and (min-width:320px) and (max-width: 760px) {
        #daterange-container {
            width: 100% !important;
        }

        #showDateRange,
        #closeDateRange {
            margin-left: 0% !important;
        }
    }

    @media screen and (min-width:761px) and (max-width: 970px) {
        #daterange-container {
            width: 100% !important;
        }

        #showDateRange,
        #closeDateRange {
            margin-left: 52% !important;
        }
    }

    .select2-container--default .select2-selection--single {
        height: 34px !important;
    }
</style>

<link href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css" rel="stylesheet">

<?php
$sType = '';
foreach ($sampleType as $samples) {
    $sType .= '<option value="' . base64_encode($samples['sample_id']) . '">' . ucwords($samples['sample_name']) . '</option>';
}
?>
<!-- BEGIN PAGE BAR -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <h1 class="page-title"><?php echo $this->translate('Labs Dashboard'); ?></h1>
</div>

<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->

<br>
<br>

<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->

<div class="row" style="margin-bottom:20px;">
    <div class="col-md-12 col-sm-12" style="text-align:center;">
        <a id="showDateRange" href="javascript:void(0);" style="color:#0d68e0;box-shadow: 1px 2px 12px rgb(173, 200, 222);border-radius: 12px;padding: 2px 10px 2px 10px;margin-left:26%;"><i class="fa fa-chevron-down" aria-hidden="true"></i> <?php echo $this->translate('Show Date Filter'); ?></a>
        <a id="closeDateRange" href="javascript:void(0);" style="color:#0d68e0;display:none;box-shadow: 1px 2px 12px rgb(173, 200, 222);border-radius: 12px;padding: 2px 10px 2px 10px;margin-left:26%;"><i class="fa fa-chevron-up" aria-hidden="true"></i> <?php echo $this->translate('Close Date Filter'); ?></a>
    </div>
</div>
<form id="dateFilter" action="#" method="">
    <div class="daterange-container row" style="margin-bottom:20px;display:none;">
        <div class="col-md-12 col-sm-12" style="text-align:right;">
            <div id="daterange-container" class="btn btn-sm form-control" data-container="body" data-placement="bottom" data-original-title="Change date range" style="text-align:center;width:50%;">
                <i class="icon-calendar"></i>&nbsp;
                <span class="thin uppercase hidden-xs"></span>&nbsp;
                <i class="fa fa-angle-down"></i>
                <input type="hidden" name="daterange" id="daterange" />
            </div>&nbsp;&nbsp;
            <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getSampleResult('daterange');"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
            <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetDateFilter();" style="margin-right:5.8%;"><?php echo $this->translate('Reset'); ?></a>
        </div>
    </div>
</form>
<div class="row">
    <div id="sampleResultDetails"></div>
</div>
<hr style="background: #000 !important;border-color:#ccc;">
<form id="pageFilter" action="#" method="">
    <div class="row" style="padding-top:10px;padding-bottom:10px;">
        <div class="col-lg-6">
            <select name="provinceName[]" id="provinceName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more province. Leave blank for All'); ?>" onchange="selectDistrictName();">
                <?php
                foreach ($provinceName as $province) {
                ?>
                    <option value="<?php echo $province['location_id']; ?>"><?php echo $province['location_name']; ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="col-lg-6" id="districtHeight">
            <select name="districtName[]" id="districtName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more district. Leave blank for All'); ?>" onchange="selectLabName();">
                <?php
                foreach ($districtName as $district) {
                ?>
                    <option data-parent-location="<?php echo $district['parent_location']; ?>" value="<?php echo $district['location_id']; ?>"><?php echo $district['location_name']; ?></option>
                <?php
                }
                ?>
                <option value="0">Empty</option>
            </select>
        </div>
    </div>
    <div class="row" style="padding-top:5px;padding-bottom:20px;">
        <div class="col-lg-6" id="labHeight">
            <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more labs. Leave blank for All'); ?>">
                <?php
                foreach ($labName as $lab) {
                ?>
                    <option data-name="<?php echo $lab['facility_name']; ?>" data-district="<?php echo $lab['facility_district']; ?>" value="<?php echo $lab['facility_id']; ?>"><?php echo $lab['facility_code'] . " - " . $lab['facility_name']; ?></option>
                <?php
                }
                ?>

            </select>
        </div>
        <div class="col-lg-3" style="display: flex;">
            <!-- <div id="sla-date-range" class="mrp-container form-control">
                <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                <div class="mrp-monthdisplay ">
                    <span class="mrp-lowerMonth"><?php echo date("M Y", strtotime('+1 month', strtotime('-1 year'))); ?></span>
                    <span class="mrp-to"> to </span>
                    <span class="mrp-upperMonth"><?php echo date('M Y'); ?></span>
                </div>
                <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" onchange="" />
                <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
            </div> -->
            <div class="input-append date" id="dpMonthsStart" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                <input type="text" class="form-control isRequired readonly" id="mrp-lowerDate" name="mrp-lowerDate" placeholder="Select month & year" title="Please select month and year" readonly="readonly" value="<?php echo date('M-Y',strtotime($startDate)); ?>" />
                <span class="add-on" style="display:none;"><i class="icon-calendar"></i></span>
            </div>
            <div class="input-group-prepend input-group-append" style=" padding-top: 5px; ">
                <span class="input-group-text font-w600" style="padding: 0.100rem .35rem;">
                    <!-- <i class="fa fa-fw fa-arrow-right"></i> --> to
                </span>
            </div>
            <div class="input-append date" id="dpMonthsEnd" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                <input type="text" class="form-control isRequired readonly" id="mrp-upperDate" name="mrp-upperDate" placeholder="Select month & year" title="Please select month and year" readonly="readonly" value="<?php echo date('M-Y',strtotime($endDate)); ?>" />
                <span class="add-on" style="display:none;"><i class="icon-calendar"></i></span>
            </div>
        </div>
        <div class="col-lg-3">
            <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getEverything();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
            <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested'); ?></span>
                </div>
                <div class="actions">
                    <!-- <a class="btn btn-danger" onclick="expandChart('stb');"><span><i class="fa fa-angle-double-right" aria-hidden="true"></i> <?php echo $this->translate('Expand'); ?></span></a> -->
                    <div class="btn-group">
                        <select id="sampleType" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getTestedSampleResult()">
                            <option value=""><?php echo $this->translate('All Sample Types'); ?></option>
                            <?php echo $sType; ?>
                        </select>

                    </div>
                </div>
            </div>
            <div class="portlet-body" style="cursor:pointer;">
                <div id="samplesTestedResult"></div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested per Lab'); ?></span>
                </div>
                <div class="actions">
                    <div class="btn-group">
                        <select id="sampleTypeVolume" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getTestedSampleResultBasedLab();">
                            <option value=""><?php echo $this->translate('All Sample Types'); ?></option>
                            <?php echo $sType; ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="portlet-body" style="cursor:pointer;">
                <div id="samplesTestedLabResult"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Gender'); ?> </span>
                </div>
                <div class="actions">
                    <div class="btn-group">
                        <!--<select id="sampleTypeGender" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getTestedSampleResultBasedGender()">-->
                        <!--    <option value="">< ?php echo $this->translate('All Sample Types'); ?></option>-->
                        <!--    < ?php echo $sType;?>-->
                        <!--</select>-->
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultGender" style="height:450px;"></div>
            </div>
        </div>
    </div>

    <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Laboratory Turnaround Time'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="labAverageTat" style="height:400px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Age < 2'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultAgeGroupLessThanTwo"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Age 2-5'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultAgeGroupTwoToFive"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Age 6-14'); ?></span>
                </div>

            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultAgeGroupSixToFourteen"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Age 15-49'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultAgeGroupFifteenToFourtyNine"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Age >=50'); ?></span>
                </div>

            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultAgeGroupGreaterThanFifty"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested based on Age unknown'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultAgeGroupUnknown"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Reason for VL Testing'); ?></span>
                </div>
                <div class="actions" style="width:20%;">
                    <div class="btn-group" style="width:100%;">
                        <select id="testedReason" name="testedReason" class="form-control" title="<?php echo $this->translate('Please choose test reason'); ?>" onchange="getTestedSampleReason();">
                            <option value=""><?php echo $this->translate('Test Reasons'); ?></option>
                            <?php
                            foreach ($testReason as $test) {
                            ?>
                                <option value="<?php echo base64_encode($test['test_reason_id']); ?>"><?php echo $test['test_reason_name']; ?></option>
                            <?php
                            }
                            ?>
                        </select>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedReason"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested - Pregnant'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultPregnantPatient"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested - Breastfeeding'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samplesTestedResultBreastfeedingPatient"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Request Form Completeness'); ?></span>
                </div>
                <div class="actions" style="width:50%;">
                    <div class="btn-group" style="width:100%;">
                        <select id="formFields" name="formFields[]" class="form-control" multiple title="<?php echo $this->translate('Please choose form fields'); ?>" onchange="getRequisitionFormsTested();">
                            <option value="patient_art_no">Patient ART Number</option>
                            <option value="patient_age_in_years"> Patient Age</option>
                            <option value="patient_gender"> Patient Gender</option>
                            <option value="current_regimen"> Current Regimen</option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="portlet-body" id="requisitionForms">
                <div id="labDashReqFormBar" style="height:500px;"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Sample Volume'); ?></span>
                </div>
                <div class="actions">
                    <div class="btn-group">
                        <select id="sampleStatus" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" onchange="getSampleVolume('change');">
                            <option value=""><?php echo $this->translate('All Samples'); ?></option>
                            <option value="sample_tested"><?php echo $this->translate('Samples Tested'); ?></option>
                            <option value="samples_not_tested"><?php echo $this->translate('Samples Not Tested'); ?></option>
                            <option value="sample_rejected"><?php echo $this->translate('Samples Rejected'); ?></option>
                        </select>
                    </div>
                </div>
            </div>
            <div class="portlet-body" id="pieChartLabResult">
                <div id="labDashSampleVolumePie" style="height:500px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Female Patients'); ?></span>
                </div>
            </div>
            <div class="portlet-body" id="femalePatientPieChart">
                <div id="labDashFemalePie" style="height:500px;"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Line Of Treatment'); ?></span>
                </div>
            </div>
            <div class="portlet-body" id="lineOfTreatmentPieChart">
                <div id="labDashLineOfTreatmentPie" style="height:500px;"></div>
            </div>
        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box">
            <div class="portlet-body">
                <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs"></i><?php echo $this->translate('Sample Overview'); ?>
                        </div>


                    </div>
                    <div class="portlet-body">

                        <div class="form-inline" style="clear:both !important;width:100% !important;">

                            <select id="quarter" class="form-control" style="width:100px;">
                                <option value="">Quarter</option>
                                <option value="1">Q1</option>
                                <option value="2">Q2</option>
                                <option value="3">Q3</option>
                                <option value="4">Q4</option>
                            </select>
                            <select id="year" class="form-control" style="width:100px;">
                                <option value="">Year</option>
                                <?php
                                $year = date('Y');
                                for ($i = $year; $i >= ($year - 5); $i--) {
                                ?>
                                    <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                                <?php
                                }


                                ?>
                            </select>
                            <div class="btn-group" style="width:300px;">
                                <select id="clinicId" class="form-control">
                                    <option value="">--All Facilities--</option>
                                    <?php
                                    foreach ($clinicName as $clinic) {
                                    ?>
                                        <option value="<?php echo $clinic['facility_id']; ?>" data-district="<?php echo $clinic['facility_district']; ?>"><?php echo $clinic['facility_code'] . " - " . $clinic['facility_name']; ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <button class="btn btn-primary" onclick="sampleStatusDataTable();return false;"><span>Filter</span></button>
                        </div>
                        <br>
                        <div class="table-toolbar" id="sampleStatusDataTableDiv">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row" style="display:none;">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('All Facilities - Geolocation'); ?></span>
                </div>
                <div class="actions">
                    <div class="btn-group">
                        <button class="btn btn-danger" onclick="expandMap();"><span><i class="fa fa-angle-double-right" aria-hidden="true"></i> <?php echo $this->translate('Expand Map'); ?></span></button>
                    </div>
                </div>
            </div>
            <div class="portlet-body">
                <div id="controls-polyline"></div>
                <div id="gmap-polyline-data"></div>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->basePath('assets/plugins/datepicker/bootstrap-datepicker.js') ?>"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFpbfAKFJZ8Ps7yAGIDZtD4EeBlsb_ANA"></script>
<script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.flash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.print.min.js"></script>
<script>
    //var gfxPath = 'https://raw.githubusercontent.com/highslide-software/pattern-fill/master/graphics/';
    var startDate;
    var endDate;
    var oTable;

    function getSampleResult(frmSource) {
        var daterange = $('#daterange').val();
        if (frmSource == 'daterange' && $.trim(daterange) == '') {
            alert('<?php echo $this->translate('Please choose date range'); ?>');
            return false;
        }
        //if(frmSource !='load'){$.blockUI.defaults.css.border = '1px solid grey'; $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);}
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-result')); ?>", {
                daterange: daterange
            },
            function(data) {
                $("#sampleResultDetails").html(data);
            });
    }


    function sampleStatusDataTable() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var sampleType = ($("#sampleType").val() == null) ? '' : $("#sampleType").val();
        var labID = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var clinicId = $("#clinicId").val();
        var year = $("#year").val();
        var quarter = $("#quarter").val();

        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-status-data-table')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                sampleType: sampleType,
                labID: labID,
                clinicId: clinicId,
                quarter: quarter,
                year: year
            },
            function(data) {
                $("#sampleStatusDataTableDiv").html(data);
                $("#sampleStatusTable").DataTable({
                    dom: 'Bfrtip',
                    buttons: [{
                        extend: 'excelHtml5',
                        text: 'Export To Excel',
                        title: 'SampleStatus-VLDashboard',
                        extension: '.xlsx'
                    }]
                });
            });


    }

    function getTestedSampleResult() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var sampleType = ($("#sampleType").val() == null) ? '' : $("#sampleType").val();
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                sampleType: sampleType,
                facilityId: facilityId
            },
            function(data) {
                $("#samplesTestedResult").html(data);
            });
    }

    function getTestedSampleResultBasedLab() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var sampleType = ($("#sampleTypeVolume").val() == null) ? '' : $("#sampleTypeVolume").val();
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-volume')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                sampleType: sampleType,
                facilityId: facilityId
            },
            function(data) {
                $("#samplesTestedLabResult").html(data);
            });
    }

    function getTestedSampleResultBasedGender() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-gender')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#samplesTestedResultGender").html(data);
            });
    }

    function getAverageLabTAT() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-lab-turn-around-time')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#labAverageTat").html(data);
            });
    }

    function getTestedSampleResultBasedAgeGroupLessThanTwo() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var age = '<2';
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-age-group')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                age: age
            },
            function(data) {
                $("#samplesTestedResultAgeGroupLessThanTwo").html(data);
            });
    }

    function getTestedSampleResultBasedAgeGroupTwoToFive() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var age = '2to5';
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-age-group-two-to-five')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                age: age
            },
            function(data) {
                $("#samplesTestedResultAgeGroupTwoToFive").html(data);
            });
    }

    function getTestedSampleResultBasedAgeGroupSixToFourteen() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var age = '6to14';
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-age-group-six-to-fourteen')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                age: age
            },
            function(data) {
                $("#samplesTestedResultAgeGroupSixToFourteen").html(data);
            });
    }

    function getTestedSampleResultBasedAgeGroupFifteenToFourtyNine() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var age = '15to49';
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-age-group-fifteen-to-fourtynine')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                age: age
            },
            function(data) {
                $("#samplesTestedResultAgeGroupFifteenToFourtyNine").html(data);
            });
    }

    function getTestedSampleResultBasedAgeGroupGreaterThanFifty() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var age = '>=50';
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-age-group-greater-fifty')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                age: age
            },
            function(data) {
                $("#samplesTestedResultAgeGroupGreaterThanFifty").html(data);
            });
    }

    function getTestedSampleResultBasedAgeGroupUnknown() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var age = 'unknown';
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-age-group-unknown')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                age: age
            },
            function(data) {
                $("#samplesTestedResultAgeGroupUnknown").html(data);
            });
    }

    function getTestedSampleReason() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var testedReason = ($('#testedReason').val() == null) ? '' : $('#testedReason').val();
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-reason-bar-chart')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                testedReason: testedReason
            },
            function(data) {
                $("#samplesTestedReason").html(data);
            });
    }

    function getTestedSampleResultBasedonPregnantPatient() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-pregnant')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#samplesTestedResultPregnantPatient").html(data);
            });
    }

    function getTestedSampleResultBasedonBreastfeedingPatient() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-test-result-breastfeeding')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#samplesTestedResultBreastfeedingPatient").html(data);
            });
    }

    function getRequisitionFormsTested() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var formFields = ($('#formFields').val() == null) ? "patient_art_no,patient_age_in_years,patient_gender,current_regimen" : $('#formFields').val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-requisition-forms')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                formFields: formFields
            },
            function(data) {
                $("#labDashReqFormBar").html(data);
            });
    }

    function getSampleVolume(formSrc) {
        //if(formSrc == 'change'){$.blockUI.defaults.css.border = '1px solid grey';$(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);}
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        var sampleStatus = ($("#sampleStatus").val() == null) ? '' : $("#sampleStatus").val();
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-volume')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                sampleStatus: sampleStatus
            },
            function(data) {
                $("#labDashSampleVolumePie").html(data);
            });
    }

    function femalePatient() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-female-patient-result')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#labDashFemalePie").html(data);
            });
    }

    function lineOfTreatment() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-line-of-treatment')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#labDashLineOfTreatmentPie").html(data);
            });
    }

    function getLabFacilities() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('laboratory', array('action' => 'get-lab-facilities')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId,
                height: '600px;'
            },
            function(data) {
                $("#gmap-polyline-data").html(data);
            });
    }

    $(function() {
        $('#provinceName').select2({
            placeholder: "<?php echo $this->translate('All Province'); ?>",
            allowClear: true
        });
        $('#districtName').select2({
            placeholder: "<?php echo $this->translate('All Districts'); ?>",
            allowClear: true,
            //maxPlaceholderOpts : 10
        });
        $('#provinceName').on('select2:close', function(evt) {
            var uldiv = $('#districtName').siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
            var uldiv = $('#labName').siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
        });
        $('#districtName').on('select2:close', function(evt) {
            var uldiv = $(this).siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
            var uldiv = $('#labName').siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
        });

        $('#labName').select2({
            placeholder: "<?php echo $this->translate('All Labs'); ?>",
            allowClear: true
        });
        $('#labName').on('select2:close', function(evt) {
            var uldiv = $('#labName').siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
        });

        $('#age').select2({
            placeholder: "<?php echo $this->translate('All Age Group'); ?>",
            allowClear: true
        });

        $('#age').on('select2:close', function(evt) {
            var uldiv = $(this).siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
        });

        $('#formFields').select2({
            placeholder: "<?php echo $this->translate('All'); ?>",
            allowClear: true
        });

        $('#formFields').on('select2:close', function(evt) {
            var uldiv = $(this).siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
        });

        $('#clinicId').select2({
            placeholder: "<?php echo $this->translate('All Facilities'); ?>",
            allowClear: true
        }).on("change", function(e) {

        });

        var start = moment().subtract(12, 'months');
        var end = moment();

        function cb(start, end) {
            $('#daterange-container span').html(start.format('MMM D, YYYY') + ' to ' + end.format('MMM D, YYYY'));
            $('#daterange').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        }
        $('#daterange-container').daterangepicker({
            format: 'DD-MMM-YYYY',
            separator: ' to ',
            startDate: start,
            endDate: end,
            <?php if(isset($logincontainer->sampleTable) && $logincontainer->sampleTable == "dash_vl_request_form_current"){?>
            minDate:moment().subtract(12, 'months'),
            <?php }?>
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start, end);
        $('#dashboard-range').show();
        $('#daterange-container span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');

        getSampleResult('load');
        getEverything();

    });

    function getEverything() {
        $.blockUI.defaults.css.border = '1px solid grey';
        //$(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        if (!$('#sampleCollectionDate').val()) {
            $('#sampleCollectionDate').val(moment().subtract('days', 179).format('YYYY-MM-DD') + ' to ' + moment().format('YYYY-MM-DD'));
        }



        $.when(getTestedSampleResult(), getTestedSampleResultBasedLab())
            .done(function() {
                getTestedSampleResultBasedGender();
                getAverageLabTAT();
            });

        $.when(getTestedSampleResultBasedAgeGroupLessThanTwo(),
                getTestedSampleResultBasedAgeGroupTwoToFive(),
                getTestedSampleResultBasedAgeGroupSixToFourteen(),
                getTestedSampleResultBasedAgeGroupFifteenToFourtyNine(),
                getTestedSampleResultBasedAgeGroupGreaterThanFifty(),
                getTestedSampleResultBasedAgeGroupUnknown())
            .done(function() {

                $.when(getTestedSampleReason(),
                        getTestedSampleResultBasedonPregnantPatient(),
                        getTestedSampleResultBasedonBreastfeedingPatient())
                    .done(function() {
                        getRequisitionFormsTested();
                        getSampleVolume('load');
                        // getLabFacilities();
                        femalePatient();
                        lineOfTreatment();
                        sampleStatusDataTable();
                    });


            });














    }

    function resetEverything() {
        $('#pageFilter')[0].reset();
        $('#labName').val('').change();
        getEverything();
    }

    function doSampleResultAwaitedRedirect(frmSource) {
        window.open("/labs/sample-result-awaited?src=" + frmSource);
    }

    function doSampleTestedRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/samples-tested?month=' + month + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonGenderRedirect(month, gender) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/samples-tested?month=' + month + '&gender=' + gender + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonAgeRedirect(month, age) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/samples-tested?month=' + month + '&age=' + age + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonPregnantPatientRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/samples-tested?month=' + month + '&gender=F&femaleFilter=P&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonBreastfeedingPatientRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/samples-tested?month=' + month + '&gender=F&femaleFilter=BF&lab=' + selectedLabs, '_blank');
    }

    function doLabTATRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/times/dashboard?month=' + month + '&lab=' + selectedLabs, '_blank');
    }

    function doRequisitionFormRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/requisition-forms-incomplete?month=' + month + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleVolumeRedirect(labCode) {
        window.open('/labs/sample-volume?fromMonth=' + formatDate($('#mrp-lowerDate').val()) + '&toMonth=' + formatDate($('#mrp-upperDate').val()) + '&lab=' + labCode + '&result=' + $("#sampleStatus").val(), '_blank');
    }

    function doFemalePatientRedirect(field) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/samples-tested?fromMonth=' + formatDate($('#mrp-lowerDate').val()) + '&toMonth=' + formatDate($('#mrp-upperDate').val()) + '&gender=F&femaleFilter=' + field + '&lab=' + selectedLabs, '_blank');
    }

    function doLineofTreatmentRedirect(field) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/labs/samples-tested?fromMonth=' + formatDate($('#mrp-lowerDate').val()) + '&toMonth=' + formatDate($('#mrp-upperDate').val()) + '&lt=' + field + '&lab=' + selectedLabs, '_blank');
    }

    function expandMap() {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open("/labs/get-facilities-geolocation?fromDate=" + formatDate($('#mrp-lowerDate').val()) + "&toDate=" + formatDate($('#mrp-upperDate').val()) + "&lab=" + selectedLabs);
    }

    $("#showDateRange").click(function() {
        $("#showDateRange").hide();
        $("#closeDateRange,.daterange-container").show();
    });

    $("#closeDateRange").click(function() {
        $("#closeDateRange,.daterange-container").hide();
        $("#showDateRange").show();
    });

    function resetDateFilter() {
        $('#dateFilter')[0].reset();
        $('#daterange-container span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');
        getSampleResult('reset');
    }

    function selectDistrictName() {
        var pName = $("#provinceName").val();
        if (pName == null) {
            $('#districtName').select2('val', []);
        } else {
            for (i = 0; i < pName.length; i++) {
                $("#districtName option[data-parent-location='" + pName[i] + "']").attr("selected", "selected");
            }
            $('#districtName').select2('val', $("#districtName").val());
            selectLabName();
        }
    }

    function selectLabName() {
        var dName = $("#districtName").val();
        var pName = $("#provinceName").val();
        if (dName == null || pName == null) {
            $('#labName').select2('val', []);
        } else {
            for (i = 0; i < dName.length; i++) {
                $("#labName option[data-district='" + dName[i] + "']").attr("selected", "selected");
            }
            $('#labName').select2('val', $("#labName").val());
        }
    }

    function expandChart(from) {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        showModal('labs/expand-bar-chart/?fromDate=' + fromDate + '&toDate=' + toDate + '&facilityId=' + facilityId + '&from=' + from, '800', '450');
    }

    // function exportSampleResult(){
    //    $.blockUI.defaults.css.border = '1px solid grey';
    //    $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI); 
    //    $.post("<?php echo $this->url('laboratory', array('action' => 'export-sample-status-result-excel')); ?>", {result : $("#sampleStatus").val()},
    //     function(data){
    //         if(data == "" || data == null || data == undefined){
    //             alert('<?php echo $this->translate('Unable to export excel') ?>');
    //         }else{
    //             window.open('../temporary/'+data,'_blank');
    //         }
    //     }); 
    // }

    jQuery(function() {
        // set default dates
        var start = new Date();
        // set end date to max one year period:
        var end = new Date(new Date().setYear(start.getFullYear()-1));

        $('#dpMonthsStart').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
            format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
            <?php if(isset($logincontainer->sampleTable) && $logincontainer->sampleTable == "dash_vl_request_form_current"){?>
            startDate : end,
            <?php }?>
            endDate: "0m"
        }).on('changeDate', function(e) {
            $('#dpMonthsEnd').val('');
			var _satrt = new Date(e.date.valueOf());
			$('#dpMonthsEnd').datepicker('setStartDate', _satrt);
        });
        $('#dpMonthsEnd').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
            format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
            <?php if(isset($logincontainer->sampleTable) && $logincontainer->sampleTable == "dash_vl_request_form_current"){?>
            startDate : end,
            <?php }?>
            endDate: "0m"
        })
    });

    function formatDate(date) {
        var d = new Date(date),
            month = '' + (d.getMonth() + 1),
            year = d.getFullYear();
        if (month.length < 2) month = '0' + month;

        return [year, month].join('-');
    }
</script>