<script>
       $(function () {
       $('#barcontainer').highcharts({
       chart: {
            type: 'column'
       },
       title: {
            text: '<?php echo $this->translate('Completed VS Incomplete Forms'); ?>'
       },
       credits: {
              enabled: false
       },
        xAxis: {
            categories: [<?php
            if(isset($result['lab']) && count($result['lab'])>0){
              foreach($result['lab'] as $lab){
                  echo "'".$lab."',";
              }
            }
            ?>]
        },
        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: ''
            },
            labels: { formatter: function() { return this.value; } },
        },
        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    '<?php echo $this->translate('Total'); ?>: ' + this.point.stackTotal;
            }
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [<?php
        if(isset($result['form']) && count($result['form']) >0){
              foreach($result['form'] as $key=>$condition){
              ?>
              {
              name:'<?php echo $this->translate($key);?>',
              data:[<?php
                  foreach($condition as $count){
                      echo '{y:'.$count.'},';
                  }
              ?>],
              },
              <?php
              }
        }
            ?>],
            colors: ['#64ade5','#8877a9'],
    });
    });
</script>