<div id="gotoPie"></div>

<script>
       $(function () {
        $('#gotoPie').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: ''
        },
        exporting:{
            chartOptions:{
                subtitle: {
                    text:'Sample Volume',
                }
            }
        },
       credits: {
              enabled: false
       },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}% ({point.number})</b>'
        },
        legend: {
            layout: 'vertical',
            useHTML: true,
            itemMarginBottom: 5,
            labelFormatter: function () {
                return '<div style="width:230px"><span style="float:left;font-size:10px;">' + this.name + ' - </span><span style="font-size:10px;padding:1px; "> '+ this.percentage.toFixed(1)+'% ('+Highcharts.numberFormat(this.y, 0)+')</span></div>';
            }
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Labs',
            point: {
              events: {
                  click: function(e) {
                     doRedirect(this.name);
                     e.preventDefault();
                  }
              }
            },
            colorByPoint: true,
            data: [<?php
            if(count($result)>0 && $result!=''){
            foreach($result as $lab){
                ?>{
                  name:<?php echo "'".$lab[1]."'";?>,
                  y:<?php echo $lab[0];?>,
                  number:<?php echo $lab[0];?>
                },
                <?php
            }
            }
            ?>]
        }]
    });
    });
</script>