
<script>
       $(function () {
          
    $('#barcontainer').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
       credits: {
              enabled: false
       },
        xAxis: {
            categories: [
               <?php if(count($result)>0){
                            foreach($result as $lab){
                                   echo "'".$lab[1]."',";
                            }
                     }
              ?>
            ],
            crosshair: true
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Samples'
            },
            labels: { formatter: function() { return this.value; } },
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.0f}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'Samples',
            data:[<?php
                  foreach($result as $lab){
                      echo $lab[0].",";
                  }
              ?>],

        }]
    });
    
    });
</script>