 <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="/labs/dashboard">Labs Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">Facilities Geolocation</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"></h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption ">
                    <span class="caption-subject">Facilities - Geolocation</span>
                </div>
            </div>                                
            <div class="portlet-body">
                <div id="controls-polyline"></div>
                <div id="gmap-polyline-data">
                    <div id="gmap-polyline"  class="mapChart" style="height:900px;"></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://maps.google.com/maps/api/js?libraries=geometry&v=3&key=AIzaSyAFpbfAKFJZ8Ps7yAGIDZtD4EeBlsb_ANA"></script>
<script src="<?php echo $this->basePath('assets/global/scripts/maplace.min.js'); ?>"></script>
<script>
    var locations = null;
    
    $(function () {
        //initMap();
    });

  google.maps.event.addDomListener(window, "load", initMap);  

function initMap() {
    
locations = [
  //Starting Point is "Home", and links to other locations"//
  
  <?php
  foreach($result as $lab){
    if(isset($lab['latitude']) && $lab['latitude'] != null && $lab['latitude'] != '' && isset($lab['longitude']) && $lab['longitude'] != null && $lab['longitude'] != ''){
        ?>
        ["<?php echo $lab['facility_name'];?>", "<?php echo $lab['latitude'];?>", "<?php echo $lab['longitude'];?>", '<?php echo $this->basePath('assets/img/lab0.png') ?>', '<h5><?php echo $lab['facility_name'];?></h5><span>No. of Samples : <?php echo $lab['labCount'];?></span>'],
        <?php
        foreach($lab['clinic'] as $cName)
        {
            if(isset($cName['latitude']) && $cName['latitude'] != null && $cName['latitude'] != '' && isset($cName['longitude']) && $cName['longitude'] != null && $cName['longitude'] != ''){
                ?>
                ["<?php echo $cName['facility_name'];?>", "<?php echo $cName['latitude'];?>", "<?php echo $cName['longitude'];?>", '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<h5><?php echo $cName['facility_name'];?></h5><span>No. of Samples : <?php echo $cName['clinicCount'];?></span>'],
                <?php
            }
        }
    }
  }
?>
];    

  var map = new google.maps.Map(document.getElementById('gmap-polyline'), {
    scrollwheel: false,
    zoom: 6,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    center: {
      lat: -18.665700,
      lng: 35.535093
    }
  });
  var markers = [];
  var prev_infowindow = false;
  var bounds = new google.maps.LatLngBounds();
  // Add the markers and infowindows to the map
  for (var i = 0; i < locations.length; i++) {

    var marker = new google.maps.Marker({
      position: new google.maps.LatLng(locations[i][1], locations[i][2]),
      title: locations[i][0],     
      map: map,
      icon: locations[i][3]      
    });
    
    marker['infowindow'] = new google.maps.InfoWindow({
        content: locations[i][4]      
    });    
    
    google.maps.event.addListener(marker, 'mouseover', function() {
        if( prev_infowindow ) {
           prev_infowindow.close();
        }

        prev_infowindow = this['infowindow'];
        setTimeout("this['infowindow'].close()", 3000)
        this['infowindow'].open(map, this);
    });    
    
    markers.push(marker);
    bounds.extend(marker.getPosition());
    if (i > 0) {
      var sitepath = new google.maps.Map({
        path: [markers[0].getPosition(), marker.getPosition()],
        geodesic: true,
        strokeColor: '#F00',
        strokeOpacity: 0.5,
        strokeWeight: 2,
        map: map
      });
    }
  }
  map.fitBounds(bounds);
}
</script>