<div id="reqformspie"></div>
<script>
$(function () {
$('#reqformspie').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        exporting:{
            chartOptions:{
                subtitle: {
                    text:'Requisition Forms for Testing',
                }
            }
        },
       credits: {
              enabled: false
       },
        xAxis: {
            categories: [<?php
       if(count($result['date'])>0){
            foreach($result['date'] as $date){
                echo "'".$date."',";
            }
       }
            ?>]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Forms'
            },
            labels: { formatter: function() { return this.value; } },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        legend: {
            align: 'right',
            x: -30,
            verticalAlign: 'top',
            y: 25,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
            borderColor: '#CCC',
            borderWidth: 1,
            shadow: false
        },
        tooltip: {
            headerFormat: '<b>{point.x}</b><br/>',
            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                cursor: 'pointer',
                point: {
                    events: {
                        click: function (e) {
                            doRequisitionRedirect(e.point.category);
                        }
                    }
                },
                dataLabels: {
                    enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black'
                    }
                }
            }
        },
        series: [
              <?php
              if(count($result['Complete'])>0){
              ?>
                {
                    name: 'Complete',
                    data: [<?php echo implode(",",$result['Complete']);?>]
                },
                {
                    name: 'Incomplete',
                    data: [<?php echo implode(",",$result['Incomplete']);?>]
                },
                <?php } ?>
                ],
    colors: [
        '#64ade5',
        '#8877a9'
    ]
    });
    });
</script>