<div id="labAverageTat"></div>
<script>
$('#labAverageTat').highcharts( {
    chart: {
        zoomType: 'xy',
        marginTop: 100
    },
    legend: {
        align: 'center',
        x: 0,
        verticalAlign: 'top',
        y: 30,
        floating: true,
        backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
    },
    title: {
        text: ''
    },
    exporting:{
        chartOptions:{
            subtitle: {
                text:'<?php echo $this->translate('Laboratory Turnaround Time'); ?>',
            }
        }
    },
    credits: {
        enabled: false
    },
    xAxis: [{
        categories: [<?php
       if(isset($result['date']) && count($result['date'])>0){
            foreach($result['date'] as $date){
                echo "'".$date."',";
            }
       }
            ?>],
        crosshair: true
    }],
    yAxis: [{ // Primary yAxis
        gridLineWidth: 0,
        title: {
            text: '<?php echo $this->translate('Samples Collected'); ?>',
            style: {
                
            }
        },
        labels: {
            format: '{value}',
            style: {
                
            }
        },
        opposite: true

    },{ // Secondary yAxis
        labels: {
            format: '{value}',
            style: {
                
            }
        },
        title: {
            text: '<?php echo $this->translate('Average TAT in Days'); ?>',
            style: {
                
            }
        },
        

    },  { // Tertiary yAxis
        gridLineWidth: 0,
        title: {
            text: '<?php echo $this->translate('Samples Pending'); ?>',
            style: {
                
            }
        },
        labels: {
            format: '{value}',
            style: {
                
            }
        },
        opposite: true
    }],
    tooltip: {
        shared: true
    },
    series: [{
        name: 'Samples Collected',
            type: 'column',
            data: [
            <?php if(isset($result['samples_collected']) && count($result['samples_collected']) >0){
                  foreach($result['samples_collected'] as $samplesCollected){        
                    echo $samplesCollected.',';
                  }
                  ?>
           <?php  } ?>
            ],
            tooltip: {
                valueSuffix: ' '
            }
    }, {
        name: 'Samples Pending',
            type: 'column',
            yAxis: 2,
            data: [
            <?php if(isset($result['samples_pending']) && count($result['samples_pending']) >0){
                  foreach($result['samples_pending'] as $samplesPending){       
                    echo $samplesPending.',';
                  }
                  ?>
           <?php  } ?>
            ],
            tooltip: {
                valueSuffix: ' '
            }
    },
    <?php
        foreach($sampleType as $sample){
            if(isset($result[$sample['sample_name']])){
                foreach($result[$sample['sample_name']] as $key=>$condition){
                ?>
                {
                name:'<?php echo $sample['sample_name'];?>',
                type: 'spline',
                yAxis: 1,
                data:[<?php
                    foreach($condition as $count){
                        echo $count.",";
                    }
                ?>],
                color : getRandomColor(),
                visible:false
                },
                <?php
                }
            }
        }
        if(isset($result['all'])){
        ?>
        {
        //showInLegend: false,
        name: '<?php echo $this->translate('TAT'); ?>',
        type: 'spline',
        yAxis: 1,
        data: [<?php echo implode(",",$result['all']);?>],
        color : '#1B325F',
        }
       <?php } ?>
    ]
});
function getRandomColor() {
    var letters = '0123456789ABCDEF';
    var color = '#';
    for (var i = 0; i < 6; i++ ) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}
</script>