<script>
       $(function () {
        $('#piecontainer').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Sample Type Volume'
        },
        credits: {
              enabled: false
       },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false,
                    format: '<b>{point.name}</b> : {point.percentage:.1f}%',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Sample',
            colorByPoint: true,
            data: [<?php
            if(count($result)>0 && $result!=''){
            foreach($result as $key=>$lab){
                ?>
                {
                  name:<?php echo "'".$key."'";?>,
                  y:<?php echo $result[$key];?>
                },
                <?php
            }
            }
            ?>]
        }]
    });
    });
</script>