<?php
//\Zend\Debug\Debug::dump($result[0]);die;
?>
<div id="gotoLineOfTreatmentPie"></div>

<script>
       $(function () {
        $('#gotoLineOfTreatmentPie').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: ''
        },
        exporting:{
            chartOptions:{
                subtitle: {
                    text:'Line Of Treatment',
                }
            }
        },
       credits: {
              enabled: false
       },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}% ({point.number})</b>'
        },
        legend: {
            layout: 'vertical',
            align: 'center',
            //backgroundColor: '#f3f3f3',
            useHTML: true,
            itemMarginBottom: 5,
            labelFormatter: function () {
                return '<div style="width:230px"><span style="float:left;font-size:10px;">' + this.name + ' - </span><span style="font-size:10px;padding:1px; ">'+ this.percentage.toFixed(1)+'% ('+Highcharts.numberFormat(this.y, 0)+')</span></div>';
            }
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Labs',
            colorByPoint: true,
            data: [<?php
            if(count($result)>0 && $result!=''){
              foreach($result[0] as $key=>$lineResult){
                ?>
                {
                  name:<?php echo "'".str_replace("_"," ",$key)."'";?>,
                  y:<?php echo $result[0][$key];?>,
                  number:<?php echo $result[0][$key];?>
                },
                <?php
            }
            }
            ?>]
        }]
    });
    });
</script>