<?php
$districts = '';
$labs = '';
$clinics = '';
if (isset($result['provinceDistricts']) && !empty($result['provinceDistricts'])) {
    foreach ($result['provinceDistricts'] as $district) {
        $districts .= '<option value="' . $district['geo_id'] . '">' . ucwords($district['geo_name']) . '</option>';
    }
}
if (isset($result['labs']) && !empty($result['labs'])) {
    foreach ($result['labs'] as $lab) {
        $labs .= '<option value="' . $lab['facility_id'] . '">' . ucwords($lab['facility_name']) . '</option>';
    }
}
if (isset($result['clinics']) && !empty($result['clinics'])) {
    foreach ($result['clinics'] as $clinic) {
        $clinics .= '<option value="' . $clinic['facility_id'] . '">' . ucwords($clinic['facility_name']) . '</option>';
    }
}
echo $districts . '##' . $labs . '##' . $clinics;
