<div id="labSampleTested"></div>
<script>
       $(function () {
        $('#labSampleTested').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: '<?php echo $this->translate('VL Samples Tested'); ?>'
        },
       credits: {
              enabled: false
       },
        xAxis: {
            categories: [<?php
            if(isset($result['date']) && count($result['date'])>0){
              foreach($result['date'] as $date){
                  echo "'".$date."',";
              }
            }
            ?>]
        },
        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: ''
            },
            labels: { formatter: function() { return this.value; } },
        },
        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [<?php
            if(isset($result['rslt']) && count($result['rslt']) >0){
              foreach($result['rslt'] as $key=>$condition){
              ?>
              {
              name:'<?php echo $this->translate($key);?>',
              data:[<?php
                  foreach($condition as $count){
                     echo '{y:'.$count.'},';
                  }
              ?>],
              },
              <?php
              }
            }
            ?>
        ],
        colors: ['#60d18f','#ff1900'],
    });
    });
</script>