 <?php
  if((isset($fromMonth) && trim($fromMonth)!= '') && (isset($toMonth) && trim($toMonth)!= '')){
    $splitFromMonth = explode("-",$fromMonth);
    $startDate = $splitFromMonth[1].'-'.date('m', strtotime($splitFromMonth[0]));
    $startMonth = date('m', strtotime($splitFromMonth[0]));
    $startYear = $splitFromMonth[1];
    $startDisplayDate = $fromMonth;
    $splitToMonth = explode("-",$toMonth);
    $endDate = $splitToMonth[1].'-'.date('m', strtotime($splitToMonth[0]));
    $endMonth = date('m', strtotime($splitToMonth[0]));
    $endYear = $splitToMonth[1];
    $endDisplayDate = $toMonth;
}else{
    $startDate = date("Y", strtotime("-1 year")).'-'.date('m', strtotime('+1 month', strtotime('-1 year')));
    $endDate = date('Y').'-'.date('m');
    $startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
    $endMonth = date('m');
    $startYear = date("Y", strtotime("-1 year"));
    $endYear = date('Y');
    $startDisplayDate  = strtoupper(date('M', strtotime('+1 month', strtotime('-1 year')))).' '.date("Y", strtotime("-1 year"));
    $endDisplayDate  = strtoupper(date('M')).' '.date('Y');
}
//set selected labs
$selectedLabs = array();
if(isset($labFilter) && trim($labFilter)!= ''){
 $selectedLabs = explode(",",$labFilter);
}
 ?>
 <link href="<?php echo $this->basePath('assets/global/css/month-year-rang-picker.css'); ?>" rel="stylesheet" type="text/css" />
 <div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <a href="/labs/dashboard"><?php echo $this->translate('Labs Dashboard'); ?></a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <?php echo $this->translate('Facilities Geolocation'); ?>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<form id="pageFilter" action="#" method="">
  <div class="row" style="padding-top:10px;padding-bottom:20px;">
    <div class="col-lg-6">
        <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more labs. Leave blank for All'); ?>">
            <?php
            foreach($labName as $lab){
                ?>
                <option data-name="<?php echo $lab['facility_name']; ?>" value="<?php echo $lab['facility_id']; ?>" <?php echo(in_array($lab['facility_id'],$selectedLabs))?'selected="selected"':''; ?>><?php echo $lab['facility_code']." - ".$lab['facility_name'];?></option>
                <?php
            }
            ?>
        </select>
    </div>
    <div class="col-lg-3">
        <div id="sla-data-range" class="mrp-container form-control">
            <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                    <div class="mrp-monthdisplay ">
                      <span class="mrp-lowerMonth"><?php echo $startDisplayDate; ?></span>
                      <span class="mrp-to"> to </span>
                      <span class="mrp-upperMonth"><?php echo $endDisplayDate; ?></span>
                    </div>
                  <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" />
                  <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
        </div>
    </div>                        
    <div class="col-lg-3">
     <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getLabFacilities();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
     <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
    </div>
  </div>
</form>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption ">
                    <span class="caption-subject"><?php echo $this->translate('All Facilities - Geolocation'); ?></span>
                </div>
            </div>                                
            <div class="portlet-body">
                <div id="controls-polyline"></div>
                <div id="gmap-polyline-data">
                 
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFpbfAKFJZ8Ps7yAGIDZtD4EeBlsb_ANA"></script>
<script>
   var locations = null;
   $(function () {
     $('#labName').select2({
        placeholder: "<?php echo $this->translate('All Labs'); ?>",
        allowClear: true
     });
     getLabFacilities();
   });
    
   function getLabFacilities(){
     $.blockUI.defaults.css.border = '1px solid grey'; 
     $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
     facilityId = ($("#labName").val() == null)?'':$("#labName").val();
     fromDate=$('#mrp-lowerDate').val();
     toDate=$('#mrp-upperDate').val();
     $.post("<?php echo $this->url('laboratory', array('action' => 'get-lab-facilities')); ?>",{fromDate:fromDate,toDate:toDate,facilityId:facilityId,height:'900px'},
     function(data) {
      $("#gmap-polyline-data").html(data);
     });
   }
   
   function resetEverything(){
     $('#pageFilter')[0].reset();
     $('#labName').val('').change();
     getLabFacilities();
   }
    
   var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
   
   $(function () {
     startMonth = '<?php echo $startMonth; ?>';
     startYear = '<?php echo $startYear; ?>';
     endMonth = '<?php echo $endMonth; ?>';
     endYear = '<?php echo $endYear; ?>';
     fiscalMonth = 7;
     //if(startMonth < 10)
       //startDate = parseInt("" + startYear + '0' + startMonth + "");
     //else
       startDate = parseInt("" + startYear  + startMonth + "");
     //if(endMonth < 10)
       //endDate = parseInt("" + endYear + '0' + endMonth + "");
     //else
       endDate = parseInt("" + endYear + endMonth + "");
     
     content = '<div class="row mpr-calendarholder">';
     calendarCount = endYear - startYear;
     if(calendarCount == 0)
       calendarCount++;
     var d = new Date();
     for(y = 0; y < 2; y++){
                   content += '<div class="col-xs-6" ><div class="mpr-calendar row" id="mpr-calendar-' + (y+1) + '">'
                                                    + '<h5 class="col-xs-12"><i class="mpr-yeardown fa fa-chevron-circle-left"></i><span>' + (startYear + y).toString() + '</span><i class="mpr-yearup fa fa-chevron-circle-right"></i></h5><div class="mpr-monthsContainer"><div class="mpr-MonthsWrapper">';
       for(m=0; m < 12; m++){
         var monthval;
         if((m+1) < 10)
           monthval = "0" + (m+1);
         else
           monthval = "" + (m+1);
                           content += '<span data-month="' + monthval  + '" class="col-xs-3 mpr-month">' + MONTHS[m] + '</span>';
       }
       content += '</div></div></div></div>';
     }
     content += '<div class="col-xs-1">';
     //content += '<button class="btn btn-info mpr-fiscal-ytd">Fiscal YTD</button>';
     //content += '<button class="btn btn-info mpr-ytd">YTD</button>';
     //content += '<button class="btn btn-info mpr-prev-fiscal">Previous FY</button>';
     //content += '<button class="btn btn-info mpr-prev-year">Previous Year</button>';
     content += '<button class="btn btn-info mpr-close">Apply</button>';
     content += '</div>';
     content += '</div>';
     
     $(document).on('click','.mpr-month',function(e){
       e.stopPropagation();
                   $month = $(this);
           var monthnum = $month.data('month');
           var year = $month.parents('.mpr-calendar').children('h5').children('span').html();
           if($month.parents('#mpr-calendar-1').size() > 0){
             //Start Date
             startDate = parseInt("" + year + monthnum);
             if(startDate > endDate){
               
               if(year != parseInt(endDate/100))
                 $('.mpr-calendar:last h5 span').html(year);
                  endDate = startDate;
             }
           }else{
             //End Date
             endDate = parseInt("" + year + monthnum);
             if(startDate > endDate){
               if(year != parseInt(startDate/100))
                 $('.mpr-calendar:first h5 span').html(year);
               startDate = endDate;
             }
           }
       
           paintMonths();
     });
     
     
     $(document).on('click','.mpr-yearup',function(e){
           $('.mpr-month').css("color","black");
           e.stopPropagation();
                   var year = parseInt($(this).prev().html());
           year++;
           $(this).prev().html(""+year);
                   $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
           paintMonths();
           $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
         });
     });
     
     $(document).on('click','.mpr-yeardown',function(e){
           $('.mpr-month').css("color","black");
           e.stopPropagation();
                   var year = parseInt($(this).next().html());
           year--;
           $(this).next().html(""+year);
                   //paintMonths();
         $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
           paintMonths();
           $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
         });
     });
     
     $(document).on('click','.mpr-ytd', function(e){
       e.stopPropagation();
       var d = new Date();
       startDate = parseInt(d.getFullYear() + "01");
       var month = d.getMonth() + 1;
       if(month < 9)
         month = "0" + month;
       endDate = parseInt("" + d.getFullYear() + month);
       $('.mpr-calendar').each(function(){
         var $cal = $(this);
         var year = $('h5 span',$cal).html(d.getFullYear());
       });
       $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
           paintMonths();
           $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
       });
     });
     
     $(document).on('click','.mpr-prev-year', function(e){
       e.stopPropagation();
       var d = new Date();
       var year = d.getFullYear()-1;
       startDate = parseInt(year + "01");
       endDate = parseInt(year + "12");
       $('.mpr-calendar').each(function(){
         var $cal = $(this);
         $('h5 span',$cal).html(year);
       });
       $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
           paintMonths();
           $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
       });
     });
     
     $(document).on('click','.mpr-fiscal-ytd', function(e){
       e.stopPropagation();
       var d = new Date();
       var year;
       if((d.getMonth()+1) < fiscalMonth)
         year = d.getFullYear() - 1;
       else
         year = d.getFullYear();
       if(fiscalMonth < 10)
         fm = "0" + fiscalMonth;
       else
         fm = fiscalMonth;
       if(d.getMonth()+1 < 10)
         cm = "0" + (d.getMonth()+1);
       else
         cm = (d.getMonth()+1);
       startDate = parseInt("" + year + fm);
       endDate = parseInt("" + d.getFullYear() + cm);
       $('.mpr-calendar').each(function(i){
         var $cal = $(this);
         if(i == 0)
           $('h5 span',$cal).html(year);
         else
           $('h5 span',$cal).html(d.getFullYear());
       });
       $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
           paintMonths();
           $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
       });
     });
     
     $(document).on('click','.mpr-prev-fiscal', function(){
       var d = new Date();
       var year;
       if((d.getMonth()+1) < fiscalMonth)
         year = d.getFullYear() - 2;
       else
         year = d.getFullYear() - 1;
       if(fiscalMonth < 10)
         fm = "0" + fiscalMonth;
       else
         fm = fiscalMonth;
       if(fiscalMonth -1 < 10)
         efm = "0" + (fiscalMonth-1);
       else
         efm = (fiscalMonth-1);
       startDate = parseInt("" + year + fm);
       endDate = parseInt("" + (d.getFullYear() - 1) + efm);
       $('.mpr-calendar').each(function(i){
         var $cal = $(this);
         if(i == 0)
           $('h5 span',$cal).html(year);
         else
           $('h5 span',$cal).html(d.getFullYear()-1);
       });
       $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
           paintMonths();
           $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
       });
     });
     
     var mprVisible = false;
     var mprpopover = $('.mrp-container').popover({
       container: "body",
       placement: "bottom",
       html: true,
       content: content
     }).on('show.bs.popover', function () {
       $('.popover').remove();
       var waiter = setInterval(function(){
         if($('.popover').size() > 0){
           clearInterval(waiter);
           setViewToCurrentYears();
                   paintMonths();
         }
       },50);
     }).on('shown.bs.popover', function(){
       mprVisible = true;
     }).on('hidden.bs.popover', function(){
       mprVisible = false;
     }); 
     
     $(document).on('click','.mpr-calendarholder',function(e){
       e.preventDefault();
       e.stopPropagation();
     });
     $(document).on("click",".mrp-container",function(e){
       if(mprVisible){
         e.preventDefault();
           e.stopPropagation();
         mprVisible = false;
       }
     });
     
     $(document).on("click",function(e){
      
       if(mprVisible){
           $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
           $('.mpr-calendarholder').parents('.popover').remove();
           $('.mrp-container').trigger('click');
         });
         mprVisible = false;
       }
     });
     
     $(document).on('click','.mpr-close', function(e){
       //console.log(e);
       if(mprVisible){
           $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
           $('.mpr-calendarholder').parents('.popover').remove();
           $('.mrp-container').trigger('click');
         });
         mprVisible = false;
       }
     });
     
   });
</script>
<script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>