 <?php
    if ((isset($fromMonth) && trim($fromMonth) != '') && (isset($toMonth) && trim($toMonth) != '')) {
        $splitFromMonth = explode("-", $fromMonth);
        $startDate = $splitFromMonth[1] . '-' . date('m', strtotime($splitFromMonth[0]));
        $startMonth = date('m', strtotime($splitFromMonth[0]));
        $startYear = $splitFromMonth[1];
        $startDisplayDate = $fromMonth;
        $splitToMonth = explode("-", $toMonth);
        $endDate = $splitToMonth[1] . '-' . date('m', strtotime($splitToMonth[0]));
        $endMonth = date('m', strtotime($splitToMonth[0]));
        $endYear = $splitToMonth[1];
        $endDisplayDate = $toMonth;
    } else {
        $startDate = date("Y", strtotime("-1 year")) . '-' . date('m', strtotime('+1 month', strtotime('-1 year')));
        $endDate = date('Y') . '-' . date('m');
        $startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
        $endMonth = date('m');
        $startYear = date("Y", strtotime("-1 year"));
        $endYear = date('Y');
        $startDisplayDate  = strtoupper(date('M', strtotime('+1 month', strtotime('-1 year')))) . ' ' . date("Y", strtotime("-1 year"));
        $endDisplayDate  = strtoupper(date('M')) . ' ' . date('Y');
    }
    //set selected labs
    $selectedLabs = [];
    if (isset($labFilter) && trim($labFilter) != '') {
        $selectedLabs = explode(",", $labFilter);
    }
    ?>
 <link href="<?php echo $this->basePath('assets/global/css/month-year-rang-picker.css'); ?>" rel="stylesheet" type="text/css" />
 <div class="page-bar">
     <ul class="page-breadcrumb">
         <li>
             <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
             <i class="fa fa-circle"></i>
         </li>
         <li>
             <a href="/labs/dashboard"><?php echo $this->translate('Labs Dashboard'); ?></a>
             <i class="fa fa-circle"></i>
         </li>
         <li>
             <?php echo $this->translate('Facilities Geolocation'); ?>
         </li>
     </ul>
 </div>
 <!-- END PAGE BAR -->
 <!-- BEGIN PAGE TITLE-->
 <h3 class="page-title"></h3>
 <!-- END PAGE TITLE-->
 <!-- END PAGE HEADER-->
 <form id="pageFilter" action="#" method="">
     <div class="row" style="padding-top:10px;padding-bottom:20px;">
         <div class="col-lg-6">
             <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more labs. Leave blank for All'); ?>">
                 <?php
                    foreach ($labName as $lab) {
                    ?>
                     <option data-name="<?php echo $lab['facility_name']; ?>" value="<?php echo $lab['facility_id']; ?>" <?php echo (in_array($lab['facility_id'], $selectedLabs)) ? 'selected="selected"' : ''; ?>><?php echo $lab['facility_code'] . " - " . $lab['facility_name']; ?></option>
                 <?php
                    }
                    ?>
             </select>
         </div>
         <div class="col-lg-3">
             <div id="sla-data-range" class="mrp-container form-control">
                 <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                 <div class="mrp-monthdisplay ">
                     <span class="mrp-lowerMonth"><?php echo $startDisplayDate; ?></span>
                     <span class="mrp-to"> to </span>
                     <span class="mrp-upperMonth"><?php echo $endDisplayDate; ?></span>
                 </div>
                 <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" />
                 <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
             </div>
         </div>
         <div class="col-lg-3">
             <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getLabFacilities();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
             <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
         </div>
     </div>
 </form>
 <div class="row">
     <div class="col-md-12 col-sm-12">
         <div class="portlet box blue">
             <div class="portlet-title">
                 <div class="caption">
                     <span class="caption-subject"><?php echo $this->translate('All Facilities - Geolocation'); ?></span>
                 </div>
             </div>
             <div class="portlet-body">
                 <div id="controls-polyline"></div>
                 <div id="gmap-polyline-data">

                 </div>
             </div>
         </div>
     </div>
 </div>
 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFpbfAKFJZ8Ps7yAGIDZtD4EeBlsb_ANA"></script>
 <script>
     var locations = null;
     $(function() {
         $('#labName').select2({
             placeholder: "<?php echo $this->translate('All Labs'); ?>",
             allowClear: true
         });
         getLabFacilities();
     });

     function getLabFacilities() {
         $.blockUI.defaults.css.border = '1px solid grey';
         $(document).ajaxStart($.blockUI({
             message: '<h2><?php echo $this->translate('Processing...'); ?></h2>'
         })).ajaxStop($.unblockUI);
         facilityId = ($("#labName").val() == null) ? '' : $("#labName").val();
         fromDate = $('#mrp-lowerDate').val();
         toDate = $('#mrp-upperDate').val();
         $.post("<?php echo $this->url('laboratory', array('action' => 'get-lab-facilities')); ?>", {
                 fromDate: fromDate,
                 toDate: toDate,
                 facilityId: facilityId,
                 height: '900px'
             },
             function(data) {
                 $("#gmap-polyline-data").html(data);
             });
     }

     function resetEverything() {
         $('#pageFilter')[0].reset();
         $('#labName').val('').change();
         getLabFacilities();
     }
 </script>
 <script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>
