<?php
if(count($result['sample']['Suppressed'])>0){
    for($i=0;$i<count($result['sample']['Suppressed']);$i++){
        ?>
        <tr>
            <td><?php echo $result['lab'][$i];?></td>
            <td><?php echo $result['sample']['Suppressed'][$i];?></td>
            <td><?php echo $result['sample']['Not Suppressed'][$i];?></td>
            <td><?php echo $result['sample']['Rejected'][$i];?></td>
        </tr>
        <?php
    }
}else{
    ?>
    <tr>
        <td colspan="5" class="dataTables_empty">Loading data from server</td>
    </tr>
    <?php
}
?>