<?php
if(isset($searchMonth) && trim($searchMonth)!= ''){
    $splitSearchMonth = explode("-",$searchMonth);
    $startDate = $endDate = $splitSearchMonth[1].'-'.date('m', strtotime($splitSearchMonth[0]));
    $startMonth = $endMonth = date('m', strtotime($splitSearchMonth[0]));
    $startYear = $endYear = $splitSearchMonth[1];
    $startDisplayDate = $endDisplayDate = $searchMonth;
}else{
    $startDate = date("Y", strtotime("-1 year")).'-'.date('m', strtotime('+1 month', strtotime('-1 year')));
    $endDate = date('Y').'-'.date('m');
    $startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
    $endMonth = date('m');
    $startYear = date("Y", strtotime("-1 year"));
    $endYear = date('Y');
    $startDisplayDate  = strtoupper(date('M', strtotime('+1 month', strtotime('-1 year')))).' '.date("Y", strtotime("-1 year"));
    $endDisplayDate  = strtoupper(date('M')).' '.date('Y');
}
?>
<link href="<?php echo $this->basePath('assets/global/css/month-year-rang-picker.css'); ?>" rel="stylesheet" type="text/css" />
           <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                     <div class="page-bar">
                        <h1 class="page-title">Requisition Forms Completion
                        <ul class="page-breadcrumb pull-right">
                            <li>
                                <i class="fa fa-arrow-left"></i>
                                <a href="/labs/dashboard">Back to Labs Dashboard</a>
                            </li>
                        </ul>
                        </h1>
                    </div>                    
                   
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"></h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    
                    <div class="row">
                        <div class="col-md-12" style="padding-left:30px;">
                            <form class="form-Horizontal">
                        <div class="col-md-12">
                            <div class="form-group col-lg-4">
                                <label class="control-label">Date Range&nbsp;</label>
                              <div id="sla-data-range" class="btn btn-sm form-control col-lg-6 mrp-container ">
                                
                                <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                                <div class="mrp-monthdisplay ">
                                  <span class="mrp-lowerMonth"><?php echo $startDisplayDate; ?></span>
                                  <span class="mrp-to"> to </span>
                                  <span class="mrp-upperMonth"><?php echo $endDisplayDate; ?></span>
                                </div>
                              <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" />
                              <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
                            
                            </div>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">Lab&nbsp;</label>
                                <select name="labName" id="labName" class="form-control" title="Please choose lab name">
                                    <option value="">All Labs</option>
                                    <?php
                                    foreach($labList as $lab){
                                    ?>
                                        <option value="<?php echo base64_encode($lab['facility_id']);?>" <?php echo(isset($labFilter) && trim($labFilter)!= '' && $labFilter == $lab['facility_name'])?'selected="selected"':''; ?>><?php echo $lab['facility_name'];?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">Gender</label>
                              <select class="form-control" name="gender" id="gender">
                                <option value="">All</option>
                                <option value="M">Male</option>
                                <option value="F">Female</option>
                                <option value="not_specified">Not Specified</option>
                              </select>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group col-lg-4" style="margin-top:26px;">
                                <a href="javascript:void(0);" class="btn btn-primary" onclick="searchIncompleteSampleResult()">Submit</a>
                            </div>
                        </div>
                          </form>
                        </div>
                    </div>
                    
                    
                    <div class="row" style="margin-bottom:30px;">
                        <div class="col-lg-6">
                            <div id="piecontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
                        </div>
                        <div class="col-lg-6">
                            <div id="barcontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
                        </div>
                    </div>

<script>
    function generatePieContainer(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        fromDate = $('#mrp-lowerDate').val();
        toDate = $('#mrp-upperDate').val();
        lab = $("#labName").val();
        gender = $("#gender").val();
        
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-incomplete-sample-details')); ?>",{fromDate:fromDate,toDate:toDate,lab:lab,gender:gender},
        function(data) {
            $("#piecontainer").html(data);
        });
    }
    
    function generateChartContainer(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        fromDate = $('#mrp-lowerDate').val();
        toDate = $('#mrp-upperDate').val();
        lab = $("#labName").val();
        gender = $("#gender").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-incomplete-bar-sample-details')); ?>",{fromDate:fromDate,toDate:toDate,lab:lab,gender:gender},
        function(data) {
            $("#barcontainer").html(data);
        });
    }
    
    $(document).ready(function(){
        $('#piebutton').on('click', function () {
            $('#piecontainer').fadeIn(function () {
                generatePieContainer();
            });
        });
        $('#barbutton').on('click', function () {
            $('#barcontainer').fadeIn(function () {
                generateChartContainer();
            });
        }); 
      generatePieContainer();
      generateChartContainer();
    });

    

function searchIncompleteSampleResult(){
    generatePieContainer();
    generateChartContainer();
}

var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

$(function () {
  startMonth = '<?php echo $startMonth; ?>';
  startYear = '<?php echo $startYear; ?>';
  endMonth = '<?php echo $endMonth; ?>';
  endYear = '<?php echo $endYear; ?>';
  fiscalMonth = 7;
  //if(startMonth < 10)
    //startDate = parseInt("" + startYear + '0' + startMonth + "");
  //else
    startDate = parseInt("" + startYear  + startMonth + "");
  //if(endMonth < 10)
    //endDate = parseInt("" + endYear + '0' + endMonth + "");
  //else
    endDate = parseInt("" + endYear + endMonth + "");
  
  content = '<div class="row mpr-calendarholder">';
  calendarCount = endYear - startYear;
  if(calendarCount == 0)
    calendarCount++;
  var d = new Date();
  for(y = 0; y < 2; y++){
		content += '<div class="col-xs-6" ><div class="mpr-calendar row" id="mpr-calendar-' + (y+1) + '">'
 						 + '<h5 class="col-xs-12"><i class="mpr-yeardown fa fa-chevron-circle-left"></i><span>' + (startYear + y).toString() + '</span><i class="mpr-yearup fa fa-chevron-circle-right"></i></h5><div class="mpr-monthsContainer"><div class="mpr-MonthsWrapper">';
    for(m=0; m < 12; m++){
      var monthval;
      if((m+1) < 10)
        monthval = "0" + (m+1);
      else
        monthval = "" + (m+1);
			content += '<span data-month="' + monthval  + '" class="col-xs-3 mpr-month">' + MONTHS[m] + '</span>';
    }
    content += '</div></div></div></div>';
  }
  content += '<div class="col-xs-1">';
  //content += '<button class="btn btn-info mpr-fiscal-ytd">Fiscal YTD</button>';
  //content += '<button class="btn btn-info mpr-ytd">YTD</button>';
  //content += '<button class="btn btn-info mpr-prev-fiscal">Previous FY</button>';
  //content += '<button class="btn btn-info mpr-prev-year">Previous Year</button>';
  content += '<button class="btn btn-info mpr-close">Apply</button>';
  content += '</div>';
  content += '</div>';
  
  $(document).on('click','.mpr-month',function(e){
    e.stopPropagation();
  		$month = $(this);
    	var monthnum = $month.data('month');
    	var year = $month.parents('.mpr-calendar').children('h5').children('span').html();
        if($month.parents('#mpr-calendar-1').size() > 0){
          //Start Date
          startDate = parseInt("" + year + monthnum);
          if(startDate > endDate){
            
            if(year != parseInt(endDate/100))
              $('.mpr-calendar:last h5 span').html(year);
               endDate = startDate;
          }
        }else{
          //End Date
          endDate = parseInt("" + year + monthnum);
          if(startDate > endDate){
            if(year != parseInt(startDate/100))
              $('.mpr-calendar:first h5 span').html(year);
            startDate = endDate;
          }
        }
    
    	paintMonths();
  });
  
  
  $(document).on('click','.mpr-yearup',function(e){
        $('.mpr-month').css("color","black");
    	e.stopPropagation();
  		var year = parseInt($(this).prev().html());
    	year++;
    	$(this).prev().html(""+year);
   	 	$(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
      });
  });
  
  $(document).on('click','.mpr-yeardown',function(e){
        $('.mpr-month').css("color","black");
    	e.stopPropagation();
  		var year = parseInt($(this).next().html());
    	year--;
    	$(this).next().html(""+year);
   	 	//paintMonths();
      $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
      });
  });
  
  $(document).on('click','.mpr-ytd', function(e){
    e.stopPropagation();
    var d = new Date();
    startDate = parseInt(d.getFullYear() + "01");
    var month = d.getMonth() + 1;
    if(month < 9)
      month = "0" + month;
    endDate = parseInt("" + d.getFullYear() + month);
    $('.mpr-calendar').each(function(){
      var $cal = $(this);
      var year = $('h5 span',$cal).html(d.getFullYear());
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  $(document).on('click','.mpr-prev-year', function(e){
    e.stopPropagation();
    var d = new Date();
    var year = d.getFullYear()-1;
    startDate = parseInt(year + "01");
    endDate = parseInt(year + "12");
    $('.mpr-calendar').each(function(){
      var $cal = $(this);
      $('h5 span',$cal).html(year);
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  $(document).on('click','.mpr-fiscal-ytd', function(e){
    e.stopPropagation();
    var d = new Date();
    var year;
    if((d.getMonth()+1) < fiscalMonth)
      year = d.getFullYear() - 1;
    else
      year = d.getFullYear();
    if(fiscalMonth < 10)
      fm = "0" + fiscalMonth;
    else
      fm = fiscalMonth;
    if(d.getMonth()+1 < 10)
      cm = "0" + (d.getMonth()+1);
    else
      cm = (d.getMonth()+1);
    startDate = parseInt("" + year + fm);
    endDate = parseInt("" + d.getFullYear() + cm);
    $('.mpr-calendar').each(function(i){
      var $cal = $(this);
      if(i == 0)
      	$('h5 span',$cal).html(year);
      else
        $('h5 span',$cal).html(d.getFullYear());
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  $(document).on('click','.mpr-prev-fiscal', function(){
    var d = new Date();
    var year;
    if((d.getMonth()+1) < fiscalMonth)
      year = d.getFullYear() - 2;
    else
      year = d.getFullYear() - 1;
    if(fiscalMonth < 10)
      fm = "0" + fiscalMonth;
    else
      fm = fiscalMonth;
    if(fiscalMonth -1 < 10)
      efm = "0" + (fiscalMonth-1);
    else
      efm = (fiscalMonth-1);
    startDate = parseInt("" + year + fm);
    endDate = parseInt("" + (d.getFullYear() - 1) + efm);
    $('.mpr-calendar').each(function(i){
      var $cal = $(this);
      if(i == 0)
      	$('h5 span',$cal).html(year);
      else
        $('h5 span',$cal).html(d.getFullYear()-1);
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  var mprVisible = false;
  var mprpopover = $('.mrp-container').popover({
    container: "body",
    placement: "bottom",
    html: true,
    content: content
  }).on('show.bs.popover', function () {
    $('.popover').remove();
    var waiter = setInterval(function(){
      if($('.popover').size() > 0){
        clearInterval(waiter);
        setViewToCurrentYears();
    		paintMonths();
      }
    },50);
  }).on('shown.bs.popover', function(){
    mprVisible = true;
  }).on('hidden.bs.popover', function(){
    mprVisible = false;
  }); 
  
  $(document).on('click','.mpr-calendarholder',function(e){
    e.preventDefault();
    e.stopPropagation();
  });
  $(document).on("click",".mrp-container",function(e){
    if(mprVisible){
      e.preventDefault();
    	e.stopPropagation();
      mprVisible = false;
    }
  });
  
  $(document).on("click",function(e){
   
    if(mprVisible){
    	$('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
        $('.mpr-calendarholder').parents('.popover').remove();
        $('.mrp-container').trigger('click');
      });
      mprVisible = false;
    }
  });
  
  $(document).on('click','.mpr-close', function(e){
    //console.log(e);
    if(mprVisible){
    	$('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
        $('.mpr-calendarholder').parents('.popover').remove();
        $('.mrp-container').trigger('click');
      });
      mprVisible = false;
    }
  });
  
});

  
</script>
<script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>