
           <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">Incomplete Requisition Forms</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"></h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cogs"></i>Incomplete Requisition Forms </div>
                                </div>
                                <div class="portlet-body">
                                    <div class="table-toolbar">
                                        <table class="table table-striped table-bordered table-hover order-column" id="sample_1">
                                                    <thead>
                                                        <tr>
                                                            <th> Facility Name </th>
                                                            <th> Form Date </th>
                                                            <th> Reason </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        <tr>
                                                        <td>Clinic 01010</td>                                                        
                                                        <td>30 Mar 2016</td>                                                        
                                                        <td>Some things are not filled as per requirements</td>                                                        
                                                        </tr>
                                                        <tr>
                                                        <td>Clinic 34343</td>                                                        
                                                        <td>04 Apr 2016</td>                                                        
                                                        <td>Illegible entries</td>                                                        
                                                        </tr>
                                                    </tbody>
                                                </table>

                                    </div>
                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
<script>
    $(document).ready(function(){
    
    
    
    
                var e = $("#sample_1").dataTable({
                language: {
                    aria: {
                        sortAscending: ": activate to sort column ascending",
                        sortDescending: ": activate to sort column descending"
                    },
                    emptyTable: "No data available in table",
                    info: "Showing _START_ to _END_ of _TOTAL_ records",
                    infoEmpty: "No records found",
                    infoFiltered: "(filtered1 from _MAX_ total records)",
                    lengthMenu: "Show _MENU_",
                    search: "Search:",
                    zeroRecords: "No matching records found",
                    paginate: {
                        previous: "Prev",
                        next: "Next",
                        last: "Last",
                        first: "First"
                    }
                },
                bStateSave: !0,

                lengthMenu: [
                    [5, 15, 20, -1],
                    [5, 15, 20, "All"]
                ],
                pageLength: 5,
                pagingType: "bootstrap_full_number",

                order: [
                    [1, "asc"]
                ]
            });
            
            jQuery("#sample_1_wrapper");
            e.find(".group-checkable").change(function() {
                var e = jQuery(this).attr("data-set"),
                    a = jQuery(this).is(":checked");
                jQuery(e).each(function() {
                    a ? ($(this).prop("checked", !0), $(this).parents("tr").addClass("active")) : ($(this).prop("checked", !1), $(this).parents("tr").removeClass("active"))
                }), jQuery.uniform.update(e)
            }), e.on("change", "tbody tr .checkboxes", function() {
                $(this).parents("tr").toggleClass("active")
            })
        
    
    
    });

    


</script>