<?php
if(isset($searchMonth) && trim($searchMonth)!= ''){
    $splitSearchMonth = explode("-",$searchMonth);
    $startDate = $endDate = $splitSearchMonth[1].' '.date('m', strtotime($splitSearchMonth[0]));
    $startMonth = $endMonth = date('m', strtotime($splitSearchMonth[0]));
    $startYear = $endYear = $splitSearchMonth[1];
    $startDisplayDate = $endDisplayDate = str_replace('-',' ',$searchMonth);
}else if((isset($fromMonth) && trim($fromMonth)!= '') && (isset($toMonth) && trim($toMonth)!= '')){
    $splitFromMonth = explode("-",$fromMonth);
    $startDate = $splitFromMonth[1].'-'.date('m', strtotime($splitFromMonth[0]));
    $startMonth = date('m', strtotime($splitFromMonth[0]));
    $startYear = $splitFromMonth[1];
    $startDisplayDate = $fromMonth;
    $splitToMonth = explode("-",$toMonth);
    $endDate = $splitToMonth[1].'-'.date('m', strtotime($splitToMonth[0]));
    $endMonth = date('m', strtotime($splitToMonth[0]));
    $endYear = $splitToMonth[1];
    $endDisplayDate = $toMonth;
}else{
    $startDate = date("Y", strtotime("-1 year")).'-'.date('m', strtotime('+1 month', strtotime('-1 year')));
    $endDate = date('Y').'-'.date('m');
    $startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
    $endMonth = date('m');
    $startYear = date("Y", strtotime("-1 year"));
    $endYear = date('Y');
    $startDisplayDate  = strtoupper(date('M', strtotime('+1 month', strtotime('-1 year')))).' '.date("Y", strtotime("-1 year"));
    $endDisplayDate  = strtoupper(date('M')).' '.date('Y');
}
//set selected labs
$selectedLabs = array();
if(isset($labFilter) && trim($labFilter)!= ''){
    $selectedLabs = explode(",",$labFilter);
}
//set selected provinces
$selectedProvinces = array();
if(isset($facilityInfo['selectedProvinces']) && count($facilityInfo['selectedProvinces']) >0){
    foreach($facilityInfo['selectedProvinces'] as $province){
        $selectedProvinces[] = $province['location_id'];
    }
}
//set selected districts
$selectedDistricts = array();
if(isset($facilityInfo['labDistricts']) && count($facilityInfo['labDistricts']) >0){
    foreach($facilityInfo['labDistricts'] as $district){
        $selectedDistricts[] = $district['facility_district'];
    }
}
?>
<link href="<?php echo $this->basePath('assets/global/css/month-year-rang-picker.css'); ?>" rel="stylesheet" type="text/css" />
<!-- BEGIN PAGE HEADER-->
<!-- BEGIN THEME PANEL -->
<!-- END THEME PANEL -->
<!-- BEGIN PAGE BAR -->
 <div class="page-bar">
    <h1 class="page-title"><?php echo $this->translate('Samples Turnaround Time'); ?>
    <ul class="page-breadcrumb pull-right">
        <li>
            <i class="fa fa-arrow-left"></i>
            <a href="/labs/dashboard"><?php echo $this->translate('Back to Labs Dashboard'); ?></a>
        </li>
    </ul>
    </h1>
</div>                    

<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<form id="pageFilter" action="#" method="">
    <div class="row">
        <div class="col-md-12" style="padding-left:30px;">
        <div class="col-md-12">
            <div class="form-group col-lg-4">
                <label class="control-label"><?php echo $this->translate('Date Range'); ?>&nbsp;</label>
              <div id="sla-data-range" class="btn btn-sm form-control col-lg-6 mrp-container ">
                <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                <div class="mrp-monthdisplay ">
                  <span class="mrp-lowerMonth"><?php echo $startDisplayDate; ?></span>
                  <span class="mrp-to"> to </span>
                  <span class="mrp-upperMonth"><?php echo $endDisplayDate; ?></span>
                </div>
              <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" />
              <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
            
            </div>
            </div>
            <div class="form-group col-lg-4">
                <label class="control-label"><?php echo $this->translate('Provinces'); ?>&nbsp;</label>
                <select name="provinces[]" id="provinces" class="form-control" multiple title="<?php echo $this->translate('Please choose provinces'); ?>" onchange="getLocationInfo('provinces');">
                    <?php
                    if(isset($facilityInfo['provinces']) && count($facilityInfo['provinces']) > 0){
                        foreach($facilityInfo['provinces'] as $province){
                    ?>
                        <option value="<?php echo $province['location_id']; ?>" <?php echo(in_array($province['location_id'],$selectedProvinces))?'selected="selected"':''; ?>><?php echo ucwords($province['location_name']); ?></option>
                    <?php } } ?>
                </select>
            </div>
            <div class="form-group col-lg-4">
                <label class="control-label"><?php echo $this->translate('Districts'); ?>&nbsp;</label>
                <select name="districts[]" id="districts" class="form-control" multiple title="<?php echo $this->translate('Please choose districts'); ?>" onchange="getLocationInfo('districts');">
                    <?php
                    if(isset($facilityInfo['provinceDistricts']) && count($facilityInfo['provinceDistricts']) > 0){
                        foreach($facilityInfo['provinceDistricts'] as $provinceDistrict){
                    ?>
                        <option value="<?php echo $provinceDistrict['location_id']; ?>" <?php echo(in_array($provinceDistrict['location_id'],$selectedDistricts))?'selected="selected"':''; ?>><?php echo ucwords($provinceDistrict['location_name']); ?></option>
                    <?php } } ?>
                </select>
            </div>
        </div>                                
        <div class="col-md-12">        
            <div class="form-group col-lg-4">
                <label class="control-label"><?php echo $this->translate('Labs'); ?>&nbsp;</label>
                <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please choose labs'); ?>">
                    <?php
                    if(isset($facilityInfo['labs']) && count($facilityInfo['labs']) > 0){
                        foreach($facilityInfo['labs'] as $labs){
                    ?>
                        <option value="<?php echo $labs['facility_id']; ?>" <?php echo(in_array($labs['facility_id'],$selectedLabs))?'selected="selected"':''; ?>><?php echo ucwords($labs['facility_name']); ?></option>
                    <?php } } ?>
                </select>
            </div>
            <div class="form-group col-lg-4">
                <label class="control-label"><?php echo $this->translate('Clinics'); ?>&nbsp;</label>
                <select class="form-control" id="clinicId" name="clinicId[]" multiple title="<?php echo $this->translate('Please choose clinics'); ?>">
                    <?php
                    if(isset($facilityInfo['clinics']) && count($facilityInfo['clinics']) > 0){
                        foreach($facilityInfo['clinics'] as $clinics){
                    ?>
                        <option value="<?php echo $clinics['facility_id']; ?>"><?php echo ucwords($clinics['facility_name']); ?></option>
                    <?php } } ?>
                </select>
            </div>
            <div class="form-group col-lg-4">
                <label class="control-label"><?php echo $this->translate('Sample Type'); ?></label>
                <select class="form-control" id="sampleType" name="sampleType">
                    <option value=""><?php echo $this->translate('All'); ?></option>
                    <?php
                    foreach($sampleType as $samples){
                    ?>
                     <option value="<?php echo base64_encode($samples['sample_id']);?>"><?php echo $samples['sample_name'];?></option>
                    <?php
                    }
                    ?>
                </select>
            </div>
        </div>                                
        <div class="col-md-12">
            <div class="form-group col-lg-4">
              <label class="control-label"><?php echo $this->translate('Gender'); ?></label>
              <select class="form-control" name="gender" id="gender">
                <option value=""><?php echo $this->translate('All'); ?></option>
                <option value="M"><?php echo $this->translate('Male'); ?></option>
                <option value="F"><?php echo $this->translate('Female'); ?></option>
                <option value="not_specified"><?php echo $this->translate('Not Specified'); ?></option>
              </select>
            </div>
            <div class="form-group col-lg-4 femaleSection" style="display:<?php echo (isset($searchGender) && $searchGender == 'F')?'':'none'; ?>;">
                <label class="control-label"><?php echo $this->translate('Is Patient Pregnant'); ?></label>
                <select class="form-control" name="isPregnant" id="isPregnant">
                  <option value=""><?php echo $this->translate('All'); ?></option>  
                  <option value="yes"><?php echo $this->translate('Yes'); ?></option>
                  <option value="no"><?php echo $this->translate('No'); ?></option>
                  <option value="unreported"><?php echo $this->translate('Unreported'); ?></option>
                </select>
            </div>
            <div class="form-group col-lg-4 femaleSection" style="display:<?php echo (isset($searchGender) && $searchGender == 'F')?'':'none'; ?>;">
                <label class="control-label"><?php echo $this->translate('Is Patient Breastfeeding'); ?></label>
                <select class="form-control" name="isBreastfeeding" id="isBreastfeeding">
                  <option value=""><?php echo $this->translate('All'); ?></option>  
                  <option value="yes"><?php echo $this->translate('Yes'); ?></option>
                  <option value="no"><?php echo $this->translate('No'); ?></option>
                  <option value="unreported"><?php echo $this->translate('Unreported'); ?></option>
                </select>
            </div>
        </div>
        <div class="col-md-12">
            <div class="form-group col-lg-12" style="text-align:center;margin-top:10px;">
                <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="searchSampleTestedTAT();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
            </div>
        </div>
        </div>
    </div>
</form>
<hr style="background: #000 !important;border-color:#ccc;">
<div class="row" style="margin-bottom:30px;">
    <div class="col-lg-6">
        <div id="piecontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
    </div>
    <div class="col-lg-6">
        <div id="barcontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
    </div>
</div>
    <br>
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?php echo $this->translate('Samples Tested'); ?>
                </div>
                <div class="tools">
                    <button class="btn btn-default" onclick="exportSampleResult();"><span><i class="fa fa-file-excel-o" aria-hidden="true"></i> <?php echo $this->translate('Excel'); ?></span></button>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <table class="table table-striped table-bordered table-hover order-column" id="sampleDataTable">
                        <thead>
                            <tr>
                                <th><?php echo $this->translate('Month and Year'); ?> </th>
                                <th><?php echo $this->translate('Samples Collected'); ?> </th>
                                <th><?php echo $this->translate('Samples Tested'); ?> </th>
                                <th><?php echo $this->translate('Results Not Available'); ?> </th>
                                <th><?php echo $this->translate('Samples Suppressed'); ?> </th>
                                <th><?php echo $this->translate('Samples Not Suppressed'); ?> </th>
                                <th><?php echo $this->translate('Samples Rejected'); ?> </th>
                                <th><?php echo $this->translate('Average TAT in Days'); ?></th>
                            </tr>
                        </thead>
                        <tbody id="barChartCountInTable">
                            <tr>
                                <td colspan="8" class="dataTables_empty">Loading data from server</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
<script>
    function generatePieContainer(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        var fromDate = $('#mrp-lowerDate').val();
        var toDate = $('#mrp-upperDate').val();
        var provinces = $("#provinces").val();
        var districts = $("#districts").val();
        var lab = $("#labName").val();
        var clinicId = $("#clinicId").val();
        var sampleType = $("#sampleType").val();
        var gender = $("#gender").val();
        var isPregnant = $("#isPregnant").val();
        var isBreastfeeding = $("#isBreastfeeding").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-pie-sample-tat')); ?>",{fromDate:fromDate,toDate:toDate,provinces:provinces,districts:districts,lab:lab,clinicId:clinicId,sampleType:sampleType,sampleStatus:'sample_tested',gender:gender,isPregnant:isPregnant,isBreastfeeding:isBreastfeeding},
        function(data) {
            $("#piecontainer").html(data);
        });
    }
    
    function generateBarContainer() {
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        var fromDate = $('#mrp-lowerDate').val();
        var toDate = $('#mrp-upperDate').val();
        var provinces = $("#provinces").val();
        var districts = $("#districts").val();
        var lab = $("#labName").val();
        var clinicId = $("#clinicId").val();
        var sampleType = $("#sampleType").val();
        var gender = $("#gender").val();
        var isPregnant = $("#isPregnant").val();
        var isBreastfeeding = $("#isBreastfeeding").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-bar-sample-tat')); ?>",{fromDate:fromDate,toDate:toDate,provinces:provinces,districts:districts,lab:lab,clinicId:clinicId,sampleType:sampleType,sampleStatus:'sample_tested',gender:gender,isPregnant:isPregnant,isBreastfeeding:isBreastfeeding},
        function(data) {
            $("#barcontainer").html(data);
        });
    }
    
    var oTable = null;
    $(document).ready(function(){
        $('#provinces').select2({
            placeholder: "<?php echo $this->translate('All Provinces'); ?>",
            allowClear: true
        });
        $('#districts').select2({
            placeholder: "<?php echo $this->translate('All Districts'); ?>",
            allowClear: true
        });
        $('#labName').select2({
            placeholder: "<?php echo $this->translate('All Labs'); ?>",
            allowClear: true
        });
        $('#clinicId').select2({
            placeholder: "<?php echo $this->translate('All Clinics'); ?>",
            allowClear: true
        });
        $('#piebutton').on('click', function () {
            $('#piecontainer').fadeIn(function () {
                generatePieContainer();
            });
        });
            
        $('#barbutton').on('click', function () {
            $('#barcontainer').fadeIn(function () {
                generateBarContainer();
            });
        });
        generatePieContainer();
        generateBarContainer();
        loadSampleDataTable();
    });

    
    function searchSampleTestedTAT(){
        generatePieContainer();
        generateBarContainer();
        oTable.fnDraw();
    }
    
    function resetEverything(){
        $('#pageFilter')[0].reset();
        $('#provinces').val('').change();
        $('#districts').val('').change();
        $('#labName').val('').change();
        $('#clinicId').val('').change();
        if($('#gender').val() == 'F'){
          $('.femaleSection').show();  
        }else{
          $('.femaleSection').hide();  
        }
        searchSampleTestedTAT();
    }
    
    function loadSampleDataTable(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        oTable = $('#sampleDataTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                {"sClass":"center"},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[ 0, "desc" ]],
            "sAjaxSource": "<?php echo $this->url('laboratory',array('action' => 'get-filter-sample-tat')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                aoData.push({"name": "fromDate", "value": $('#mrp-lowerDate').val()});
                aoData.push({"name": "toDate", "value": $('#mrp-upperDate').val()});
                aoData.push({"name": "provinces", "value": $('#provinces').val()});
                aoData.push({"name": "districts", "value": $('#districts').val()});
                aoData.push({"name": "lab", "value": $('#labName').val()});
                aoData.push({"name": "clinicId", "value": $('#clinicId').val()});
                aoData.push({"name": "sampleType", "value": $('#sampleType').val()});
                aoData.push({"name": "gender", "value": $('#gender').val()});
                aoData.push({"name": "isPregnant", "value": $("#isPregnant").val()});
                aoData.push({"name": "isBreastfeeding", "value": $("#isBreastfeeding").val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );
    }
    
    var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    
    $(function () {
      startMonth = '<?php echo $startMonth; ?>';
      startYear = '<?php echo $startYear; ?>';
      endMonth = '<?php echo $endMonth; ?>';
      endYear = '<?php echo $endYear; ?>';
      fiscalMonth = 7;
      //if(startMonth < 10)
        //startDate = parseInt("" + startYear + '0' + startMonth + "");
      //else
        startDate = parseInt("" + startYear  + startMonth + "");
      //if(endMonth < 10)
        //endDate = parseInt("" + endYear + '0' + endMonth + "");
      //else
        endDate = parseInt("" + endYear + endMonth + "");
      
      content = '<div class="row mpr-calendarholder">';
      calendarCount = endYear - startYear;
      if(calendarCount == 0)
        calendarCount++;
      var d = new Date();
      for(y = 0; y < 2; y++){
                    content += '<div class="col-xs-6" ><div class="mpr-calendar row" id="mpr-calendar-' + (y+1) + '">'
                                                     + '<h5 class="col-xs-12"><i class="mpr-yeardown fa fa-chevron-circle-left"></i><span>' + (startYear + y).toString() + '</span><i class="mpr-yearup fa fa-chevron-circle-right"></i></h5><div class="mpr-monthsContainer"><div class="mpr-MonthsWrapper">';
        for(m=0; m < 12; m++){
          var monthval;
          if((m+1) < 10)
            monthval = "0" + (m+1);
          else
            monthval = "" + (m+1);
                            content += '<span data-month="' + monthval  + '" class="col-xs-3 mpr-month">' + MONTHS[m] + '</span>';
        }
        content += '</div></div></div></div>';
      }
      content += '<div class="col-xs-1">';
      //content += '<button class="btn btn-info mpr-fiscal-ytd">Fiscal YTD</button>';
      //content += '<button class="btn btn-info mpr-ytd">YTD</button>';
      //content += '<button class="btn btn-info mpr-prev-fiscal">Previous FY</button>';
      //content += '<button class="btn btn-info mpr-prev-year">Previous Year</button>';
      content += '<button class="btn btn-info mpr-close">Apply</button>';
      content += '</div>';
      content += '</div>';
      
      $(document).on('click','.mpr-month',function(e){
        e.stopPropagation();
                    $month = $(this);
            var monthnum = $month.data('month');
            var year = $month.parents('.mpr-calendar').children('h5').children('span').html();
            if($month.parents('#mpr-calendar-1').size() > 0){
              //Start Date
              startDate = parseInt("" + year + monthnum);
              if(startDate > endDate){
                
                if(year != parseInt(endDate/100))
                  $('.mpr-calendar:last h5 span').html(year);
                   endDate = startDate;
              }
            }else{
              //End Date
              endDate = parseInt("" + year + monthnum);
              if(startDate > endDate){
                if(year != parseInt(startDate/100))
                  $('.mpr-calendar:first h5 span').html(year);
                startDate = endDate;
              }
            }
        
            paintMonths();
      });
      
      
      $(document).on('click','.mpr-yearup',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
                    var year = parseInt($(this).prev().html());
            year++;
            $(this).prev().html(""+year);
                    $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });
      
      $(document).on('click','.mpr-yeardown',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
                    var year = parseInt($(this).next().html());
            year--;
            $(this).next().html(""+year);
                    //paintMonths();
          $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });
      
      $(document).on('click','.mpr-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        startDate = parseInt(d.getFullYear() + "01");
        var month = d.getMonth() + 1;
        if(month < 9)
          month = "0" + month;
        endDate = parseInt("" + d.getFullYear() + month);
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          var year = $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-prev-year', function(e){
        e.stopPropagation();
        var d = new Date();
        var year = d.getFullYear()-1;
        startDate = parseInt(year + "01");
        endDate = parseInt(year + "12");
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          $('h5 span',$cal).html(year);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-fiscal-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 1;
        else
          year = d.getFullYear();
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(d.getMonth()+1 < 10)
          cm = "0" + (d.getMonth()+1);
        else
          cm = (d.getMonth()+1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + d.getFullYear() + cm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-prev-fiscal', function(){
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 2;
        else
          year = d.getFullYear() - 1;
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(fiscalMonth -1 < 10)
          efm = "0" + (fiscalMonth-1);
        else
          efm = (fiscalMonth-1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + (d.getFullYear() - 1) + efm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear()-1);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      var mprVisible = false;
      var mprpopover = $('.mrp-container').popover({
        container: "body",
        placement: "bottom",
        html: true,
        content: content
      }).on('show.bs.popover', function () {
        $('.popover').remove();
        var waiter = setInterval(function(){
          if($('.popover').size() > 0){
            clearInterval(waiter);
            setViewToCurrentYears();
                    paintMonths();
          }
        },50);
      }).on('shown.bs.popover', function(){
        mprVisible = true;
      }).on('hidden.bs.popover', function(){
        mprVisible = false;
      }); 
      
      $(document).on('click','.mpr-calendarholder',function(e){
        e.preventDefault();
        e.stopPropagation();
      });
      $(document).on("click",".mrp-container",function(e){
        if(mprVisible){
          e.preventDefault();
            e.stopPropagation();
          mprVisible = false;
        }
      });
      
      $(document).on("click",function(e){
       
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
      });
      
      $(document).on('click','.mpr-close', function(e){
        //console.log(e);
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
      });
      
    });
    
    $('#gender').on('change',function() {
        if(this.value == 'F'){
            $('.femaleSection').show();
        }else{
           $('.femaleSection').hide();
           $("#isPregnant").val('');
           $("#isBreastfeeding").val('');
        }
    });
    
    function getLocationInfo(fromSrc){
        var provinces = ($("#provinces").val() == null || $("#provinces").val() == '')?[]:$("#provinces").val();
        var districts = ($("#districts").val() == null || $("#districts").val() == '')?[]:$("#districts").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-location-info')); ?>", {provinces:provinces,districts:districts,fromSrc:fromSrc},
        function(data){
            if(fromSrc == 'provinces'){ $('#districts').val('').change(); }
            $('#labName').val('').change();
            $('#clinicId').val('').change();
            locationInfoArray = data.split('##');
            if(fromSrc == 'provinces'){ $('#districts').html(locationInfoArray[0]); }
            $('#labName').html(locationInfoArray[1]);
            $('#clinicId').html(locationInfoArray[2]);
        });
    }
    
    function exportSampleResult(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        $.post("<?php echo $this->url('laboratory', array('action' => 'export-sample-tested-result-tat-excel')); ?>", { },
         function(data){
             if(data == "" || data == null || data == undefined){
                 alert('<?php echo $this->translate('Unable to export excel'); ?>');
             }else{
                 window.open('../temporary/'+data,'_blank');
             }
         }); 
    }
</script>
<script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>