<?php
$startYear=date("Y", strtotime("-1 year"));
$startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
$endYear = date('Y');
$endMonth = date('m');

$startDate = date('Y-m', strtotime('+1 month', strtotime('-1 year')));
$endDate=date('Y-m');

?>
<link href="<?php echo $this->basePath('assets/global/css/month-year-rang-picker.css'); ?>" rel="stylesheet" type="text/css" />
           <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">Samples Tested</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"></h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    
                    
                    
                    
                    <div class="row">

                        <div class="col-md-12" style="padding-left:30px;">
                            <form class="form-Horizontal">
                                
                        <div class="col-md-12">
                            <div class="form-group col-lg-4">
                                <label class="control-label">Date Range&nbsp;</label>
                              <div id="sla-data-range" class="btn btn-sm form-control col-lg-6 mrp-container ">
                                
                                <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                                <div class="mrp-monthdisplay ">
                                  <span class="mrp-lowerMonth"><?php echo date('M', strtotime('+1 month', strtotime('-1 year')));; ?> <?php echo $startYear; ?></span>
                                  <span class="mrp-to"> to </span>
                                  <span class="mrp-upperMonth"><?php echo date('M'); ?> <?php echo date('Y'); ?></span>
                                </div>
                              <input type="hidden" value="" id="mrp-lowerDate" />
                              <input type="hidden" value="" id="mrp-upperDate" />
                            
                            </div>
                            </div>                            
                        </div>                                
                        <div class="col-md-12">        
                            <div class="form-group col-lg-4">
                                <label class="control-label">Lab&nbsp;</label>
                                <select name="labName" id="labName" class="form-control" title="Please choose lab name">
                                    <option value="">All Labs</option>
                                    <?php
                                    foreach($labName as $lab)
                                    {
                                    ?>
                                        <option value="<?php echo base64_encode($lab['facility_id']);?>"><?php echo $lab['facility_name'];?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            
                            <div class="form-group col-lg-4">
                                <label class="control-label">Hub </label>
                                <select class="form-control" id="hub" name="hub">
                                    <option value="">All Hubs</option>
                                    <?php
                                    foreach($hubName as $hub){
                                    ?>
                                    <option value="<?php echo base64_encode($hub['facility_id']);?>"><?php echo $hub['facility_name'];?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>                            
                            <div class="form-group col-lg-4">
                                <label class="control-label">Clinic&nbsp;</label>
                                <select class="form-control" id="clinicId" name="clinicId">
                                    <option value="">All Clinics</option>
                                    <?php
                                    foreach($clinicName as $clinic){
                                    ?>
                                    <option value="<?php echo base64_encode($clinic['facility_id']);?>"><?php echo $clinic['facility_name'];?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>

                        </div>                                
                        <div class="col-md-12">
                            <div class="form-group col-lg-4">
                                <label class="control-label">Current Regimen</label>
                                <select class="form-control" id="currentRegimen" name="currentRegimen">
                                    <option value="">All</option>
                                    <?php
                                    foreach($currentRegimen as $regimen){
                                    ?>
                                    <option value="<?php echo base64_encode($regimen['art_code']);?>"><?php echo $regimen['art_code'];?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">ARV Adherence</label>
                              <select class="form-control" name="adherence" id="adherence">
                                <option value="">--Select--</option>
                                <option value="good">Good >= 95%</option>
                                <option value="fair">Fair 85-94%</option>
                                <option value="poor">Poor < 85%</option>
                              </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">Age Group</label>
                                <select class="form-control" name="age" id="age" title="Please choose age group">
                                  <option value="">-- Age --</option>
                                  <option value="0-10">0-10</option>
                                  <option value="10-20">10-20</option>
                                  <option value="20-30">20-30</option>
                                  <option value="30-40">30-40</option>
                                  <option value="40-50">40-50</option>
                                  <option value="50-60">50-60</option>
                                  <option value="60-70">60-70</option>
                                  <option value="70-80">70-80</option>
                                  <option value="80">Above 80</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group col-lg-4">
                                <label class="control-label">Test Result&nbsp;</label>
                                <select class="form-control" name="testResult" id="testResult" title="Please choose result">
                                <option value="">All</option>
                                <option value=">1000" <?php echo(($searchRange=='>1000') ? "selected='selected'" : "") ?>>> 1000 cp/mL</option>
                                <option value="<1000" <?php echo(($searchRange=='<1000') ? "selected='selected'" : "") ?>>< 1000 cp/mL</option>
                              </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">Sample Type</label>
                                <select class="form-control" id="sampleType" name="sampleType">
                                    <option value="">All</option>
                                    <?php
                                    foreach($sampleType as $samples){
                                    ?>
                                    <option value="<?php echo base64_encode($samples['sample_id']);?>"><?php echo $samples['sample_name'];?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                              
                            </div>
                            <div class="form-group col-lg-4">
                                <br>
                                <a href="javascript:void(0);" class="btn btn-primary" onclick="searchSampleTestedResult()">Submit</a>
                            </div>
                        </div>
                            
                          </form>
                        </div>
                    </div>
                    
                    

                    <div class="row" style="margin-bottom:30px;">
                        <div class="col-lg-6">
                            <div id="piecontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
                        </div>
                        <div class="col-lg-6">
                            <div id="barcontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
                        </div>
                    </div>

                        <br>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cogs"></i>Samples
                                    </div>
                                    <div class="tools">
                                        <button class="btn btn-default"><span><i class="fa fa-file-excel-o" aria-hidden="true"></i> Excel</span></button>
                                    </div>

                                </div>
                                <div class="portlet-body">
                                    <div class="table-toolbar">
                                        <table class="table table-striped table-bordered table-hover order-column" id="sample_1">
                                            <thead>
                                                <tr>
                                                    <th> Date </th>
                                                    <th> No. of Samples </th>
                                                    <th> Sample Type </th>
                                                    <th> Clinics </th>
                                                    <th> Hubs </th>
                                                    <th> Status </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <td>20-Apr-2016</td>
                                                    <td>20</td>
                                                    <td>Plasma</td>
                                                    <td>Clinic 001</td>
                                                    <td>Hub 002</td>
                                                    <td>Tested</td>
                                                </tr>
                                                <tr>
                                                    <td>21-Apr-2016</td>
                                                    <td>24</td>
                                                    <td>DBS</td>
                                                    <td>Clinic 002</td>
                                                    <td>Hub 002</td>
                                                    <td>Tested</td>
                                                </tr>
                                                <tr>
                                                    <td>22-Apr-2016</td>
                                                    <td>30</td>
                                                    <td>DBS</td>
                                                    <td>Clinic 003</td>
                                                    <td>Hub 002</td>
                                                    <td>Tested</td>
                                                </tr>
                                                <tr>
                                                    <td>23-Apr-2016</td>
                                                    <td>22</td>
                                                    <td>Plasma</td>
                                                    <td>Clinic 001</td>
                                                    <td>Hub 002</td>
                                                    <td>Pending</td>
                                                </tr>
                                                <tr>
                                                    <td>24-Apr-2016</td>
                                                    <td>18</td>
                                                    <td>Plasma</td>
                                                    <td>Clinic 002</td>
                                                    <td>Hub 003</td>
                                                    <td>Tested</td>
                                                </tr>
                                                <tr>
                                                    <td>25-Apr-2016</td>
                                                    <td>14</td>
                                                    <td>Plasma</td>
                                                    <td>Clinic 003</td>
                                                    <td>Hub 001</td>
                                                    <td>Tested</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>

<script>
    
    function generateBarContainer() {
        searchGender = '<?php echo $searchGender ?>';
        searchMonth = '<?php echo $searchMonth ?>';
        testResult = $("#testResult").val();
        facilityId = $("#labName").val();
        sampleType = $("#sampleType").val();
        currentRegimen = $("#currentRegimen").val();
        adherence = $("#adherence").val();
        age = $("#age").val();
        
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-bar-sample-details')); ?>",{testResult:testResult,searchMonth:searchMonth,gender:searchGender,facilityId:facilityId,sampleType:sampleType,currentRegimen:currentRegimen,adherence:adherence,age:age},
        function(data) {
            $("#barcontainer").html(data);
        });
    }
    
    
    function generatePieContainer(){
        searchGender = '<?php echo $searchGender ?>';
        searchMonth = '<?php echo $searchMonth ?>';
        testResult = $("#testResult").val();
        facilityId = $("#labName").val();
        sampleType = $("#sampleType").val();
        currentRegimen = $("#currentRegimen").val();
        adherence = $("#adherence").val();
        age = $("#age").val();
        
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-details')); ?>",{testResult:testResult,searchMonth:searchMonth,gender:searchGender,facilityId:facilityId,sampleType:sampleType,currentRegimen:currentRegimen,adherence:adherence,age:age},
        function(data) {
            $("#piecontainer").html(data);
        });
    }
    
    
    
    $(document).ready(function(){
    
    
    
$('#piebutton').on('click', function () {
    $('#piecontainer').fadeIn(function () {
        generatePieContainer();
    });
});
    
$('#barbutton').on('click', function () {
    $('#barcontainer').fadeIn(function () {
        generateBarContainer();
    });
});
    
    generatePieContainer();
    generateBarContainer();
    
    
    
            
        });

    

function searchSampleTestedResult(){
    generatePieContainer();
    generateBarContainer();
}

var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

$(function () {
   startMonth = 7;
  startYear = 2014
  endMonth = 8;
  endYear = 2015;
  fiscalMonth = 7;
  if(startMonth < 10)
  	startDate = parseInt("" + startYear + '0' + startMonth + "");
  else
    startDate = parseInt("" + startYear  + startMonth + "");
  if(endMonth < 10)
  	endDate = parseInt("" + endYear + '0' + endMonth + "");
  else
    endDate = parseInt("" + endYear + endMonth + "");
  
  content = '<div class="row mpr-calendarholder">';
  calendarCount = endYear - startYear;
  if(calendarCount == 0)
    calendarCount++;
  var d = new Date();
  for(y = 0; y < 2; y++){
		content += '<div class="col-xs-6" ><div class="mpr-calendar row" id="mpr-calendar-' + (y+1) + '">'
 						 + '<h5 class="col-xs-12"><i class="mpr-yeardown fa fa-chevron-circle-left"></i><span>' + (startYear + y).toString() + '</span><i class="mpr-yearup fa fa-chevron-circle-right"></i></h5><div class="mpr-monthsContainer"><div class="mpr-MonthsWrapper">';
    for(m=0; m < 12; m++){
      var monthval;
      if((m+1) < 10)
        monthval = "0" + (m+1);
      else
        monthval = "" + (m+1);
			content += '<span data-month="' + monthval  + '" class="col-xs-3 mpr-month">' + MONTHS[m] + '</span>';
    }
    content += '</div></div></div></div>';
  }
  content += '<div class="col-xs-1">';
  //content += '<button class="btn btn-info mpr-fiscal-ytd">Fiscal YTD</button>';
  //content += '<button class="btn btn-info mpr-ytd">YTD</button>';
  //content += '<button class="btn btn-info mpr-prev-fiscal">Previous FY</button>';
  //content += '<button class="btn btn-info mpr-prev-year">Previous Year</button>';
  content += '<button class="btn btn-info mpr-close">Apply</button>';
  content += '</div>';
  content += '</div>';
  
  $(document).on('click','.mpr-month',function(e){
    e.stopPropagation();
  		$month = $(this);
    	var monthnum = $month.data('month');
    	var year = $month.parents('.mpr-calendar').children('h5').children('span').html();
        if($month.parents('#mpr-calendar-1').size() > 0){
          //Start Date
          startDate = parseInt("" + year + monthnum);
          if(startDate > endDate){
            
            if(year != parseInt(endDate/100))
              $('.mpr-calendar:last h5 span').html(year);
               endDate = startDate;
          }
        }else{
          //End Date
          endDate = parseInt("" + year + monthnum);
          if(startDate > endDate){
            if(year != parseInt(startDate/100))
              $('.mpr-calendar:first h5 span').html(year);
            startDate = endDate;
          }
        }
    
    	paintMonths();
  });
  
  
  $(document).on('click','.mpr-yearup',function(e){
        $('.mpr-month').css("color","black");
    	e.stopPropagation();
  		var year = parseInt($(this).prev().html());
    	year++;
    	$(this).prev().html(""+year);
   	 	$(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
      });
  });
  
  $(document).on('click','.mpr-yeardown',function(e){
        $('.mpr-month').css("color","black");
    	e.stopPropagation();
  		var year = parseInt($(this).next().html());
    	year--;
    	$(this).next().html(""+year);
   	 	//paintMonths();
      $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
      });
  });
  
  $(document).on('click','.mpr-ytd', function(e){
    e.stopPropagation();
    var d = new Date();
    startDate = parseInt(d.getFullYear() + "01");
    var month = d.getMonth() + 1;
    if(month < 9)
      month = "0" + month;
    endDate = parseInt("" + d.getFullYear() + month);
    $('.mpr-calendar').each(function(){
      var $cal = $(this);
      var year = $('h5 span',$cal).html(d.getFullYear());
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  $(document).on('click','.mpr-prev-year', function(e){
    e.stopPropagation();
    var d = new Date();
    var year = d.getFullYear()-1;
    startDate = parseInt(year + "01");
    endDate = parseInt(year + "12");
    $('.mpr-calendar').each(function(){
      var $cal = $(this);
      $('h5 span',$cal).html(year);
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  $(document).on('click','.mpr-fiscal-ytd', function(e){
    e.stopPropagation();
    var d = new Date();
    var year;
    if((d.getMonth()+1) < fiscalMonth)
      year = d.getFullYear() - 1;
    else
      year = d.getFullYear();
    if(fiscalMonth < 10)
      fm = "0" + fiscalMonth;
    else
      fm = fiscalMonth;
    if(d.getMonth()+1 < 10)
      cm = "0" + (d.getMonth()+1);
    else
      cm = (d.getMonth()+1);
    startDate = parseInt("" + year + fm);
    endDate = parseInt("" + d.getFullYear() + cm);
    $('.mpr-calendar').each(function(i){
      var $cal = $(this);
      if(i == 0)
      	$('h5 span',$cal).html(year);
      else
        $('h5 span',$cal).html(d.getFullYear());
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  $(document).on('click','.mpr-prev-fiscal', function(){
    var d = new Date();
    var year;
    if((d.getMonth()+1) < fiscalMonth)
      year = d.getFullYear() - 2;
    else
      year = d.getFullYear() - 1;
    if(fiscalMonth < 10)
      fm = "0" + fiscalMonth;
    else
      fm = fiscalMonth;
    if(fiscalMonth -1 < 10)
      efm = "0" + (fiscalMonth-1);
    else
      efm = (fiscalMonth-1);
    startDate = parseInt("" + year + fm);
    endDate = parseInt("" + (d.getFullYear() - 1) + efm);
    $('.mpr-calendar').each(function(i){
      var $cal = $(this);
      if(i == 0)
      	$('h5 span',$cal).html(year);
      else
        $('h5 span',$cal).html(d.getFullYear()-1);
    });
    $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
        paintMonths();
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
    });
  });
  
  var mprVisible = false;
  var mprpopover = $('.mrp-container').popover({
    container: "body",
    placement: "bottom",
    html: true,
    content: content
  }).on('show.bs.popover', function () {
    $('.popover').remove();
    var waiter = setInterval(function(){
      if($('.popover').size() > 0){
        clearInterval(waiter);
        setViewToCurrentYears();
    		paintMonths();
      }
    },50);
  }).on('shown.bs.popover', function(){
    mprVisible = true;
  }).on('hidden.bs.popover', function(){
    mprVisible = false;
  }); 
  
  $(document).on('click','.mpr-calendarholder',function(e){
    e.preventDefault();
    e.stopPropagation();
  });
  $(document).on("click",".mrp-container",function(e){
    if(mprVisible){
      e.preventDefault();
    	e.stopPropagation();
      mprVisible = false;
    }
  });
  
  $(document).on("click",function(e){
   
    if(mprVisible){
    	$('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
        $('.mpr-calendarholder').parents('.popover').remove();
        $('.mrp-container').trigger('click');
      });
      mprVisible = false;
    }
  });
  
  $(document).on('click','.mpr-close', function(e){
    //console.log(e);
    if(mprVisible){
    	$('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
        $('.mpr-calendarholder').parents('.popover').remove();
        $('.mrp-container').trigger('click');
      });
      mprVisible = false;
    }
  });
  
});

  
</script>
<script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>