<?php
if(isset($searchMonth) && trim($searchMonth)!= ''){
    $splitSearchMonth = explode("-",$searchMonth);
    $startDate = $endDate = $splitSearchMonth[1].' '.date('m', strtotime($splitSearchMonth[0]));
    $startMonth = $endMonth = date('m', strtotime($splitSearchMonth[0]));
    $startYear = $endYear = $splitSearchMonth[1];
    $startDisplayDate = $endDisplayDate = str_replace('-',' ',$searchMonth);
}else if((isset($fromMonth) && trim($fromMonth)!= '') && (isset($toMonth) && trim($toMonth)!= '')){
    $splitFromMonth = explode("-",$fromMonth);
    $startDate = $splitFromMonth[0].'-'.$splitFromMonth[1];
    $startMonth = $splitFromMonth[1];
    $startYear = $splitFromMonth[0];
    $startDisplayDate = date("M", mktime(0, 0, 0, $splitFromMonth[1])).' '.$splitFromMonth[0];
    $splitToMonth = explode("-",$toMonth);
    $endDate = $splitToMonth[0].'-'.$splitToMonth[1];
    $endMonth = $splitToMonth[1];
    $endYear = $splitToMonth[0];
    $endDisplayDate = date("M", mktime(0, 0, 0, $splitToMonth[1])).' '.$splitToMonth[0];
}else{
    $startDate = date("Y", strtotime("-1 year")).'-'.date('m', strtotime('+1 month', strtotime('-1 year')));
    $endDate = date('Y').'-'.date('m');
    $startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
    $endMonth = date('m');
    $startYear = date("Y", strtotime("-1 year"));
    $endYear = date('Y');
    $startDisplayDate  = strtoupper(date('M', strtotime('+1 month', strtotime('-1 year')))).' '.date("Y", strtotime("-1 year"));
    $endDisplayDate  = strtoupper(date('M')).' '.date('Y');
}
//set selected labs
$selectedLabs = array();
if(isset($labFilter) && trim($labFilter)!= ''){
    $selectedLabs = explode(",",$labFilter);
}
//set selected provinces
$selectedProvinces = array();
if(isset($facilityInfo['selectedProvinces']) && count($facilityInfo['selectedProvinces']) >0){
    foreach($facilityInfo['selectedProvinces'] as $province){
        $selectedProvinces[] = $province['location_id'];
    }
}
//set selected districts
$selectedDistricts = array();
if(isset($facilityInfo['labDistricts']) && count($facilityInfo['labDistricts']) >0){
    foreach($facilityInfo['labDistricts'] as $district){
        $selectedDistricts[] = $district['facility_district'];
    }
}
?>
<link href="<?php echo $this->basePath('assets/global/css/month-year-rang-picker.css'); ?>" rel="stylesheet" type="text/css" />
<!-- BEGIN PAGE HEADER-->
    <!-- BEGIN THEME PANEL -->
    <!-- END THEME PANEL -->
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <h1 class="page-title"><?php echo $this->translate('Samples Overview'); ?>
        <ul class="page-breadcrumb pull-right">
            <li>
                <i class="fa fa-arrow-left"></i>
                <a href="/labs/dashboard"><?php echo $this->translate('Back to Labs Dashboard'); ?></a>
            </li>
        </ul>
        </h1>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <h3 class="page-title"></h3>
    <!-- END PAGE TITLE-->
    <!-- END PAGE HEADER-->
    <form id="pageFilter" action="#" method="">
        <div class="row">
            <div class="col-md-12" style="padding-left:30px;">
            <div class="col-md-12">
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Date Range'); ?>&nbsp;</label>
                  <div id="sla-data-range" class="btn btn-sm form-control col-lg-6 mrp-container ">
                    
                    <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                    <div class="mrp-monthdisplay ">
                      <span class="mrp-lowerMonth"><?php echo $startDisplayDate; ?></span>
                      <span class="mrp-to"> to </span>
                      <span class="mrp-upperMonth"><?php echo $endDisplayDate; ?></span>
                    </div>
                  <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" />
                  <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
                </div>
                </div>
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Provinces'); ?>&nbsp;</label>
                    <select name="provinces[]" id="provinces" class="form-control" multiple title="<?php echo $this->translate('Please choose provinces'); ?>" onchange="getLocationInfo('provinces');">
                        <?php
                        if(isset($facilityInfo['provinces']) && count($facilityInfo['provinces']) > 0){
                            foreach($facilityInfo['provinces'] as $province){
                        ?>
                            <option value="<?php echo $province['location_id']; ?>" <?php echo(in_array($province['location_id'],$selectedProvinces))?'selected="selected"':''; ?>><?php echo ucwords($province['location_name']); ?></option>
                        <?php } } ?>
                    </select>
                </div>
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Districts'); ?>&nbsp;</label>
                    <select name="districts[]" id="districts" class="form-control" multiple title="<?php echo $this->translate('Please choose districts'); ?>" onchange="getLocationInfo('districts');">
                        <?php
                        if(isset($facilityInfo['provinceDistricts']) && count($facilityInfo['provinceDistricts']) > 0){
                            foreach($facilityInfo['provinceDistricts'] as $provinceDistrict){
                        ?>
                            <option value="<?php echo $provinceDistrict['location_id']; ?>" <?php echo(in_array($provinceDistrict['location_id'],$selectedDistricts))?'selected="selected"':''; ?>><?php echo ucwords($provinceDistrict['location_name']); ?></option>
                        <?php } } ?>
                    </select>
                </div>
            </div>                                
            <div class="col-md-12">        
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Labs'); ?>&nbsp;</label>
                    <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please choose labs'); ?>">
                        <?php
                        if(isset($facilityInfo['labs']) && count($facilityInfo['labs']) > 0){
                            foreach($facilityInfo['labs'] as $labs){
                        ?>
                            <option value="<?php echo $labs['facility_id']; ?>" <?php echo(in_array($labs['facility_id'],$selectedLabs))?'selected="selected"':''; ?>><?php echo ucwords($labs['facility_name']); ?></option>
                        <?php } } ?>
                    </select>
                </div>
                <!--<div class="form-group col-lg-4">
                    <label class="control-label">< ?php echo $this->translate('Hub'); ?> </label>
                    <select class="form-control" id="hub" name="hub">
                        <option value="">All Hubs</option>
                        < ?php
                        foreach($hubName as $hub){
                        ?>
                          <option value="< ?php echo base64_encode($hub['facility_id']);?>">< ?php echo $hub['facility_name'];?></option>
                        < ?php
                        }
                        ?>
                    </select>
                </div>  -->                          
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Clinics'); ?>&nbsp;</label>
                    <select class="form-control" id="clinicId" name="clinicId[]" multiple title="<?php echo $this->translate('Please choose clinics'); ?>">
                        <?php
                        if(isset($facilityInfo['clinics']) && count($facilityInfo['clinics']) > 0){
                            foreach($facilityInfo['clinics'] as $clinics){
                        ?>
                            <option value="<?php echo $clinics['facility_id']; ?>"><?php echo ucwords($clinics['facility_name']); ?></option>
                        <?php } } ?>
                    </select>
                </div>
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Current Regimen'); ?></label>
                    <select class="form-control" id="currentRegimen" name="currentRegimen">
                        <option value=""><?php echo $this->translate('All'); ?></option>
                        <?php
                        foreach($currentRegimen as $regimen){
                        ?>
                          <option value="<?php echo base64_encode($regimen['art_code']);?>"><?php echo $regimen['art_code'];?></option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
            </div>                                
            <div class="col-md-12">
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('ARV Adherence'); ?></label>
                  <select class="form-control" name="adherence" id="adherence">
                    <option value="">-- <?php echo $this->translate('Select'); ?> --</option>
                    <option value="good"><?php echo $this->translate('Good'); ?> >= 95%</option>
                    <option value="fair"><?php echo $this->translate('Fair'); ?> 85-94%</option>
                    <option value="poor"><?php echo $this->translate('Poor'); ?> < 85%</option>
                  </select>
                </div>
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Age Group'); ?></label>
                    <select class="form-control" name="age[]" id="age" multiple title="<?php echo $this->translate('Please choose age group'); ?>">
                      <option value="<2" <?php echo((isset($age) && $age =='<2')) ? "selected='selected'" : ""; ?>> < 2</option>
                      <option value="2to5" <?php echo((isset($age) && $age =='2-5')) ? "selected='selected'" : ""; ?>> 2 - 5</option>
                      <option value="6to14" <?php echo((isset($age) && $age =='6-14')) ? "selected='selected'" : ""; ?>> 6 - 14</option>
                      <option value="15to49" <?php echo((isset($age) && $age =='15-49')) ? "selected='selected'" : ""; ?>> 15 - 49</option>
                      <option value=">=50" <?php echo((isset($age) && $age =='>=50')) ? "selected='selected'" : ""; ?>> >= 50</option>
                      <option value="unknown" <?php echo((isset($age) && $age =='Unknown')) ? "selected='selected'" : ""; ?>> <?php echo $this->translate('Unknown'); ?></option>
                    </select>
                </div>
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Test Result'); ?>&nbsp;</label>
                    <select class="form-control" name="testResult" id="testResult" title="<?php echo $this->translate('Please choose result'); ?>">
                    <option value=""><?php echo $this->translate('All'); ?></option>
                    <option value=">=1000" <?php echo((isset($result) && $result=='Not Suppressed') ? "selected='selected'" : "") ?>><?php echo $this->translate('>= 1000 cp/ml'); ?></option>
                    <option value="<1000" <?php echo((isset($result) && $result=='Suppressed') ? "selected='selected'" : "") ?>><?php echo $this->translate('< 1000 cp/ml'); ?></option>
                  </select>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Sample Type'); ?></label>
                    <select class="form-control" id="sampleType" name="sampleType">
                        <option value=""><?php echo $this->translate('All'); ?></option>
                        <?php
                        foreach($sampleType as $samples){
                        ?>
                          <option value="<?php echo base64_encode($samples['sample_id']);?>"><?php echo $samples['sample_name'];?></option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
                <div class="form-group col-lg-4">
                    <label class="control-label"><?php echo $this->translate('Line of Treatment'); ?></label>
                    <select class="form-control" name="lineOfTreatment" id="lineOfTreatment">
                      <option value=""><?php echo $this->translate('All'); ?></option>
                      <option value="1" <?php echo (isset($lt) && $lt == 'LOT1')?'selected="selected"':''; ?>><?php echo $this->translate('Line Of Treatment 1'); ?></option>
                      <option value="2" <?php echo (isset($lt) && $lt == 'LOT2')?'selected="selected"':''; ?>><?php echo $this->translate('Line Of Treatment 2'); ?></option>
                      <option value="3" <?php echo (isset($lt) && $lt == 'LOT3')?'selected="selected"':''; ?>><?php echo $this->translate('Line Of Treatment 3'); ?></option>
                      <option value="not_specified" <?php echo (isset($lt) && $lt == 'NS')?'selected="selected"':''; ?>><?php echo $this->translate('Not Specified'); ?></option>
                    </select>
                </div>
                <div class="form-group col-lg-4">
                  <label class="control-label"><?php echo $this->translate('Gender'); ?></label>
                  <select class="form-control" name="gender" id="gender">
                    <option value=""><?php echo $this->translate('All'); ?></option>
                    <option value="M" <?php echo (isset($searchGender) && $searchGender == 'M')?'selected="selected"':''; ?>><?php echo $this->translate('Male'); ?></option>
                    <option value="F" <?php echo (isset($searchGender) && $searchGender == 'F')?'selected="selected"':''; ?>><?php echo $this->translate('Female'); ?></option>
                    <option value="not_specified" <?php echo (isset($searchGender) && $searchGender == 'Not Specified')?'selected="selected"':''; ?>><?php echo $this->translate('Not Specified'); ?></option>
                  </select>
                </div>
            </div>
            <div class="col-md-12">
                <div class="form-group col-lg-4 femaleSection" style="display:<?php echo (isset($searchGender) && $searchGender == 'F')?'':'none'; ?>;">
                    <label class="control-label"><?php echo $this->translate('Is Patient Pregnant'); ?></label>
                    <select class="form-control" name="isPregnant" id="isPregnant">
                      <option value=""><?php echo $this->translate('All'); ?></option>  
                      <option value="yes" <?php echo(isset($femaleFilter) && $femaleFilter == 'P')?'selected="selected"':''; ?>><?php echo $this->translate('Yes'); ?></option>
                      <option value="no" <?php echo(isset($femaleFilter) && $femaleFilter == 'NP')?'selected="selected"':''; ?>><?php echo $this->translate('No'); ?></option>
                      <option value="unreported" <?php echo(isset($femaleFilter) && $femaleFilter == 'PU')?'selected="selected"':''; ?>><?php echo $this->translate('Unreported'); ?></option>
                    </select>
                </div>
                <div class="form-group col-lg-4 femaleSection" style="display:<?php echo (isset($searchGender) && $searchGender == 'F')?'':'none'; ?>;">
                    <label class="control-label"><?php echo $this->translate('Is Patient Breastfeeding'); ?></label>
                    <select class="form-control" name="isBreastfeeding" id="isBreastfeeding">
                      <option value=""><?php echo $this->translate('All'); ?></option>  
                      <option value="yes" <?php echo(isset($femaleFilter) && $femaleFilter == 'BF')?'selected="selected"':''; ?>><?php echo $this->translate('Yes'); ?></option>
                      <option value="no" <?php echo(isset($femaleFilter) && $femaleFilter == 'NBF')?'selected="selected"':''; ?>><?php echo $this->translate('No'); ?></option>
                      <option value="unreported" <?php echo(isset($femaleFilter) && $femaleFilter == 'BFU')?'selected="selected"':''; ?>><?php echo $this->translate('Unreported'); ?></option>
                    </select>
                </div>
            </div>
            <div class="col-md-12">
               <div class="form-group col-lg-12" style="text-align:center;margin-top:10px;">
                    <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="searchSampleTestedResult()"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                    <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
                </div>
             </div>
            </div>
        </div>
    </form>
    <hr style="background: #000 !important;border-color:#ccc;">
    <div class="row" style="margin-bottom:30px;">
        <div class="col-lg-6">
            <div id="piecontainer" style="min-width: 310px; height: 600px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
        </div>
        <div class="col-lg-6">
            <div id="vlSuppressedNotsuppressedPieContainer" style="min-width: 310px; height: 600px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
        </div>
    </div>
    <div class="row" style="margin-bottom:30px;">
        <div class="col-lg-12">
            <div id="barcontainer" style="width:100%;height: 600px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-cogs"></i><?php echo $this->translate('Samples Tested'); ?>
                    </div>
                    <div class="tools">
                        <button class="btn btn-default" onclick="exportSampleResult();"><span><i class="fa fa-file-excel-o" aria-hidden="true"></i> <?php echo $this->translate('Excel'); ?></span></button>
                    </div>

                </div>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <table class="table table-striped table-bordered table-hover order-column" id="sampleDataTable">
                            <thead>
                                <tr>
                                    <th><?php echo $this->translate('Lab'); ?> </th>
                                    <th><?php echo $this->translate('Samples Collected'); ?> </th>
                                    <th><?php echo $this->translate('Samples Tested'); ?> </th>
                                    <th><?php echo $this->translate('Results Not Available'); ?> </th>
                                    <th><?php echo $this->translate('Samples Suppressed'); ?> </th>
                                    <th><?php echo $this->translate('Samples Not Suppressed'); ?> </th>
                                    <th><?php echo $this->translate('Samples Rejected'); ?> </th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td colspan="7" class="dataTables_empty">Loading data from server</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
<script>
    function generatePieContainer(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        var fromDate = $('#mrp-lowerDate').val();
        var toDate = $('#mrp-upperDate').val();
        var provinces = ($("#provinces").val() == null)?'':$("#provinces").val().join(',');
        var districts = ($("#districts").val() == null)?'':$("#districts").val().join(',');
        var lab = ($("#labName").val() == null)?'':$("#labName").val().join(',');
        var clinicId = ($("#clinicId").val() == null)?'':$("#clinicId").val().join(',');
        var currentRegimen = $("#currentRegimen").val();
        var adherence = $("#adherence").val();
        var age = ($("#age").val() == null)?'':$("#age").val().join(',');
        var testResult = $("#testResult").val();
        var sampleType = $("#sampleType").val();
        var gender = $("#gender").val();
        var isPregnant = $("#isPregnant").val();
        var isBreastfeeding = $("#isBreastfeeding").val();
        var lineOfTreatment = $("#lineOfTreatment").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-details')); ?>",{fromDate:fromDate,toDate:toDate,provinces:provinces,districts:districts,lab:lab,clinicId:clinicId,currentRegimen:currentRegimen,adherence:adherence,age:age,testResult:testResult,sampleType:sampleType,gender:gender,isPregnant:isPregnant,isBreastfeeding:isBreastfeeding,lineOfTreatment:lineOfTreatment},
        function(data) {
            $("#piecontainer").html(data);
        });
    }
    
    function generateVlOutComePiechart(){
        var fromDate = $('#mrp-lowerDate').val();
        var toDate = $('#mrp-upperDate').val();
        var provinces = ($("#provinces").val() == null)?'':$("#provinces").val().join(',');
        var districts = ($("#districts").val() == null)?'':$("#districts").val().join(',');
        var lab = ($("#labName").val() == null)?'':$("#labName").val().join(',');
        var clinicId = ($("#clinicId").val() == null)?'':$("#clinicId").val().join(',');
        var currentRegimen = $("#currentRegimen").val();
        var adherence = $("#adherence").val();
        var age = ($("#age").val() == null)?'':$("#age").val().join(',');
        var testResult = $("#testResult").val();
        var sampleType = $("#sampleType").val();
        var gender = $("#gender").val();
        var isPregnant = $("#isPregnant").val();
        var isBreastfeeding = $("#isBreastfeeding").val();
        var lineOfTreatment = $("#lineOfTreatment").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-vl-out-comes')); ?>",{fromDate:fromDate,toDate:toDate,provinces:provinces,districts:districts,lab:lab,clinicId:clinicId,currentRegimen:currentRegimen,adherence:adherence,age:age,testResult:testResult,sampleType:sampleType,gender:gender,isPregnant:isPregnant,isBreastfeeding:isBreastfeeding,lineOfTreatment:lineOfTreatment},
        function(data) {
            $("#vlSuppressedNotsuppressedPieContainer").html(data);
        });
    }
    
    function generateBarContainer() {
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        var fromDate = $('#mrp-lowerDate').val();
        var toDate = $('#mrp-upperDate').val();
        var provinces = ($("#provinces").val() == null)?'':$("#provinces").val().join(',');
        var districts = ($("#districts").val() == null)?'':$("#districts").val().join(',');
        var lab = ($("#labName").val() == null)?'':$("#labName").val().join(',');
        var clinicId = ($("#clinicId").val() == null)?'':$("#clinicId").val().join(',');
        var currentRegimen = $("#currentRegimen").val();
        var adherence = $("#adherence").val();
        var age = ($("#age").val() == null)?'':$("#age").val().join(',');
        var testResult = $("#testResult").val();
        var sampleType = $("#sampleType").val();
        var gender = $("#gender").val();
        var isPregnant = $("#isPregnant").val();
        var isBreastfeeding = $("#isBreastfeeding").val();
        var lineOfTreatment = $("#lineOfTreatment").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-bar-sample-details')); ?>",{fromDate:fromDate,toDate:toDate,provinces:provinces,districts:districts,lab:lab,clinicId:clinicId,currentRegimen:currentRegimen,adherence:adherence,age:age,testResult:testResult,sampleType:sampleType,gender:gender,isPregnant:isPregnant,isBreastfeeding:isBreastfeeding,lineOfTreatment:lineOfTreatment},
        function(data) {
            $("#barcontainer").html(data);
        });
    }
    
    var oTable = null;
    $(document).ready(function(){
        $('#provinces').select2({
            placeholder: "<?php echo $this->translate('All Provinces'); ?>",
            allowClear: true
        });
        $('#districts').select2({
            placeholder: "<?php echo $this->translate('All Districts'); ?>",
            allowClear: true
        });
        $('#labName').select2({
            placeholder: "<?php echo $this->translate('All Labs'); ?>",
            allowClear: true
        });
        $('#clinicId').select2({
            placeholder: "<?php echo $this->translate('All Clinics'); ?>",
            allowClear: true
        });
        $('#age').select2({
            placeholder: "<?php echo $this->translate('All'); ?>",
            allowClear: true
        });
        $('#piebutton').on('click', function () {
            $('#piecontainer').fadeIn(function () {
                generatePieContainer();
            });
        });
            
        $('#barbutton').on('click', function () {
            $('#barcontainer').fadeIn(function () {
                generateBarContainer();
            });
        });
        generatePieContainer();
        generateVlOutComePiechart();
        generateBarContainer();
        loadSampleDataTable();
    });

    
    function searchSampleTestedResult(){
        generatePieContainer();
        generateVlOutComePiechart();
        generateBarContainer();
        oTable.fnDraw();
    }
    
    function resetEverything(){
        $("#pageFilter")[0].reset();
        $('#provinces').val('').change();
        $('#districts').val('').change();
        $('#labName').val('').change();
        $('#clinicId').val('').change();
        $('#age').val('').change();
        if($('#gender').val() == 'F'){
          $('.femaleSection').show();
        }else{
          $('.femaleSection').hide();  
        }
        searchSampleTestedResult();
    }
    
    function loadSampleDataTable(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        oTable = $('#sampleDataTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                {"sClass":"center"},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[ 0, "asc" ]],
            "sAjaxSource": "<?php echo $this->url('laboratory',array('action' => 'get-filter-sample-details')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                aoData.push({"name": "fromDate", "value": $('#mrp-lowerDate').val()});
                aoData.push({"name": "toDate", "value": $('#mrp-upperDate').val()});
                aoData.push({"name": "provinces", "value": $('#provinces').val()});
                aoData.push({"name": "districts", "value": $('#districts').val()});
                aoData.push({"name": "lab", "value": $('#labName').val()});
                aoData.push({"name": "clinicId", "value": $('#clinicId').val()});
                aoData.push({"name": "currentRegimen", "value": $('#currentRegimen').val()});
                aoData.push({"name": "adherence", "value": $('#adherence').val()});
                aoData.push({"name": "age", "value": $('#age').val()});
                aoData.push({"name": "sampleType", "value": $('#sampleType').val()});
                aoData.push({"name": "gender", "value": $('#gender').val()});
                aoData.push({"name": "isPregnant", "value": $("#isPregnant").val()});
                aoData.push({"name": "isBreastfeeding", "value": $("#isBreastfeeding").val()});
                aoData.push({"name": "lineOfTreatment", "value": $("#lineOfTreatment").val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );
    }
    
    $('#gender').on('change',function() {
        if(this.value == 'F'){
            $('.femaleSection').show();
        }else{
           $('.femaleSection').hide();
           $("#isPregnant").val('');
           $("#isBreastfeeding").val('');
        }
    });
    
    function getLocationInfo(fromSrc){
        var provinces = ($("#provinces").val() == null || $("#provinces").val() == '')?[]:$("#provinces").val();
        var districts = ($("#districts").val() == null || $("#districts").val() == '')?[]:$("#districts").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-location-info')); ?>", {provinces:provinces,districts:districts,fromSrc:fromSrc},
        function(data){
            if(fromSrc == 'provinces'){ $('#districts').val('').change(); }
            $('#labName').val('').change();
            $('#clinicId').val('').change();
            var locationInfoArray = data.split('##');
            if(fromSrc == 'provinces'){ $('#districts').html(locationInfoArray[0]); }
            $('#labName').html(locationInfoArray[1]);
            $('#clinicId').html(locationInfoArray[2]);
        });
    }
    
    function exportSampleResult(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        $.post("<?php echo $this->url('laboratory', array('action' => 'export-sample-result-excel')); ?>", {fromDate:$('#mrp-lowerDate').val(),toDate:$('#mrp-upperDate').val()},
         function(data){
            if(data == "" || data == null || data == undefined){
                alert('<?php echo $this->translate('Unable to export excel'); ?>');
            }else{
                window.open('../temporary/'+data,'_blank');
            }
         }); 
    }
</script>
<script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>