<?php
if(isset($searchMonth) && trim($searchMonth)!= ''){
    $splitSearchMonth = explode("-",$searchMonth);
    $startDate = $endDate = $splitSearchMonth[1].'-'.date('m', strtotime($splitSearchMonth[0]));
    $startMonth = $endMonth = date('m', strtotime($splitSearchMonth[0]));
    $startYear = $endYear = $splitSearchMonth[1];
    $startDisplayDate = $endDisplayDate = $searchMonth;
}else if((isset($fromMonth) && trim($fromMonth)!= '') && (isset($toMonth) && trim($toMonth)!= '')){
    $splitFromMonth = explode("-",$fromMonth);
    $startDate = $splitFromMonth[1].'-'.date('m', strtotime($splitFromMonth[0]));
    $startMonth = date('m', strtotime($splitFromMonth[0]));
    $startYear = $splitFromMonth[1];
    $startDisplayDate = $fromMonth;
    $splitToMonth = explode("-",$toMonth);
    $endDate = $splitToMonth[1].'-'.date('m', strtotime($splitToMonth[0]));
    $endMonth = date('m', strtotime($splitToMonth[0]));
    $endYear = $splitToMonth[1];
    $endDisplayDate = $toMonth;
}else{
    $startDate = date("Y", strtotime("-1 year")).'-'.date('m', strtotime('+1 month', strtotime('-1 year')));
    $endDate = date('Y').'-'.date('m');
    $startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
    $endMonth = date('m');
    $startYear = date("Y", strtotime("-1 year"));
    $endYear = date('Y');
    $startDisplayDate  = strtoupper(date('M', strtotime('+1 month', strtotime('-1 year')))).' '.date("Y", strtotime("-1 year"));
    $endDisplayDate  = strtoupper(date('M')).' '.date('Y');
}
//set selected labs
$selectedLabs = array();
if(isset($labFilter) && trim($labFilter)!= ''){
    $selectedLabs = explode(",",$labFilter);
}
//set selected provinces
$selectedProvinces = array();
if(isset($facilityInfo['selectedProvinces']) && count($facilityInfo['selectedProvinces']) >0){
    foreach($facilityInfo['selectedProvinces'] as $province){
        $selectedProvinces[] = $province['location_id'];
    }
}
//set selected districts
$selectedDistricts = array();
if(isset($facilityInfo['labDistricts']) && count($facilityInfo['labDistricts']) >0){
    foreach($facilityInfo['labDistricts'] as $district){
        $selectedDistricts[] = $district['facility_district'];
    }
}
?>
<link href="<?php echo $this->basePath('assets/global/css/month-year-rang-picker.css'); ?>" rel="stylesheet" type="text/css" />
           <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                     <div class="page-bar">
                        <h1 class="page-title"><?php echo $this->translate('Sample Test Volume'); ?>
                        <ul class="page-breadcrumb pull-right">
                            <li>
                                <i class="fa fa-arrow-left"></i>
                                <a href="/labs/dashboard"><?php echo $this->translate('Back to Labs Dashboard'); ?></a>
                            </li>
                        </ul>
                        </h1>
                    </div>                    
                   
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"></h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <form id="pageFilter" action="#" method="">
                        <div class="row">
                            <div class="col-md-12" style="padding-left:30px;">
                            <div class="col-md-12">
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Date Range'); ?>&nbsp;</label>
                                  <div id="sla-data-range" class="btn btn-sm form-control col-lg-6 mrp-container ">
                                    
                                    <span class="mrp-icon"><i class="fa fa-calendar"></i> &nbsp;</span>
                                    <div class="mrp-monthdisplay ">
                                      <span class="mrp-lowerMonth"><?php echo $startDisplayDate; ?></span>
                                      <span class="mrp-to"> to </span>
                                      <span class="mrp-upperMonth"><?php echo $endDisplayDate; ?></span>
                                    </div>
                                  <input type="hidden" value="<?php echo $startDate; ?>" id="mrp-lowerDate" />
                                  <input type="hidden" value="<?php echo $endDate; ?>" id="mrp-upperDate" />
                                
                                </div>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Provinces'); ?>&nbsp;</label>
                                    <select name="provinces[]" id="provinces" class="form-control" multiple title="<?php echo $this->translate('Please choose provinces'); ?>" onchange="getLocationInfo('provinces');">
                                        <?php
                                        if(isset($facilityInfo['provinces']) && count($facilityInfo['provinces']) > 0){
                                            foreach($facilityInfo['provinces'] as $province){
                                        ?>
                                            <option value="<?php echo $province['location_id']; ?>" <?php echo(in_array($province['location_id'],$selectedProvinces))?'selected="selected"':''; ?>><?php echo ucwords($province['location_name']); ?></option>
                                        <?php } } ?>
                                    </select>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Districts'); ?>&nbsp;</label>
                                    <select name="districts[]" id="districts" class="form-control" multiple title="<?php echo $this->translate('Please choose districts'); ?>" onchange="getLocationInfo('districts');">
                                        <?php
                                        if(isset($facilityInfo['provinceDistricts']) && count($facilityInfo['provinceDistricts']) > 0){
                                            foreach($facilityInfo['provinceDistricts'] as $provinceDistrict){
                                        ?>
                                            <option value="<?php echo $provinceDistrict['location_id']; ?>" <?php echo(in_array($provinceDistrict['location_id'],$selectedDistricts))?'selected="selected"':''; ?>><?php echo ucwords($provinceDistrict['location_name']); ?></option>
                                        <?php } } ?>
                                    </select>
                                </div>
                            </div>                                
                            <div class="col-md-12">        
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Labs'); ?>&nbsp;</label>
                                    <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please choose labs'); ?>">
                                        <?php
                                        if(isset($facilityInfo['labs']) && count($facilityInfo['labs']) > 0){
                                            foreach($facilityInfo['labs'] as $labs){
                                        ?>
                                            <option value="<?php echo $labs['facility_id']; ?>" <?php echo(in_array($labs['facility_code'],$selectedLabs))?'selected="selected"':''; ?>><?php echo ucwords($labs['facility_name']); ?></option>
                                        <?php } } ?>
                                    </select>
                                </div>
                                
                                <!--<div class="form-group col-lg-4">
                                    <label class="control-label">< ?php echo $this->translate('Hub'); ?> </label>
                                    <select class="form-control" id="hub" name="hub">
                                        <option value="">All Hubs</option>
                                        < ?php
                                        foreach($hubName as $hub){
                                        ?>
                                        <option value="< ?php echo base64_encode($hub['facility_id']);?>">< ?php echo $hub['facility_name'];?></option>
                                        < ?php
                                        }
                                        ?>
                                    </select>
                                </div>  -->                          
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Clinics'); ?>&nbsp;</label>
                                    <select class="form-control" id="clinicId" name="clinicId[]" multiple title="<?php echo $this->translate('Please choose clinics'); ?>">
                                        <?php
                                        if(isset($facilityInfo['clinics']) && count($facilityInfo['clinics']) > 0){
                                            foreach($facilityInfo['clinics'] as $clinics){
                                        ?>
                                            <option value="<?php echo $clinics['facility_id']; ?>"><?php echo ucwords($clinics['facility_name']); ?></option>
                                        <?php } } ?>
                                    </select>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Current Regimen'); ?></label>
                                    <select class="form-control" id="currentRegimen" name="currentRegimen">
                                        <option value=""><?php echo $this->translate('All'); ?></option>
                                        <?php
                                        foreach($currentRegimen as $regimen){
                                        ?>
                                          <option value="<?php echo base64_encode($regimen['art_code']);?>"><?php echo $regimen['art_code'];?></option>
                                        <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>                                
                            <div class="col-md-12">
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('ARV Adherence'); ?></label>
                                  <select class="form-control" name="adherence" id="adherence">
                                    <option value="">-- <?php echo $this->translate('Select'); ?> --</option>
                                    <option value="good"><?php echo $this->translate('Good'); ?> >= 95%</option>
                                    <option value="fair"><?php echo $this->translate('Fair'); ?> 85-94%</option>
                                    <option value="poor"><?php echo $this->translate('Poor'); ?> < 85%</option>
                                  </select>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Age Group'); ?></label>
                                    <select class="form-control" name="age" id="age" title="<?php echo $this->translate('Please choose age group'); ?>">
                                      <option value="">-- <?php echo $this->translate('Age'); ?> --</option>
                                      <option value="<18" <?php echo (isset($age) && $age == '<18')?'selected="selected"':''; ?>> <18</option>
                                      <option value=">18" <?php echo (isset($age) && $age == '>18')?'selected="selected"':''; ?>> >18</option>
                                      <option value="unknown"> <?php echo $this->translate('Unknown'); ?></option>
                                    </select>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Sample Type'); ?></label>
                                    <select class="form-control" id="sampleType" name="sampleType">
                                        <option value=""><?php echo $this->translate('All'); ?></option>
                                        <?php
                                        foreach($sampleType as $samples){
                                        ?>
                                          <option value="<?php echo base64_encode($samples['sample_id']);?>"><?php echo $samples['sample_name'];?></option>
                                        <?php
                                        }
                                        ?>
                                    </select>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Sample Status'); ?></label>
                                  <select class="form-control" name="sampleStatus" id="sampleStatus">
                                    <option value=""><?php echo $this->translate('All Samples'); ?></option>
                                    <option value="sample_tested" <?php echo (isset($sampleStatus) && trim($sampleStatus) == 'sample_tested')?'selected="selected"':''; ?>><?php echo $this->translate('Samples Tested'); ?></option>
                                    <option value="samples_not_tested" <?php echo (isset($sampleStatus) && trim($sampleStatus) == 'samples_not_tested')?'selected="selected"':''; ?>><?php echo $this->translate('Samples Not Tested'); ?></option>
                                    <option value="sample_rejected" <?php echo (isset($sampleStatus) && trim($sampleStatus) == 'sample_rejected')?'selected="selected"':''; ?>><?php echo $this->translate('Samples Rejected'); ?></option>
                                  </select>
                                </div>
                                <div class="form-group col-lg-4">
                                    <label class="control-label"><?php echo $this->translate('Gender'); ?></label>
                                  <select class="form-control" name="gender" id="gender">
                                    <option value=""><?php echo $this->translate('All'); ?></option>
                                    <option value="M"><?php echo $this->translate('Male'); ?></option>
                                    <option value="F"><?php echo $this->translate('Female'); ?></option>
                                    <option value="not_specified"><?php echo $this->translate('Not Specified'); ?></option>
                                  </select>
                                </div>
                                <div class="form-group col-lg-4 femaleSection" style="display:none;">
                                    <label class="control-label"><?php echo $this->translate('Is Patient Pregnant'); ?></label><br>
                                    <input id="pregnantYes" name="isPregnant" value="yes" type="radio"> <?php echo $this->translate('Yes'); ?>&nbsp;&nbsp;
                                    <input id="pregnantNo" name="isPregnant" value="no" type="radio"> <?php echo $this->translate('No'); ?>&nbsp;&nbsp;
                                    <input id="pregnantUnreported" name="isPregnant" value="unreported" type="radio"> <?php echo $this->translate('Unreported'); ?>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group col-lg-4 femaleSection" style="display:none;">
                                    <label class="control-label"><?php echo $this->translate('Is Patient Breastfeeding'); ?></label><br>
                                    <input id="breastfeedingYes" name="isBreastfeeding" value="yes" type="radio"> <?php echo $this->translate('Yes'); ?>&nbsp;&nbsp;
                                    <input id="breastfeedingNo" name="isBreastfeeding" value="no" type="radio"> <?php echo $this->translate('No'); ?>&nbsp;&nbsp;
                                    <input id="breastfeedingUnreported" name="isBreastfeeding" value="unreported" type="radio"> <?php echo $this->translate('Unreported'); ?>
                                </div>
                            </div>
                            <div class="col-md-12">
                                <div class="form-group col-lg-12" style="text-align:center;margin-top:10px;">
                                    <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="searchSampleVolume()"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                                    <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
                                </div>
                            </div>
                            </div>
                        </div>
                     </form>
                    <hr style="background: #000 !important;border-color:#ccc;">
                    <div class="row" style="margin-bottom:30px;">
                        <div class="col-lg-6">
                            <div id="piecontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
                        </div>
                        <div class="col-lg-6">
                            <div id="barcontainer" style="min-width: 310px; height: 400px; max-width: 100%; margin: 0 auto;padding:1.5%;"></div>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <i class="fa fa-cogs"></i><?php echo $this->translate('Samples'); ?>
                                    </div>
                                    <div class="tools">
                                        <button class="btn btn-default" onclick="exportSampleResult();"><span><i class="fa fa-file-excel-o" aria-hidden="true"></i> <?php echo $this->translate('Excel'); ?></span></button>
                                    </div>

                                </div>
                                <div class="portlet-body">
                                    <div class="table-toolbar">
                                        <table class="table table-striped table-bordered table-hover order-column" id="sampleDataTable">
                                            <thead>
                                                <tr>
                                                    <th><?php echo $this->translate('Lab'); ?> </th>
                                                    <th><?php echo $this->translate('Suppressed'); ?> </th>
                                                    <th><?php echo $this->translate('Not Suppressed'); ?> </th>
                                                    <th><?php echo $this->translate('Rejected'); ?> </th>
                                                </tr>
                                            </thead>
                                            <tbody id="barChartCountInTable">
                                                <tr>
                                                    <td colspan="4" class="dataTables_empty">Loading data from server</td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>

<script>
    function generatePieContainer(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        fromDate = $('#mrp-lowerDate').val();
        toDate = $('#mrp-upperDate').val();
        provinces = $("#provinces").val();
        districts = $("#districts").val();
        lab = $("#labName").val();
        clinicId = $("#clinicId").val();
        currentRegimen = $("#currentRegimen").val();
        adherence = $("#adherence").val();
        age = $("#age").val();
        sampleType = $("#sampleType").val();
        sampleStatus = $("#sampleStatus").val();
        gender = $("#gender").val();
        isPregnant = $('input[name="isPregnant"]:checked').val();
        isBreastfeeding = $('input[name="isBreastfeeding"]:checked').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-sample-details')); ?>",{fromDate:fromDate,toDate:toDate,provinces:provinces,districts:districts,lab:lab,clinicId:clinicId,currentRegimen:currentRegimen,adherence:adherence,age:age,sampleType:sampleType,sampleStatus:sampleStatus,gender:gender,isPregnant:isPregnant,isBreastfeeding:isBreastfeeding,fromSrc:'sampleVolume'},
        function(data) {
            $("#piecontainer").html(data);
        });
    }
    
    function generateBarContainer() {
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        fromDate = $('#mrp-lowerDate').val();
        toDate = $('#mrp-upperDate').val();
        provinces = $("#provinces").val();
        districts = $("#districts").val();
        lab = $("#labName").val();
        clinicId = $("#clinicId").val();
        currentRegimen = $("#currentRegimen").val();
        adherence = $("#adherence").val();
        age = $("#age").val();
        sampleType = $("#sampleType").val();
        sampleStatus = $("#sampleStatus").val();
        gender = $("#gender").val();
        isPregnant = $('input[name="isPregnant"]:checked').val();
        isBreastfeeding = $('input[name="isBreastfeeding"]:checked').val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-bar-sample-details')); ?>",{fromDate:fromDate,toDate:toDate,provinces:provinces,districts:districts,lab:lab,clinicId:clinicId,currentRegimen:currentRegimen,adherence:adherence,age:age,sampleType:sampleType,sampleStatus:sampleStatus,gender:gender,isPregnant:isPregnant,isBreastfeeding:isBreastfeeding,fromSrc:'sampleVolume'},
        function(data) {
            $("#barcontainer").html(data);
        });
    }
    
    var oTable = null;
    $(document).ready(function(){
        $('#provinces').select2({
            placeholder: "<?php echo $this->translate('All Provinces'); ?>",
            allowClear: true
        });
        $('#districts').select2({
            placeholder: "<?php echo $this->translate('All Districts'); ?>",
            allowClear: true
        });
        $('#labName').select2({
            placeholder: "<?php echo $this->translate('All Labs'); ?>",
            allowClear: true
        });
        $('#clinicId').select2({
            placeholder: "<?php echo $this->translate('All Clinics'); ?>",
            allowClear: true
        });
        $('#piebutton').on('click', function () {
            $('#piecontainer').fadeIn(function () {
                generatePieContainer();
            });
        });
            
        $('#barbutton').on('click', function () {
            $('#barcontainer').fadeIn(function () {
                generateBarContainer();
            });
        });
       generatePieContainer();
       generateBarContainer();
       loadSampleDataTable();
    });

    function searchSampleVolume(){
        generatePieContainer();
        generateBarContainer();
        oTable.fnDraw();
    }
    
    function resetEverything(){
        $('#pageFilter')[0].reset();
        $('#provinces').val('').change();
        $('#districts').val('').change();
        $('#labName').val('').change();
        $('#clinicId').val('').change();
        if($('#gender').val() == 'F'){
          $('.femaleSection').show();
        }else{
          $('.femaleSection').hide();  
        }
        searchSampleVolume();
    }
    
    function loadSampleDataTable(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        oTable = $('#sampleDataTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                {"sClass":"center"},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false},
                {"sClass":"center","bSortable":false}
            ],
            "aaSorting": [[ 0, "asc" ]],
            "sAjaxSource": "<?php echo $this->url('laboratory',array('action' => 'get-filter-sample-details')); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                aoData.push({"name": "fromDate", "value": $('#mrp-lowerDate').val()});
                aoData.push({"name": "toDate", "value": $('#mrp-upperDate').val()});
                aoData.push({"name": "provinces", "value": $('#provinces').val()});
                aoData.push({"name": "districts", "value": $('#districts').val()});
                aoData.push({"name": "lab", "value": $('#labName').val()});
                aoData.push({"name": "clinicId", "value": $('#clinicId').val()});
                aoData.push({"name": "currentRegimen", "value": $('#currentRegimen').val()});
                aoData.push({"name": "adherence", "value": $('#adherence').val()});
                aoData.push({"name": "age", "value": $('#age').val()});
                aoData.push({"name": "sampleType", "value": $('#sampleType').val()});
                aoData.push({"name": "sampleStatus", "value": $('#sampleStatus').val()});
                aoData.push({"name": "gender", "value": $('#gender').val()});
                aoData.push({"name": "isPregnant", "value": $('input[name="isPregnant"]:checked').val()});
                aoData.push({"name": "isBreastfeeding", "value": $('input[name="isBreastfeeding"]:checked').val()});
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        } );
    }
    
    var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];
    
    $(function () {
      startMonth = '<?php echo $startMonth; ?>';
      startYear = '<?php echo $startYear; ?>';
      endMonth = '<?php echo $endMonth; ?>';
      endYear = '<?php echo $endYear; ?>';
      fiscalMonth = 7;
      //if(startMonth < 10)
        //startDate = parseInt("" + startYear + '0' + startMonth + "");
      //else
        startDate = parseInt("" + startYear  + startMonth + "");
      //if(endMonth < 10)
        //endDate = parseInt("" + endYear + '0' + endMonth + "");
      //else
        endDate = parseInt("" + endYear + endMonth + "");
      
      content = '<div class="row mpr-calendarholder">';
      calendarCount = endYear - startYear;
      if(calendarCount == 0)
        calendarCount++;
      var d = new Date();
      for(y = 0; y < 2; y++){
                    content += '<div class="col-xs-6" ><div class="mpr-calendar row" id="mpr-calendar-' + (y+1) + '">'
                                                     + '<h5 class="col-xs-12"><i class="mpr-yeardown fa fa-chevron-circle-left"></i><span>' + (startYear + y).toString() + '</span><i class="mpr-yearup fa fa-chevron-circle-right"></i></h5><div class="mpr-monthsContainer"><div class="mpr-MonthsWrapper">';
        for(m=0; m < 12; m++){
          var monthval;
          if((m+1) < 10)
            monthval = "0" + (m+1);
          else
            monthval = "" + (m+1);
                            content += '<span data-month="' + monthval  + '" class="col-xs-3 mpr-month">' + MONTHS[m] + '</span>';
        }
        content += '</div></div></div></div>';
      }
      content += '<div class="col-xs-1">';
      //content += '<button class="btn btn-info mpr-fiscal-ytd">Fiscal YTD</button>';
      //content += '<button class="btn btn-info mpr-ytd">YTD</button>';
      //content += '<button class="btn btn-info mpr-prev-fiscal">Previous FY</button>';
      //content += '<button class="btn btn-info mpr-prev-year">Previous Year</button>';
      content += '<button class="btn btn-info mpr-close">Apply</button>';
      content += '</div>';
      content += '</div>';
      
      $(document).on('click','.mpr-month',function(e){
        e.stopPropagation();
                    $month = $(this);
            var monthnum = $month.data('month');
            var year = $month.parents('.mpr-calendar').children('h5').children('span').html();
            if($month.parents('#mpr-calendar-1').size() > 0){
              //Start Date
              startDate = parseInt("" + year + monthnum);
              if(startDate > endDate){
                
                if(year != parseInt(endDate/100))
                  $('.mpr-calendar:last h5 span').html(year);
                   endDate = startDate;
              }
            }else{
              //End Date
              endDate = parseInt("" + year + monthnum);
              if(startDate > endDate){
                if(year != parseInt(startDate/100))
                  $('.mpr-calendar:first h5 span').html(year);
                startDate = endDate;
              }
            }
        
            paintMonths();
      });
      
      
      $(document).on('click','.mpr-yearup',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
                    var year = parseInt($(this).prev().html());
            year++;
            $(this).prev().html(""+year);
                    $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });
      
      $(document).on('click','.mpr-yeardown',function(e){
            $('.mpr-month').css("color","black");
            e.stopPropagation();
                    var year = parseInt($(this).next().html());
            year--;
            $(this).next().html(""+year);
                    //paintMonths();
          $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $(this).parents('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
          });
      });
      
      $(document).on('click','.mpr-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        startDate = parseInt(d.getFullYear() + "01");
        var month = d.getMonth() + 1;
        if(month < 9)
          month = "0" + month;
        endDate = parseInt("" + d.getFullYear() + month);
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          var year = $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-prev-year', function(e){
        e.stopPropagation();
        var d = new Date();
        var year = d.getFullYear()-1;
        startDate = parseInt(year + "01");
        endDate = parseInt(year + "12");
        $('.mpr-calendar').each(function(){
          var $cal = $(this);
          $('h5 span',$cal).html(year);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-fiscal-ytd', function(e){
        e.stopPropagation();
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 1;
        else
          year = d.getFullYear();
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(d.getMonth()+1 < 10)
          cm = "0" + (d.getMonth()+1);
        else
          cm = (d.getMonth()+1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + d.getFullYear() + cm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear());
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      $(document).on('click','.mpr-prev-fiscal', function(){
        var d = new Date();
        var year;
        if((d.getMonth()+1) < fiscalMonth)
          year = d.getFullYear() - 2;
        else
          year = d.getFullYear() - 1;
        if(fiscalMonth < 10)
          fm = "0" + fiscalMonth;
        else
          fm = fiscalMonth;
        if(fiscalMonth -1 < 10)
          efm = "0" + (fiscalMonth-1);
        else
          efm = (fiscalMonth-1);
        startDate = parseInt("" + year + fm);
        endDate = parseInt("" + (d.getFullYear() - 1) + efm);
        $('.mpr-calendar').each(function(i){
          var $cal = $(this);
          if(i == 0)
            $('h5 span',$cal).html(year);
          else
            $('h5 span',$cal).html(d.getFullYear()-1);
        });
        $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeOut(175,function(){
            paintMonths();
            $('.mpr-calendar').find('.mpr-MonthsWrapper').fadeIn(175);
        });
      });
      
      var mprVisible = false;
      var mprpopover = $('.mrp-container').popover({
        container: "body",
        placement: "bottom",
        html: true,
        content: content
      }).on('show.bs.popover', function () {
        $('.popover').remove();
        var waiter = setInterval(function(){
          if($('.popover').size() > 0){
            clearInterval(waiter);
            setViewToCurrentYears();
                    paintMonths();
          }
        },50);
      }).on('shown.bs.popover', function(){
        mprVisible = true;
      }).on('hidden.bs.popover', function(){
        mprVisible = false;
      }); 
      
      $(document).on('click','.mpr-calendarholder',function(e){
        e.preventDefault();
        e.stopPropagation();
      });
      $(document).on("click",".mrp-container",function(e){
        if(mprVisible){
          e.preventDefault();
            e.stopPropagation();
          mprVisible = false;
        }
      });
      
      $(document).on("click",function(e){
       
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
      });
      
       $(document).on('click','.mpr-close', function(e){
        //console.log(e);
        if(mprVisible){
            $('.mpr-calendarholder').parents('.popover').fadeOut(200,function(){
            $('.mpr-calendarholder').parents('.popover').remove();
            $('.mrp-container').trigger('click');
          });
          mprVisible = false;
        }
       });
      
    });
    
    function exportSampleResult(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
        $.post("<?php echo $this->url('laboratory', array('action' => 'export-sample-result-excel')); ?>", {fromDate:$('#mrp-lowerDate').val(),toDate:$('#mrp-upperDate').val(),clinicId:$('#clinicId').val(),sampleType:$('#sampleType').val(),currentRegimen:$('#currentRegimen').val(),adherence:$('#adherence').val(),age:$('#age').val(),sampleStatus:$('#sampleStatus').val()},
         function(data){
             if(data == "" || data == null || data == undefined){
                 alert('Unable to export result excel');
             }else{
                 window.open('../temporary/'+data,'_blank');
             }
         }); 
    }
    
    $('#gender').on('change',function() {
        if(this.value == 'F'){
            $('.femaleSection').show();
        }else{
           $('.femaleSection').hide();
           $('#pregnantYes').prop('checked',false);
           $('#pregnantNo').prop('checked',false);
           $('#breastfeedingYes').prop('checked',false);
           $('#breastfeedingNo').prop('checked',false);
        }
    });
    
    function getLocationInfo(fromSrc){
        provinces = ($("#provinces").val() == null || $("#provinces").val() == '')?[]:$("#provinces").val();
        districts = ($("#districts").val() == null || $("#districts").val() == '')?[]:$("#districts").val();
        $.post("<?php echo $this->url('laboratory', array('action' => 'get-location-info')); ?>", {provinces:provinces,districts:districts,fromSrc:fromSrc},
        function(data){
            if(fromSrc == 'provinces'){ $('#districts').val('').change(); }
            $('#labName').val('').change();
            $('#clinicId').val('').change();
            splitLocationInfo = data.split('##');
            if(fromSrc == 'provinces'){ $('#districts').html(splitLocationInfo[0]); }
            $('#labName').html(splitLocationInfo[1]);
            $('#clinicId').html(splitLocationInfo[2]);
        });
    }
</script>
<script src="<?php echo $this->basePath('assets/js/month-year-rang-picker.js'); ?>" type="text/javascript"></script>