                    <!-- BEGIN PAGE BAR -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/clinics/dashboard">Clinics Dashboard</a>
                            </li>
                        </ul>
                    </div>

                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    
                    
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <br>
                    <br>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">Overall Viral Load Status</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="combochart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row" style="padding-top:10px;padding-bottom:20px;">
                        <div class="col-lg-6">
                                <select class="form-control">
                                    <option>All my Clinics</option>
                                    <option>Clinic 001</option>
                                    <option>Clinic 002</option>
                                    <option>Clinic 003</option>
                                    <option>Clinic 004</option>
                                    <option>Clinic 005</option>
                                </select>
                            </div>
                        <div class="col-lg-6">
                            <div id="dashboard-report-range" class="btn btn-sm form-control"
                                 data-container="body"
                                 data-placement="bottom"
                                 data-original-title="Change dashboard date range">
                                        DATE RANGE&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-calendar"></i>&nbsp;
                                        <span class="thin uppercase hidden-xs"></span>&nbsp;
                                        <i class="fa fa-angle-down"></i>
                            </div>
                        </div>
                    </div>
                    
                    
                    <div class="row">
                        
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">VL Ordered</span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <a href="" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> Filter Range
                                                <span class="fa fa-angle-down"> </span>
                                            </a>
                                            <ul class="dropdown-menu pull-right">
                                                <li class="active">
                                                    <a href="javascript:;"> Weekly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Monthly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Quarterly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Yearly
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="portlet-body">
                                    <div id="vlOrderedContainer" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">VL ( < 1000 cp/ml)</span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <a href="" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> Filter Range
                                                <span class="fa fa-angle-down"> </span>
                                            </a>
                                            <ul class="dropdown-menu pull-right">
                                                <li class="active">
                                                    <a href="javascript:;"> Weekly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Monthly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Quarterly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Yearly
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="portlet-body">
                                    <div id="vlSuppressed" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                    <div class="row">
                                                <div class="col-md-12 col-sm-12">
                            <div class="portlet box">
                                <div class="portlet-body">
                                    
                                        <div class="portlet box blue">
                                            <div class="portlet-title">
                                                <div class="caption">
                                                    <i class="fa fa-cogs"></i>Test Results
                                                </div>
                                                <div class="tools">
                                                    
                                                </div>
            
                                            </div>
                                            <div class="portlet-body">
                                                <div class="table-toolbar">
                                                    <table class="table table-striped table-bordered table-hover order-column" id="testResults">
                                                        <thead>
                                                            <tr>
                                                                <th> Sample ID </th>
                                                                <th> Date Collected</th>
                                                                <th> Date Tested</th>
                                                                <th> Viral Load <br> (cp per ml) </th>                                                                
                                                                <th> Action </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td>S0101</td>
                                                                <td>20-Apr-2016</td>
                                                                <td>25-Apr-2016</td>
                                                                <td>1020</td>                                                                
                                                                <td>
                                                                    <a href="#" class="btn btn-primary btn-xs">View</a>
                                                                    
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>S0701</td>
                                                                <td>21-Apr-2016</td>
                                                                <td>25-Apr-2016</td>
                                                                <td>1100</td>                                                                
                                                                <td>
                                                                    <a href="#" class="btn btn-primary btn-xs">View</a>
                                                                    
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>S2131</td>
                                                                <td>23-Apr-2016</td>
                                                                <td>24-Apr-2016</td>
                                                                <td>1300</td>                                                                
                                                                <td>
                                                                    <a href="#" class="btn btn-primary btn-xs">View</a>
                                                                    
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>S0178</td>
                                                                <td>24-Apr-2016</td>
                                                                <td>25-Apr-2016</td>
                                                                <td>1220</td>                                                                
                                                                <td>
                                                                    <a href="#" class="btn btn-primary btn-xs">View</a>
                                                                    
                                                                </td>
                                                            </tr>
                                                            <tr>
                                                                <td>S9101</td>
                                                                <td>25-Apr-2016</td>
                                                                <td>26-Apr-2016</td>
                                                                <td>1520</td>                                                                
                                                                <td>
                                                                    <a href="#" class="btn btn-primary btn-xs">View</a>
                                                                    
                                                                </td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                                
                                            </div>
                                        </div>
                                    
                                    
                                    
                                    
                                    
                                    
                                    
                                </div>
                            </div>
                        </div>                        

                        
                        
                    </div>
        
        <script src="https://code.highcharts.com/highcharts.js"></script>
        
<script>
    $(function () {
    $('#vlOrderedContainer').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        xAxis: {
            categories: ["21 Apr", "22 Apr", "23 Apr", "24 Apr", "25 Apr", "26 Apr", "27 Apr"]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Samples'
            },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        legend: {
            align: 'right',
            x: 0,
            verticalAlign: 'top',
            y: -3,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
            borderColor: '#CCC',
            borderWidth: 1,
            shadow: false
        },
        tooltip: {
            headerFormat: '<b>{point.x}</b><br/>',
            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black'
                    }
                }
            }
        },
        series: [{
            name: 'Routine Monitoring',
            data: [5, 8, 9, 12, 10,5, 8]
        }, {
            name: 'Repeat VL Test',
            data: [3, 6, 3, 6, 7,3, 6]
        }, {
            name: 'Suspected Treatment Failure',
            data: [1, 4, 1, 4, 2,2, 5]
        }],
    colors: [
        '#9CC4E4', '#3A89C9' ,'#1B325F'
    ]
    });
    
    
    
    
    
    
    $('#vlSuppressed').highcharts({

        chart: {
            type: 'column'
        },

        title: {
            text: ''
        },

        xAxis: {
            categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: ''
            }
        },

        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },

        plotOptions: {
            column: {
                stacking: 'normal',
                pointPadding: 0.2,
                borderWidth: 0,
                cursor: 'pointer',
                point: {
                    events: {
                        click: function () {
                            window.location.href='/labs/samples-tested';
                        }
                    }
                }
            }
        },

        series: [
        {
            name: 'Plasma ( > 1000 cp/ml)',
            data: [2, 5, 6, 2, 1, 2, 1],
            stack: 'female'
        }, {
            name: 'Plasma ( < 1000 cp/ml)',
            data: [3, 2, 4, 4, 3, 4, 3],
            stack: 'female'
        },
        {
            name: 'DBS ( > 1000 cp/ml)',
            data: [12, 9, 8, 12, 4, 6, 9],
            stack: 'male'
        }, {
            name: 'DBS ( < 1000 cp/ml)',
            data: [9, 5, 4, 4, 3, 4, 3],
            stack: 'male'
        }
        ],
    colors: [
        '#F36A5A',
        '#60d18f',
        '#ff1900',
        '#09843a',
    ]
    });
    
    
    
    
$('#combochart').highcharts({

        chart: {
            type: 'column'
        },

        title: {
            text: ''
        },

        xAxis: {
            categories: ['No. of VL Tested',
                         'No. of ( < 1000 cp/ml)',
                         'No. of VL ( > 1000 cp/ml)',
                         'Lines of Treatment',
                         'Total 1st Line',
                         '1st Line ( > 1000 cp/ml)',
                         'Total 2nd Line',
                         '2nd Line ( > 1000 cp/ml)',
                         'Total 3rd Line',
                         '3rd Line ( > 1000 cp/ml)'
                         ]
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'Number of Samples'
            }
        },

        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },

        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },

        series: [{
            name: 'Sample',
            showInLegend: false, 
            data: [ { y : 70 , color : '#ECD078' },
                    { y : 45 , color : '#ddef55' },
                    { y : 28 , color : '#D95B43' },
                    { y : 15 , color : '#3598DC' },
                    { y : 26 , color : '#A7DBD8' },
                    { y : 15 , color : '#D95B43' },
                    { y : 20 , color : '#53777A' },
                    { y : 10 , color : '#D95B43' },
                    { y : 15 , color : '#3598DC' },
                    { y : 3 , color : '#D95B43' }
                   ],
            stack: 'male'
        }, {
            name: 'Sample',
            showInLegend: false, 
            data: [null, null, null, { y : 20 , color : '#53777A' }, null, null, null, null, null, null],
            stack: 'male'
        }, {
            name: 'Sample',
            showInLegend: false, 
            data: [null, null, null, { y : 26 , color : '#A7DBD8' }, null, null, null, null, null, null],
            stack: 'male'
        }]
    });    
    
    
    
});
    
</script>        
        
        
