<?php

$sType = '';
foreach($sampleType as $samples){
    $sType.='<option value="'.base64_encode($samples['sample_id']).'">'.ucwords($samples['sample_name']).'</option>';
}
?>
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/clinics/dashboard">Clinics Dashboard</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <br>
                    <br>
                    <div class="row" style="padding-top:10px;padding-bottom:20px;">
                        <div class="col-lg-6">
                            <select class="form-control" id="clinicId" name="clinicId">
                                <option value="">All my Clinics</option>
                                <?php
                                foreach($clinicName as $clinic){
                                    ?>
                                    <option value="<?php echo base64_encode($clinic['facility_id']);?>"><?php echo $clinic['facility_name'];?></option>
                                    <?php
                                }
                                ?>
                            </select>
                        </div>
                        <div class="col-lg-6">
                            <div id="dashboard-report-range" class="btn btn-sm form-control"
                                 data-container="body"
                                 data-placement="bottom"
                                 data-original-title="Change dashboard date range">
                                        DATE RANGE&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-calendar"></i>&nbsp;
                                        <span class="thin uppercase hidden-xs"></span>&nbsp;
                                        <i class="fa fa-angle-down"></i>
                                        <input type="hidden" name="sampleCollectionDate" id="sampleCollectionDate" />
                            </div>
                        </div>
                    </div>

                    <div class="row" style="display:none;">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">Overall Viral Load Status</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="combochart" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="">
                        <div class="col-md-12">
                            <div class="form-group col-lg-4">
                                <label class="control-label">Test Result&nbsp;</label>
                              <select class="form-control" name="testResult" id="testResult" title="Please choose result">
                                <option value="">All</option>
                                <option value=">1000">> 1000 cp/mL</option>
                                <option value="<1000">< 1000 cp/mL</option>
                              </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">Sample Type</label>
                              <select class="form-control" name="sampleId" id="sampleId" title="Please choose sample type">
                                <option value="">All</option>
                                <?php echo $sType;?>
                              </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">Age Group&nbsp;</label>
                              <select class="form-control" name="age" id="age" title="Please choose age group">
                                <option value="">-- Age --</option>
                                <option value="0-10">0-10</option>
                                <option value="10-20">10-20</option>
                                <option value="20-30">20-30</option>
                                <option value="30-40">30-40</option>
                                <option value="40-50">40-50</option>
                                <option value="50-60">50-60</option>
                                <option value="60-70">60-70</option>
                                <option value="70-80">70-80</option>
                                <option value="80">Above 80</option>
                              </select>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group col-lg-4">
                                <label class="control-label">ARV Adherence</label>
                                <select class="form-control" name="adherence" id="adherence">
                                  <option>--Select--</option>
                                  <option value="good">Good >= 95%</option>
                                  <option value="fair">Fair 85-94%</option>
                                  <option value="poor">Poor < 85%</option>
                                </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <label class="control-label">Gender</label>
                              <select class="form-control" name="gender" id="gender">
                                <option>--Select--</option>
                                <option value="male">Male</option>
                                <option value="female">Female</option>
                                <option value="other">Other</option>
                              </select>
                            </div>
                            <div class="form-group col-lg-4">
                                <br>
                                <a href="javascript:void(0);" class="btn btn-primary btn-sm"  onclick="searchData();getTestedSampleResult();">Filter</a>
                            </div>
                        </div>
                        </div>
                    </div>
                    
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">Overall Viral Load Status</span>
                                    </div>
                                </div>
                                <div class="portlet-body col-md-12 col-sm-12">
                                    <div class="col-md-6 col-sm-6">
                                    <div id="combochart1" style="min-width: 310px; height: 520px; margin: 0 auto"></div>
                                    </div>
                                    <div class="col-md-6 col-sm-6" id="viralLoadTable">
                                    
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    
                    <br><br>
                    <div class="row">
                        
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">VL Ordered</span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            <a href="" class="btn white btn-outline btn-circle btn-sm dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true"> Filter Range
                                                <span class="fa fa-angle-down"> </span>
                                            </a>
                                            <ul class="dropdown-menu pull-right">
                                                <li class="active">
                                                    <a href="javascript:;"> Weekly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Monthly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Quarterly
                                                    </a>
                                                </li>
                                                <li>
                                                    <a href="javascript:;"> Yearly
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>                                    
                                </div>
                                <div class="portlet-body">
                                    <div id="vlOrderedContainer" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption ">
                                        <span class="caption-subject">VL ( < 1000 cp/mL)</span>
                                    </div>
                                    <div class="actions">
                                        <div class="btn-group">
                                            
                                        </div>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="samplesTestedResult" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                                </div>
                            </div>
                        </div>
                        
                        
                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box">
                                <div class="portlet-body">
                                    
                                        <div class="portlet box blue">
                                            <div class="portlet-title">
                                                <div class="caption">
                                                    <i class="fa fa-cogs"></i>Test Results
                                                </div>
                                                <div class="tools">
                                                    
                                                </div>
            
                                            </div>
                                            <div class="portlet-body">
                                                <div class="table-toolbar">
                                                    <table class="table table-striped table-bordered table-hover order-column " id="testResults">
                                                        <thead>
                                                            <tr>
                                                                <th> Sample ID </th>
                                                                <th> Date Collected</th>
                                                                <th> Date Tested</th>
                                                                <th> Viral Load <br> (cp/mL) </th>                                                                
                                                                <th> Action </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr>
                                                                <td colspan="5" class="dataTables_empty">Loading data from server</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                </div>
                            </div>
                        </div>                        
                    </div>
        
<script>
    var oTable = null;
    $(function () {
        $('#dashboard-report-range').daterangepicker({
                "ranges": {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
                    'Last 7 Days': [moment().subtract('days', 6), moment()],
                    'Last 30 Days': [moment().subtract('days', 29), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
                },
                "locale": {
                    "format": "YYYY-MM-DD",
                    "separator": " to ",
                    "applyLabel": "Apply",
                    "cancelLabel": "Cancel",
                    "fromLabel": "From",
                    "toLabel": "To",
                    "customRangeLabel": "Custom",
                    "daysOfWeek": [
                        "Su",
                        "Mo",
                        "Tu",
                        "We",
                        "Th",
                        "Fr",
                        "Sa"
                    ],
                    "monthNames": [
                        "January",
                        "February",
                        "March",
                        "April",
                        "May",
                        "June",
                        "July",
                        "August",
                        "September",
                        "October",
                        "November",
                        "December"
                    ],
                    //"firstDay": 1
                },
                //"startDate": "11/08/2015",
                //"endDate": "11/14/2015",
                opens: "left",
            }, function(start, end, label) {
                $('#dashboard-report-range span').html(start.format('MMMM D, YYYY') + ' to ' + end.format('MMMM D, YYYY'));
                $('#sampleCollectionDate').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
            });
                $('#dashboard-report-range span').html(moment().subtract('days', 29).format('MMMM D, YYYY') + ' to ' + moment().format('MMMM D, YYYY'));
                $('#dashboard-report-range').show();
        
        getOverAllViralLoad();
        
        
    $('#vlOrderedContainer').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: ''
        },
        xAxis: {
            categories: ["21 Apr", "22 Apr", "23 Apr", "24 Apr", "25 Apr", "26 Apr", "27 Apr"]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Samples'
            },
            stackLabels: {
                enabled: true,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        legend: {
            align: 'right',
            x: 0,
            verticalAlign: 'top',
            y: -3,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
            borderColor: '#CCC',
            borderWidth: 1,
            shadow: false
        },
        tooltip: {
            headerFormat: '<b>{point.x}</b><br/>',
            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black'
                    }
                }
            }
        },
        series: [{
            name: 'Routine Monitoring',
            data: [5, 8, 9, 12, 10,5, 8]
        }, {
            name: 'Repeat VL Test',
            data: [3, 6, 3, 6, 7,3, 6]
        }, {
            name: 'Suspected Treatment Failure',
            data: [1, 4, 1, 4, 2,2, 5]
        }],
    colors: [
        '#9CC4E4', '#3A89C9' ,'#1B325F'
    ]
    });
    
    
    
$('#combochart').highcharts({

        chart: {
            type: 'column'
        },

        title: {
            text: ''
        },

        xAxis: {
            categories: ['No. of VL Tested',
                         'No. of ( < 1000 cp/mL)',
                         'No. of VL ( > 1000 cp/mL)',
                         'Lines of Treatment',
                         'Total 1st Line',
                         '1st Line ( > 1000 cp/mL)',
                         'Total 2nd Line',
                         '2nd Line ( > 1000 cp/mL)',
                         'Total 3rd Line',
                         '3rd Line ( > 1000 cp/mL)'
                         ]
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'Number of Samples'
            }
        },

        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },

        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },

        series: [{
            name: 'Sample',
            showInLegend: false, 
            data: [ { y : 70 , color : '#ECD078' },
                    { y : 45 , color : '#ddef55' },
                    { y : 28 , color : '#D95B43' },
                    { y : 15 , color : '#3598DC' },
                    { y : 26 , color : '#A7DBD8' },
                    { y : 15 , color : '#D95B43' },
                    { y : 20 , color : '#53777A' },
                    { y : 10 , color : '#D95B43' },
                    { y : 15 , color : '#3598DC' },
                    { y : 3 , color : '#D95B43' }
                   ],
            stack: 'male'
        }, {
            name: 'Sample',
            showInLegend: false, 
            data: [null, null, null, { y : 20 , color : '#53777A' }, null, null, null, null, null, null],
            stack: 'male'
        }, {
            name: 'Sample',
            showInLegend: false, 
            data: [null, null, null, { y : 26 , color : '#A7DBD8' }, null, null, null, null, null, null],
            stack: 'male'
        }]
    });    
    
    
    //$(".datatables").dataTable();    
    oTable=$('#testResults').dataTable( {
        
        "bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
        "aoColumns": [
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center"},
            {"sClass":"center","bSortable":false}
            ],
        "aaSorting": [[ 1, "desc" ]],

        "sAjaxSource": "<?php echo $this->url('clinics',array('action' => 'test-result')); ?>",
        "fnServerData": function ( sSource, aoData, fnCallback ) {
            aoData.push({ "name":"sampleCollectionDate","value": $("#sampleCollectionDate").val()});
			aoData.push({ "name":"clinicId","value": $("#clinicId").val()});
			aoData.push({ "name":"sampleId","value": $("#sampleId").val()});
			aoData.push({ "name":"testResult","value": $("#testResult").val()});
			aoData.push({ "name":"age","value": $("#age").val()});
			aoData.push({ "name":"gender","value": $("#gender").val()});
            $.ajax({
                "dataType": 'json',
                "type": "POST",
                "url": sSource,
                "data": aoData,
                "success": fnCallback
            });
        }
    } );
     getTestedSampleResult();
});

function getOverAllViralLoad()
{
    
    dateRange = $("#sampleCollectionDate").val();
    clinicId = $("#clinicId").val();
    sampleId = $("#sampleId").val();
    testResult = $("#testResult").val();
    age = $("#age").val();
    $.post("<?php echo $this->url('clinics', array('action' => 'overall-viral-load')); ?>",{sampleCollectionDate:dateRange,clinicId:clinicId,sampleId:sampleId,testResult:testResult,age:age},
    function(data) {
    $("#viralLoadTable").html(data);
    });
}

function searchData(){
    //alert($('#sampleCollectionDate').val());
    //console.log(oTable.fnDraw());
    getOverAllViralLoad();
}

    function getTestedSampleResult()
    {
        sampleType = $("#sampleId").val();
        testResult = $("#testResult").val();
        age = $("#age").val();
        dateRange = $("#sampleCollectionDate").val();
        clinicId = $("#clinicId").val();
        gender = $("#gender").val();
        adherence = $("#adherence").val();
        $.post("<?php echo $this->url('clinics', array('action' => 'get-sample-test-result')); ?>",{sampleCollectionDate:dateRange,sampleType:sampleType,facilityId:clinicId,gender:gender,age:age,testResult:testResult,adherence:adherence},
        function(data) {
        $("#samplesTestedResult").html(data);
        });
    }
</script>        
        
        
