<script>
    $(function () {
     $('#overall-vl-status').highcharts({
        chart: {
            type: 'column'
        },

        title: {
            text: ''
        },
        exporting:{
            chartOptions:{
                subtitle: {
                    text:'<?php echo $this->translate('Overall Viral Load Status'); ?>',
                }
            }
        },
        credits: {
            enabled: false
        },
        xAxis: {
            categories: ['<?php echo $this->translate('VL Tested'); ?>',
                         '<?php echo $this->translate('VL Not Tested'); ?>',
                         '<?php echo $this->translate('< 1000 cp/ml'); ?>',
                         '<?php echo $this->translate('>= 1000 cp/ml'); ?>',
                         //'< ?php echo $this->translate('Total Samples'); ?>'
                         ]
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: '<?php echo $this->translate('No. of Samples'); ?>'
            }
        },

        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    '<?php echo $this->translate('Total'); ?>: ' + this.point.stackTotal;
            }
        },

        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },

        series: [{
            name: '<?php echo $this->translate('Sample'); ?>',
            showInLegend: false, 
            data: [
                    { y : <?php echo (isset($chartResult[0]['total']))?$chartResult[0]['total']:0; ?> , color : '#ECD078' },{ y : <?php echo (isset($chartResult[1]['total']))?$chartResult[1]['total']:0; ?> , color : '#DDDF00' },{ y : <?php echo (isset($chartResult[2]['total']))?$chartResult[2]['total']:0; ?> , color : '#b9ecbe' },{ y : <?php echo (isset($chartResult[3]['total']))?$chartResult[3]['total']:0; ?> , color : '#D95B43' }
                ],
            stack: 'total'
        }]
    });    
    });
</script>