<?php
$type = array('Total','VL Not Suppressed','VL Suppressed');
?>
<script>
       $(function () {
        $('#overall-load-chart').highcharts({
       chart: {
            type: 'column'
        },
       
        title: {
            text: ''
        },
        exporting:{
            chartOptions:{
                subtitle: {
                    text:'',
                }
            }
        },
       credits: {
              enabled: false
       },
        xAxis: {
            categories: ['Male','Female','Not Specified']
        },
        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'No. of Samples'
            }
        },
        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                pointPadding: 0.2,
                borderWidth: 0
                //cursor: 'pointer',
                //point: {
                //    events: {
                //        click: function (e) {
                //            
                //        }
                //    }
                //}
            }
        },
        series: [<?php
              if(isset($result) && count($result) >0){
                 for($t=0;$t<count($type);$t++){
                     $typeColor = '#3598dc';
                     if($type[$t] == 'VL Suppressed'){
                         $typeColor = '#60d18f';   
                     }else if($type[$t] == 'VL Not Suppressed'){
                         $typeColor = '#ff1900';   
                     }
              ?>
              {
                     name:'<?php echo $type[$t]; ?>',
                     data:[<?php
                          foreach($result[$type[$t]] as $key=>$val){
                           ?>
                            { y:<?php echo $val[0]; ?> },
                        <?php } ?>
                     ],
                     stack:'<?php echo($type[$t] == 'Total')?'total':'others'; ?>',
                     color: '<?php echo $typeColor; ?>'
              },
         <?php } } ?>
        ],
        //colors: ['#3598dc','#ff1900','#60d18f'],
    });
    });
</script>