<div id="vlOrderedContainer" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
    $(function () {
        $('#vlOrderedContainer').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: ''
        },
        
        credits: {
              enabled: false
       },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}% ({point.number})</b>'
        },
        legend: {
            itemMarginBottom: 5,
            labelFormatter: function () {
                return '<div ><span style="float:left;font-size:10px;">' + this.myData + ' -  </span><span style="font-size:10px; ">'+ this.percentage.toFixed(1)+'% ('+Highcharts.numberFormat(this.y, 0)+')</span></div>';
            }
        },
        plotOptions: {
            pie: {
                dataLabels: {
                    distance:-30,
                    
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'white'
                    }
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Clinics',
            colorByPoint: true,
            data: [<?php
            if(count($result)>0){
                foreach($testReason as $reason){
                    if(isset($result[$reason['test_reason_name']])){
                    foreach($result[$reason['test_reason_name']] as $resultTotal){
                        ?>
                        {
                            myData:'<?php echo ucwords(($reason['test_reason_name']));?>',
                            name:'<?php echo ucwords(($reason['test_reason_code']));?>',
                            y:<?php echo $resultTotal['total'];?>,
                            number:<?php echo $resultTotal['total'];?>,
                        },
                        <?php
                    }
                    }
                }
            }
            ?>]
        }]
    });
    });
</script>