<script>
    $(function () {
     $('#combochart1').highcharts({
        chart: {
            type: 'column'
        },

        title: {
            text: ''
        },

        xAxis: {
            categories: ['VL Tested',
                         '< 1000 cp/mL',
                         '> 1000 cp/mL',
                         'Total Samples'
                         ]
        },

        yAxis: {
            allowDecimals: false,
            min: 0,
            title: {
                text: 'Number of Samples'
            }
        },

        tooltip: {
            formatter: function () {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y + '<br/>' +
                    'Total: ' + this.point.stackTotal;
            }
        },

        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: true
                },
                enableMouseTracking: false
            }
        },

        series: [{
            name: 'Sample',
            showInLegend: false, 
            data: [ { y : <?php echo $chartResult[0]['total'];?> , color : '#ECD078' },
                    { y : <?php echo $chartResult[1]['total'];?> , color : '#ddef55' },
                    { y : <?php echo $chartResult[2]['total'];?> , color : '#D95B43' },
                    { y : <?php echo $chartResult[3]['total'];?> , color : '#3598DC' }
                   ],
            stack: 'male'
        }]
    });    
    });
</script>