<?php

use Application\Service\CommonService;

$common = new CommonService();
foreach ($requestType as $key => $value) {
	$requestTypeOption[$value['request_type']] = $value['request_type'];
}
?>
<div class="page-bar">
	<ul class="page-breadcrumb">
		<li>
			<a href="/"><?php echo $this->translate('Dashboard'); ?></a>
			<i class="fa fa-circle"></i>
		</li>
		<li>
			<?php echo $this->translate('API History'); ?>
		</li>
	</ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
	<div class="col-md-12">
		<!-- BEGIN EXAMPLE TABLE PORTLET-->
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-cogs"></i><?php echo $this->translate('Manage API History'); ?>
				</div>
			</div>
			<div class="portlet-body">
				<div class="table-toolbar">
					<div class="row">
						<div class="col-md-12">
							<div class="box">
								<table aria-describedby="table" class="table" aria-hidden="true" cellspacing="3" style="margin-left:1%;margin-top:20px;width:100%;">
									<tr>
										<td style="width:10%;"><strong>
												<?php echo $this->translate('Date Range'); ?>&nbsp;:
											</strong></td>
										<td style="width:20%;">
											<input type="text" id="daterange" name="daterange" class="form-control daterangefield" placeholder="<?php echo $this->translate('Enter date range'); ?>" style="width:220px;background:#fff;" />
										</td>
										<td style="width:10%;"><strong>
												<?php echo $this->translate("Test Type"); ?>&nbsp;:
											</strong></td>
										<td style="width:20%;">
											<select id="testType" name="testType" class="form-control" placeholder="<?php echo $this->translate('Please select the Test types'); ?>">
												<option value="">
													<?php echo $this->translate("-- Select --"); ?>
												</option>
												<option value="vl">
													<?php echo $this->translate("Viral Load"); ?>
												</option>
												<option value="eid">
													<?php echo $this->translate("Early Infant Diagnosis"); ?>
												</option>
												<option value="covid19">
													<?php echo $this->translate("Covid-19"); ?>
												</option>
												<option value='hepatitis'>
													<?php echo $this->translate("Hepatitis"); ?>
												</option>
												<option value='tb'>
													<?php echo $this->translate("TB"); ?>
												</option>
											</select>
										</td>
										<td style="width:10%;"><strong>
												<?php echo $this->translate("API Type"); ?>&nbsp;:
											</strong></td>
										<td style="width:20%;">
											<select style="width:220px;" class="form-control select2" id="syncedType" name="syncedType" title="<?php echo $this->translate('Please select the API type'); ?>">
												<?php echo $common->generateSelectOptions($requestTypeOption, null, '--Select--'); ?>
											</select>
										</td>
										<td style="width:10%;"><button onclick="oTable.fnDraw();" value="Search" class="btn btn-primary btn-sm"><span>
													<?php echo $this->translate("Search"); ?>
												</span></button></td>
									</tr>
								</table>
							</div>
							<!-- /.box -->
						</div>
					</div>
					<br>
					<table id="apiSyncTable" class="table table-striped table-bordered table-hover table-checkable order-column">
						<thead>
							<tr>
								<th style="width:15%;"><?php echo $this->translate('Transaction ID'); ?></th>
								<th style="width:15%;"><?php echo $this->translate('Number of Records Synced'); ?></th>
								<th style="width:15%;"><?php echo $this->translate('Sync Type'); ?></th>
								<th style="width:10%;"><?php echo $this->translate('Test Type'); ?></th>
								<th style="width:15%;"><?php echo $this->translate('URL'); ?></th>
								<th style="width:15%;"><?php echo $this->translate('Synced On'); ?></th>
								<th style="width:15%;"><?php echo $this->translate('Action'); ?> </th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td colspan="7" class="dataTables_empty">Loading data from server</td>
							</tr>
						</tbody>
					</table>

				</div>

			</div>
		</div>
		<!-- END EXAMPLE TABLE PORTLET-->
	</div>
</div>
<script type="text/javascript">
	/* Table initialisation */
	oTable = null;
	$(document).ready(function() {

		$('#daterange').daterangepicker({
			"ranges": {
				'Today': [moment(), moment()],
				'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
				'Last 7 Days': [moment().subtract(6, 'days'), moment()],
				'Last 30 Days': [moment().subtract(29, 'days'), moment()],
				'This Month': [moment().startOf('month'), moment().endOf('month')],
				'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
			},
			"locale": {
				"format": "DD-MMM-YYYY",
				"separator": " to ",
				"applyLabel": "Apply",
				"cancelLabel": "Cancel",
				"fromLabel": "From",
				"toLabel": "To",
				"customRangeLabel": "Custom",
				"daysOfWeek": [
					"Su",
					"Mo",
					"Tu",
					"We",
					"Th",
					"Fr",
					"Sa"
				],
				"monthNames": [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December"
				],
				"firstDay": 1
			},
			//"startDate": "11/08/2015",
			//"endDate": "11/14/2015",
			opens: "left",
		}, function(start, end, label) {
			$('#daterange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
		});

		oTable = $('#apiSyncTable').dataTable({
			"bAutoWidth": false,
			"bProcessing": true,
			"bServerSide": true,
			"aoColumns": [{
					"sClass": "center",
				}, {
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center"
				},
				{
					"sClass": "center",
					"bSortable": false
				}
			],
			"sAjaxSource": "<?php echo $this->url('api-sync-history', array('action' => 'index')); ?>",
			"fnServerData": function(sSource, aoData, fnCallback) {
				aoData.push({
					"name": "daterange",
					"value": $("#daterange").val()
				});
				aoData.push({
					"name": "testType",
					"value": $("#testType").val()
				});
				aoData.push({
					"name": "syncedType",
					"value": $("#syncedType").val()
				});
				$.ajax({
					"dataType": 'json',
					"type": "POST",
					"url": sSource,
					"data": aoData,
					"success": fnCallback
				});
			}
		});
	});
</script>