<?php
use Laminas\Session\Container;
$languagecontainer = new Container('language');
?>
    <style>
        .col-sm-12{
            overflow-x:scroll;
            overflow-y:hidden;
        }
        .txtCenter{
            text-align:center;
        }
        .oddTxt{
            background-color:#ecf1ef !important;
        }
        .evenTxt{
            background-color:#fffff2 !important;
        }
        #selectedSamples{
            font-size:13px;
            background-color: #fff;
            -moz-box-shadow: 0px 0px 1px #b9abab;
            -webkit-box-shadow: 0px 0px 1px #b9abab;
            -o-box-shadow: 0px 0px 1px #b9abab;
            -ms-box-shadow: 0px 0px 1px #b9abab;
            box-shadow: 0px 0px 1px #b9abab;
            -moz-border-radius:50px;
            -webkit-border-radius:50px;
            -o-border-radius:50px;
            -ms-border-radius:50px;
            border-radius:50px;
            padding: 5px;
        }
        input[type=checkbox] {
          -ms-transform: scale(1.4);
          -moz-transform: scale(1.4);
          -webkit-transform: scale(1.4);
          -o-transform: scale(1.4);
           padding: 10px;
        }
    </style>
    <!-- BEGIN PAGE BAR -->
    <div class="page-bar">
        <h1 class="page-title"><?php echo $this->translate('Duplicate Data'); ?></h1>
    </div>
    <!-- END PAGE BAR -->
    <!-- BEGIN PAGE TITLE-->
    <!-- END PAGE TITLE-->
    <!-- END PAGE HEADER-->
    <br>
    <div class="row">
        <div class="col-md-6 col-sm-6">
          <input type="hidden" id="removedSamples" name="removedSamples"/>
          <span id="selectedSamples">0 <?php echo $this->translate('Sample(s) Selected'); ?></span>&nbsp;&nbsp;<a href="javascript:void(0);" id="remove-btn" class="btn btn-danger btn-sm" onclick="confirmSamplesRemoval();" disabled style="pointer-events:none;"><?php echo $this->translate('Remove Selected Samples'); ?></a>
        </div>
    </div><br>
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <div class="portlet box">
                <div class="portlet-body">
                        <div class="portlet box blue">
                            <div class="portlet-title">
                                <div class="caption">
                                    <i class="fa fa-cogs"></i><?php echo $this->translate('Samples'); ?>
                                </div>
                            </div>
                            <div class="portlet-body">
                                <div class="table-toolbar">
                                    <table class="table table-striped table-bordered table-hover order-column" id="allSamples">
                                        <thead>
                                            <tr>
                                                <th>&nbsp;&nbsp;&nbsp;&nbsp;# </th>
                                                <th> <?php echo $this->translate('Sample ID'); ?> </th>
                                                <th> <?php echo $this->translate('Date Collected'); ?></th>
                                                <th> <?php echo $this->translate('Batch Code'); ?> </th>
                                                <th> <?php echo $this->translate('Patient ART No'); ?>. </th>
                                                <th> <?php echo $this->translate('Patient Name'); ?> </th>
                                                <th> <?php echo $this->translate('Facility Name'); ?> </th>
                                                <th> <?php echo $this->translate('Province/State'); ?> </th>
                                                <th> <?php echo $this->translate('District/County'); ?> </th>
                                                <th> <?php echo $this->translate('Sample Type'); ?></th>
                                                <th> <?php echo $this->translate('Viral Load(cp/ml)'); ?> </th>
                                                <th> <?php echo $this->translate('Status'); ?> </th>
                                                <th> <?php echo $this->translate('Action'); ?> </th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td colspan="13" class="dataTables_empty">Loading data from server</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                </div>
            </div>
        </div>                        
    </div>
<script>
    var oTable = null;
    oTableLastSampleRow = [];
    oTableLastSampleRowColor = [];
    removedSampleRow = [];
    $(document).ready(function(){
        oTable = $('#allSamples').DataTable({
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [
                {"sClass":"txtCenter","bSortable":false},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center"},
                {"sClass":"center","bSortable":false}
            ],
            "iDisplayLength": 10,
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
                if($.inArray(aData[1], oTableLastSampleRow) == -1){
                    oTableLastSampleRow = [];
                    oTableLastSampleRow.push(aData[1]);
                    if($.inArray("#ecf1ef", oTableLastSampleRowColor) == -1){
                        oTableLastSampleRowColor = [];
		        oTableLastSampleRowColor.push("#ecf1ef");
                        $(nRow).attr("class","");
                        $(nRow).addClass("oddTxt");
                        //$('.sorting_1').css('background-color','#ecf1ef !important');
                    }else{
                        oTableLastSampleRowColor = [];
		        oTableLastSampleRowColor.push("#fffff2");
                        $(nRow).attr("class","");
                        $(nRow).addClass("evenTxt");
                        //$('.sorting_1').css('background-color','#fffff2 !important');
                    }
                }else{
                    if($.inArray("#ecf1ef", oTableLastSampleRowColor) == -1){
                        $(nRow).attr("class","");
                        $(nRow).addClass("evenTxt");
                        //$('.sorting_1').css('background-color','#fffff2 !important');
                    }if($.inArray("#fffff2", oTableLastSampleRowColor) == -1){
                        $(nRow).attr("class","");
                        $(nRow).addClass("oddTxt");
                        //$('.sorting_1').css('background-color','#ecf1ef !important');
                    }
                }
	    },
            "fnDrawCallback": function( oSettings ) {
                $('input:checkbox').each(function () {
                    if($.inArray(this.id, removedSampleRow)!= -1){
                        $('#'+this.id).prop('checked',true);
                    }
                });
            },
            "aaSorting": [[ 1, "desc" ]],
            "sAjaxSource": "<?php echo $this->url('duplicate-data'); ?>",
            "fnServerData": function ( sSource, aoData, fnCallback ) {
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });
    });
    
    function duplicateCheck(obj){
        var rowClass = $(obj).attr('class');
        var rowId = $(obj).attr('id');
        var rowValue = $(obj).attr('value');
        if($('#'+rowId).is(':checked')){
            removedSampleRow.push(rowValue);
            notChecked = 0;
            $('.'+rowClass).each(function() {
                if(this.id!= rowId){
                   if(!$('#'+this.id).is(':checked')){
                       notChecked+=1;
                   }
                }
            });
            if(notChecked == 1){
                $('.'+rowClass).each(function() {
                    if(!$('#'+this.id).is(':checked')){
                        $('#'+this.id).prop('disabled',true);
                    }
                })
            }
        }else{
            var sampleIndex = removedSampleRow.indexOf(rowValue);
            removedSampleRow.splice(sampleIndex, 1);
            $('.'+rowClass).prop('disabled',false);
        }
        //style part
        if(removedSampleRow.length >0){
          $('#remove-btn').css('pointer-events','auto');
          $('#remove-btn').removeAttr('disabled');
        }else{
          $('#remove-btn').css('pointer-events','none');
          $('#remove-btn').prop('disabled',true);
        }
        //set count to display
        $('#removedSamples').val(removedSampleRow);
        $('#selectedSamples').html('('+removedSampleRow.length+') <?php echo $this->translate('Sample(s) Selected'); ?>');
    }
    
    function confirmSamplesRemoval(){
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({ message: '<h2><?php echo $this->translate('Processing...'); ?></h2>' })).ajaxStop($.unblockUI);
        $.post("<?php echo $this->url('duplicate-data', array('action' => 'remove')); ?>", {rows : $('#removedSamples').val()},
        function(data){
            if(data == 0){
                alert('<?php echo $this->translate('OOPS..Error while removing duplicate samples'); ?>');
            }else{
                //reset removedSampleRow array
                removedSampleRow = [];
                $('#removedSamples').val('');
                $('#selectedSamples').html('('+removedSampleRow.length+') <?php echo $this->translate('Sample(s) Selected'); ?>');
                $('#remove-btn').css('pointer-events','none');
                $('#remove-btn').prop('disabled',true);
                oTable.draw();
            }
        });
    }
</script>