<?php

use Laminas\Session\Container;

$loginContainer = new Container('credo');
$languagecontainer = new Container('language');
$startYear = date("Y", strtotime("-1 year"));
$startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
$endYear = date('Y');
$endMonth = date('m');

$startDate = date('Y-m', strtotime('+1 month', strtotime('-1 year')));
$endDate = date('Y-m');
?>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/plugins/datepicker/datepicker3.css') ?>">
<style>
    .bluebox,
    .dashboard-stat2 {
        border: 1px solid #3598DC;
    }

    .mrp-monthdisplay {
        display: inline-block !important;
        border-radius: 0px 5px 5px 0px;
        cursor: pointer;
    }

    .mrp-lowerMonth,
    .mrp-upperMonth {
        color: #40667A;
        font-weight: bold;
        font-size: 11px;
        text-transform: uppercase;
    }

    .mrp-to {
        color: #aaa;
        margin-right: 0px;
        margin-left: 0px;
        font-size: 11px;
        text-transform: uppercase;
        /* background-color: #eee; */
        padding: 5px 3px 5px 3px;
    }

    .mpr-calendar {
        display: inline-block;
        padding: 3px 5px;
        border-right: solid #999 1px;
    }

    .mpr-calendar::last-child {
        border-right: none;
    }

    .mpr-month {
        padding: 20px;
        text-transform: uppercase;
        font-size: 12px;
    }

    .mpr-calendar h5 {
        width: 100%;
        text-align: center;
        font-weight: bold;
        font-size: 18px
    }

    .mpr-selected {}

    .mpr-month:hover {
        border-radius: 5px;
        box-shadow: 0 0 0 1px #ddd inset;
        cursor: pointer;
    }

    .mpr-selected.mpr-month:hover {
        border-radius: 0px;
        box-shadow: none;
    }

    .mpr-calendarholder .col-xs-6 {
        max-width: 250px;
        min-width: 250px;
    }

    .mpr-calendarholder .col-xs-1 {
        max-width: 150px;
        min-width: 150px;
    }

    .mpr-calendarholder .btn-info {
        background-color: #40667A;
        border-color: #406670;
        width: 100%;
        margin-bottom: 10px;
        text-transform: uppercase;
        font-size: 10px;
        padding: 10px 0px;
    }

    .mpr-quickset {
        color: #666;
        text-transform: uppercase;
        text-align: center;
    }

    .mpr-yeardown,
    .mpr-yearup {
        margin-left: 5px;
        cursor: pointer;
        color: #666;
    }

    .mpr-yeardown {
        float: left;
    }

    .mpr-yearup {
        float: right;
    }

    .mpr-yeardown:hover,
    .mpr-yearup:hover {
        color: #40667A;
    }

    .mpr-calendar:first .mpr-selected:first {
        background-color: #40667A;
    }

    .mpr-calendar:last .mpr-selected:last {
        background-color: #40667A;
    }

    .popover {
        max-width: 1920px !important;
    }

    .table>tbody>tr>td,
    .table>tbody>tr>th,
    .table>tfoot>tr>td,
    .table>tfoot>tr>th,
    .table>thead>tr>td,
    .table>thead>tr>th {
        padding: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '8' : '3'; ?>px;
        font-size: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '14' : '13'; ?>px;
    }

    .select2-search__field,
    .select2-selection__rendered {
        color: #333;
        text-align: center;
    }

    .select2-container--default {
        width: 100% !important;
    }

    .select2-selection--multiple {
        border-radius: 10px !important;
    }

    @media screen and (min-width:320px) and (max-width: 760px) {
        #daterange-container {
            width: 100% !important;
        }

        #showDateRange,
        #closeDateRange {
            margin-left: 0% !important;
        }
    }

    @media screen and (min-width:761px) and (max-width: 970px) {
        #daterange-container {
            width: 100% !important;
        }

        #showDateRange,
        #closeDateRange {
            margin-left: 52% !important;
        }
    }

    .select2-container--default .select2-selection--single {
        height: 34px !important;
    }
</style>

<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css" integrity="sha384-+gDdQ+wPJnvpg+GAYKltqZXTUO8MDW1MfzZ1FnLAZDzp0kjKrxlbWVfT72s5X43U" crossorigin="anonymous">

<?php
//$sType = '';
// foreach ($sampleType as $samples) {
//     $sType .= '<option value="' . base64_encode($samples['sample_id']) . '">' . ucwords($samples['sample_name']) . '</option>';
// }
?>
<!-- BEGIN PAGE BAR -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <h1 class="page-title"><?php echo $this->translate('Labs Dashboard for EID Testing'); ?></h1>
</div>

<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->

<br>
<br>

<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->

<div class="row" style="margin-bottom:20px;">
    <div class="col-md-12 col-sm-12" style="text-align:center;">
        <a id="showDateRange" href="javascript:void(0);" style="color:#0d68e0;box-shadow: 1px 2px 12px rgb(173, 200, 222);border-radius: 12px;padding: 2px 10px 2px 10px;margin-left:26%;"><i class="fa fa-chevron-down" aria-hidden="true"></i> <?php echo $this->translate('Show Date Filter'); ?></a>
        <a id="closeDateRange" href="javascript:void(0);" style="color:#0d68e0;display:none;box-shadow: 1px 2px 12px rgb(173, 200, 222);border-radius: 12px;padding: 2px 10px 2px 10px;margin-left:26%;"><i class="fa fa-chevron-up" aria-hidden="true"></i> <?php echo $this->translate('Close Date Filter'); ?></a>
    </div>
</div>
<form id="dateFilter" action="#" method="">
    <div class="daterange-container row" style="margin-bottom:20px;display:none;">
        <div class="col-md-12 col-sm-12" style="text-align:right;">
            <div id="daterange-container" class="btn btn-sm form-control" data-container="body" data-placement="bottom" data-original-title="Change date range" style="text-align:center;width:50%;">
                <i class="icon-calendar"></i>&nbsp;
                <span class="thin uppercase hidden-xs"></span>&nbsp;
                <i class="fa fa-angle-down"></i>
                <input type="hidden" name="daterange" id="daterange" />
            </div>&nbsp;&nbsp;
            <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getSampleResult('daterange');"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
            <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetDateFilter();" style="margin-right:5.8%;"><?php echo $this->translate('Reset'); ?></a>
        </div>
    </div>
</form>
<div class="row">
    <div id="sampleResultDetails"></div>
</div>
<hr style="background: #000 !important;border-color:#ccc;">
<form id="pageFilter" action="#" method="">
    <div class="row" style="padding-top:10px;padding-bottom:10px;">
        <div class="col-lg-6">
            <select name="provinceName[]" id="provinceName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more province. Leave blank for All'); ?>" onchange="selectDistrictName();">
                <?php
                foreach ($provinceName as $province) {
                ?>
                    <option value="<?php echo $province['geo_id']; ?>"><?php echo $province['geo_name']; ?></option>
                <?php
                }
                ?>
            </select>
        </div>
        <div class="col-lg-6" id="districtHeight">
            <select name="districtName[]" id="districtName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more district. Leave blank for All'); ?>" onchange="selectLabName();">
                <!-- <?php
                        foreach ($districtName as $district) {
                        ?>
                    <option data-parent-location="<?php echo $district['geo_parent']; ?>" value="<?php echo $district['geo_id']; ?>"><?php echo $district['geo_name']; ?></option>
                <?php
                        }
                ?>
                <option value="0">Empty</option> -->
            </select>
        </div>
    </div>
    <div class="row" style="padding-top:5px;padding-bottom:20px;">
        <div class="col-lg-6" id="labHeight">
            <select name="labName[]" id="labName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more labs. Leave blank for All'); ?>">
                <?php foreach ($labName as $lab) { ?>
                    <option data-name="<?php echo $lab['facility_name']; ?>" data-district="<?php echo $lab['facility_district']; ?>" value="<?php echo $lab['facility_id']; ?>"><?php echo $lab['facility_code'] . " - " . $lab['facility_name']; ?></option>
                <?php } ?>
            </select>
        </div>
        <div class="col-lg-3" style="display: flex;">

            <div class="input-append date" id="dpMonthsStart" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                <input type="text" class="form-control isRequired readonly" id="mrp-lowerDate" name="mrp-lowerDate" placeholder="Select month & year" title="Please select month and year" readonly="readonly" value="<?php echo date('M-Y', strtotime($startDate)); ?>" />
                <span class="add-on" style="display:none;"><i class="icon-calendar"></i></span>
            </div>
            <div class="input-group-prepend input-group-append" style=" padding-top: 5px; ">
                <span class="input-group-text font-w600" style="padding: 0.100rem .35rem;">
                    <!-- <i class="fa fa-fw fa-arrow-right"></i> --> to
                </span>
            </div>
            <div class="input-append date" id="dpMonthsEnd" data-date-format="M/yyyy" data-date-viewmode="years" data-date-minviewmode="months">
                <input type="text" class="form-control isRequired readonly" id="mrp-upperDate" name="mrp-upperDate" placeholder="Select month & year" title="Please select month and year" readonly="readonly" value="<?php echo date('M-Y', strtotime($endDate)); ?>" />
                <span class="add-on" style="display:none;"><i class="icon-calendar"></i></span>
            </div>
        </div>
        <div class="col-lg-3">
            <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getEverything();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
            <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="resetEverything();"><?php echo $this->translate('Reset'); ?></a>
        </div>
    </div>
</form>

<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Tests with valid outcomes'); ?></span>
                </div>

            </div>
            <div class="portlet-body" style="cursor:pointer;">
                <div id="monthlyCounts"></div>
            </div>
        </div>
    </div>

    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested per Lab'); ?></span>
                </div>
            </div>
            <div class="portlet-body" style="cursor:pointer;">
                <div id="monthlyCountsByLab"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('EID Outcomes by Age'); ?></span>
                </div>
            </div>
            <div class="portlet-body" id="eidOutcomesByAgeBody">
                <div id="eidOutcomesByAge" style="height:400px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Positivity Rate'); ?></span>
                </div>
            </div>
            <div class="portlet-body" id="positivityRateBody">
                <div id="positivityRate" style="height:400px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Laboratory Turnaround Time'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="labAverageTat" style="height:400px;"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Laboratory Performance'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="labPerformance"></div>
            </div>
        </div>
    </div>
</div>

<div class="row" id="summaryOfKeyIndicatorsDiv">
    <div class="col-md-12 col-sm-12">
        <div class="portlet box">
            <div class="portlet box blue">
                <div class="portlet-title">
                    <div class="caption" id="blockTitle">
                        <i class="fa fa-cogs"></i><?php echo $this->translate('SUMMARY OF KEY INDICATORS'); ?>
                    </div>
                    <div class="actions" style="width:<?php echo (isset($languagecontainer->locale) &&  $languagecontainer->locale == 'pt_BR') ? '36%' : '44%'; ?>;">
                        <div class="tools" id="exportHighVlSample" style="float:right;text-align:right;">
                            <button class="btn btn-default" onclick="exportSummaryIndicatorResult();"><span><i class="fa fa-file-excel-o" aria-hidden="true"></i> <?php echo $this->translate('Export Excel'); ?></span></button>
                        </div>&nbsp;&nbsp;
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-toolbar" id="keyIndicatorsSummary" style="overflow-x:scroll;">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="<?php echo $this->basePath('assets/plugins/datepicker/bootstrap-datepicker.js') ?>"></script>

<script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js" integrity="sha384-QyXw3+FbFWMGvHERjd2qCYZRk+b2Pjmtq15C/hioWsjhRQ7ogFIq/TyxV45EzU1H" crossorigin="anonymous"></script>

<script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js" integrity="sha384-nk2cQ4sDpysew3G+v7tJwHnXPn+hFSYDfMXNCUVhYGNn3vSW9vuAgG1jEEVx5DFe" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.flash.min.js" integrity="sha384-OGZNE8UcOgofYMP/794wtqdqPXdlNe0jqWVfXV699b0qNEoZjAng7eE3JSFzj4mE" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js" integrity="sha384-yib/J8n+cev8VyEYY+4A3nSvnqCRhEkxUQhVFp8X+YuIXd0qhT3rTYXqel0zWzni" crossorigin="anonymous"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js" integrity="sha384-7B0GkWcyEmGJnsHkE0Z0cCpXaUS9i1tFM1/e0jAKoxA2YkI2XYaZdCOJo0kBBsS5" crossorigin="anonymous"></script>
<script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js" integrity="sha384-Zu5dDR1DhOW4Qpz55vgv84xMQSt0V2nX/rGj309pIyhOnc2KHssTcYszIjiYUjYL" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.print.min.js" integrity="sha384-sVbeHA0n97H3zikZ3aj3R1iGOBYGKXaj36uB+oJhkHN1vjGFAQT8hE+AWAFFYzgd" crossorigin="anonymous"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js'); ?>" type="text/javascript"></script>
<script>
    //var gfxPath = 'https://raw.githubusercontent.com/highslide-software/pattern-fill/master/graphics/';
    var startDate;
    var endDate;
    var oTable;

    function getSampleResult(frmSource) {
        var daterange = $('#daterange').val();
        if (frmSource == 'daterange' && $.trim(daterange) == '') {
            alert('<?php echo $this->translate('Please choose date range'); ?>');
            return false;
        }
        //if(frmSource !='load'){$.blockUI.defaults.css.border = '1px solid grey'; $(document).ajaxStart($.blockUI({ message: '<h2><?php echo $this->translate('Processing...'); ?></h2>' })).ajaxStop($.unblockUI);}
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'stats')); ?>", {
                daterange: daterange
            },
            function(data) {
                $("#sampleResultDetails").html(data);
            });
    }



    function getMonthlySampleCount() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var sampleType = ($("#sampleType").val() == null) ? '' : $("#sampleType").val();
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-monthly-sample-count')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                sampleType: sampleType,
                facilityId: facilityId
            },
            function(data) {
                $("#monthlyCounts").html(data);
            });
    }

    function getMonthlySampleCountbyLab() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var sampleType = ($("#sampleType").val() == null) ? '' : $("#sampleType").val();
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');


        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-monthly-sample-count-by-labs')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                sampleType: sampleType,
                facilityId: facilityId
            },
            function(data) {
                $("#monthlyCountsByLab").html(data);


            });
    }

    function getAverageLabTAT() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-lab-turn-around-time')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#labAverageTat").html(data);
            });
    }

    function getLabPerformance() {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-lab-performance')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#labPerformance").html(data);
            });
    }


    $(function() {
        $('#provinceName').select2({
            placeholder: "<?php echo $this->translate('Provinces'); ?>",
            allowClear: true
        });
        $('#districtName').select2({
            placeholder: "<?php echo $this->translate('Districts'); ?>",
            allowClear: true,
            //maxPlaceholderOpts : 10
        });

        $('#labName').select2({
            placeholder: "<?php echo $this->translate('Testing Labs'); ?>",
            allowClear: true
        });

        $('#age').select2({
            placeholder: "<?php echo $this->translate('All Age Group'); ?>",
            allowClear: true
        });

        $('#age').on('select2:close', function(evt) {
            var uldiv = $(this).siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
        });

        $('#formFields').select2({
            placeholder: "<?php echo $this->translate('All'); ?>",
            allowClear: true
        });

        $('#formFields').on('select2:close', function(evt) {
            var uldiv = $(this).siblings('span.select2').find('ul');
            var count = uldiv.find('li').length - 1;
            uldiv.html("<li>" + count + " items selected</li>");
        });

        $('#clinicId').select2({
            placeholder: "<?php echo $this->translate('All Facilities'); ?>",
            allowClear: true
        }).on("change", function(e) {

        });

        var start = moment().subtract(12, 'months');
        var end = moment();

        function cb(start, end) {
            $('#daterange-container span').html(start.format('MMM D, YYYY') + ' to ' + end.format('MMM D, YYYY'));
            $('#daterange').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        }
        $('#daterange-container').daterangepicker({
            format: 'DD-MMM-YYYY',
            separator: ' to ',
            startDate: start,
            endDate: end,
            <?php if (isset($loginContainer->useCurrentTables) && $loginContainer->useCurrentTables === true) { ?>
                minDate: moment().subtract(12, 'months'),
            <?php } ?>
            maxDate: moment(),
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start, end);
        $('#dashboard-range').show();
        $('#daterange-container span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');

        // The reason why getSampleResult is a separate call is because it does not follow
        // the Date and Lab filters of the other functions.
        getSampleResult('load');
        getEverything();

        $('#provinceName,#districtName,#labName').on('select2:close', function() {
            let select = $(this)
            $(this).next('span.select2').find('ul').html(function() {
                let count = select.select2('data').length
                if (count > 2) {
                    return "<li>" + count + " items selected</li>"
                }
            })
        })

    });



    function getEverything() {
        $.blockUI.defaults.css.border = '1px solid grey';
        //$(document).ajaxStart($.blockUI({ message: '<h2><?php echo $this->translate('Processing...'); ?></h2>' })).ajaxStop($.unblockUI);
        if (!$('#sampleCollectionDate').val()) {
            $('#sampleCollectionDate').val(moment().subtract(179, 'days').format('YYYY-MM-DD') + ' to ' + moment().format('YYYY-MM-DD'));
        }

        $.when(getMonthlySampleCount(), getMonthlySampleCountbyLab())
            .done(function() {
                geteidOutcomesByAge();
                positivityRate();
                getAverageLabTAT();
                getLabPerformance();
                getSummaryIndicators();
            });
    }

    function resetEverything() {
        $('#pageFilter')[0].reset();
        $('#labName').val('').change();
        getEverything();
    }

    function getSummaryIndicators() {
        $(document).ajaxStart($.blockUI({
            message: '<h4> <?php echo ($this->translate('Processing Summary of Key Indicators')); ?> ... </h4>'
        })).ajaxStop($.unblockUI);
        var indClinicIdList = ($("#labName").val() == null) ? '' : $('#labName').val().join(',');
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        $.post("<?php echo $this->url('eid-summary', array('action' => 'get-indicators')); ?>", {
                clinics: indClinicIdList,
                fromDate: fromDate,
                toDate: toDate
            },
            function(data) {
                $("#keyIndicatorsSummary").html(data);
                $.unblockUI();
            });
    }

    function exportSummaryIndicatorResult() {
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({
            message: '<h2><?php echo $this->translate('Processing...'); ?></h2>'
        })).ajaxStop($.unblockUI);
        $.post("<?php echo $this->url('eid-summary', array('action' => 'export-indicator-result-excel')); ?>", {
                result: $("#sampleStatus").val()
            },
            function(data) {
                if (data == "" || data == null || data == undefined) {
                    alert('<?php echo $this->translate('Unable to export excel') ?>');
                } else {
                    window.open('/temporary/' + data, '_blank');
                }
            });
    }


    $("#showDateRange").click(function() {
        $("#showDateRange").hide();
        $("#closeDateRange,.daterange-container").show();
    });

    $("#closeDateRange").click(function() {
        $("#closeDateRange,.daterange-container").hide();
        $("#showDateRange").show();
    });

    function resetDateFilter() {
        $('#dateFilter')[0].reset();
        $('#daterange-container span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');
        getSampleResult('reset');
    }

    function selectDistrictName() {
        $('#districtName').html('');
        $('#districtName,#labName').select2('val', '');

        var pName = $("#provinceName").val();
        if (pName != null && pName.length > 0) {
            $.post("<?php echo $this->url('common', array('action' => 'get-district-list')); ?>", {
                    provinceName: pName
                },
                function(data) {
                    if (data != "" || data != null || data != undefined) {
                        $('#districtName').html(data);
                    }
                });
        }
    }

    function selectLabName() {
        /* $('#labName').html('');
        $('#labName').select2('val', '');
        var dName = $("#districtName").val();
        if (dName != null && dName.length > 0) {
            $.post("<?php echo $this->url('common', array('action' => 'get-facility-list')); ?>", {
                    districtName: dName,
                    facilityType: 2
                },
                function(data) {
                    if (data != "" || data != null || data != undefined) {
                        $('#labName').html(data);
                    }
                });
        } */
    }

    function expandChart(from) {
        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');
        showModal('eid/labs/expand-bar-chart/?fromDate=' + fromDate + '&toDate=' + toDate + '&facilityId=' + facilityId + '&from=' + from, '800', '450');
    }

    jQuery(function() {
        // set default dates
        var start = new Date();
        // set end date to max one year period:
        var end = new Date(new Date().setYear(start.getFullYear() - 1));

        $('#dpMonthsStart').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
            format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
            <?php if (isset($loginContainer->useCurrentTables) && $loginContainer->useCurrentTables === true) { ?>
                startDate: end,
            <?php } ?>
            endDate: "0m"
        }).on('changeDate', function(e) {
            $('#dpMonthsEnd').val('');
            var _satrt = new Date(e.date.valueOf());
            $('#dpMonthsEnd').datepicker('setStartDate', _satrt);
        });
        $('#dpMonthsEnd').datepicker({
            clearBtn: true,
            autoclose: true,
            todayHighlight: true,
            format: 'M-yyyy',
            viewMode: "months",
            minViewMode: "months",
            <?php if (isset($loginContainer->useCurrentTables) && $loginContainer->useCurrentTables === true) { ?>
                startDate: end,
            <?php } ?>
            endDate: "0m"
        })
    });

    function formatDate(date) {
        // We are formatting Mon-Year date as 01/Mon/Year
        // because firefox was not able to parse Mon-Year format
        var d = new Date('01/' + date.replace("-", "/")),
            month = '' + (d.getMonth() + 1),
            year = d.getFullYear();
        if (month.length < 2) month = '0' + month;
        return [year, month].join('-');
    }

    function doLabTATRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/eid/labs/time?month=' + month + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleResultAwaitedRedirect(frmSource) {
        window.open("/eid/labs/drill-down-result-awaited?src=" + frmSource);
    }

    function doSampleTestedRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/eid/labs/drill-down?month=' + month + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonGenderRedirect(month, gender) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/eid/labs/drill-down?month=' + month + '&gender=' + gender + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonAgeRedirect(month, age) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/eid/labs/drill-down?month=' + month + '&age=' + age + '&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonPregnantPatientRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/eid/labs/drill-down?month=' + month + '&gender=F&femaleFilter=P&lab=' + selectedLabs, '_blank');
    }

    function doSampleTestedBasedonBreastfeedingPatientRedirect(month) {
        var selectedLabs = ($("#labName").val() == null) ? '' : $("#labName").val();
        window.open('/eid/labs/drill-down?month=' + month + '&gender=F&femaleFilter=BF&lab=' + selectedLabs, '_blank');
    }

    function geteidOutcomesByAge() {
        $(document).ajaxStart($.blockUI({
            message: '<h4> <?php echo ($this->translate('Processing EID Outcomes By Age')); ?> ... </h4>'
        })).ajaxStop($.unblockUI);

        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');

        $.post("<?php echo $this->url('eid-labs', array('action' => 'get-eid-outcomes-by-age')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#eidOutcomesByAge").html(data);
                $.unblockUI();
            });
    }

    function positivityRate() {
        $(document).ajaxStart($.blockUI({
            message: '<h4> <?php echo ($this->translate('Processing Positivity Rate')); ?> ... </h4>'
        })).ajaxStop($.unblockUI);

        var fromDate = formatDate($('#mrp-lowerDate').val());
        var toDate = formatDate($('#mrp-upperDate').val());
        var facilityId = ($("#labName").val() == null) ? '' : $("#labName").val().join(',');

        $.post("<?php echo $this->url('eid-labs', array('action' => 'get-eid-positivity-rate')); ?>", {
                fromDate: fromDate,
                toDate: toDate,
                facilityId: facilityId
            },
            function(data) {
                $("#positivityRate").html(data);
                $.unblockUI();
            });
    }
</script>
