<table class="table table-striped table-bordered table-hover order-column" id="labPerformanceTable">
    <thead>
        <tr>
            <th><?php echo $this->translate('Lab Name'); ?></th>
            <th><?php echo $this->translate('Child Name'); ?></th>
            <th><?php echo $this->translate('Mother Name'); ?></th>
            <th><?php echo $this->translate('Care Taker Phone Number'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($result as $row) { ?>
            <tr>
                <td><?= $row['lab_name']; ?></td>
                <td class="center"><?= $row['child_name']; ?></td>
                <td class="center"><?= $row['mother_name']; ?></td>
                <td class="center"><?= $row['caretaker_phone_number']; ?></td>
                <td class="center"><?= $row['result']; ?></td>
            </tr>
        <?php } ?>
    </tbody>

</table>

<script>
    $(function() {
        $("#labPerformanceTable").DataTable();
    });
</script>