<table class="table table-striped table-bordered table-hover order-column" id="labPerformanceTable">
    <thead>
        <tr>
            <th><?php echo $this->translate('Lab Name'); ?></th>
            <th><?php echo $this->translate('Facility Email'); ?></th>
            <th><?php echo $this->translate('Contact Person'); ?></th>
            <th><?php echo $this->translate('Mobile Number'); ?></th>
            <th><?php echo $this->translate('Status'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($result as $row) { ?>
            <tr>
                <td><?= $row['lab_name']; ?></td>
                <td class="center"><?= $row['facility_emails']; ?></td>
                <td class="center"><?= $row['contact_person']; ?></td>
                <td class="center"><?= $row['facility_mobile_numbers']; ?></td>
                <td class="center"><?= $row['result']; ?></td>
            </tr>
        <?php } ?>
    </tbody>

</table>

<script>
    $(function() {
        $("#labPerformanceTable").DataTable();
    });
</script>