<div id="labAverageTat"></div>
<script>
    $('#labAverageTat').highcharts({
        chart: {
            type: 'line'
        },
        title: {
            text: 'Laboratory Turnaround Time'
        },
        exporting: {
            chartOptions: {
                subtitle: {
                    text: 'Laboratory Turnaround Time',
                }
            }
        },
        credits: {
            enabled: false
        },
        xAxis: {
            //categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
            categories: [<?php
                            if (isset($result['date']) && count($result['date']) > 0) {
                                foreach ($result['date'] as $date) {
                                    echo "'" . $date . "',";
                                }
                            }
                            ?>]
        },
        yAxis: [{
            title: {
                text: 'Average TAT in Days'
            },
            labels: {
                formatter: function() {
                    return this.value;
                }
            }
        }, { // Secondary yAxis
            gridLineWidth: 0,
            title: {
                text: 'No. of Tests'
            },
            labels: {
                format: '{value}'
            },
            opposite: true
        }],
        plotOptions: {
            line: {
                dataLabels: {
                    enabled: true
                },
                cursor: 'pointer',
                point: {
                    events: {
                        click: function(e) {
                            doLabTATRedirect(e.point.category);
                        }
                    }
                }
            },
            series: {
                dataLabels: {
                    enabled: true
                }
            }
        },

        series: [{
                type: 'column',
                name: 'No. of Samples Tested',
                data: [<?php echo implode(",", $result['totalSamples']); ?>],
                color: '#7CB5ED',
                yAxis: 1
            },
            <?php
            if (isset($result['sampleReceivedDiff'])) {
            ?> {
                    connectNulls: false,
                    showInLegend: true,
                    name: 'Collected - Received at Lab',
                    data: [<?php echo implode(",", $result['sampleReceivedDiff']); ?>],
                    color: '#edb47c',
                },
            <?php
            }
            if (isset($result['sampleReceivedTested'])) {
            ?> {
                    connectNulls: false,
                    showInLegend: true,
                    name: 'Received - Tested',
                    data: [<?php echo implode(",", $result['sampleReceivedTested']); ?>],
                    color: '#0f3f6e',
                },
            <?php
            }
            if (isset($result['sampleTestedDiff'])) {
            ?> {
                    connectNulls: false,
                    showInLegend: true,
                    name: 'Collected - Tested',
                    data: [<?php echo implode(",", $result['sampleTestedDiff']); ?>],
                    color: '#ed7c7d',
                },
            <?php
            }
            ?>
        ],
    });

    /* $('#labAverageTat').highcharts({
        chart: {
            zoomType: 'xy',
            marginTop: 100
        },
        legend: {
            align: 'center',
            x: 0,
            verticalAlign: 'top',
            y: 30,
            floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || '#FFFFFF'
        },
        title: {
            text: ''
        },
        exporting: {
            chartOptions: {
                subtitle: {
                    text: '<?php echo $this->translate('Laboratory Turnaround Time'); ?>',
                }
            }
        },
        credits: {
            enabled: false
        },
        xAxis: [{
            categories: [<?php
                            if (isset($result['dates']) && count($result['dates']) > 0) {
                                foreach ($result['dates'] as $date) {
                                    echo "'" . $date . "',";
                                }
                            }
                            ?>],
            crosshair: true
        }],
        yAxis: [{
            gridLineWidth: 0,
            allowDecimals: false,
            title: {
                text: '<?php echo $this->translate('No. of Samples'); ?>',
                style: {}
            },
            labels: {
                format: '{value}',
                style: {}
            },
            opposite: true

        }, {
            labels: {
                format: '{value}',
                style: {}
            },
            title: {
                text: '<?php echo $this->translate('Average TAT in Days'); ?>',
                style: {}
            },
            min: 0
        }],
        tooltip: {
            formatter: function() {
                return '<b>' + this.x + '</b><br/>' +
                    this.series.name + ': ' + this.y
            }
        },
        series: [<?php
                    if (isset($result['data']) && count($result['data']) > 0) {
                        foreach ($result['data'] as $key => $condition) {
                    ?> {
                        name: '<?php echo $this->translate($key); ?>',
                        type: 'column',
                        cursor: 'pointer',
                        point: {
                            events: {
                                click: function(e) {
                                    doLabTATRedirect(this.category);
                                    e.preventDefault();
                                }
                            }
                        },
                        data: [<?php
                                foreach ($condition as $count) {
                                    echo '{y:' . $count . '},';
                                }
                                ?>],
                    },
                <?php
                        }
                    }
                    if (isset($result['all'])) {
                ?> {
                    //showInLegend: false,
                    name: '<?php echo $this->translate('TAT'); ?>',
                    type: 'spline',
                    yAxis: 1,
                    cursor: 'pointer',
                    point: {
                        events: {
                            click: function(e) {
                                doLabTATRedirect(this.category);
                                e.preventDefault();
                            }
                        }
                    },
                    data: [<?php echo implode(",", $result['all']); ?>],
                    color: '#1B325F',

                }
            <?php } ?>
        ]
    }); */

    function getRandomColor() {
        var letters = '0123456789ABCDEF';
        var color = '#';
        for (var i = 0; i < 6; i++) {
            color += letters[Math.floor(Math.random() * 16)];
        }
        return color;
    }
</script>