<?php

use Laminas\Session\Container;

$logincontainer = new Container('credo');
$languagecontainer = new Container('language');
$startYear = date("Y", strtotime("-1 year"));
$startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
$endYear = date('Y');
$endMonth = date('m');

$startDate = date('Y-m', strtotime('+1 month', strtotime('-1 year')));
$endDate = date('Y-m');
?>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/plugins/datepicker/datepicker3.css') ?>">
<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js"></script>



<style>
   

    .table>tbody>tr>td,
    .table>tbody>tr>th,
    .table>tfoot>tr>td,
    .table>tfoot>tr>th,
    .table>thead>tr>td,
    .table>thead>tr>th {
        padding: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '8' : '3'; ?>px;
        font-size: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '14' : '13'; ?>px;
    }

    
</style>

<link href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css" rel="stylesheet">

<?php
//$sType = '';
// foreach ($sampleType as $samples) {
//     $sType .= '<option value="' . base64_encode($samples['sample_id']) . '">' . ucwords($samples['sample_name']) . '</option>';
// }
?>
<!-- BEGIN PAGE BAR -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <h1 class="page-title"><?php echo $this->translate('Samples Tested'); ?></h1>
</div>

<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->

<br>
<br>

<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->


<!-- <hr style="background: #000 !important;border-color:#ccc;"> -->

<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="labPerformance"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6 col-lg-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Summary Outcomes'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samTestPosNeg"></div>
            </div>
        </div>
    </div>
</div>



<!-- <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAFpbfAKFJZ8Ps7yAGIDZtD4EeBlsb_ANA"></script> -->
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js"></script>

<script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.flash.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.print.min.js"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js'); ?>" type="text/javascript"></script>
<script>
    //var gfxPath = 'https://raw.githubusercontent.com/highslide-software/pattern-fill/master/graphics/';
    var startDate;
    var endDate;

   

    function getSampleTested() {
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-lat-lon-map')); ?>", {
            daterange : '<?php echo $daterange; ?>',
            lab : '<?php echo $lab; ?>'
            },
            function(data) {
                $("#labPerformance").html(data);
            });
    }

    function getSampleTestedPositiveNegative() {
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-lat-lon-map-pos-neg')); ?>", {
            daterange : '<?php echo $daterange; ?>',
            lab : '<?php echo $lab; ?>'
            },
            function(data) {
                $("#samTestPosNeg").html(data);
            });
    }

    $(function() {
        getSampleTested();
        getSampleTestedPositiveNegative();
    });

    function resetEverything() {
        // $('#pageFilter')[0].reset();
        getSampleTested();
    }
</script>