<?php

use Laminas\Session\Container;

$loginContainer = new Container('credo');
$languagecontainer = new Container('language');
$startYear = date("Y", strtotime("-1 year"));
$startMonth = date('m', strtotime('+1 month', strtotime('-1 year')));
$endYear = date('Y');
$endMonth = date('m');

$startDate = date('Y-m', strtotime('+1 month', strtotime('-1 year')));
$endDate = date('Y-m');
?>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/plugins/datepicker/datepicker3.css') ?>">
<script src="https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.3.6/proj4.js" integrity="sha384-M06Wz+wp7/Hfi8Ks7DJtWxAFDqihGPCsNmjmWhnUQ8vBTSwd/1Os0uhf2hcYXt2t" crossorigin="anonymous"></script>



<style>
    .table>tbody>tr>td,
    .table>tbody>tr>th,
    .table>tfoot>tr>td,
    .table>tfoot>tr>th,
    .table>thead>tr>td,
    .table>thead>tr>th {
        padding: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '8' : '3'; ?>px;
        font-size: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '14' : '13'; ?>px;
    }
</style>

<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.1.0/css/buttons.dataTables.min.css" integrity="sha384-+gDdQ+wPJnvpg+GAYKltqZXTUO8MDW1MfzZ1FnLAZDzp0kjKrxlbWVfT72s5X43U" crossorigin="anonymous">

<?php
//$sType = '';
// foreach ($sampleType as $samples) {
//     $sType .= '<option value="' . base64_encode($samples['sample_id']) . '">' . ucwords($samples['sample_name']) . '</option>';
// }
?>
<!-- BEGIN PAGE BAR -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <h1 class="page-title"><?php echo $this->translate('Samples Tested'); ?></h1>
</div>

<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->

<br>
<br>

<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->


<!-- <hr style="background: #000 !important;border-color:#ccc;"> -->
<div class="row" style="padding-top:5px;padding-bottom:20px;">
    <div class="col-lg-1" id="labHeight">
        <p>Lab Name </p>
    </div>
    <div class="col-lg-4" id="labHeight" style="margin-top: 12px;">
        <select name="labName[]" id="labName" class="form-control" onchange="labChange();" title="<?php echo $this->translate('Please select one or more labs. Leave blank for All'); ?>">
            <?php
            foreach ($labName as $lab1) {
            ?>
                <option data-name="<?php echo $lab1['facility_name']; ?>" value="<?php echo $lab1['facility_id']; ?>" <?php if ($lab1['facility_id'] == $lab) {
                                                                                                                            echo 'selected';
                                                                                                                        } ?>><?php echo $lab1['facility_code'] . " - " . $lab1['facility_name']; ?></option>
            <?php
            }
            ?>

        </select>
    </div>
    <div class='col-lg-5' style="margin-top: 12px;">
        <div id="daterange-container" class="btn btn-sm form-control" data-container="body" data-placement="bottom" data-original-title="Change date range" style="text-align:center;width:50%;">
            <i class="icon-calendar"></i>&nbsp;
            <span class="thin uppercase hidden-xs"></span>&nbsp;
            <i class="fa fa-angle-down"></i>
            <input type="hidden" name="daterange" id="daterange" onchange="labChange();" />
        </div>
        &nbsp;&nbsp;
        <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="labChange();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-sm-12 col-lg-12">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="labPerformance"></div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 col-sm-6 col-lg-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Summary Outcomes'); ?></span>
                </div>
            </div>
            <div class="portlet-body">
                <div id="samTestPosNeg"></div>
            </div>
        </div>
    </div>
</div>



<!--  -->
<script src="https://cdn.datatables.net/1.10.10/js/jquery.dataTables.min.js" integrity="sha384-QyXw3+FbFWMGvHERjd2qCYZRk+b2Pjmtq15C/hioWsjhRQ7ogFIq/TyxV45EzU1H" crossorigin="anonymous"></script>
<script src="<?php echo $this->basePath('assets/plugins/datepicker/bootstrap-datepicker.js') ?>"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/dataTables.buttons.min.js" integrity="sha384-nk2cQ4sDpysew3G+v7tJwHnXPn+hFSYDfMXNCUVhYGNn3vSW9vuAgG1jEEVx5DFe" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.flash.min.js" integrity="sha384-OGZNE8UcOgofYMP/794wtqdqPXdlNe0jqWVfXV699b0qNEoZjAng7eE3JSFzj4mE" crossorigin="anonymous"></script>
<script src="https://cdn.datatables.net/buttons/1.1.0/js/buttons.print.min.js" integrity="sha384-sVbeHA0n97H3zikZ3aj3R1iGOBYGKXaj36uB+oJhkHN1vjGFAQT8hE+AWAFFYzgd" crossorigin="anonymous"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js'); ?>" type="text/javascript"></script>
<script>
    //var gfxPath = 'https://raw.githubusercontent.com/highslide-software/pattern-fill/master/graphics/';
    var startDate;
    var endDate;



    function getSampleTested() {
        var lab = $("#labName").val();
        var daterange = $('#daterange').val();
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-lat-lon-map')); ?>", {
                daterange: daterange,
                lab: lab
            },
            function(data) {
                $("#labPerformance").html(data);
            });
    }

    function getSampleTestedPositiveNegative() {
        var lab = $("#labName").val();
        var daterange = $('#daterange').val();
        return $.post("<?php echo $this->url('eid-labs', array('action' => 'get-lat-lon-map-pos-neg')); ?>", {
                daterange: daterange,
                lab: lab
            },
            function(data) {
                $("#samTestPosNeg").html(data);
            });
    }

    function labChange() {
        getSampleTested();
        getSampleTestedPositiveNegative();
    }

    $(function() {
        var daterange = '<?php echo str_replace(array('%20', ' '), array('', ''), $daterange); ?>'
        if (daterange) {
            var date = daterange.split("to");
            var start = date[0];
            var end = date[1];
            daterange = start + ' to ' + end
            var start = moment().subtract(12, 'months');
            var end = moment();
            console.log(start);

            function cb(start, end) {
                $('#daterange-container span').html(start.format('MMM D, YYYY') + ' to ' + end.format('MMM D, YYYY'));
                $('#daterange').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
            }

            $('#daterange-container').daterangepicker({
                format: 'DD-MMM-YYYY',
                separator: ' to ',
                startDate: start,
                endDate: end,
                minDate: <?= (isset($loginContainer->useCurrentTables) && $loginContainer->useCurrentTables === true) ? "moment().subtract(12, 'months')" : "moment().subtract(12, 'years')" ?>,
                maxDate: moment(),
                ranges: {
                    'Today': [moment(), moment()],
                    'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                    'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                    'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                    'This Month': [moment().startOf('month'), moment().endOf('month')],
                    'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
                }
            }, cb);
            cb(start, end);
            $('#dashboard-range').show();
            $('input[name="daterange"]').val(daterange);
        } else
            $('#daterange-container span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        getSampleTested();
        getSampleTestedPositiveNegative();
    });

    function resetEverything() {
        // $('#pageFilter')[0].reset();
        getSampleTested();
    }
</script>
