<?php
use Zend\Session\Container;
$container = new Container('alert');
$logincontainer = new Container('credo');
$languagecontainer = new Container('language');
$config = $this->GetConfigData();
$languagecontainer->locale = $this->GetLocaleData('locale',$config['language']);
?>
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->translate('Smart Connect'); ?> | <?php echo $this->translate('Dashboard for Enhancement of VL Treatment Cascade'); ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="<?php echo $this->basePath('assets/global/css/google-fonts.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/simple-line-icons/simple-line-icons.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css" />
        
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css'); ?>" rel="stylesheet" type="text/css" />
        
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="<?php echo $this->basePath('assets/global/css/components-rounded.min.css'); ?>" rel="stylesheet" id="style_components" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/css/plugins.min.css'); ?>" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="<?php echo $this->basePath('assets/layouts/layout/css/layout.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/layouts/layout/css/themes/blue.min.css'); ?>" rel="stylesheet" type="text/css" id="style_color" />
        
        <link href="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'); ?>" rel="stylesheet" type="text/css" />         
        <link href="<?php echo $this->basePath('assets/global/plugins/select2/css/select2.min.css'); ?>" rel="stylesheet" type="text/css" />      
        <style>
            <?php if($activeTab !='duplicate-data') { ?>
              table.dataTable td.sorting_1,table.dataTable td.sorting_2,table.dataTable td.sorting_3,table.dataTable th.sorting_1,table.dataTable th.sorting_2,table.dataTable th.sorting_3{background:#fbfcfd!important}
            <?php } ?>
        </style>
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" />

        <script src="<?php echo $this->basePath('assets/global/plugins/jquery.min.js'); ?>" type="text/javascript"></script>
    </head>
    <!-- END HEAD -->

    <body class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-content-white">
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner ">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="/">
                        <?php
                        if(isset($config['logo']) && trim($config['logo']) != "" && file_exists(UPLOAD_PATH . DIRECTORY_SEPARATOR . "logo" . DIRECTORY_SEPARATOR . $config['logo'])){ ?>
                          <img src="<?php echo $this->basePath('uploads/logo/'.$config['logo']); ?>" alt="logo" class="logo-default" style="width:32px;height:32px;margin-top:-5px;margin-right:5px;"/>
                        <?php } else { ?>
                          <img src="<?php echo $this->basePath('assets/layouts/layout/img/logo.png'); ?>" alt="logo" class="logo-default" style="margin-top:-5px;margin-right:5px;"/>
                        <?php } ?>
                        <span style="color:#fff;line-height:50px;"><?php echo $this->translate('Smart Connect'); ?></span>
                    </a>
                    <div class="menu-toggler sidebar-toggler"> </div>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN TOP NAVIGATION MENU -->
                <span style="color:#ccc;padding:10px;line-height:50px;font-weight:lighter"><?php echo $this->translate('Development/Test Environment with dummy data'); ?></span>
                <div class="top-menu">
                    <ul class="nav navbar-nav pull-right">
                        <!-- BEGIN USER LOGIN DROPDOWN -->
                        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                        <li class="dropdown dropdown-user">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <img alt="" class="img-circle" src="<?php echo $this->basePath('assets/img/default-avatar.png'); ?>" />
                                <span class="username username-hide-on-mobile"> <?php echo $logincontainer->name ?> </span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                <li>
                                    <a href="/login/logout"><i class="icon-key"></i> <?php echo $this->translate('Log Out'); ?> </a>
                                </li>
                            </ul>
                        </li>
                        <!-- END USER LOGIN DROPDOWN -->

                    </ul>
                </div>
                <!-- END TOP NAVIGATION MENU -->
            </div>
            <!-- END HEADER INNER -->
        </div>
        <!-- END HEADER -->
        <!-- BEGIN HEADER & CONTENT DIVIDER -->
        <div class="clearfix"> </div>
        <!-- END HEADER & CONTENT DIVIDER -->
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar-wrapper">
                <!-- BEGIN SIDEBAR -->
                <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                <div class="page-sidebar navbar-collapse collapse">
                    <!-- BEGIN SIDEBAR MENU -->
                    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
                    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
                    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
                    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
                    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                    <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-light " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
                        <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                        <li class="sidebar-toggler-wrapper hide">
                            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                            <div class="sidebar-toggler"> </div>
                            <!-- END SIDEBAR TOGGLER BUTTON -->
                        </li>
                        <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
                        <?php
                        if($logincontainer->role == 1 || $logincontainer->role == 2){ ?>
                            <li class="nav-item start <?php echo ($activeTab == 'labs-dashboard' ? " active open " : ""); ?>">
                                 <a href="/labs/dashboard" class="nav-link nav-toggle">
                                     <i class="icon-home"></i>
                                     <span class="title"><?php echo $this->translate('Labs Dashboard'); ?></span>
                                     <span class="selected"></span>
                                 </a>
                                 
                            </li>
                        <?php } ?>
                        <?php
                        if($logincontainer->role == 1 || $logincontainer->role == 4){ ?>
                            <!--<li class="nav-item < ?php echo ($activeTab == 'hubs-dashboard' ? " active open " : ""); ?>">
                                 <a href="/hubs/dashboard" class="nav-link nav-toggle">
                                     <i class="icon-home"></i>
                                     <span class="title">< ?php echo $this->translate('Hubs Dashboard'); ?></span>
                                     <span class="selected"></span>
                                 </a>
                                 
                            </li>-->
                        <?php } ?>
                        <?php
                        if($logincontainer->role == 1 || $logincontainer->role == 3){ ?>
                            <li class="nav-item <?php echo ($activeTab == 'clinics-dashboard' ? " active open " : ""); ?>">
                                 <a href="/clinics/dashboard" class="nav-link nav-toggle">
                                     <i class="icon-home"></i>
                                     <span class="title"><?php echo $this->translate('Clinics Dashboard'); ?></span>
                                     <span class="selected"></span>
                                 </a>
                            </li>
                        <?php } ?>
                        
                        <?php if($logincontainer->role == 1){ ?>
                            <li class="nav-item <?php echo ($activeTab == 'duplicate-data') ? " active open " : ""; ?>">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-settings"></i>
                                    <span class="title"><?php echo $this->translate('Data Management'); ?></span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item start <?php echo ($activeTab == 'duplicate-data') ? " active open" : ""; ?>">
                                        <a href="<?php echo $this->url('duplicate-data') ?>" class="nav-link ">
                                          <i class="fa fa-angle-right"></i> <span class="title"><?php echo $this->translate('Duplicate Data'); ?></span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        <?php } ?>
                        
                        <?php
                        if($logincontainer->role == 1){ ?>
                            <li class="nav-item <?php echo ($activeTab == 'config' || $activeTab == 'users' || $activeTab == 'facility') ? " active open " : ""; ?>">
                                <a href="javascript:;" class="nav-link nav-toggle">
                                    <i class="icon-settings"></i>
                                    <span class="title"><?php echo $this->translate('Admin'); ?></span>
                                    <span class="arrow"></span>
                                </a>
                                <ul class="sub-menu">
                                    <li class="nav-item start <?php echo ($activeTab == 'config') ? " active open" : ""; ?>">
                                        <a href="<?php echo $this->url('config', array('action' => 'index')) ?>" class="nav-link ">
                                          <i class="fa fa-angle-right"></i>   <span class="title"><?php echo $this->translate('Global Config'); ?></span>
                                        </a>
                                    </li>
                                    <li class="nav-item end <?php echo ($activeTab == 'users') ? " active open" : ""; ?>">
                                        <a href="<?php echo $this->url('users', array('action' => 'index')) ?>" class="nav-link ">
                                          <i class="fa fa-angle-right"></i>   <span class="title"><?php echo $this->translate('Users'); ?></span>
                                        </a>
                                    </li>
                                    <li class="nav-item end <?php echo ($activeTab == 'facility') ? " active open" : ""; ?>">
                                        <a href="<?php echo $this->url('facility', array('action' => 'index')) ?>" class="nav-link ">
                                          <i class="fa fa-angle-right"></i>   <span class="title"><?php echo $this->translate('Facilities'); ?></span>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        <?php } ?>
                        <!--
                        <li class="nav-item < ?php echo ($activeTab == 'vl-request' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">VL Request</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">
                                <li class="nav-item  < ?php echo (isset($activeMenu) && $activeMenu == 'vl-request' ? " active open " : ""); ?>  ">
                                    <a href="/vl-request/import-file" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Import Excel</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        -->
                       <?php if(isset($logincontainer->accessType) && $logincontainer->accessType == '4') { ?>
                       
                        <li class="nav-item <?php echo ($activeTab == 'admin' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Admin</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">

                                <li class="nav-item  <?php echo ($activeMenu == 'organizations' ? " active open " : ""); ?>  ">
                                    <a href="/organizations" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Manage Facilities</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'users' ? " active open " : ""); ?>  ">
                                    <a href="/users" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">Manage Users</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'config-email' ? " active open " : ""); ?>  ">
                                    <a href="javascript:;" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Configure Email</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'config-sms' ? " active open " : ""); ?>  ">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">Configure SMS</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'config-general' ? " active open " : ""); ?>  ">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">General Config</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'source' ? " active open " : ""); ?>  ">
                                    <a href="<?php echo $this->url('source', array('action' => 'index'));?>" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">Sources</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        
                        <?php } ?>
                        <?php if(isset($logincontainer->accessType) && ($logincontainer->accessType == '1' ||$logincontainer->accessType == '4')) { ?>
                        <li class="nav-item <?php echo ($activeTab == 'clinic' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Clinic</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">

                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">VL Test Request</span>
                                    </a>
                                </li>                           
                               <!-- <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <span class="title">Create Batch</span>
                                    </a>
                                </li> -->
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Sample Shipment</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-print"></i>  <span class="title">Print VL Test Results</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-marker"></i>  <span class="title">VL Sample Tracking</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-mobile" style="font-size:23px;color:red;"></i>  <span class="title">Send Results</span>
                                    </a>
                                </li>
                               <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <i class="fa fa-angle-right"></i>  <span class="title">User Information</span>
                                    </a>
                                </li>                                  
                            </ul>
                        </li>
                        <?php } ?>
                        <?php if(isset($logincontainer->accessType) &&  ($logincontainer->accessType == '2' ||$logincontainer->accessType == '4')) { ?>
                        <li class="nav-item <?php echo ($activeTab == 'clinic' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Hub</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">

                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">VL Test Request</span>
                                    </a>
                                </li>                              
                               <!-- <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <span class="title">Create Batch</span>
                                    </a>
                                </li> -->
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Sample Shipment</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-print"></i>  <span class="title">Print VL Test Results</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-marker"></i>  <span class="title">VL Sample Tracking</span>
                                    </a>
                                </li>
                               <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <i class="fa fa-angle-right"></i>  <span class="title">User Information</span>
                                    </a>
                                </li>                                  
                            </ul>
                        </li>
                        <?php } ?>
                        <?php if(isset($logincontainer->accessType) &&  ($logincontainer->accessType == '3' ||$logincontainer->accessType == '4')) { ?>                        
                        <li class="nav-item <?php echo ($activeTab == 'laboratory' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Laboratory</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">                          
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title"> VL Test Request</span>
                                    </a>
                                </li>
                                
                               <!-- <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <span class="title">Batch Creation</span>
                                    </a>
                                </li> -->
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-print"></i>  <span class="title">Print VL Test Results</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-marker"></i>  <span class="title">VL Sample Tracking</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-mobile" style="font-size:23px;color:red;"></i>  <span class="title">Send Results</span>
                                    </a>
                                </li>
                               <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <i class="fa fa-angle-right"></i>  <span class="title">User Information</span>
                                    </a>
                                </li>                                  
                            </ul>
                        </li>
                    <?php } ?>
                    </ul>
                    <!-- END SIDEBAR MENU -->
                    <!-- END SIDEBAR MENU -->
                </div>
                <!-- END SIDEBAR -->
            </div>
            <!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE HEADER-->
                    
                    <?php echo $this->content; ?>
                    
                    
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner" style="width:100%;font-size:1em;">
                <a href="javascript:void(0);" onclick="clearCache();" style="font-size:8px;cursor:pointer;color:#fff;">Clear Cache</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->translate('Smart Connect - The Viral Load Dashboard (Testing Environment with dummy data) | Funded by'); ?>
                <a href="https://www.taskforce.org/" style="color:#ccc;text-decoration:underline;"><?php echo $this->translate('The Task Force for Global Health'); ?></a>  &
                <a href="https://www.emory.edu/home/index.html" style="color:#ccc;text-decoration:underline;"><?php echo $this->translate('Emory University / PEPFAR'); ?></a>
            </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
        </div>
        <!-- END FOOTER -->
        <!--[if lt IE 9]>
            <script src="<?php echo $this->basePath('assets/global/plugins/respond.min.js'); ?>"></script>
            <script src="<?php echo $this->basePath('assets/global/plugins/excanvas.min.js'); ?>"></script> 
        <![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="<?php echo $this->basePath('assets/global/scripts/highcharts.js'); ?>"></script>
        <script src="<?php echo $this->basePath('assets/global/scripts/highchart-exporting-4.2.2.js'); ?>"></script>
        <script src="<?php echo $this->basePath('assets/global/scripts/highcharts-watermark.js'); ?>"></script>
        
        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/js.cookie.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js'); ?>" type="text/javascript"></script>
        
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?php echo $this->basePath('assets/global/plugins/moment.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js'); ?>" type="text/javascript"></script>

        <script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.waypoints.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.counterup.min.js'); ?>" type="text/javascript"></script>
        


        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<?php echo $this->basePath('assets/global/scripts/app.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="<?php echo $this->basePath('assets/layouts/layout/scripts/layout.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/js/deforayValidation.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/js/cookie.js'); ?>" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->
        <!-- page script -->
        <script>
          $(function () {
             <?php
                if (isset($container->alertMsg) && $container->alertMsg != "") {
                    ?>
                    alert("<?php echo $this->translate($container->alertMsg); ?>");
                    <?php
                    $container->alertMsg = "";
                    unset($container->alertMsg);
                }
            ?>
          });
          
          $(document).ready(function () {
                $("body").on("contextmenu",function(e){
                  //return false;
                });
          });
          
          $(document).ajaxStop(function () {
            setTimeout(showAnnouncementMsg, 2000);
          });
          
          function showAnnouncementMsg(){
            if(document.cookie.indexOf("msg_on") == -1 || getCookie('msg_on') == ''){
                <?php if(isset($config['announcement_msg']) && trim($config['announcement_msg'])!= ''){ ?>
                   alert('<?php echo ucfirst($config['announcement_msg']); ?>');
                   setCookie('msg_on',1);
                <?php } ?>
            }
          }
          
          function clearCache(){
            $.blockUI.defaults.css.border = '1px solid grey'; 
            $(document).ajaxStart($.blockUI({ message: '<h2>Processing...</h2>' })).ajaxStop($.unblockUI);
            $.post("<?php echo $this->url('common', array('action' => 'clear-cache')); ?>",{ },
            function(data) {
                //The parameter set to 'true' reloads a fresh copy from the server. Leaving it out will serve the page from cache.
                window.location.reload(true);
            });
          }
          
          //watermark text default configuration
            Highcharts.setOptions({
                watermark: {
                    text: '<?php echo (isset($config['watermark_text']) && trim($config['watermark_text'])!= '')?$this->translate($config['watermark_text']):''; ?>',
                    width: 60,
                    height: 0
                }
            });
            jQuery(".checkNum").keydown(function (e) {
                // Allow: backspace, delete, tab, escape, enter and .
                if ($.inArray(e.keyCode, [46, 8, 9, 27, 13, 110, 190]) !== -1 ||
                     // Allow: Ctrl+A
                    (e.keyCode == 65 && e.ctrlKey === true) || 
                     // Allow: home, end, left, right
                    (e.keyCode >= 35 && e.keyCode <= 39)) {
                         // let it happen, don't do anything
                         return;
                }
                // Ensure that it is a number and stop the keypress
                if ((e.shiftKey || (e.keyCode < 48 || e.keyCode > 57)) && (e.keyCode < 96 || e.keyCode > 105)) {
                    e.preventDefault();
                }
            });
        </script>
    </body>

</html>
