<?php
use Zend\Session\Container;


$container = new Container('alert');
$logincontainer = new Container('credo');

?>

<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->

    <head>
        <meta charset="utf-8" />
        <title>Viral Load | Dashboard</title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/simple-line-icons/simple-line-icons.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css" />
        
        <link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css'); ?>" rel="stylesheet" type="text/css" />
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css'); ?>" rel="stylesheet" type="text/css" />
        
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="<?php echo $this->basePath('assets/global/css/components-rounded.min.css'); ?>" rel="stylesheet" id="style_components" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/css/plugins.min.css'); ?>" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="<?php echo $this->basePath('assets/layouts/layout/css/layout.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/layouts/layout/css/themes/darkblue.min.css'); ?>" rel="stylesheet" type="text/css" id="style_color" />
        
        
        <link href="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'); ?>" rel="stylesheet" type="text/css" />           
        
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="favicon.ico" />
    
    
    <script src="<?php echo $this->basePath('assets/global/plugins/jquery.min.js'); ?>" type="text/javascript"></script>
    
    </head>
    <!-- END HEAD -->

    <body class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-content-white">
        <!-- BEGIN HEADER -->
        <div class="page-header navbar navbar-fixed-top">
            <!-- BEGIN HEADER INNER -->
            <div class="page-header-inner ">
                <!-- BEGIN LOGO -->
                <div class="page-logo">
                    <a href="/">
                        <img src="<?php echo $this->basePath('assets/layouts/layout/img/logo.png'); ?>" alt="logo" class="logo-default" /> </a>
                    <div class="menu-toggler sidebar-toggler"> </div>
                </div>
                <!-- END LOGO -->
                <!-- BEGIN RESPONSIVE MENU TOGGLER -->
                <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"> </a>
                <!-- END RESPONSIVE MENU TOGGLER -->
                <!-- BEGIN TOP NAVIGATION MENU -->
                <div class="top-menu">
                    <ul class="nav navbar-nav pull-right">
                        <!-- BEGIN USER LOGIN DROPDOWN -->
                        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                        <li class="dropdown dropdown-user">
                            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                                <img alt="" class="img-circle" src="<?php echo $this->basePath('assets/img/default-avatar.png'); ?>" />
                                <span class="username username-hide-on-mobile"> <?php echo $logincontainer->name ?> </span>
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-default">
                                
                                <li>
                                    <a href="/login/logout">
                                        <i class="icon-key"></i> Log Out </a>
                                </li>
                            </ul>
                        </li>
                        <!-- END USER LOGIN DROPDOWN -->

                    </ul>
                </div>
                <!-- END TOP NAVIGATION MENU -->
            </div>
            <!-- END HEADER INNER -->
        </div>
        <!-- END HEADER -->
        <!-- BEGIN HEADER & CONTENT DIVIDER -->
        <div class="clearfix"> </div>
        <!-- END HEADER & CONTENT DIVIDER -->
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN SIDEBAR -->
            <div class="page-sidebar-wrapper">
                <!-- BEGIN SIDEBAR -->
                <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                <div class="page-sidebar navbar-collapse collapse">
                    <!-- BEGIN SIDEBAR MENU -->
                    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
                    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
                    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
                    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
                    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                    <ul class="page-sidebar-menu  page-header-fixed page-sidebar-menu-light " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
                        <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
                        <li class="sidebar-toggler-wrapper hide">
                            <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
                            <div class="sidebar-toggler"> </div>
                            <!-- END SIDEBAR TOGGLER BUTTON -->
                        </li>
                        <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
                       <li class="nav-item start <?php echo ($activeTab == 'labs-dashboard' ? " active open " : ""); ?>">
                            <a href="/labs/dashboard" class="nav-link nav-toggle">
                                <i class="icon-home"></i>
                                <span class="title">Labs Dashboard</span>
                                <span class="selected"></span>
                            </a>
                            
                        </li>
                       <li class="nav-item start <?php echo ($activeTab == 'clinics-dashboard' ? " active open " : ""); ?>">
                            <a href="/clinics/dashboard" class="nav-link nav-toggle">
                                <i class="icon-home"></i>
                                <span class="title">Clinics Dashboard</span>
                                <span class="selected"></span>
                            </a>
                            
                        </li>
                       
                       <?php if(isset($logincontainer->accessType) && $logincontainer->accessType == '4') { ?>
                       
                        <li class="nav-item <?php echo ($activeTab == 'admin' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Admin</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">

                                <li class="nav-item  <?php echo ($activeMenu == 'organizations' ? " active open " : ""); ?>  ">
                                    <a href="/organizations" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Manage Facilities</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'users' ? " active open " : ""); ?>  ">
                                    <a href="/users" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">Manage Users</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'config-email' ? " active open " : ""); ?>  ">
                                    <a href="javascript:;" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Configure Email</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'config-sms' ? " active open " : ""); ?>  ">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">Configure SMS</span>
                                    </a>
                                </li>
                                <li class="nav-item  <?php echo ($activeMenu == 'config-general' ? " active open " : ""); ?>  ">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">General Config</span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        
                        <?php } ?>
                        <?php if(isset($logincontainer->accessType) && $logincontainer->accessType == '1') { ?>
                        <li class="nav-item <?php echo ($activeTab == 'clinic' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Clinic</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">

                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">VL Test Request</span>
                                    </a>
                                </li>                           
                               <!-- <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <span class="title">Create Batch</span>
                                    </a>
                                </li> -->
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Sample Shipment</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-print"></i>  <span class="title">Print VL Test Results</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-marker"></i>  <span class="title">VL Sample Tracking</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-mobile" style="font-size:23px;color:red;"></i>  <span class="title">Send Results</span>
                                    </a>
                                </li>
                               <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <i class="fa fa-angle-right"></i>  <span class="title">User Information</span>
                                    </a>
                                </li>                                  
                            </ul>
                        </li>
                        <?php } ?>
                        <?php if(isset($logincontainer->accessType) && $logincontainer->accessType == '2') { ?>
                        <li class="nav-item <?php echo ($activeTab == 'clinic' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Hub</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">

                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title">VL Test Request</span>
                                    </a>
                                </li>                              
                               <!-- <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <span class="title">Create Batch</span>
                                    </a>
                                </li> -->
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                      <i class="fa fa-angle-right"></i>   <span class="title">Sample Shipment</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-print"></i>  <span class="title">Print VL Test Results</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-marker"></i>  <span class="title">VL Sample Tracking</span>
                                    </a>
                                </li>
                               <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <i class="fa fa-angle-right"></i>  <span class="title">User Information</span>
                                    </a>
                                </li>                                  
                            </ul>
                        </li>
                        <?php } ?>
                        <?php if(isset($logincontainer->accessType) && $logincontainer->accessType == '3') { ?>                        
                        <li class="nav-item <?php echo ($activeTab == 'laboratory' ? " active open " : ""); ?> ">
                            <a href="javascript:;" class="nav-link nav-toggle">
                                <i class="icon-settings"></i>
                                <span class="title">Laboratory</span>
                                <span class="arrow"></span>
                            </a>
                            <ul class="sub-menu">                          
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-angle-right"></i>  <span class="title"> VL Test Request</span>
                                    </a>
                                </li>
                                
                               <!-- <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <span class="title">Batch Creation</span>
                                    </a>
                                </li> -->
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-print"></i>  <span class="title">Print VL Test Results</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-marker"></i>  <span class="title">VL Sample Tracking</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                       <i class="fa fa-mobile" style="font-size:23px;color:red;"></i>  <span class="title">Send Results</span>
                                    </a>
                                </li>
                               <li class="nav-item">
                                    <a href="javascript:;" class="nav-link ">
                                        <i class="fa fa-angle-right"></i>  <span class="title">User Information</span>
                                    </a>
                                </li>                                  
                            </ul>
                        </li>
                    <?php } ?>
                        
                    </ul>
                    <!-- END SIDEBAR MENU -->
                    <!-- END SIDEBAR MENU -->
                </div>
                <!-- END SIDEBAR -->
            </div>
            <!-- END SIDEBAR -->
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE HEADER-->
                    
                    <?php echo $this->content; ?>
                    
                    
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
        <!-- BEGIN FOOTER -->
        <div class="page-footer">
            <div class="page-footer-inner"> 2016 &copy; Viral Load
                
            </div>
            <div class="scroll-to-top">
                <i class="icon-arrow-up"></i>
            </div>
        </div>
        <!-- END FOOTER -->
        <!--[if lt IE 9]>
            <script src="<?php echo $this->basePath('assets/global/plugins/respond.min.js'); ?>"></script>
            <script src="<?php echo $this->basePath('assets/global/plugins/excanvas.min.js'); ?>"></script> 
        <![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        
        <script src="https://code.highcharts.com/highcharts.js"></script>
        
        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/js.cookie.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js'); ?>" type="text/javascript"></script>
        
        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js'); ?>" type="text/javascript"></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?php echo $this->basePath('assets/global/plugins/moment.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.js'); ?>" type="text/javascript"></script>

        <script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.waypoints.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.counterup.min.js'); ?>" type="text/javascript"></script>
        


        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<?php echo $this->basePath('assets/global/scripts/app.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'); ?>" type="text/javascript"></script>
        
        
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="<?php echo $this->basePath('assets/layouts/layout/scripts/layout.min.js'); ?>" type="text/javascript"></script>

        <!-- END THEME LAYOUT SCRIPTS -->
    </body>

</html>