<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
    <!--<![endif]-->
    <!-- BEGIN HEAD -->
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->translate('Smart Connect'); ?> | <?php echo $this->translate('Dashboard for Enhancement of VL Treatment Cascade'); ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <!-- BEGIN GLOBAL MANDATORY STYLES -->
        <link href="<?php echo $this->basePath('assets/global/css/google-fonts.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/font-awesome/css/font-awesome.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/simple-line-icons/simple-line-icons.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/bootstrap/css/bootstrap.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link rel="stylesheet" href="<?php echo $this->basePath() . '/assets/global/css/deforayModal.css';?>">
        <!-- END GLOBAL MANDATORY STYLES -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css'); ?>" rel="stylesheet" type="text/css" />
        
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL STYLES -->
        <link href="<?php echo $this->basePath('assets/global/css/components-rounded.min.css'); ?>" rel="stylesheet" id="style_components" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/css/plugins.min.css'); ?>" rel="stylesheet" type="text/css" />
        <!-- END THEME GLOBAL STYLES -->
        <!-- BEGIN THEME LAYOUT STYLES -->
        <link href="<?php echo $this->basePath('assets/layouts/layout/css/layout.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/layouts/layout/css/themes/blue.min.css'); ?>" rel="stylesheet" type="text/css" id="style_color" />
        
        <link href="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.css'); ?>" rel="stylesheet" type="text/css" />
        <link href="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css'); ?>" rel="stylesheet" type="text/css" />         
        <link href="<?php echo $this->basePath('assets/global/plugins/select2/css/select2.min.css'); ?>" rel="stylesheet" type="text/css" />      
        <style>
            <?php if($activeTab !='duplicate-data') { ?>
              table.dataTable td.sorting_1,table.dataTable td.sorting_2,table.dataTable td.sorting_3,table.dataTable th.sorting_1,table.dataTable th.sorting_2,table.dataTable th.sorting_3{background:#fbfcfd!important}
            <?php } ?>
            .resize-page-logo{
                width:auto !important;
            }
            .manage-logo-default{
                margin-top:8px !important;
            }
            .hide-default-text{
                display:none;
            }
            .scroll-to-top>i {
                color: #ff7a7a !important;
            }
        </style>
        <!-- END THEME LAYOUT STYLES -->
        <link rel="shortcut icon" href="/favicon.ico" />

        <script src="<?php echo $this->basePath('assets/global/plugins/jquery.min.js'); ?>" type="text/javascript"></script>
    </head>
    <!-- END HEAD -->

    <body class="page-header-fixed page-container-bg-solid page-content-white page-sidebar-closed">
        <!-- BEGIN HEADER & CONTENT DIVIDER -->
        <div class="clearfix"> </div>
        <!-- END HEADER & CONTENT DIVIDER -->
        <!-- BEGIN CONTAINER -->
        <div class="page-container">
            <!-- BEGIN CONTENT -->
            <div class="page-content-wrapper">
                <!-- BEGIN CONTENT BODY -->
                <div class="page-content">
                    <!-- BEGIN PAGE HEADER-->
                    <?php echo $this->content; ?>
                </div>
                <!-- END CONTENT BODY -->
            </div>
            <!-- END CONTENT -->
        </div>
        <!-- END CONTAINER -->
        
        <div id="dDiv" class="dialog"> 
            <div style="text-align:center"><span onclick="closeModal();" style="float:right;clear:both;" class="closeModal"></span></div> 
            <iframe id="dFrame" src="" style="border:none;" scrolling='yes' marginwidth='0' marginheight='0' frameborder='0' vspace='0' hspace='0' >some problem</iframe> 
        </div>
        <!-- END FOOTER -->
        <!--[if lt IE 9]>
            <script src="<?php echo $this->basePath('assets/global/plugins/respond.min.js'); ?>"></script>
            <script src="<?php echo $this->basePath('assets/global/plugins/excanvas.min.js'); ?>"></script> 
        <![endif]-->
        <!-- BEGIN CORE PLUGINS -->
        <script src="<?php echo $this->basePath('assets/global/scripts/highcharts.js'); ?>"></script>
        <script src="<?php echo $this->basePath('assets/global/scripts/highchart-exporting-4.2.2.js'); ?>"></script>
        <script src="<?php echo $this->basePath('assets/global/scripts/highcharts-watermark.js'); ?>"></script>
        <script src="<?php echo $this->basePath('assets/global/scripts/deforayModal.js'); ?>"></script>

        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap/js/bootstrap.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/js.cookie.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js'); ?>" type="text/javascript"></script>
        
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="<?php echo $this->basePath('assets/global/plugins/moment.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js'); ?>" type="text/javascript"></script>

        <script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.waypoints.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.counterup.min.js'); ?>" type="text/javascript"></script>
        

        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN THEME GLOBAL SCRIPTS -->
        <script src="<?php echo $this->basePath('assets/global/scripts/app.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/global/plugins/select2/js/select2.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/js/jasny-bootstrap.min.js'); ?>" type="text/javascript"></script>
        <!-- END THEME GLOBAL SCRIPTS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        
        <!-- END PAGE LEVEL SCRIPTS -->
        <!-- BEGIN THEME LAYOUT SCRIPTS -->
        <script src="<?php echo $this->basePath('assets/layouts/layout/scripts/layout.min.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/js/deforayValidation.js'); ?>" type="text/javascript"></script>
        <script src="<?php echo $this->basePath('assets/js/cookie.js'); ?>" type="text/javascript"></script>
        <!-- END THEME LAYOUT SCRIPTS -->
        <!-- page script -->
        <script>
          //only visible legends export
          Highcharts.wrap(Highcharts.Chart.prototype, 'init', function (proceed, options, callback) {
                if (options.chart && options.chart.forExport && options.series) {
                    $.each(options.series, function () {
                        if (this.visible === false) {
                            this.showInLegend = false;
                        }
                    });
                }
                return proceed.call(this, options, callback);
           });
            
          //watermark text default configuration
           Highcharts.setOptions({
                watermark: {
                    text: '<?php echo (isset($config['watermark_text']) && trim($config['watermark_text'])!= '')?$this->translate($config['watermark_text']):''; ?>',
                    width: 60,
                    height: 0
                }
           });
            
            function showModal(url, w, h) {
                showdefModal('dDiv', w, h);
                document.getElementById('dFrame').style.height = h + 'px';
                document.getElementById('dFrame').style.width = w + 'px';
                document.getElementById('dFrame').src = url;
            }
            function closeModal() {
                document.getElementById('dFrame').src = "";
                hidedefModal('dDiv');
            }
        </script>
    </body>

</html>
