<div class="row">
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Recieved'); ?></span>
                </div>
            </div>
            <div class="portlet-body" id="femalePatientPieChart">
                <div id="sampleRecived" style="height:500px;"></div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-sm-6">
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <span class="caption-subject"><?php echo $this->translate('Samples Tested'); ?></span>
                </div>
            </div>
            <div class="portlet-body" id="lineOfTreatmentPieChart">
                <div id="sampleTested" style="height:500px;"></div>
            </div>
        </div>
    </div>
</div>

<table id="regTable" class="table table-striped table-bordered table-hover table-checkable order-column">
    <thead>
        <tr>
            <th style="width:40%;text-align:left;"><?php echo $this->translate('Lab Name'); ?></th>
            <th style="width:20%;text-align:center;"><?php echo $this->translate('Samples Recieved'); ?></th>
            <th style="width:20%;text-align:center;"><?php echo $this->translate('Samples Tested'); ?></th>
            <th style="width:20%;text-align:center;"><?php echo $this->translate('Samples Rejected'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php
        $echo = '';
        if (isset($result) && !empty($result)) {
            $total = 0;
            foreach ($result as $val) { ?>
                <tr>
                    <td style="width:40%;text-align:left;"><?php echo $val['clinicName'];?></td>
                    <td style="width:20%;text-align:center;"><?php echo $val['total'];?></td>
                    <td style="width:20%;text-align:center;"><?php echo $val['totalTested'];?></td>
                    <td style="width:20%;text-align:center;"><?php echo $val['totalRejected'];?></td>
                </tr>
            <?php $rtotal += $val['total'];
                $ttotal += $val['totalTested'];
                $rjtotal += $val['totalRejected'];
            } ?>
        <?php } else { ?>
            <tr>
                <td colspan="4" class="dataTables_empty">Loading data from server</td>
            </tr>
        <?php } ?>
    </tbody>
    <?php if(isset($result) && !empty($result)){ ?>
        <tfoot>
            <tr>
                <td style="width:40%;font-weight:bold;text-align:right;">Total</td>
                <td style="width:20%;font-weight:bold;text-align:center;"><?php echo $rtotal;?></td>
                <td style="width:20%;font-weight:bold;text-align:center;"><?php echo $ttotal;?></td>
                <td style="width:20%;font-weight:bold;text-align:center;"><?php echo $rjtotal;?></td>
            </tr>
        </tfoot>
    <?php } ?>
</table>
<script>
    <?php foreach(['sampleRecived', 'sampleTested'] as $val){
        $key = ($val == 'sampleRecived')? 'total' : 'totalTested';
        $heading = ($val == 'sampleRecived')? "Sample Received" : "Sample Tested";
        $subheading = ($val == 'sampleRecived')? "Received" : "Tested";?>
        $('#<?php echo $val;?>').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: ''
        },
        exporting:{
            chartOptions:{
                subtitle: {
                    text:'<?php echo $this->translate($heading); ?>',
                }
            }
        },
       credits: {
              enabled: false
       },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}% ({point.number})</b>'
        },
        legend: {
            //layout: 'vertical',
            align: 'center',
            //backgroundColor: '#f3f3f3',
            useHTML: true,
            itemMarginBottom: 5,
            labelFormatter: function () {
                return '<div style="width:230px"><span style="float:left;font-size:10px;">' + this.myData + ' ('+ this.name + ') - </span><span style="font-size:10px;padding:1px; ">'+ this.percentage.toFixed(1)+'% ('+Highcharts.numberFormat(this.y, 0)+')</span></div>';
            }
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    //enabled : false,
                distance: -30
              },
                showInLegend: true
            }
        },
        series: [{
            name: '<?php echo $this->translate($subheading); ?>',
            colorByPoint: true,
            data: [
                <?php
                    if(isset($result) && !empty($result)){
                    foreach($result as $val){ ?>
                        {
                            name:'N: <?php echo $val[$key];?>',
                            y:<?php echo $val[$key];?>,
                            number:<?php echo $val[$key];?>,
                            myData:'<?php echo $val['clinicName']; ?>'
                        },
                <?php }
                }?>
            ]
        }]
    });
    <?php } ?>
</script>