<?php

use Application\Service\CommonService;

$common = new CommonService();
foreach ($requestType as $key => $value) {
	$requestTypeOption[$value['request_type']] = $value['request_type'];
}
?>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/plugins/datepicker/datepicker3.css') ?>">
<style>
    .bluebox,
    .dashboard-stat2 {
        border: 1px solid #3598DC;
    }

    .mrp-monthdisplay {
        display: inline-block !important;
        border-radius: 0px 5px 5px 0px;
        cursor: pointer;
    }

    .mrp-lowerMonth,
    .mrp-upperMonth {
        color: #40667A;
        font-weight: bold;
        font-size: 11px;
        text-transform: uppercase;
    }

    .mrp-to {
        color: #aaa;
        margin-right: 0px;
        margin-left: 0px;
        font-size: 11px;
        text-transform: uppercase;
        /* background-color: #eee; */
        padding: 5px 3px 5px 3px;
    }

    .mpr-calendar {
        display: inline-block;
        padding: 3px 5px;
        border-right: solid #999 1px;
    }

    .mpr-calendar::last-child {
        border-right: none;
    }

    .mpr-month {
        padding: 20px;
        text-transform: uppercase;
        font-size: 12px;
    }

    .mpr-calendar h5 {
        width: 100%;
        text-align: center;
        font-weight: bold;
        font-size: 18px
    }

    /* .mpr-selected {} */

    .mpr-month:hover {
        border-radius: 5px;
        box-shadow: 0 0 0 1px #ddd inset;
        cursor: pointer;
    }

    .mpr-selected.mpr-month:hover {
        border-radius: 0px;
        box-shadow: none;
    }

    .mpr-calendarholder .col-xs-6 {
        max-width: 250px;
        min-width: 250px;
    }

    .mpr-calendarholder .col-xs-1 {
        max-width: 150px;
        min-width: 150px;
    }

    .mpr-calendarholder .btn-info {
        background-color: #40667A;
        border-color: #406670;
        width: 100%;
        margin-bottom: 10px;
        text-transform: uppercase;
        font-size: 10px;
        padding: 10px 0px;
    }

    .mpr-quickset {
        color: #666;
        text-transform: uppercase;
        text-align: center;
    }

    .mpr-yeardown,
    .mpr-yearup {
        margin-left: 5px;
        cursor: pointer;
        color: #666;
    }

    .mpr-yeardown {
        float: left;
    }

    .mpr-yearup {
        float: right;
    }

    .mpr-yeardown:hover,
    .mpr-yearup:hover {
        color: #40667A;
    }

    .mpr-calendar:first .mpr-selected:first {
        background-color: #40667A;
    }

    .mpr-calendar:last .mpr-selected:last {
        background-color: #40667A;
    }

    .popover {
        max-width: 1920px !important;
    }

    .table>tbody>tr>td,
    .table>tbody>tr>th,
    .table>tfoot>tr>td,
    .table>tfoot>tr>th,
    .table>thead>tr>td,
    .table>thead>tr>th {
        padding: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '8' : '3'; ?>px;
        font-size: <?php echo (isset($languagecontainer->locale) && $languagecontainer->locale == 'en_US') ? '14' : '13'; ?>px;
    }

    .select2-search__field,
    .select2-selection__rendered {
        color: #333;
        text-align: center;
    }

    .select2-container--default {
        width: 100% !important;
    }

    .select2-selection--multiple {
        border-radius: 10px !important;
    }

    @media screen and (min-width:320px) and (max-width: 760px) {

        #daterange-container,
        #daterange-container-key-indicator {
            width: 100% !important;
        }

        #showDateRange,
        #closeDateRange {
            margin-left: 0% !important;
        }
    }

    @media screen and (min-width:761px) and (max-width: 970px) {

        #daterange-container,
        #daterange-container-key-indicator {
            width: 100% !important;
        }

        #showDateRange,
        #closeDateRange {
            margin-left: 52% !important;
        }
    }

    .select2-container--default .select2-selection--single {
        height: 34px !important;
    }
</style>
<div class="page-bar">
	<ul class="page-breadcrumb">
		<li>
			<a href="/"><?php echo $this->translate('Dashboard'); ?></a>
			<i class="fa fa-circle"></i>
		</li>
		<li>
			<?php echo $this->translate('Snapshot'); ?>
		</li>
	</ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"><?php echo $this->translate('Snapshot'); ?></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
    <div id="sampleResultDetails"></div>
</div>

<div class="row">
	<div class="col-md-12">
		<!-- BEGIN EXAMPLE TABLE PORTLET-->
		<div class="portlet box blue">
			<!-- <div class="portlet-title">
				<div class="caption">
					<i class="fa fa-cogs"></i>
				</div>
			</div> -->
			<div class="portlet-body">
				<div class="table-toolbar">
					<div class="row">
						<div class="col-md-12">
							<div class="box">
								<table aria-describedby="table" class="table" aria-hidden="true" cellspacing="3" style="margin-left:1%;margin-top:20px;width:100%;">
									<tr>
										<td style="width:10%;"><strong><?php echo $this->translate("Test Type"); ?>&nbsp;:</strong></td>
										<td style="width:20%;">
											<select id="testType" name="testType[]" multiple class="form-control" title="<?php echo $this->translate('Please select the Test types'); ?>" style="width:100%;">
												<option value="vl"><?php echo $this->translate("Viral Load"); ?></option>
												<option value="eid"><?php echo $this->translate("Early Infant Diagnosis"); ?></option>
												<option value="covid19"><?php echo $this->translate("Covid-19"); ?></option>
												<option value='hepatitis'><?php echo $this->translate("Hepatitis"); ?></option>
												<option value='tb'><?php echo $this->translate("TB"); ?></option>
											</select>
										</td>
										<td style="width:10%;"><strong><?php echo $this->translate('Sample Collection Date'); ?>&nbsp;:</strong></td>
										<td style="width:20%;">
											<input type="text" id="collectionDate" name="collectionDate" class="form-control daterangefield" placeholder="<?php echo $this->translate('Enter date range'); ?>" style="width:100%;background:#fff;" />
										</td>
                                        <td style="width:10%;"><strong><?php echo $this->translate('Sample Tested Date'); ?>&nbsp;:</strong></td>
										<td style="width:20%;">
											<input type="text" id="testedDate" name="testedDate" class="form-control daterangefield" placeholder="<?php echo $this->translate('Enter date range'); ?>" style="width:100%;background:#fff;" />
										</td>
									</tr>
                                    <tr>
                                        <td style="width:10%;"><strong><?php echo $this->translate("Province"); ?>&nbsp;:</strong></td>
										<td style="width:20%;">
                                            <select name="provinceName[]" id="provinceName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more province. Leave blank for All'); ?>" onchange="selectDistrictName();"  style="width:100%;">
                                                <?php foreach ($provinceName as $province) {?> 
                                                    <option value="<?php echo $province['geo_id']; ?>"><?php echo $province['geo_name']; ?></option>
                                                <?php } ?>
                                            </select>
										</td>
                                        <td style="width:10%;"><strong><?php echo $this->translate("District"); ?>&nbsp;:</strong></td>
										<td style="width:20%;">
                                            <select name="districtName[]" id="districtName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more district. Leave blank for All'); ?>" onchange="selectClinicName();"  style="width:100%;">
                                            </select>
										</td>
                                        <td style="width:10%;"><strong><?php echo $this->translate("Health Facility"); ?>&nbsp;:</strong></td>
										<td style="width:20%;">
                                            <select class="form-control" id="clinicId" name="clinicId[]" multiple title="<?php echo $this->translate('Please select one or more clinics. Leave blank for All'); ?>"  style="width:100%;">
                                            </select>
										</td>
									</tr>
                                    <tr><td colspan="2">
                                        <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getData();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                                        <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="location.reload();" style="margin-right:5.8%;"><?php echo $this->translate('Reset'); ?></a>
                                    </td></tr>
								</table>
							</div>
							<!-- /.box -->
						</div>
					</div>
					<br>
					<div id="loadData"></div>
				</div>
			</div>
		</div>
		<!-- END EXAMPLE TABLE PORTLET-->
	</div>
</div>
<script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/plugins/datepicker/bootstrap-datepicker.js') ?>"></script>
<script type="text/javascript">
	/* Table initialisation */
	oTable = null;
    
	$(document).ready(function() {

        $('#testType').select2({
            placeholder: "<?php echo $this->translate('Test Type'); ?>",
            allowClear: true
        });
        $('#provinceName').select2({
            placeholder: "<?php echo $this->translate('All Province'); ?>",
            allowClear: true
        });
        $('#districtName').select2({
            placeholder: "<?php echo $this->translate('Select Province First'); ?>",
            allowClear: true
        });
        $('#clinicId').select2({
            placeholder: "<?php echo $this->translate('Select Districts First'); ?>",
            allowClear: true
        });
		$('.daterangefield').daterangepicker({
			"ranges": {
				'Today': [moment(), moment()],
				'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
				'Last 7 Days': [moment().subtract(6, 'days'), moment()],
				'Last 30 Days': [moment().subtract(29, 'days'), moment()],
				'This Month': [moment().startOf('month'), moment().endOf('month')],
				'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
			},
			"locale": {
				"format": "DD-MMM-YYYY",
				"separator": " to ",
				"applyLabel": "Apply",
				"cancelLabel": "Cancel",
				"fromLabel": "From",
				"toLabel": "To",
				"customRangeLabel": "Custom",
				"daysOfWeek": [
					"Su",
					"Mo",
					"Tu",
					"We",
					"Th",
					"Fr",
					"Sa"
				],
				"monthNames": [
					"January",
					"February",
					"March",
					"April",
					"May",
					"June",
					"July",
					"August",
					"September",
					"October",
					"November",
					"December"
				],
				"firstDay": 1
			},
			//"startDate": "11/08/2015",
			//"endDate": "11/14/2015",
			opens: "left",
		}, function(start, end, label) {
			$('.daterange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
		});

		$('#collectionDate').val(moment().subtract(1, 'month').format('DD-MMM-YYYY') + ' to ' + moment().format('DD-MMM-YYYY'));
		$('#testedDate').val('');
		getSampleResult('daterange');
		getData();
		<?php
        $minDate = (isset($loginContainer->useCurrentTables) && $loginContainer->useCurrentTables == true) ? "moment().subtract(12, 'months')" : "moment().subtract(12, 'years')";
        ?>
		$('#daterange-container, #daterange-container-key-indicator').daterangepicker({
            'format': 'DD-MMM-YYYY',
            'separator': ' to ',
            'startDate': start,
            'endDate': end,
            'minDate': <?php echo $minDate; ?>,
            'maxDate': moment(),
            'ranges': {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start, end);
        $('#dashboard-range').show();
        $('#daterange-container span, #daterange-container-key-indicator span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');

        // The reason why getSampleResult is a separate call is because it does not follow
        // the Date and Lab filters of the other functions.
        getSampleResult('load');
        getEverything();

        $('#provinceName,#districtName,#labName').on('select2:close', function() {
            let select = $(this)
            $(this).next('span.select2').find('ul').html(function() {
                let count = select.select2('data').length
                if (count > 1) {
                    return "<li>" + count + " items selected</li>"
                }
            })
        })
	});

	function getSampleResult(frmSource) {
        var daterange = $('#collectionDate').val();
        if (frmSource == 'daterange' && $.trim(daterange) == '') {
            alert('<?php echo $this->translate('Please choose date range'); ?>');
            return false;
        }
        return $.post("<?php echo $this->url('snapshot', array('action' => 'get-quick-stats')); ?>", {
                daterange: daterange
            },
            function(data) {
                $("#sampleResultDetails").html(data);
            });
    }

    function selectDistrictName() {
        $('#districtName,#clinicId').html('');
        $('#districtName,#clinicId').select2('val', '');

        var pName = $("#provinceName").val();
        if (pName != null && pName.length > 0) {
            $.post("<?php echo $this->url('common', array('action' => 'get-district-list')); ?>", {
                    provinceName: pName
                },
                function(data) {
                    if (data != "" || data != null || data != undefined) {
                        $('#districtName').html(data);
                    }
                });
        }
    }

    function selectClinicName() {
        $('#clinicId').html('');
        $('#clinicId').select2('val', '');
        var dName = $("#districtName").val();

        if (dName != null && dName.length > 0) {
            $.post("<?php echo $this->url('common', array('action' => 'get-facility-list')); ?>", {
                    districtName: dName
                },
                function(data) {
                    if (data != "" || data != null || data != undefined) {
                        $('#clinicId').html(data);
                    }
                });
        }
    }
    
    function getData() {
        // $('#clinicId').select2('val', '');
        $.post("<?php echo $this->url('snapshot', array('action' => 'get-snapshot-data')); ?>", {
            collectionDate: $('#collectionDate').val(),
            testedDate: $('#testedDate').val(),
            testType: $('#testType').val(),
            provinceName: $('#provinceName').val(),
            districtName: $('#districtName').val(),
            clinicId: $('#clinicId').val()
        },
        function(data) {
            if (data != "" || data != null || data != undefined) {
                $('#loadData').html(data);
				$('#regTable').dataTable(
					{
						"aaSorting": [
							[2, "desc"]
						],
					}
				);
            }
        });
    }

	$("#showDateRange").click(function() {
        $("#showDateRange").hide();
        $("#closeDateRange,.daterange-container").show();
    });

    $("#closeDateRange").click(function() {
        $("#closeDateRange,.daterange-container").hide();
        $("#showDateRange").show();
    });

    function resetDateFilter() {
        $('#dateFilter')[0].reset();
        $('#daterange-container span, #daterange-container-key-indicator span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');
        getSampleResult('reset');
    }
</script>
