<?php

$requestTypeOption = [];
if (isset($requestType) && !empty($requestType)) {
    foreach ($requestType as $key => $value) {
        $requestTypeOption[$value['request_type']] = $value['request_type'];
    }
}
?>
<style>
    div#regTable_wrapper {
        background: white;
        padding: 20px;
    }
</style>
<link rel="stylesheet" href="<?php echo $this->basePath('assets/plugins/datepicker/datepicker3.css') ?>">
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <?php echo $this->translate('Snapshot'); ?>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"><?php echo $this->translate('Snapshot'); ?></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-body">
                <div class="table-toolbar">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="box">
                                <table aria-describedby="table" class="table" aria-hidden="true" cellspacing="3" style="margin-left:1%;margin-top:20px;width:100%;">
                                    <tr>
                                        <td style="width:10%;"><strong><?php echo $this->translate("Test Type"); ?>&nbsp;:</strong></td>
                                        <td style="width:20%;">
                                            <select id="testType" name="testType[]" multiple class="form-control" title="<?php echo $this->translate('Please select the Test types'); ?>" style="width:100%;">
                                                <option value="vl"><?php echo $this->translate("Viral Load"); ?></option>
                                                <option value="eid"><?php echo $this->translate("Early Infant Diagnosis"); ?></option>
                                                <option value="covid19"><?php echo $this->translate("Covid-19"); ?></option>
                                                <option value='hepatitis'><?php echo $this->translate("Hepatitis"); ?></option>
                                                <option value='tb'><?php echo $this->translate("TB"); ?></option>
                                            </select>
                                        </td>
                                        <td style="width:10%;"><strong><?php echo $this->translate('Sample Collection Date'); ?>&nbsp;:</strong></td>
                                        <td style="width:20%;">
                                            <input type="text" id="collectionDate" name="collectionDate" class="form-control daterangefield" placeholder="<?php echo $this->translate('Enter date range'); ?>" style="width:100%;background:#fff;" />
                                        </td>
                                        <td style="width:10%;"><strong><?php echo $this->translate('Sample Tested Date'); ?>&nbsp;:</strong></td>
                                        <td style="width:20%;">
                                            <input type="text" id="testedDate" name="testedDate" class="form-control daterangefield" placeholder="<?php echo $this->translate('Enter date range'); ?>" style="width:100%;background:#fff;" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width:10%;"><strong><?php echo $this->translate("Province"); ?>&nbsp;:</strong></td>
                                        <td style="width:20%;">
                                            <select name="provinceName[]" id="provinceName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more province. Leave blank for All'); ?>" onchange="selectDistrictName();" style="width:100%;">
                                                <?php foreach ($provinceName as $province) { ?>
                                                    <option value="<?php echo $province['geo_id']; ?>"><?php echo $province['geo_name']; ?></option>
                                                <?php } ?>
                                            </select>
                                        </td>
                                        <td style="width:10%;"><strong><?php echo $this->translate("District"); ?>&nbsp;:</strong></td>
                                        <td style="width:20%;">
                                            <select name="districtName[]" id="districtName" class="form-control" multiple title="<?php echo $this->translate('Please select one or more district. Leave blank for All'); ?>" onchange="selectClinicName();" style="width:100%;">
                                            </select>
                                        </td>
                                        <td style="width:10%;"><strong><?php echo $this->translate("Health Facility"); ?>&nbsp;:</strong></td>
                                        <td style="width:20%;">
                                            <select class="form-control" id="clinicId" name="clinicId[]" multiple title="<?php echo $this->translate('Please select one or more clinics. Leave blank for All'); ?>" style="width:100%;">
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td style="width:10%;"><strong><?php echo $this->translate("Testing Lab"); ?>&nbsp;:</strong></td>
                                        <td style="width:20%;">
                                            <select class="form-control" id="labId" name="labId[]" multiple title="<?php echo $this->translate('Please select one or more testing lab. Leave blank for All'); ?>" style="width:100%;">
                                                <?php if (isset($lapName) && !empty($lapName)) {
                                                    foreach ($lapName as $lap) { ?>
                                                        <option value="<?php echo $lap['facility_id']; ?>"><?php echo $lap['facility_name']; ?></option>
                                                <?php }
                                                } ?>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td colspan="2">
                                            <a href="javascript:void(0);" class="btn btn-primary btn-sm" onclick="getData();"><?php echo $this->translate('Search'); ?></a>&nbsp;&nbsp;
                                            <a href="javascript:void(0);" class="btn btn-danger btn-sm" onclick="location.reload();" style="margin-right:5.8%;"><?php echo $this->translate('Reset'); ?></a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                            <!-- /.box -->
                        </div>
                    </div>
                    <br>
                </div>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>
<div class="row">
    <div id="sampleResultDetails"></div>
</div>
<br>
<div id="loadData"></div>
<script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/plugins/datepicker/bootstrap-datepicker.js') ?>"></script>
<script type="text/javascript">
    /* Table initialisation */
    oTable = null;

    $(document).ready(function() {

        $('#testType').select2({
            placeholder: "<?php echo $this->translate('Test Type'); ?>",
            allowClear: true
        });
        $('#provinceName').select2({
            placeholder: "<?php echo $this->translate('All Province'); ?>",
            allowClear: true
        });
        $('#districtName').select2({
            placeholder: "<?php echo $this->translate('Select Province First'); ?>",
            allowClear: true
        });
        $('#clinicId').select2({
            placeholder: "<?php echo $this->translate('Select Districts First'); ?>",
            allowClear: true
        });
        $('#labId').select2({
            placeholder: "<?php echo $this->translate('Select Testing Lab'); ?>",
            allowClear: true
        });
        $('.daterangefield').daterangepicker({
            "ranges": {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'Last 90 Days': [moment().subtract(89, 'days'), moment()],
                'Last 120 Days': [moment().subtract(119, 'days'), moment()],
                'Last 180 Days': [moment().subtract(179, 'days'), moment()],
                'Last 12 Months': [moment().subtract(12, 'month').startOf('month'), moment().endOf('month')],
                'Previous Year': [moment().subtract(1, 'year').startOf('year'), moment().subtract(1, 'year').endOf('year')],
                'Current Year To Date': [moment().startOf('year'), moment()]
            },
            "locale": {
                "format": "DD-MMM-YYYY",
                "separator": " to ",
                "applyLabel": "Apply",
                "cancelLabel": "Cancel",
                "fromLabel": "From",
                "toLabel": "To",
                "customRangeLabel": "Custom",
                "daysOfWeek": [
                    "Su",
                    "Mo",
                    "Tu",
                    "We",
                    "Th",
                    "Fr",
                    "Sa"
                ],
                "monthNames": [
                    "January",
                    "February",
                    "March",
                    "April",
                    "May",
                    "June",
                    "July",
                    "August",
                    "September",
                    "October",
                    "November",
                    "December"
                ],
                "firstDay": 1
            },
            //"startDate": "11/08/2015",
            //"endDate": "11/14/2015",
            opens: "left",
        }, function(start, end, label) {
            $('.daterange span').html(start.format('MMMM D, YYYY') + ' - ' + end.format('MMMM D, YYYY'));
        });

        $('#collectionDate').val(moment().subtract(1, 'month').format('DD-MMM-YYYY') + ' to ' + moment().format('DD-MMM-YYYY'));
        $('#testedDate').val('');
        getData();

        var start = moment().subtract(12, 'months');
        var end = moment();

        function cb(start, end) {
            $('#daterange-container span').html(start.format('MMM D, YYYY') + ' to ' + end.format('MMM D, YYYY'));
            $('#daterange').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
            $('#daterange-container-key-indicator span').html(start.format('MMM D, YYYY') + ' to ' + end.format('MMM D, YYYY'));
            $('#daterangeKeyIndicator').val(start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
        }
        <?php $minDate = (isset($loginContainer->useCurrentTables) && $loginContainer->useCurrentTables === true) ? "moment().subtract(12, 'months')" : "moment().subtract(12, 'years')"; ?>
        $('#daterange-container, #daterange-container-key-indicator').daterangepicker({
            'format': 'DD-MMM-YYYY',
            'separator': ' to ',
            'startDate': start,
            'endDate': end,
            'minDate': <?php echo $minDate; ?>,
            'maxDate': moment(),
            'ranges': {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            }
        }, cb);
        cb(start, end);
        $('#dashboard-range').show();
        $('#daterange-container span, #daterange-container-key-indicator span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');

        // the Date and Lab filters of the other functions.
        $('#provinceName,#districtName,#labName').on('select2:close', function() {
            let select = $(this)
            $(this).next('span.select2').find('ul').html(function() {
                let count = select.select2('data').length
                if (count > 1) {
                    return "<li>" + count + " items selected</li>"
                }
            })
        })
    });

    function getSampleResult() {

        return $.post("<?php echo $this->url('snapshot', array('action' => 'get-quick-stats')); ?>", {
                collectionDate: $('#collectionDate').val(),
                testedDate: $('#testedDate').val(),
                testType: $('#testType').val(),
                provinceName: $('#provinceName').val(),
                districtName: $('#districtName').val(),
                clinicId: $('#clinicId').val(),
                labId: $('#labId').val(),
                flag: '<?php echo $flag ?>'
            },
            function(data) {
                $.unblockUI();
                $("#sampleResultDetails").html(data);
            });
    }

    function selectDistrictName() {
        $('#districtName,#clinicId').html('');
        $('#districtName,#clinicId').select2('val', '');

        var pName = $("#provinceName").val();
        if (pName != null && pName.length > 0) {
            $.post("<?php echo $this->url('common', array('action' => 'get-district-list')); ?>", {
                    provinceName: pName,
                    flag: '<?php echo $flag ?>'
                },
                function(data) {
                    if (data != "" || data != null || data != undefined) {
                        $('#districtName').html(data);
                    }
                });
        }
    }

    function selectClinicName() {
        $('#clinicId').html('');
        $('#clinicId').select2('val', '');
        var dName = $("#districtName").val();

        if (dName != null && dName.length > 0) {
            $.post("<?php echo $this->url('common', array('action' => 'get-facility-list')); ?>", {
                    districtName: dName,
                    flag: '<?php echo $flag ?>'
                },
                function(data) {
                    if (data != "" || data != null || data != undefined) {
                        $('#clinicId').html(data);
                    }
                });
        }
    }

    function getData() {
        $.blockUI.defaults.css.border = '1px solid grey';
        $(document).ajaxStart($.blockUI({
            message: '<h2><?php echo $this->translate('Processing...'); ?></h2>'
        })).ajaxStop($.unblockUI);
        $.post("<?php echo $this->url('snapshot', array('action' => 'get-snapshot-data')); ?>", {
                collectionDate: $('#collectionDate').val(),
                testedDate: $('#testedDate').val(),
                testType: $('#testType').val(),
                provinceName: $('#provinceName').val(),
                districtName: $('#districtName').val(),
                clinicId: $('#clinicId').val(),
                labId: $('#labId').val(),
                flag: '<?php echo $flag ?>'
            },
            function(data) {
                if (data != "" || data != null || data != undefined) {
                    $('#loadData').html(data);
                    $('#regTable').dataTable({
                        "bAutoWidth": false,
                        "bProcessing": true,
                        "aaSorting": [
                            [1, "desc"]
                        ],
                        "aoColumns": [{
                                "sClass": "center",
                                "bSortable": false
                            }, {
                                "sClass": "center"
                            },
                            {
                                "sClass": "center"
                            },
                            {
                                "sClass": "center"
                            }
                        ]
                    });
                }
            });
        getSampleResult();
    }

    $("#showDateRange").click(function() {
        $("#showDateRange").hide();
        $("#closeDateRange,.daterange-container").show();
    });

    $("#closeDateRange").click(function() {
        $("#closeDateRange,.daterange-container").hide();
        $("#showDateRange").show();
    });

    function resetDateFilter() {
        $('#dateFilter')[0].reset();
        $('#daterange-container span, #daterange-container-key-indicator span').html('<?php echo $this->translate('Choose Date Range'); ?>');
        $('input[name="daterange"]').val('');
        getSampleResult('reset');
    }
</script>
