<?php
use Laminas\Session\Container;

//\Zend\Debug\Debug::dump($org);
//\Zend\Debug\Debug::dump($users);die;

$selectedUsers = [];

foreach($map as $m){
    $selectedUsers[] = $m['user_id'];
}

$logincontainer = new Container('credo');

?>
        <link href="<?php echo $this->basePath('assets/global/plugins/multiselect/css/multi-select.css'); ?>" rel="stylesheet" type="text/css" />
                    <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="/users">Users</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">Map Users</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"> Map Facility to Users
                    </h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-body">


                                <div class="portlet-body form">
                                    <form class="form-horizontal" method="post" action="/organizations/map" role="form">
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Facility Name <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <span><?php echo $org['name']; ?></span>
                                                    <input type="hidden" id="orgId" name="orgId" class="form-control" placeholder="" value="<?php echo $org['org_id']; ?>">
                                                </div>
                                            </div>
                                            
                                            
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Facilities <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                    <a href='#' id='select-all' class="btn btn-info">Select all</a>
                                                    &nbsp;
                                                    <a href='#' id='deselect-all' class="btn btn-info">Deselect all</a>
                                                    <br>
                                                    <br>
                                                    <select id="users" name="users[]" multiple="multiple" style="width:100%;">
                                                        <?php
                                                        
                                                        foreach ($users as $usr){
                                                            
                                                            if($usr['access_type'] != $org['org_type']){
                                                                continue;
                                                            }
                                                            
                                                            ?>
                                                            <option value="<?php echo $usr['user_id'] ?>" <?php echo (in_array($usr['user_id'], $selectedUsers)) ? " selected='selected' " : ""; ?> ><?php echo $usr['username'] ?></option>
                                                            <?php
                                                        }
                                                        ?>
                                                    </select>

                                                </div>
                                            </div>




                                                                                     
                                            
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <button type="submit" class="btn green">Submit</button>
                                                    <button type="button" class="btn default" onclick="document.location.href='/users'">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                    <script src="<?php echo $this->basePath('assets/global/plugins/multiselect/js/jquery.multi-select.js'); ?>" type="text/javascript"></script>
                    <script>
                        $(document).ready(function(){
                                $('#users').multiSelect();
                                $('#select-all').click(function(){
                                  $('#users').multiSelect('select_all');
                                  return false;
                                });
                                $('#deselect-all').click(function(){
                                  $('#users').multiSelect('deselect_all');
                                  return false;
                                });
                                
                        })
                    </script>
                    