<!-- BEGIN PAGE HEADER-->
<!-- BEGIN THEME PANEL -->
<!-- END THEME PANEL -->
<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="/"><?php echo $this->translate('Dashboard'); ?></a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <?php echo $this->translate('Status'); ?>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title"></h3>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?php echo $this->translate('Status Overview'); ?>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <table id="statusTable" class="table table-striped table-bordered table-hover table-checkable order-column">
                        <thead>
                            <tr>
                                <th> <?php echo $this->translate('Serial No'); ?> </th>
                                <th> <?php echo $this->translate('Lab Name'); ?> </th>
                                <th> <?php echo $this->translate('Last Synced Date Time'); ?> </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="3" class="dataTables_empty">Loading data from server</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <!-- END BASIC DETAILS TABLE-->

        <div class="portlet box blue">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-cogs"></i><?php echo $this->translate('Synced Details'); ?>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-toolbar">
                    <table id="syncTable" class="table table-striped table-bordered table-hover table-checkable order-column">
                        <thead>
                            <tr>
                                <th> <?php echo $this->translate('Serial No'); ?> </th>
                                <th> <?php echo $this->translate('Lab Name'); ?> </th>
                                <th> <?php echo $this->translate('Received On'); ?> </th>
                                <th> <?php echo $this->translate('No. of Records received'); ?> </th>
                                <th> <?php echo $this->translate('No. of records processed'); ?> </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td colspan="5" class="dataTables_empty">Loading data from server</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    /* Table initialisation */
    oTable = null;
    sTable = null;
    $(document).ready(function() {
        oTable = $('#statusTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [{
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                }
            ],
            "sAjaxSource": "<?php echo $this->url('status', array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "type",
                    "value": "status"
                });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

        sTable = $('#syncTable').dataTable({
            "bAutoWidth": false,
            "bProcessing": true,
            "bServerSide": true,
            "aoColumns": [{
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                },
                {
                    "sClass": "center"
                }
            ],
            "sAjaxSource": "<?php echo $this->url('status', array('action' => 'index')); ?>",
            "fnServerData": function(sSource, aoData, fnCallback) {
                aoData.push({
                    "name": "type",
                    "value": "sync"
                });
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            }
        });

    });
</script>