                    
                    <!-- BEGIN PAGE HEADER-->
                    <!-- BEGIN THEME PANEL -->
                    <!-- END THEME PANEL -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="/vl-request/index">vl-request</a>
                                <i class="fa fa-circle"></i>
                            </li>
                            <li>
                                <a href="javascript:;">import-file</a>
                            </li>
                        </ul>
                    </div>
                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->
                    <h3 class="page-title"> Import File
                    </h3>
                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-md-12">
                            <!-- BEGIN EXAMPLE TABLE PORTLET-->
                            <div class="portlet light bordered">
                                <div class="portlet-body">


                                <div class="portlet-body form">
                                    <form class="form-horizontal" method="post" role="form" enctype="multipart/form-data" action="<?php echo $this->url('vl-request', array('action' => 'import-file')); ?>" autocomplete="off" onsubmit="validateNow();return false;">
                                        <div class="form-group">
                                            <label class="col-md-3 control-label">Source Name <span class="font-red-mint">*</span></label>
                                            <div class="col-md-6">
                                                <select class="form-control" name="sourceName" id="sourceName">
                                                    <option value="">--Select--</option>
                                                    <?php
                                                    foreach($sourceResult as $source){
                                                        ?>
                                                        <option value="<?php echo $source['source_id'];?>"><?php echo $source['source_name'];?></option>
                                                        <?php
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="form-body">
                                            <div class="form-group">
                                                <label class="col-md-3 control-label">Attach File <span class="font-red-mint">*</span></label>
                                                <div class="col-md-6">
                                                <input type="file" name="importFile" id="importFile" title="Please choose file" class="isRequired"/>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-actions">
                                            <div class="row">
                                                <div class="col-md-offset-3 col-md-9">
                                                    <button type="submit" class="btn green">Submit</button>
                                                    <button type="button" class="btn default" onclick="document.location.href='/vl-request/index'">Cancel</button>
                                                </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                    
                                </div>
                            </div>
                            <!-- END EXAMPLE TABLE PORTLET-->
                        </div>
                    </div>
                    
                    