                    <!-- BEGIN PAGE BAR -->
                    <!-- BEGIN PAGE BAR -->
                    <div class="page-bar">
                        <ul class="page-breadcrumb">
                            <li>
                                <a href="/">Dashboard</a>
                            </li>
                        </ul>
                    </div>

                    <!-- END PAGE BAR -->
                    <!-- BEGIN PAGE TITLE-->

                    <br>
                    <br>

                    <!-- END PAGE TITLE-->
                    <!-- END PAGE HEADER-->
                    <div class="row">
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12" style="cursor:pointer;" onclick="document.location.href='/labs/samples-accession'">
                            <div class="dashboard-stat2 ">
                                <div class="display">
                                    <div class="number">
                                        <h3 class="font-green-sharp">
                                            <span data-counter="counterup" data-value="20">0</span>
                                        </h3>
                                        <small class="font-green-sharp">SAMPLES ACCESSION</small><br>
                                        <small class="font-green-sharp">27 Mar 2016</small>
                                    </div>
                                    <div class="icon">
                                        <i class="icon-pie-chart"></i>
                                    </div>
                                </div>
                                <div id="samplesReceivedChart" width="210" height="150"></div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12" style="cursor:pointer;" onclick="document.location.href='/labs/samples-waiting'">
                            <div class="dashboard-stat2 ">
                                <div class="display">
                                    <div class="number">
                                        <h3 class="font-purple-soft">
                                            <span data-counter="counterup" data-value="76"></span>
                                        </h3>
                                        <small class="font-purple-soft">SAMPLES WAITING</small><br>
                                        <small class="font-purple-soft">27 Mar 2016</small>
                                    </div>
                                    <div class="icon">
                                        <i class="icon-pie-chart"></i>
                                    </div>
                                </div>
                                <div id="resultAwaitedChart" width="210" height="150"></div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12" style="cursor:pointer;" onclick="document.location.href='/labs/drill-down'">
                            <div class="dashboard-stat2 ">
                                <div class="display">
                                    <div class="number">
                                        <h3 class="font-blue-sharp">
                                            <span data-counter="counterup" data-value="49">0</span>
                                        </h3>
                                        <small class="font-blue-sharp">SAMPLES TESTED</small><br>
                                        <small class="font-blue-sharp">27 Mar 2016</small>
                                    </div>
                                    <div class="icon">
                                        <i class="icon-pie-chart"></i>
                                    </div>
                                </div>
                                <div id="samplesTestedChart" width="210" height="150"></div>
                            </div>
                        </div>
                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12" style="cursor:pointer;" onclick="document.location.href='/labs/samples-rejected'">
                            <div class="dashboard-stat2 ">
                                <div class="display">
                                    <div class="number">
                                        <h3 class="font-red-haze">
                                            <span data-counter="counterup" data-value="57"></span>
                                        </h3>
                                        <small class="font-red-haze">SAMPLES REJECTED</small><br>
                                        <small class="font-red-haze">27 Mar 2016</small>
                                    </div>
                                    <div class="icon">
                                        <i class="icon-pie-chart"></i>
                                    </div>
                                </div>
                                <div id="samplesRejectedChart" width="210" height="150"></div>
                            </div>
                        </div>

                    </div>
                    <div class="row" style="padding-top:10px;padding-bottom:20px;">
                        <div class="col-lg-6">
                            <select class="form-control">
                                <option>All my Labs</option>
                                <option>Lab 001</option>
                                <option>Lab 002</option>
                                <option>Lab 003</option>
                                <option>Lab 004</option>
                                <option>Lab 005</option>
                            </select>
                        </div>
                        <div class="col-lg-6">
                            <div id="dashboard-report-range" class="btn btn-sm form-control"
                                data-container="body"
                                data-placement="bottom"
                                data-original-title="Change dashboard date range">
                                DATE RANGE&nbsp;&nbsp;&nbsp;&nbsp;<i class="icon-calendar"></i>&nbsp;
                                <span class="thin uppercase hidden-xs"></span>&nbsp;
                                <i class="fa fa-angle-down"></i>
                            </div>
                        </div>
                    </div>

                    <div class="row">

                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Samples Tested</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="samplesTestedVsSuppressed"></div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 col-sm-6">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Samples Tested based on Volume</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="facilitiesTestedVsSuppressed"></div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Laboratory Turnaround Time</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="labAverageTat"></div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Requisition Forms for Testing</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="reqformspie"></div>
                                </div>
                            </div>


                        </div>
                        <div class="col-md-4 col-sm-4">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Sample Volume</span>
                                    </div>
                                </div>
                                <div class="portlet-body">
                                    <div id="gotoPie"></div>
                                </div>
                            </div>


                        </div>


                    </div>
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="portlet box blue">
                                <div class="portlet-title">
                                    <div class="caption">
                                        <span class="caption-subject">Facilities</span>
                                    </div>
                                </div>
                                <div class="portlet-body">

                                    <div id="controls-polyline"></div>
                                    <div id="gmap-polyline" class="mapChart" style="height:600px !important;"></div>

                                </div>
                            </div>
                        </div>
                    </div>
                    <script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.js'); ?>" type="text/javascript"></script>
                    <script src="<?php echo $this->basePath('assets/global/scripts/maplace.min.js'); ?>"></script>

                    <script>
                        $(function() {









                            $('#resultAwaitedChart').highcharts({
                                chart: {
                                    type: 'column',
                                    height: 150
                                },
                                title: {
                                    text: ''
                                },
                                subtitle: {
                                    text: ''
                                },
                                xAxis: {
                                    categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"],
                                    crosshair: true
                                },
                                yAxis: {
                                    min: 0,
                                    title: {
                                        text: null
                                    }
                                },
                                tooltip: {
                                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                        '<td style="padding:0"><b>{point.y}</b></td></tr>',
                                    footerFormat: '</table>',
                                    shared: true,
                                    useHTML: true
                                },
                                plotOptions: {
                                    column: {
                                        pointPadding: 0.2,
                                        borderWidth: 0,
                                        cursor: 'pointer',
                                        point: {
                                            events: {
                                                click: function() {
                                                    window.location.href = '/labs/samples-waiting';
                                                }
                                            }
                                        }
                                    }
                                },
                                series: [{
                                    showInLegend: false,
                                    name: 'Samples Waiting',
                                    data: [45, 19, 45, 19, 45, 19, 76]

                                }],
                                colors: ['#8877a9']
                            });


                            $('#samplesReceivedChart').highcharts({
                                chart: {
                                    type: 'column',
                                    height: 150
                                },
                                title: {
                                    text: ''
                                },
                                subtitle: {
                                    text: ''
                                },
                                xAxis: {
                                    categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"],
                                    crosshair: true
                                },
                                yAxis: {
                                    min: 0,
                                    title: {
                                        text: null
                                    }
                                },
                                tooltip: {
                                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                        '<td style="padding:0"><b>{point.y}</b></td></tr>',
                                    footerFormat: '</table>',
                                    shared: true,
                                    useHTML: true
                                },
                                plotOptions: {
                                    column: {
                                        pointPadding: 0.2,
                                        borderWidth: 0,
                                        cursor: 'pointer',
                                        point: {
                                            events: {
                                                click: function() {
                                                    window.location.href = '/labs/samples-accession';
                                                }
                                            }
                                        }
                                    }
                                },
                                series: [{
                                    showInLegend: false,
                                    name: 'Samples Received',
                                    data: [25, 49, 60, 69, 55, 39, 20]

                                }],
                                colors: ['#2ab4c0']
                            });



                            $('#samplesTestedChart').highcharts({
                                chart: {
                                    type: 'column',
                                    height: 150
                                },
                                title: {
                                    text: ''
                                },
                                subtitle: {
                                    text: ''
                                },
                                xAxis: {
                                    categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"],
                                    crosshair: true
                                },
                                yAxis: {
                                    min: 0,
                                    title: {
                                        text: null
                                    }
                                },
                                tooltip: {
                                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                        '<td style="padding:0"><b>{point.y}</b></td></tr>',
                                    footerFormat: '</table>',
                                    shared: true,
                                    useHTML: true
                                },
                                plotOptions: {
                                    column: {
                                        pointPadding: 0.2,
                                        borderWidth: 0,
                                        cursor: 'pointer',
                                        point: {
                                            events: {
                                                click: function() {
                                                    window.location.href = '/labs/drill-down';
                                                }
                                            }
                                        }
                                    }
                                },
                                series: [{
                                    showInLegend: false,
                                    name: 'Samples Tested',
                                    data: [25, 29, 60, 29, 25, 29, 49]

                                }],
                                colors: ['#f36a5a']
                            });




                            $('#samplesRejectedChart').highcharts({
                                chart: {
                                    type: 'column',
                                    height: 150
                                },
                                title: {
                                    text: ''
                                },
                                subtitle: {
                                    text: ''
                                },
                                xAxis: {
                                    categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"],
                                    crosshair: true
                                },
                                yAxis: {
                                    min: 0,
                                    title: {
                                        text: null
                                    }
                                },
                                tooltip: {
                                    headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                                    pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                                        '<td style="padding:0"><b>{point.y}</b></td></tr>',
                                    footerFormat: '</table>',
                                    shared: true,
                                    useHTML: true
                                },
                                plotOptions: {
                                    column: {
                                        pointPadding: 0.2,
                                        borderWidth: 0,
                                        cursor: 'pointer',
                                        point: {
                                            events: {
                                                click: function() {
                                                    window.location.href = '/labs/samples-rejected';
                                                }
                                            }
                                        }
                                    }
                                },
                                series: [{
                                    showInLegend: false,
                                    name: 'Samples Rejected',
                                    data: [65, 59, 65, 59, 65, 59, 57]

                                }],
                                colors: ['#5C9BD1']
                            });


                            $('#reqformspie').highcharts({
                                chart: {
                                    type: 'column'
                                },
                                title: {
                                    text: ''
                                },
                                xAxis: {
                                    categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
                                },
                                yAxis: {
                                    min: 0,
                                    title: {
                                        text: 'Forms'
                                    },
                                    stackLabels: {
                                        enabled: true,
                                        style: {
                                            fontWeight: 'bold',
                                            color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                                        }
                                    }
                                },
                                legend: {
                                    align: 'right',
                                    x: -30,
                                    verticalAlign: 'top',
                                    y: 25,
                                    floating: true,
                                    backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                                    borderColor: '#CCC',
                                    borderWidth: 1,
                                    shadow: false
                                },
                                tooltip: {
                                    headerFormat: '<b>{point.x}</b><br/>',
                                    pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
                                },
                                plotOptions: {
                                    column: {
                                        stacking: 'normal',
                                        cursor: 'pointer',
                                        point: {
                                            events: {
                                                click: function() {
                                                    window.location.href = '/labs/requisition-forms-incomplete';
                                                }
                                            }
                                        },
                                        dataLabels: {
                                            enabled: true,
                                            color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                                            style: {
                                                textShadow: '0 0 3px black'
                                            }
                                        }
                                    }
                                },
                                series: [{
                                    name: 'Incomplete',
                                    data: [5, 3, 4, 7, 2, 7, 2]
                                }, {
                                    name: 'Complete',
                                    data: [2, 2, 3, 2, 1, 2, 1]
                                }],
                                colors: [
                                    '#64ade5',
                                    '#8877a9'
                                ]
                            });









                            $('#samplesTestedVsSuppressed').highcharts({

                                chart: {
                                    type: 'column'
                                },

                                title: {
                                    text: ''
                                },

                                xAxis: {
                                    categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
                                },

                                yAxis: {
                                    allowDecimals: false,
                                    min: 0,
                                    title: {
                                        text: ''
                                    }
                                },

                                tooltip: {
                                    formatter: function() {
                                        return '<b>' + this.x + '</b><br/>' +
                                            this.series.name + ': ' + this.y + '<br/>' +
                                            'Total: ' + this.point.stackTotal;
                                    }
                                },

                                plotOptions: {
                                    column: {
                                        stacking: 'normal',
                                        pointPadding: 0.2,
                                        borderWidth: 0,
                                        cursor: 'pointer',
                                        point: {
                                            events: {
                                                click: function() {
                                                    window.location.href = '/labs/drill-down';
                                                }
                                            }
                                        }
                                    }
                                },

                                series: [{
                                        name: 'Plasma Not Suppressed',
                                        data: [2, 5, 6, 2, 1, 2, 1],
                                        stack: 'female'
                                    }, {
                                        name: 'Plasma Suppressed',
                                        data: [3, 2, 4, 4, 3, 4, 3],
                                        stack: 'female'
                                    },
                                    {
                                        name: 'DBS Not Suppressed',
                                        data: [12, 9, 8, 12, 4, 6, 9],
                                        stack: 'male'
                                    }, {
                                        name: 'DBS Suppressed',
                                        data: [9, 5, 4, 4, 3, 4, 3],
                                        stack: 'male'
                                    }
                                ],
                                colors: [
                                    '#F36A5A',
                                    '#60d18f',
                                    '#ff1900',
                                    '#09843a',
                                ]
                            });




                            $('#facilitiesTestedVsSuppressed').highcharts({

                                chart: {
                                    type: 'column'
                                },

                                title: {
                                    text: ''
                                },

                                xAxis: {
                                    categories: ["Lab 001", "Lab 002", "Lab 003", "Lab 004", "Lab 005", "Lab 006", "Lab 007"]
                                },

                                yAxis: {
                                    allowDecimals: false,
                                    min: 0,
                                    title: {
                                        text: ''
                                    }
                                },

                                tooltip: {
                                    formatter: function() {
                                        return '<b>' + this.x + '</b><br/>' +
                                            this.series.name + ': ' + this.y + '<br/>' +
                                            'Total: ' + this.point.stackTotal;
                                    }
                                },

                                plotOptions: {
                                    column: {
                                        stacking: 'normal',
                                        pointPadding: 0.2,
                                        borderWidth: 0,
                                        cursor: 'pointer',
                                        point: {
                                            events: {
                                                click: function() {
                                                    window.location.href = '/labs/drill-down';
                                                }
                                            }
                                        }
                                    }
                                },

                                series: [{
                                        name: 'Plasma Not Suppressed',
                                        data: [35, 30, 25, 20, 15, 10, 5],
                                        stack: 'female'
                                    }, {
                                        name: 'Plasma Suppressed',
                                        data: [19, 10, 14, 14, 13, 9, 3],
                                        stack: 'female'
                                    },
                                    {
                                        name: 'DBS Not Suppressed',
                                        data: [12, 9, 8, 12, 4, 6, 9],
                                        stack: 'male'
                                    }, {
                                        name: 'DBS Suppressed',
                                        data: [9, 5, 4, 4, 3, 4, 3],
                                        stack: 'male'
                                    }
                                ],
                                colors: [
                                    '#F36A5A',
                                    '#60d18f',
                                    '#ff1900',
                                    '#09843a'
                                ]
                            });











                            $('#gotoPie').highcharts({
                                chart: {
                                    plotBackgroundColor: null,
                                    plotBorderWidth: null,
                                    plotShadow: false,
                                    type: 'pie'
                                },
                                title: {
                                    text: ''
                                },
                                tooltip: {
                                    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
                                },
                                plotOptions: {
                                    pie: {
                                        allowPointSelect: true,
                                        cursor: 'pointer',
                                        dataLabels: {
                                            enabled: false,
                                            format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                                            style: {
                                                color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                                            }
                                        },
                                        showInLegend: true
                                    }
                                },
                                series: [{
                                    name: 'Brands',
                                    colorByPoint: true,
                                    data: [{
                                        name: 'Lab 001',
                                        y: 33
                                    }, {
                                        name: 'Lab 002',
                                        y: 24
                                    }, {
                                        name: 'Lab 003',
                                        y: 10
                                    }, {
                                        name: 'Lab 004',
                                        y: 47
                                    }, {
                                        name: 'Lab 005',
                                        y: 19
                                    }, {
                                        name: 'Lab 006',
                                        y: 20
                                    }]
                                }]
                            });


                            $('#labAverageTat').highcharts({
                                chart: {
                                    type: 'line'
                                },
                                title: {
                                    text: ''
                                },
                                subtitle: {
                                    text: ''
                                },
                                xAxis: {
                                    categories: ["21 Mar", "22 Mar", "23 Mar", "24 Mar", "25 Mar", "26 Mar", "27 Mar"]
                                },
                                yAxis: {
                                    title: {
                                        text: 'TAT in Hours'
                                    },
                                    plotLines: [{
                                        value: 16,
                                        color: 'red',
                                        width: 2
                                    }]
                                },
                                plotOptions: {
                                    line: {
                                        dataLabels: {
                                            enabled: true
                                        }
                                    }
                                },
                                series: [{
                                    name: 'Plasma',
                                    data: [14, 16, 15, 13, 16, 17, 15],
                                    color: '#64ade5'
                                }, {
                                    name: 'DBS',
                                    data: [15, 17, 19, 10, 16, 11, 12],
                                    color: '#8877a9'
                                }]
                            });






                            var LocsAv2 = [{

                                    lat: -26.305201,
                                    lon: 31.1349953,
                                    title: 'Mbabne',
                                    html: '<h3>Mbabne</h3>',
                                    draggable: false
                                },
                                {
                                    lat: -26.305201,
                                    lon: 31.6049953,
                                    title: 'Big Bend',
                                    html: [
                                        '<h3>ANOTHER Bend</h3>',
                                        '<p>Lorem Ipsum..</p>'
                                    ].join(''),
                                    zoom: 8,
                                    visible: true
                                },
                                {
                                    lat: -26.210721,
                                    lon: 31.9243163,
                                    title: 'Simunye',
                                    html: '<h3>Simunye</h3>',
                                    visible: true,
                                    draggable: false
                                },
                                {
                                    lat: -26.782000,
                                    lon: 31.9285000,
                                    title: 'Big Bend',
                                    html: [
                                        '<h3>Big Bend</h3>',
                                        '<p>Lorem Ipsum..</p>'
                                    ].join(''),
                                    zoom: 8,
                                    visible: true
                                }
                            ];


                            var locations = [
                                //Starting Point is "Home", and links to other locations"//
                                ['Mbabne', -26.305201, 31.1349953, '<?php echo $this->basePath('assets/img/lab0.png') ?>', '<strong>No. of Samples : 30</strong>'],
                                ['Big Bend', -26.781057, 31.9284363, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 10</strong>'],
                                ['Simunye', -26.210721, 31.9243163, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 33</strong>'],
                                ['Siteki', -26.434603, 31.9239713, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 40</strong>'],
                                ['Maloma', -26.998871, 31.6534333, '<?php echo $this->basePath('assets/img/clinic.png') ?>', '<strong>No. of Samples : 90</strong>']
                            ]

                            function initMap() {

                                var map = new google.maps.Map(document.getElementById('gmap-polyline'), {
                                    scrollwheel: false,
                                    zoom: 13,
                                    mapTypeId: google.maps.MapTypeId.ROADMAP,
                                    center: {
                                        lat: 0,
                                        lng: 0
                                    }
                                });
                                var markers = [];
                                var bounds = new google.maps.LatLngBounds();
                                // Add the markers and infowindows to the map
                                for (var i = 0; i < locations.length; i++) {

                                    var marker = new google.maps.Marker({
                                        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
                                        title: locations[i][0],
                                        map: map,
                                        icon: locations[i][3]
                                    });

                                    marker['infowindow'] = new google.maps.InfoWindow({
                                        content: locations[i][4]
                                    });

                                    google.maps.event.addListener(marker, 'mouseover', function() {
                                        this['infowindow'].open(map, this);
                                    });


                                    markers.push(marker);
                                    bounds.extend(marker.getPosition());
                                    if (i > 0) {
                                        var sitepath = new google.maps.Polyline({
                                            path: [markers[0].getPosition(), marker.getPosition()],
                                            geodesic: true,
                                            strokeColor: '#F00',
                                            strokeOpacity: 0.5,
                                            strokeWeight: 2,
                                            map: map
                                        });
                                    }
                                }
                                map.fitBounds(bounds);
                            }
                            google.maps.event.addDomListener(window, "load", initMap);




                        });
                    </script>
