name: Build docker image
on:
  push:
    branches:
      - master
  release:
    types:
      - released

env:
  GHCR_REPO: "ghcr.io/deforay/smart-connect"

jobs:
  build:
    name: "Build image"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ env.GHCR_REPO }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
          flavor: |
            latest=false
      -
        name: Build and push image
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
