<?php

use Zend\Debug\Debug;
$val1 =  (($result['total_positive_samples'] / $result['total_samples']) * 100);
$val2 = (($result['total_negative_samples'] / $result['total_samples']) * 100); 
if($result['total_positive_samples'] != null && $result['total_negative_samples'] != null && $result['total_samples'] != null){
?>
<script>
    $('#covid19Outcomes').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: ''
        },
        credits: {
            enabled: false
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    }
                },
                showInLegend: true
            }
        },
        series: [{
            "name": "Tests",
            "colorByPoint": true,
            "data": [{
                "name": "Positive",
                "y": <?php echo (!empty($val1) && $val1 != "" && $val1 != NAN)?$val1:0; ?>,
                "sliced": true,
                "selected": true,
                "color": "#FF1900"
            }, {
                "name": "Negative",
                "y": <?php echo (!empty($val2) && $val2 != "" && $val2 != NAN)?$val2:0;?>,
                "color": "#60D18F"
            }]
        }]

    });
</script>
<?php } ?>